/* Traducción al idioma «it» de la parte del viajero. Generado por backend/torre/campana/idiomas.py desde docs/idiomas/it.tsv: no editar a mano. */
window.IDIOMAS_TRAD = window.IDIOMAS_TRAD || {};
window.IDIOMAS_TRAD["it"] = {
"frases": {
"<b>Temporada alta.</b> El sur también está lleno ese mes.": "<b>Alta stagione.</b> Anche il sud è pieno quel mese.",
"<b>Temporada alta.</b> {p0} está más tranquilo ese mes.": "<b>Alta stagione.</b> {p0} è più tranquillo quel mese.",
"<b>Temporada alta</b> quiere decir que ese mes llega {n0} % o más gente que en un mes promedio del año, o que hay {n1} % o más de probabilidad de rebasar el mes más lleno que el lugar ha tenido. Se calcula con los visitantes del INAH a las zonas arqueológicas y, en {p0}, con los cruces desde Belice.": "<b>Alta stagione</b> significa che quel mese arriva il {n0} % di gente in più (o oltre) rispetto a un mese medio dell'anno, oppure che c'è una probabilità del {n1} % o più di superare il mese più affollato che il luogo abbia mai avuto. Si calcola con i visitatori INAH ai siti archeologici e, a {p0}, con gli attraversamenti dal Belize.",
"<b>{p0} en {m0} de {n0}: temporada alta.</b> El sur también está lleno ese mes.": "<b>{p0} a {m0} {n0}: alta stagione.</b> Anche il sud è pieno quel mese.",
"<b>{p0} en {m0} de {n0}: temporada alta.</b> {p1} está más tranquilo ese mes.": "<b>{p0} a {m0} {n0}: alta stagione.</b> {p1} è più tranquillo quel mese.",
"<b>{p1} en {m0} de {n0}: temporada alta.</b> {p0} está más tranquilo ese mes.": "<b>{p1} a {m0} {n0}: alta stagione.</b> {p0} è più tranquillo quel mese.",
"<b>{p1} y {p0}</b> están como referencia, para quien pensaba ir al norte; la campaña no los promueve. Ahí se mide la ocupación de los hoteles: es temporada alta si se espera {n0} % de cuartos ocupados o más, el nivel que el Radar ya cuenta como \"concurrido\". Si el mes está lleno, te recomendamos un lugar del sur. Tómalo con cuidado en la {p0}: su ocupación bajó ({n1} % en {m0} de {n2} contra {n3} % un año antes), el pronóstico supone que sigue así y se equivoca más que solo repetir lo del año anterior; se usa porque es el único cuyo rango sí atrapó el valor real {n4} de cada {n5} veces.": "<b>{p1} e {p0}</b> sono indicati come riferimento, per chi pensava di andare al nord; la campagna non li promuove. Lì si misura l'occupazione degli hotel: è alta stagione se si prevede il {n0} % o più di camere occupate, il livello che il Radar considera già «affollato». Se il mese è pieno, ti consigliamo un luogo del sud. Prendilo con cautela per {p0}: la sua occupazione è calata ({n1} % a {m0} {n2} contro {n3} % un anno prima), la previsione presume che resti così e sbaglia più che ripetere semplicemente l'anno precedente; si usa perché è l'unica il cui intervallo ha davvero colto il valore reale {n4} volte su {n5}.",
"<span></span><b>Radar, {m0} de {n0}:</b> {n1} de los {n2} lugares del sur, tranquilos<span> · {p0}, sin dato oficial</span><span> · Ver el Radar →</span>": "<span></span><b>Radar, {m0} {n0}:</b> {n1} dei {n2} luoghi del sud sono tranquilli<span> · {p0}, nessun dato ufficiale</span><span> · Vedi il Radar →</span>",
"<span></span>Calderitas: mariscos y la zona de Oxtankah<small>{n0} km →</small>": "<span></span>Calderitas: frutti di mare e il sito di Oxtankah<small>{n0} km →</small>",
"<span></span>Felipe Carrillo Puerto (estación del Tren Maya)<small>{n0} km →</small>": "<span></span>Felipe Carrillo Puerto (stazione del Treno Maya)<small>{n0} km →</small>",
"<span></span>Kantemó: la cueva": "<span></span>Kantemó: la grotta",
"<span></span>Kohunlich y Dzibanché, en la selva": "<span></span>Kohunlich e Dzibanché, nella giungla",
"<span></span>Kohunlich, Dzibanché e Ichkabal": "<span></span>Kohunlich, Dzibanché e Ichkabal",
"<span></span>Laguna Milagros y el cenote de Xul-Ha<small>{n0} km →</small>": "<span></span>La Laguna Milagros e il cenote di Xul-Ha<small>{n0} km →</small>",
"<span></span>Señor: ecoturismo comunitario<small>{n0} km →</small>": "<span></span>Señor: ecoturismo comunitario<small>{n0} km →</small>",
"<span></span>Tihosuco: el Museo de la Guerra de Castas<small>{n0} km →</small>": "<span></span>Tihosuco: il Museo della Guerra delle Caste<small>{n0} km →</small>",
"<span></span>Tranquilo <span></span>Normal <span></span>Temporada alta": "<span></span>Tranquillo <span></span>Normale <span></span>Alta stagione",
"<span></span>{p0}: el malecón y el Museo de la Cultura Maya<small>{n0} km →</small>": "<span></span>{p0}: il lungomare e il Museo della Cultura Maya<small>{n0} km →</small>",
"<span></span>{p0}: la bahía al atardecer<small>{n0} km →</small>": "<span></span>{p0}: la baia al tramonto<small>{n0} km →</small>",
"<span>★ </span>Reseñas<span> ↗</span><span> en Google Maps (otra pestaña)</span>": "<span>★ </span>Recensioni<span> ↗</span><span> su Google Maps (nuova scheda)</span>",
"Agencia de viajes y tours · en el centro": "Agenzia di viaggi ed escursioni · in centro",
"Agencia de viajes y tours · en {p0}, a {n0} km": "Agenzia di viaggi ed escursioni · a {p0}, a {n0} km",
"Antojitos y tacos para cenar, un bar para cerrar el día y dónde dormir.": "Antojitos e tacos per cena, un bar per chiudere la giornata e dove dormire.",
"Antojitos · a {n0} km del centro": "Antojitos (spuntini messicani) · a {n0} km dal centro",
"Antojitos · en el centro": "Antojitos (spuntini messicani) · in centro",
"Asados y pollos · a {n0} km del centro": "Grigliate e pollo · a {n0} km dal centro",
"Asados y pollos · en el centro": "Grigliate e pollo · in centro",
"Así se ve la {p0}": "Ecco com'è la {p0}",
"Así se ve {p0}": "Ecco com'è {p0}",
"Así va a <em>estar</em>.": "Ecco come <em>sarà</em>.",
"Atardecer en el malecón": "Tramonto sul lungomare",
"Atardecer en una calle de Calderitas": "Tramonto in una strada di Calderitas",
"Atardecer en una calle de Calderitas<small>Foto: {x0}, {x1}</small>": "Tramonto in una strada di Calderitas<small>Foto: {x0}, {x1}</small>",
"Atardecer sobre la laguna de {p0}": "Tramonto sulla laguna di {p0}",
"Atardecer sobre la laguna de {p0}<small>Foto: {x0}, {x1}</small>": "Tramonto sulla laguna di {p0}<small>Foto: {x0}, {x1}</small>",
"Avenida Constituyentes, en Felipe Carrillo Puerto": "Avenida Constituyentes, a Felipe Carrillo Puerto",
"Aves en un muelle de la Laguna Milagros": "Uccelli su un pontile della Laguna Milagros",
"Bahía y pirámides": "Baia e piramidi",
"Balneario · a {n0} km del centro": "Luogo per fare il bagno · a {n0} km dal centro",
"Balneario · en Calderitas, a {n0} km": "Luogo per fare il bagno · a Calderitas, a {n0} km",
"Balneario · en el centro": "Luogo per fare il bagno · in centro",
"Balneario · en {p0}, a {n0} km": "Luogo per fare il bagno · a {p0}, a {n0} km",
"Bar o cantina · a {n0} km del centro": "Bar o cantina · a {n0} km dal centro",
"Bar o cantina · en el centro": "Bar o cantina · in centro",
"Bar o cantina · en {p0}, a {n0} km": "Bar o cantina · a {p0}, a {n0} km",
"Cabañas y villas · a {n0} km del centro": "Capanne e ville · a {n0} km dal centro",
"Cabañas y villas · en el centro": "Capanne e ville · in centro",
"Café, desayunos y postres · a {n0} km del centro": "Caffè, colazioni e dolci · a {n0} km dal centro",
"Café, desayunos y postres · en el centro": "Caffè, colazioni e dolci · in centro",
"Café, desayunos y postres · en {p0}, a {n0} km": "Caffè, colazioni e dolci · a {p0}, a {n0} km",
"Cambiar a {p0} en {m0}": "Passa a {p0} a {m0}",
"Campamento · en Calderitas, a {n0} km": "Campeggio · a Calderitas, a {n0} km",
"Campamento · en el centro": "Campeggio · in centro",
"Casa de huéspedes · a {n0} km del centro": "Pensione · a {n0} km dal centro",
"Casas típicas de madera en el Boulevard Bahía": "Tipiche case di legno sul Boulevard Bahía",
"Casas típicas de madera en el Boulevard Bahía<small>Foto: {x0}, {x1}</small>": "Tipiche case di legno sul Boulevard Bahía<small>Foto: {x0}, {x1}</small>",
"Centro nocturno · a {n0} km del centro": "Locale notturno · a {n0} km dal centro",
"Centro nocturno · en el centro": "Locale notturno · in centro",
"Centro nocturno · en {p0}, a {n0} km": "Locale notturno · a {p0}, a {n0} km",
"Cerrar aviso": "Chiudi avviso",
"Cerrar preguntas": "Chiudi domande",
"Cinco lugares": "Cinque luoghi",
"Cinco lugares del sur de Quintana Roo: {p4}, {p1}, {p2}, {p3} y {p0}.": "Cinque luoghi del sud del Quintana Roo: {p4}, {p1}, {p2}, {p3} e {p0}.",
"Cocina internacional · en el centro": "Cucina internazionale · in centro",
"Cocina yucateca · en el centro": "Cucina dello Yucatán · in centro",
"Comida casera · a {n0} km del centro": "Cucina casalinga · a {n0} km dal centro",
"Comida casera · en el centro": "Cucina casalinga · in centro",
"Comida para llevar · a {n0} km del centro": "Cibo da asporto · a {n0} km dal centro",
"Comida para llevar · en el centro": "Cibo da asporto · in centro",
"Comida rápida · a {n0} km del centro": "Fast food · a {n0} km dal centro",
"Comida rápida · en el centro": "Fast food · in centro",
"Comparte con {p0} la vigilancia del sargazo en la bahía.": "Condivide con {p0} la sorveglianza del sargasso nella baia.",
"Con datos oficiales": "Con dati ufficiali",
"Cuatro están en el mismo municipio que {p0}.": "Quattro sono nello stesso comune di {p0}.",
"Cómo llega la gente": "Come arrivano le persone",
"Cómo llegar<span> ↗</span><span> (Google Maps, otra pestaña)</span>": "Come arrivare<span> ↗</span><span> (Google Maps, nuova scheda)</span>",
"De día": "Di giorno",
"De fuentes oficiales y abiertas: Secretaría de Turismo, gobierno de Quintana Roo, INEGI, INAH, NOAA, Open-Meteo y la Reserva Federal. Las fotos, de Wikimedia Commons con licencia libre.": "Da fonti ufficiali e aperte: Ministero del Turismo, governo del Quintana Roo, INEGI, INAH, NOAA, Open-Meteo e la Federal Reserve statunitense. Le foto vengono da Wikimedia Commons con licenza libera.",
"De noche": "Di notte",
"Del Museo de la Cultura Maya en {p0} al de la Guerra de Castas en Tihosuco: la historia del sur contada desde aquí.": "Dal Museo della Cultura Maya a {p0} a quello della Guerra delle Caste a Tihosuco: la storia del sud raccontata da qui.",
"Del mar a la selva, en un <em>solo</em> viaje.": "Dal mare alla giungla, in un <em>solo</em> viaggio.",
"Depende del lugar: arriba, en \"Planea tu viaje\", eliges lugar y mes y te decimos cómo va a estar. Por ejemplo, a la {p0} llega {n0} % menos gente que en un mes promedio en {m0}, y {n1} % más en {m1}.": "Dipende dal luogo: in alto, in «Pianifica il tuo viaggio», scegli luogo e mese e ti diciamo come sarà. Per esempio, a {p0} arriva il {n0} % di gente in meno rispetto a un mese medio a {m0}, e il {n1} % in più a {m1}.",
"Distancias en línea recta entre los centros de cada lugar (no hay datos abiertos de distancias por carretera). Sin precios: ninguna fuente oficial los publica. Las reseñas se leen en Google Maps.": "Distanze in linea d'aria tra i centri di ogni luogo (non ci sono dati aperti sulle distanze stradali). Niente prezzi: nessuna fonte ufficiale li pubblica. Le recensioni si leggono su Google Maps.",
"Documento": "Documento",
"Dzibanché: el Templo del Búho": "Dzibanché: il Tempio del Gufo",
"Dzibanché: el Templo del Búho, {p0}": "Dzibanché: il Tempio del Gufo, {p0}",
"Dzibanché: el Templo del Búho. Foto: {x0}, {x1}, vía Wikimedia Commons.": "Dzibanché: il Tempio del Gufo. Foto: {x0}, {x1}, tramite Wikimedia Commons.",
"Dzibanché: el Templo del Búho<small>Foto: {x0}, {x1}</small>": "Dzibanché: il Tempio del Gufo<small>Foto: {x0}, {x1}</small>",
"Dzibanché: la Estructura {n0}": "Dzibanché: la Struttura {n0}",
"Dzibanché: la Estructura {n0}<small>Foto: {x0}, {x1}</small>": "Dzibanché: la Struttura {n0}<small>Foto: {x0}, {x1}</small>",
"Dónde comer": "Dove mangiare",
"Dónde dormir": "Dove dormire",
"El Boulevard Bahía de {p0}: casas de madera, monumentos y el sol bajando sobre el agua.": "Il Boulevard Bahía di {p0}: case di legno, monumenti e il sole che tramonta sull'acqua.",
"El Mercado {n0} en el centro de {p0}": "Il Mercato {n0} nel centro di {p0}",
"El Mercado {n0} en el centro de {p0}<small>Foto: {x0}, {x1}</small>": "Il Mercato {n0} nel centro di {p0}<small>Foto: {x0}, {x1}</small>",
"El Monumento a la Bandera frente a la bahía": "Il Monumento alla Bandiera di fronte alla baia",
"El Monumento a la Bandera frente a la bahía<small>Foto: {x0}, {x1}</small>": "Il Monumento alla Bandiera di fronte alla baia<small>Foto: {x0}, {x1}</small>",
"El Monumento al Pescador al atardecer, en la bahía": "Il Monumento al Pescatore al tramonto, sulla baia",
"El Monumento al Pescador al atardecer, en la bahía, {p0}": "Il Monumento al Pescatore al tramonto, sulla baia, {p0}",
"El Monumento al Pescador al atardecer, en la bahía. Foto: {x0}, {x1}, vía Wikimedia Commons.": "Il Monumento al Pescatore al tramonto, sulla baia. Foto: {x0}, {x1}, tramite Wikimedia Commons.",
"El Monumento al Pescador al atardecer, en la bahía<small>Foto: {x0}, {x1}</small>": "Il Monumento al Pescatore al tramonto, sulla baia<small>Foto: {x0}, {x1}</small>",
"El Portal Maya del parque Fundadores": "Il Portale Maya del parco Fundadores",
"El Portal Maya del parque Fundadores<small>Foto: {x0}, {x1}</small>": "Il Portale Maya del parco Fundadores<small>Foto: {x0}, {x1}</small>",
"El Radar": "Il Radar",
"El agua turquesa de la Laguna Milagros": "L'acqua turchese della Laguna Milagros",
"El cenote de Xul-Ha": "Il cenote di Xul-Ha",
"El clima es el normal de {n0} a {n1}. El riesgo de tormenta cuenta las tormentas que pasaron a {n2} km o menos del lugar desde {n3} ({n4} en el caso de {p1}). {p0} y la Laguna Milagros no tienen estadística oficial de visitantes, así que no están en el planeador; los encuentras en \"Los lugares\".": "Il clima è quello normale dal {n0} al {n1}. Il rischio di tempesta conta le tempeste passate a {n2} km o meno dal luogo dal {n3} ({n4} nel caso di {p1}). {p0} e la Laguna Milagros non hanno statistiche ufficiali dei visitatori, quindi non sono nel pianificatore; li trovi in «I luoghi».",
"El dato": "Il dato",
"El dinero": "Il denaro",
"El kiosco del centro de {p0}": "Il chiosco del centro di {p0}",
"El kiosco del centro de {p0}<small>Foto: {x0}, {x1}</small>": "Il chiosco del centro di {p0}<small>Foto: {x0}, {x1}</small>",
"El norte": "Il nord",
"El parque y los restaurantes de Calderitas al atardecer": "Il parco e i ristoranti di Calderitas al tramonto",
"El parque y los restaurantes de Calderitas al atardecer<small>Foto: {x0}, {x1}</small>": "Il parco e i ristoranti di Calderitas al tramonto<small>Foto: {x0}, {x1}</small>",
"El problema": "Il problema",
"El sur": "Il sud",
"El sur tiene <em>espacio</em>.": "Il sud ha <em>spazio</em>.",
"El sur tiene <em>espacio</em>.<br>Y te está esperando.": "Il sud ha <em>spazio</em>.<br>E ti sta aspettando.",
"Elige a dónde y cuándo. Te decimos cómo va a estar.": "Scegli dove e quando. Ti diciamo come sarà.",
"En Calderitas, a {n0} km de {p0}, se come viendo el agua; al lado está Oxtankah, la ciudad maya de la bahía.": "A Calderitas, a {n0} km da {p0}, si mangia guardando l'acqua; accanto c'è Oxtankah, la città maya della baia.",
"En Felipe Carrillo Puerto, Señor y Tihosuco las comunidades mayas reciben a quien llega: selva, historia y su forma de vivir.": "A Felipe Carrillo Puerto, Señor e Tihosuco le comunità maya accolgono chi arriva: giungla, storia e il loro modo di vivere.",
"En la costa de {p1} y Calderitas no hay reporte de sargazo. Sí apareció en los canales de entrada de la bahía ({m0} de {n0}), así que se vigila. La ruta de las pirámides, {p0} y la laguna están lejos del mar abierto.": "Sulla costa di {p1} e Calderitas non ci sono segnalazioni di sargasso. È comparso nei canali d'ingresso della baia ({m0} {n0}), quindi viene sorvegliato. La via delle piramidi, {p0} e la laguna sono lontane dal mare aperto.",
"En los municipios de los cinco lugares no hay ningún hospedaje grande: {n0} son chicos (hasta {n1} personas) y {n2} medianos. La derrama económica por destino no se muestra porque la fuente no dice en qué unidad está.": "Nei comuni dei cinque luoghi non c'è nessuna grande struttura ricettiva: {n0} sono piccole (fino a {n1} persone) e {n2} medie. La spesa turistica per destinazione non viene mostrata perché la fonte non indica in che unità è.",
"En {m0} el sur también tiene temporada alta. Si puedes mover tu viaje, busca los meses en verde.": "A {m0} anche il sud è in alta stagione. Se puoi spostare il viaggio, cerca i mesi in verde.",
"En {m0}, <b>{p0}</b> no está en temporada alta: hay espacio, sin el gentío del norte.": "A {m0}, <b>{p0}</b> non è in alta stagione: c'è spazio, senza la folla del nord.",
"En {m0}, <b>{p1}</b> está más tranquilo. O ve a la {p0} en <b>{m1}</b>: menos gente, poca lluvia y fuera de la temporada de tormentas.": "A {m0}, <b>{p1}</b> è più tranquillo. Oppure vai alla {p0} a <b>{m1}</b>: meno gente, poca pioggia e fuori dalla stagione delle tempeste.",
"En {m0}, <b>{p1}</b> está más tranquilo. O ve a {p0} en <b>{m1}</b>: menos gente, poca lluvia y fuera de la temporada de tormentas.": "A {m0}, <b>{p1}</b> è più tranquillo. Oppure vai a {p0} a <b>{m1}</b>: meno gente, poca pioggia e fuori dalla stagione delle tempeste.",
"En {n0} llegaron {n1} pasajeros en avión a {p1}, y el Tren Maya para en {p1}, Bacalar y Felipe Carrillo Puerto ({p0}). Solo en {m0} de {n2} {n3} personas bajaron del tren en {p1}.": "Nel {n0} sono arrivati {n1} passeggeri in aereo a {p1}, e il Treno Maya ferma a {p1}, Bacalar e Felipe Carrillo Puerto ({p0}). Solo a {m0} {n2}, {n3} persone sono scese dal treno a {p1}.",
"Enviar pregunta": "Invia domanda",
"Escribe tu pregunta": "Scrivi la tua domanda",
"Escribe tu pregunta…": "Scrivi la tua domanda…",
"Ese mes todavía no está en el pronóstico (llega hasta {m0} de {n0}): en un {m1} típico, de {n1} a {n2} los hoteles estuvieron al <b>{n3} %</b>.": "Quel mese non è ancora nella previsione (arriva fino a {m0} {n0}): in un {m1} tipico, dal {n1} al {n2}, gli hotel erano al <b>{n3} %</b>.",
"Ese mes todavía no está en el pronóstico (llega hasta {m0} de {n0}): esto es lo típico de {m1}.": "Quel mese non è ancora nella previsione (arriva fino a {m0} {n0}): ecco cosa è tipico di {m1}.",
"Esta parte está en español: son los datos técnicos del proyecto.": "Questa parte è in spagnolo: contiene i dati tecnici del progetto.",
"Estructura {n0} de Oxtankah, con pintura original": "Struttura {n0} di Oxtankah, con la pittura originale",
"Estructura {n0} de Oxtankah, con pintura original<small>Foto: {x0}, {x1}</small>": "Struttura {n0} di Oxtankah, con la pittura originale<small>Foto: {x0}, {x1}</small>",
"Fotos de los cinco lugares; se pueden recorrer con las flechas": "Foto dei cinque luoghi; puoi scorrerle con le frecce",
"Fuente: ECOSUR y notas del {n0} de {m0} de {n1}": "Fonte: ECOSUR e notizie del {n0} {m0} {n1}",
"Fuente: Gobierno de Quintana Roo (SITUR-Q)": "Fonte: Governo del Quintana Roo (SITUR-Q)",
"Fuente: INAH (BdINAH) y forma del año del proyecto (Fase {n0})": "Fonte: INAH (BdINAH) e forma dell'anno del progetto (Fase {n0})",
"Fuente: INAH (BdINAH), SITUR-Q (frontera con Belice), SECTUR-DataTur (ocupación hotelera de {p1} y {p0}), NOAA HURDAT2, Open-Meteo (clima {n0}–{n1}) y pronóstico del proyecto (Fase {n2}); negocios: INEGI, DENUE.": "Fonte: INAH (BdINAH), SITUR-Q (frontiera con il Belize), SECTUR-DataTur (occupazione alberghiera di {p1} e {p0}), NOAA HURDAT2, Open-Meteo (clima {n0}–{n1}) e previsione del progetto (Fase {n2}); attività: INEGI, DENUE.",
"Fuente: INEGI (DENUE) y SITUR-Q": "Fonte: INEGI (DENUE) e SITUR-Q",
"Fuente: INEGI y gobierno de Quintana Roo": "Fonte: INEGI e governo del Quintana Roo",
"Fuente: INEGI, Directorio Estadístico Nacional de Unidades Económicas (DENUE). El tipo de lugar y el momento del día los sugiere un clasificador de texto que lee el nombre y el giro oficial de cada negocio (acertó {n0} de {n1} en una revisión al azar). Cuando un lugar no tiene algo cerca, se muestra lo más cercano de los otros lugares del sur. \"Ver en Google Maps\" abre Google Maps en otra pestaña; esta página no descarga nada de Google.": "Fonte: INEGI, Directory statistica nazionale delle unità economiche (DENUE). Il tipo di luogo e il momento della giornata li suggerisce un classificatore di testo che legge il nome e l'attività ufficiale di ogni esercizio (ne ha azzeccati {n0} su {n1} in un controllo a campione). Quando un luogo non ha qualcosa vicino, si mostra il più vicino tra gli altri luoghi del sud. «Vedi su Google Maps» apre Google Maps in una nuova scheda; questa pagina non scarica nulla da Google.",
"Fuente: Inventario de fuentes del proyecto": "Fonte: inventario delle fonti del progetto",
"Fuente: Secretaría de Turismo y notas verificadas de {n0}": "Fonte: Ministero del Turismo e notizie verificate del {n0}",
"Fuente: Selección de regiones del proyecto": "Fonte: selezione delle regioni del progetto",
"Fuente: Torre del Caribe": "Fonte: Torre del Caribe",
"Girar el mapa solo": "Fai ruotare la mappa da sola",
"Habrá mucha gente: los hoteles suelen pasar del {n0} % de cuartos ocupados, lo que el Radar ya cuenta como \"concurrido\".": "Ci sarà molta gente: gli hotel di solito superano il {n0} % di camere occupate, ciò che il Radar considera già «affollato».",
"Habrá mucha gente: se espera que los hoteles pasen del {n0} % de cuartos ocupados, lo que el Radar ya cuenta como \"concurrido\".": "Ci sarà molta gente: si prevede che gli hotel superino il {n0} % di camere occupate, ciò che il Radar considera già «affollato».",
"Hasta {m0} de {n0} hay un pronóstico con su rango: el valor real cayó dentro de ese rango entre {n1} y {n2} de cada {n3} veces cuando se probó con meses que el modelo nunca vio. Después de esa fecha se muestra lo típico de cada mes.": "Fino a {m0} {n0} c'è una previsione con il suo intervallo: il valore reale è caduto in quell'intervallo tra {n1} e {n2} volte su {n3} quando è stata testata su mesi che il modello non aveva mai visto. Dopo quella data si mostra ciò che è tipico di ogni mese.",
"Hay espacio: los hoteles suelen quedar debajo del {n0} % de cuartos ocupados, lo que el Radar cuenta como \"concurrido\".": "C'è spazio: gli hotel di solito restano sotto il {n0} % di camere occupate, ciò che il Radar considera «affollato».",
"Hay espacio: se espera que los hoteles queden debajo del {n0} % de cuartos ocupados, lo que el Radar cuenta como \"concurrido\".": "C'è spazio: si prevede che gli hotel restino sotto il {n0} % di camere occupate, ciò che il Radar considera «affollato».",
"Hay lugar: {n0} de cada {n1} cuartos de hotel de {p0} se quedaron vacíos en {n2}. <small>Fuente: Gobierno de Quintana Roo (SITUR-Q)</small>": "C'è posto: {n0} camere d'albergo su {n1} a {p0} sono rimaste vuote nel {n2}. <small>Fonte: Governo del Quintana Roo (SITUR-Q)</small>",
"Hay pocos cuartos de hotel: la campaña pone un límite de visitantes para no rebasar a los pueblos.": "Ci sono poche camere d'albergo: la campagna fissa un limite di visitatori per non sovraccaricare i villaggi.",
"Hola. Pregúntame sobre los cinco lugares, cómo llegar o de dónde salen los datos.": "Ciao. Chiedimi dei cinque luoghi, di come arrivare o da dove vengono i dati.",
"Hospedaje de la gente de aquí: en los municipios de los cinco lugares hay {n0} hospedajes chicos, {n1} medianos y {n2} grandes. <small>Fuente: INEGI (DENUE)</small>": "Alloggi della gente del posto: nei comuni dei cinque luoghi ci sono {n0} strutture piccole, {n1} medie e {n2} grandi. <small>Fonte: INEGI (DENUE)</small>",
"Hostal · en el centro": "Ostello · in centro",
"Hostal · en {p0}, a {n0} km": "Ostello · a {p0}, a {n0} km",
"Hotel · en Xul-ha, a {n0} km": "Hotel · a Xul-Ha, a {n0} km",
"Hotel · en el centro": "Hotel · in centro",
"Hotel · en {p0}, a {n0} km": "Hotel · a {p0}, a {n0} km",
"Idioma": "Lingua",
"Idioma / Language": "Lingua / Language",
"Iglesia en Felipe Carrillo Puerto": "Chiesa a Felipe Carrillo Puerto",
"Iglesia en Felipe Carrillo Puerto. Foto: {x0}, {x1}, vía Wikimedia Commons.": "Chiesa a Felipe Carrillo Puerto. Foto: {x0}, {x1}, tramite Wikimedia Commons.",
"Jardín botánico o zoológico · a {n0} km del centro": "Orto botanico o zoo · a {n0} km dal centro",
"Jardín botánico o zoológico · en el centro": "Orto botanico o zoo · in centro",
"Jardín botánico o zoológico · en {p0}, a {n0} km": "Orto botanico o zoo · a {p0}, a {n0} km",
"Kohunlich, Dzibanché e Ichkabal: ciudades mayas entre la selva, con sus mascarones y templos.": "Kohunlich, Dzibanché e Ichkabal: città maya nella giungla, con le loro maschere e i loro templi.",
"Kohunlich, Dzibanché e Ichkabal: tres ciudades mayas en la selva, lejos del mar.": "Kohunlich, Dzibanché e Ichkabal: tre città maya nella giungla, lontano dal mare.",
"Kohunlich, Dzibanché e Ichkabal: tres ciudades mayas en la selva, lejos del mar. Tiene {n0} lugares para comer y {n1} para dormir. Cuidado: los poblados cercanos casi no tienen hoteles: la visita se hace desde {p0}.": "Kohunlich, Dzibanché e Ichkabal: tre città maya nella giungla, lontano dal mare. Ci sono {n0} posti dove mangiare e {n1} dove dormire. Attenzione: i villaggi vicini non hanno quasi hotel, la visita si fa partendo da {p0}.",
"Kohunlich: detalle de un mascarón": "Kohunlich: dettaglio di una maschera",
"Kohunlich: detalle de un mascarón<small>Foto: {x0}, {x1}</small>": "Kohunlich: dettaglio di una maschera<small>Foto: {x0}, {x1}</small>",
"Kohunlich: el juego de pelota": "Kohunlich: il campo del gioco della palla",
"Kohunlich: el juego de pelota<small>Foto: {x0}, {x1}</small>": "Kohunlich: il campo del gioco della palla<small>Foto: {x0}, {x1}</small>",
"Kohunlich: los mascarones de estuco": "Kohunlich: le maschere di stucco",
"Kohunlich: los mascarones de estuco<small>Foto: {x0}, {x1}</small>": "Kohunlich: le maschere di stucco<small>Foto: {x0}, {x1}</small>",
"Kohunlich: una de sus plataformas en la selva": "Kohunlich: una delle sue piattaforme nella giungla",
"Kohunlich: una de sus plataformas en la selva<small>Foto: {x0}, {x1}</small>": "Kohunlich: una delle sue piattaforme nella giungla<small>Foto: {x0}, {x1}</small>",
"La Campana del Bicentenario": "La Campana del Bicentenario",
"La Campana del Bicentenario<small>Foto: {x0}, {x1}</small>": "La Campana del Bicentenario<small>Foto: {x0}, {x1}</small>",
"La Laguna Milagros y el cenote de Xul-Ha, a {n0} km de {p0}. Es frágil: se nada sin bloqueador y sin dejar nada.": "La Laguna Milagros e il cenote di Xul-Ha, a {n0} km da {p0}. È fragile: si nuota senza crema solare e senza lasciare nulla.",
"La Quinta Avenida de Playa del Carmen": "La Quinta Avenida di Playa del Carmen",
"La Quinta Avenida de Playa del Carmen<small>Foto: {x0}, {x1}</small>": "La Quinta Avenida di Playa del Carmen<small>Foto: {x0}, {x1}</small>",
"La bahía de {p0} desde el Boulevard": "La baia di {p0} dal Boulevard",
"La bahía de {p0} desde el Boulevard. Foto: {x0}, {x1}, vía Wikimedia Commons.": "La baia di {p0} dal Boulevard. Foto: {x0}, {x1}, tramite Wikimedia Commons.",
"La bahía frente a Calderitas": "La baia di fronte a Calderitas",
"La bahía frente a Calderitas. Foto: {x0}, {x1}, vía Wikimedia Commons.": "La baia di fronte a Calderitas. Foto: {x0}, {x1}, tramite Wikimedia Commons.",
"La bahía vista desde Calderitas": "La baia vista da Calderitas",
"La bahía vista desde Calderitas, {p0}": "La baia vista da Calderitas, {p0}",
"La bahía vista desde Calderitas. Foto: {x0}, {x1}, vía Wikimedia Commons.": "La baia vista da Calderitas. Foto: {x0}, {x1}, tramite Wikimedia Commons.",
"La bahía vista desde Calderitas<small>Foto: {x0}, {x1}</small>": "La baia vista da Calderitas<small>Foto: {x0}, {x1}</small>",
"La capilla antigua dentro de la zona de Oxtankah": "L'antica cappella dentro il sito di Oxtankah",
"La capilla antigua dentro de la zona de Oxtankah<small>Foto: {x0}, {x1}</small>": "L'antica cappella dentro il sito di Oxtankah<small>Foto: {x0}, {x1}</small>",
"La capilla de Nuestra Señora del Carmen": "La cappella di Nostra Signora del Carmelo",
"La capilla de Nuestra Señora del Carmen<small>Foto: {x0}, {x1}</small>": "La cappella di Nostra Signora del Carmelo<small>Foto: {x0}, {x1}</small>",
"La capital del estado, frente a la bahía, con el Museo de la Cultura Maya.": "La capitale dello stato, sulla baia, con il Museo della Cultura Maya.",
"La capital del estado, frente a la bahía, con el Museo de la Cultura Maya. Tiene {n0} lugares para comer y {n1} para dormir; {n2} personas llegaron en el Tren Maya en {m0} de {n3}. Cuidado: se vigila el sargazo que apareció en los canales de entrada de la bahía ({m1} de {n4}).": "La capitale dello stato, sulla baia, con il Museo della Cultura Maya. Ci sono {n0} posti dove mangiare e {n1} dove dormire; {n2} persone sono arrivate con il Treno Maya a {m0} {n3}. Attenzione: si sorveglia il sargasso comparso nei canali d'ingresso della baia ({m1} {n4}).",
"La gran pirámide de Dzibanché en la selva": "La grande piramide di Dzibanché nella giungla",
"La gran pirámide de Dzibanché en la selva. Foto: {x0}, {x1}, vía Wikimedia Commons.": "La grande piramide di Dzibanché nella giungla. Foto: {x0}, {x1}, tramite Wikimedia Commons.",
"La laguna Nichupté": "La laguna Nichupté",
"La laguna Nichupté<small>Foto: {x0}, {x1}</small>": "La laguna Nichupté<small>Foto: {x0}, {x1}</small>",
"La laguna es frágil: visitas con límite estricto y sin actividades que la dañen.": "La laguna è fragile: visite con un limite rigoroso e senza attività che la danneggino.",
"La orilla de la laguna en Huay-Pix": "La riva della laguna a Huay-Pix",
"La playa del pueblo, en Playa del Carmen": "La spiaggia del paese, a Playa del Carmen",
"La playa del pueblo, en Playa del Carmen<small>Foto: {x0}, {x1}</small>": "La spiaggia del paese, a Playa del Carmen<small>Foto: {x0}, {x1}</small>",
"Laguna y selva": "Laguna e giungla",
"Las fases": "Le fasi",
"Las fotos son de Wikimedia Commons, con licencia libre, y cada una se tomó dentro del municipio del lugar (su coordenada se comprobó con el mapa oficial).": "Le foto vengono da Wikimedia Commons, con licenza libera, e ognuna è stata scattata nel comune del luogo (le sue coordinate sono state verificate sulla mappa ufficiale).",
"Llega más o menos la gente de un mes promedio.": "Arriva più o meno la gente di un mese medio.",
"Llega {n0} % menos gente que en un mes promedio: hay espacio.": "Il {n0} % di gente in meno rispetto a un mese medio: c'è spazio.",
"Llega {n0} % más gente que en un mes promedio, y hay {n1} % de probabilidad de rebasar el mes más lleno de su historia.": "Il {n0} % di gente in più rispetto a un mese medio, e una probabilità del {n1} % di superare il mese più affollato della sua storia.",
"Llega {n0} % más gente que en un mes promedio.": "Il {n0} % di gente in più rispetto a un mese medio.",
"Lo que hay <em>detrás</em> del viaje.": "Cosa c'è <em>dietro</em> il viaggio.",
"Lo que no te <em>cuentan</em> del Caribe.": "Quello che non ti <em>raccontano</em> dei Caraibi.",
"Lo que todos <em>preguntan</em>.": "Quello che tutti <em>chiedono</em>.",
"Los Voladores en el parque Fundadores": "I Voladores nel parco Fundadores",
"Los Voladores en el parque Fundadores<small>Foto: {x0}, {x1}</small>": "I Voladores nel parco Fundadores<small>Foto: {x0}, {x1}</small>",
"Los datos": "I dati",
"Los lugares": "I luoghi",
"Los lugares del sur con estadística están en temporada alta este mes. Mejor ve a la {p0} en <b>{m0}</b>: menos gente, poca lluvia y fuera de la temporada de tormentas.": "I luoghi del sud con statistiche sono in alta stagione questo mese. Meglio andare alla {p0} a <b>{m0}</b>: meno gente, poca pioggia e fuori dalla stagione delle tempeste.",
"Los lugares del sur con estadística están en temporada alta este mes. Mejor ve a {p0} en <b>{m0}</b>: menos gente, poca lluvia y fuera de la temporada de tormentas.": "I luoghi del sud con statistiche sono in alta stagione questo mese. Meglio andare a {p0} a <b>{m0}</b>: meno gente, poca pioggia e fuori dalla stagione delle tempeste.",
"Los poblados cercanos casi no tienen hoteles: la visita se hace desde {p0}.": "I villaggi vicini non hanno quasi hotel: la visita si fa partendo da {p0}.",
"Lugar": "Luogo",
"Lugares reales del directorio de negocios del INEGI, del más cercano al más lejano. No son reseñas ni anuncios pagados y el directorio no publica horarios: confirma antes de ir.": "Luoghi reali dall'elenco delle attività dell'INEGI, dal più vicino al più lontano. Non sono recensioni né pubblicità a pagamento, e l'elenco non pubblica gli orari: verifica prima di andare.",
"Maqueta del sur de Quintana Roo. Arrastra para girarla.": "Plastico del sud del Quintana Roo. Trascina per ruotarlo.",
"Mariposa búho cerca de Chunhuhub": "Farfalla civetta vicino a Chunhuhub",
"Mariposa en la selva cerca de Chunhuhub": "Farfalla nella giungla vicino a Chunhuhub",
"Mariscos frente a la bahía": "Frutti di mare sulla baia",
"Mariscos y pescado · a {n0} km del centro": "Frutti di mare e pesce · a {n0} km dal centro",
"Mariscos y pescado · en el centro": "Frutti di mare e pesce · in centro",
"Mejor mes: <b>{m0}</b> · el mes más seco y sin tormentas (no hay estadística de visitantes)": "Mese migliore: <b>{m0}</b> · il mese più secco e senza tempeste (non ci sono statistiche dei visitatori)",
"Mejor mes: <b>{m0}</b> · menos gente, poca lluvia y sin temporada de tormentas": "Mese migliore: <b>{m0}</b> · meno gente, poca pioggia e niente stagione delle tempeste",
"Mejor ve al sur": "Meglio il sud",
"Menú": "Menu",
"Mes": "Mese",
"Mes normal": "Mese normale",
"Mes tranquilo": "Mese tranquillo",
"Modo noche": "Modalità notte",
"Museo · a {n0} km del centro": "Museo · a {n0} km dal centro",
"Museo · en el centro": "Museo · in centro",
"Museo · en {p0}, a {n0} km": "Museo · a {p0}, a {n0} km",
"Museos de la cultura maya": "Musei della cultura maya",
"Nadar en la Laguna Milagros": "Nuotare nella Laguna Milagros",
"No damos precios: ninguna fuente oficial abierta publica tarifas de hotel por lugar, y no las inventamos. Lo que sí sabemos es que en el sur los hoteles son chicos: {n0} cuartos por hotel en {p0} contra {n1} en {p1} ({m0} de {n2}).": "Non diamo prezzi: nessuna fonte ufficiale aperta pubblica le tariffe alberghiere per luogo, e non le inventiamo. Quello che sappiamo è che al sud gli hotel sono piccoli: {n0} camere per hotel a {p0} contro {n1} a {p1} ({m0} {n2}).",
"No hay estadística oficial de visitantes: por eso se cuida con un límite estricto de gente. <small>Fuente: Selección de regiones del proyecto</small>": "Non ci sono statistiche ufficiali dei visitatori: per questo è tutelata con un limite rigoroso di persone. <small>Fonte: selezione delle regioni del progetto</small>",
"Palapas en Huay-Pix, a la orilla de la laguna": "Palapas a Huay-Pix, sulla riva della laguna",
"Parque · a {n0} km del centro": "Parco · a {n0} km dal centro",
"Parque · en {p0}, a {n0} km": "Parco · a {p0}, a {n0} km",
"Paseo en lancha · en el centro": "Giro in barca · in centro",
"Paseo en lancha · en {p0}, a {n0} km": "Giro in barca · a {p0}, a {n0} km",
"Pirámide de la Tumba {n0} en Oxtankah": "Piramide della Tomba {n0} a Oxtankah",
"Pirámide de la Tumba {n0} en Oxtankah<small>Foto: {x0}, {x1}</small>": "Piramide della Tomba {n0} a Oxtankah<small>Foto: {x0}, {x1}</small>",
"Pirámides en la selva": "Piramidi nella giungla",
"Pizzas y hamburguesas · a {n0} km del centro": "Pizza e hamburger · a {n0} km dal centro",
"Pizzas y hamburguesas · en el centro": "Pizza e hamburger · in centro",
"Planea tu viaje": "Pianifica il tuo viaggio",
"Planea tu viaje · el sur de Quintana Roo": "Pianifica il tuo viaggio · il sud del Quintana Roo",
"Playa Gaviota Azul, en la punta de {p0}": "Spiaggia Gaviota Azul, sulla punta di {p0}",
"Playa Gaviota Azul, en la punta de {p0}, {p0}": "Spiaggia Gaviota Azul, sulla punta di {p0}, {p0}",
"Playa Gaviota Azul, en la punta de {p0}. Foto: {x0}, {x1}, vía Wikimedia Commons.": "Spiaggia Gaviota Azul, sulla punta di {p0}. Foto: {x0}, {x1}, tramite Wikimedia Commons.",
"Playa Gaviota Azul, en la punta de {p0}<small>Foto: {x0}, {x1}</small>": "Spiaggia Gaviota Azul, sulla punta di {p0}<small>Foto: {x0}, {x1}</small>",
"Playa de la zona hotelera de {p0}": "Spiaggia della zona alberghiera di {p0}",
"Playa de la zona hotelera de {p0}<small>Foto: {x0}, {x1}</small>": "Spiaggia della zona alberghiera di {p0}<small>Foto: {x0}, {x1}</small>",
"Playa del Carmen desde el aire": "Playa del Carmen dall'alto",
"Playa del Carmen desde el aire, {p0}": "Playa del Carmen dall'alto, {p0}",
"Playa del Carmen desde el aire. Foto: {x0}, {x1}, vía Wikimedia Commons.": "Playa del Carmen dall'alto. Foto: {x0}, {x1}, tramite Wikimedia Commons.",
"Playa del Carmen desde el aire<small>Foto: {x0}, {x1}</small>": "Playa del Carmen dall'alto<small>Foto: {x0}, {x1}</small>",
"Por la tarde": "Di pomeriggio",
"Posada · a {n0} km del centro": "Locanda · a {n0} km dal centro",
"Posada · en el centro": "Locanda · in centro",
"Posada · en {p0}, a {n0} km": "Locanda · a {p0}, a {n0} km",
"Postales del sur": "Cartoline dal sud",
"Postales del sur · fotos tomadas en cada lugar": "Cartoline dal sud · foto scattate in ogni luogo",
"Preguntas": "Domande",
"Preguntas frecuentes": "Domande frequenti",
"Preguntas rápidas": "Domande rapide",
"Pregúntanos": "Chiedici",
"Pueblo de pescadores junto a la bahía y la zona arqueológica de Oxtankah, casi siempre sin filas.": "Villaggio di pescatori sulla baia con il sito archeologico di Oxtankah, quasi sempre senza code.",
"Pueblo de pescadores junto a la bahía y la zona arqueológica de Oxtankah, casi siempre sin filas. Tiene {n0} lugares para comer y {n1} para dormir. Cuidado: comparte con {p0} la vigilancia del sargazo en la bahía.": "Villaggio di pescatori sulla baia con il sito archeologico di Oxtankah, quasi sempre senza code. Ci sono {n0} posti dove mangiare e {n1} dove dormire. Attenzione: condivide con {p0} la sorveglianza del sargasso nella baia.",
"Pueblos de {p0}": "Villaggi di {p0}",
"Pueblos mayas con turismo comunitario y la cueva de Kantemó.": "Villaggi maya con turismo comunitario e la grotta di Kantemó.",
"Pueblos mayas con turismo comunitario y la cueva de Kantemó. Tiene {n0} lugares para comer y {n1} para dormir; {n2} personas llegaron en el Tren Maya en {m0} de {n3}. Cuidado: hay pocos cuartos de hotel: la campaña pone un límite de visitantes para no rebasar a los pueblos.": "Villaggi maya con turismo comunitario e la grotta di Kantemó. Ci sono {n0} posti dove mangiare e {n1} dove dormire; {n2} persone sono arrivate con il Treno Maya a {m0} {n3}. Attenzione: ci sono poche camere d'albergo, quindi la campagna fissa un limite di visitatori per non sovraccaricare i villaggi.",
"Qué hacer": "Cosa fare",
"Radar, {m0} de {n0}:": "Radar, {m0} {n0}:",
"Recreación · a {n0} km del centro": "Svago · a {n0} km dal centro",
"Recreación · en Xul-ha, a {n0} km": "Svago · a Xul-Ha, a {n0} km",
"Recreación · en el centro": "Svago · in centro",
"Recreación · en {p0}, a {n0} km": "Svago · a {p0}, a {n0} km",
"Respondo con los datos del proyecto. Si no lo sé, lo digo.": "Rispondo con i dati del progetto. Se non lo so, lo dico.",
"Restaurante Bahía Villamar, en una casa de madera": "Ristorante Bahía Villamar, in una casa di legno",
"Restaurante Bahía Villamar, en una casa de madera<small>Foto: {x0}, {x1}</small>": "Ristorante Bahía Villamar, in una casa di legno<small>Foto: {x0}, {x1}</small>",
"Restaurante a la carta · a {n0} km del centro": "Ristorante alla carta · a {n0} km dal centro",
"Restaurante a la carta · en el centro": "Ristorante alla carta · in centro",
"Rutas de {n0} y {n1} días": "Itinerari di {n0} e {n1} giorni",
"Saltar al contenido": "Vai al contenuto",
"Se espera alrededor de <b>{n0} %</b> de los cuartos de hotel ocupados, muy probablemente entre {n1} y {n2} %.": "Si prevede circa il <b>{n0} %</b> di camere d'albergo occupate, molto probabilmente tra il {n1} e il {n2} %.",
"Se esperan alrededor de <b>{n0}</b> cruces desde Belice, muy probablemente entre {n1} y {n2}.": "Si prevedono circa <b>{n0}</b> attraversamenti dal Belize, molto probabilmente tra {n1} e {n2}.",
"Se esperan alrededor de <b>{n0}</b> visitantes a Kohunlich, Dzibanché e Ichkabal, muy probablemente entre {n1} y {n2}.": "Si prevedono circa <b>{n0}</b> visitatori a Kohunlich, Dzibanché e Ichkabal, molto probabilmente tra {n1} e {n2}.",
"Se esperan alrededor de <b>{n0}</b> visitantes a la zona de Oxtankah, muy probablemente entre {n1} y {n2}.": "Si prevedono circa <b>{n0}</b> visitatori al sito di Oxtankah, molto probabilmente tra {n1} e {n2}.",
"Se vigila el sargazo que apareció en los canales de entrada de la bahía ({m0} de {n0}).": "Si sorveglia il sargasso comparso nei canali d'ingresso della baia ({m0} {n0}).",
"Secciones": "Sezioni",
"Seis experiencias con lugares reales y una cifra oficial cada una. Sin precios: ninguna fuente oficial los publica.": "Sei esperienze con luoghi reali e un dato ufficiale ciascuna. Niente prezzi: nessuna fonte ufficiale li pubblica.",
"Sin dato": "Nessun dato",
"Sin dato oficial": "Nessun dato ufficiale",
"Sí: en {n0} {n1} de cada {n2} cuartos de hotel de {p0} se quedaron vacíos ({n3} de {n4} noches ocupadas).": "Sì: nel {n0}, {n1} camere d'albergo su {n2} a {p0} sono rimaste vuote ({n3} notti occupate su {n4}).",
"Tacos y tortas · a {n0} km del centro": "Tacos e tortas · a {n0} km dal centro",
"Tacos y tortas · en el centro": "Tacos e tortas · in centro",
"Te conviene más": "Ti conviene di più",
"Temporada alta": "Alta stagione",
"Temporada alta.": "Alta stagione.",
"Tienen sargazo y se llenan: en su semana más llena, {p0} tuvo {n0} de cada {n1} cuartos ocupados, y en Tulum se reportaron cierres de negocios en {n2}. La campaña lleva gente a donde sí hay espacio.": "Hanno il sargasso e si riempiono: nella settimana più piena, {p0} ha avuto {n0} camere occupate su {n1}, e a Tulum sono state segnalate chiusure di attività nel {n2}. La campagna porta la gente dove c'è davvero spazio.",
"Todo lo que viste arriba sale de datos oficiales, modelos y pruebas. Esta parte es para quien quiera revisar cómo lo sabemos.": "Tutto quello che hai visto sopra viene da dati ufficiali, modelli e test. Questa parte è per chi vuole verificare come lo sappiamo.",
"Tranquilo": "Tranquillo",
"Tu viaje": "Il tuo viaggio",
"Turismo comunitario maya": "Turismo comunitario maya",
"Un balneario o un parque, y a comer: mariscos, cocina yucateca o comida casera.": "Un luogo per fare il bagno o un parco, e poi a tavola: frutti di mare, cucina dello Yucatán o cucina casalinga.",
"Un día en <em>{p0}</em>": "Un giorno a <em>{p0}</em>",
"Un equipo de estudiantes de Ciencias de Datos para Negocios de la Universidad Nacional Rosario Castellanos (UNRC), como proyecto escolar {n0}-{n1}.": "Un gruppo di studenti di Scienza dei dati per le imprese dell'Università Nazionale Rosario Castellanos (UNRC), come progetto scolastico {n0}-{n1}.",
"Un matapalo en la selva de Felipe Carrillo Puerto": "Un fico strangolatore nella giungla di Felipe Carrillo Puerto",
"Un muelle en la Laguna Milagros": "Un pontile sulla Laguna Milagros",
"Un muelle en la Laguna Milagros. Foto: {x0}, {x1}, vía Wikimedia Commons.": "Un pontile sulla Laguna Milagros. Foto: {x0}, {x1}, tramite Wikimedia Commons.",
"Una laguna del mismo sistema que Bacalar, con pueblos a la orilla.": "Una laguna dello stesso sistema di Bacalar, con villaggi sulle sponde.",
"Una laguna del mismo sistema que Bacalar, con pueblos a la orilla. Tiene {n0} lugares para comer y {n1} para dormir. Cuidado: la laguna es frágil: visitas con límite estricto y sin actividades que la dañen.": "Una laguna dello stesso sistema di Bacalar, con villaggi sulle sponde. Ci sono {n0} posti dove mangiare e {n1} dove dormire. Attenzione: la laguna è fragile, quindi visite con un limite rigoroso e senza attività che la danneggino.",
"Una laguna dulce y un cenote": "Una laguna d'acqua dolce e un cenote",
"Unas {n0} personas al día entre las tres zonas en {n1}: tienes la pirámide casi para ti. <small>Fuente: INAH</small>": "Circa {n0} persone al giorno nei tre siti insieme nel {n1}: la piramide è quasi tutta per te. <small>Fonte: INAH</small>",
"Ver cómo está en {m0}": "Guarda com'è a {m0}",
"Ver cómo va a estar": "Guarda come sarà",
"Ver la {p0} en {m0}": "Vedi la {p0} a {m0}",
"Ver todo el mapa": "Vedi tutta la mappa",
"Ver {p0} en {m0}": "Vedi {p0} a {m0}",
"Vive el sur": "Vivi il sud",
"Zona arqueológica (INAH)": "Sito archeologico (INAH)",
"Zona arqueológica de El Meco": "Sito archeologico di El Meco",
"Zona arqueológica de El Meco<small>Foto: {x0}, {x1}</small>": "Sito archeologico di El Meco<small>Foto: {x0}, {x1}</small>",
"Zonas arqueológicas, museos y paseos; para empezar, un café o un desayuno.": "Siti archeologici, musei e passeggiate; per iniziare, un caffè o una colazione.",
"de lluvia en un {m0} normal": "di pioggia in un {m0} normale",
"de máxima, en promedio": "di massima, in media",
"de probabilidad de tormenta": "di probabilità di tempesta",
"llegaron en el Tren Maya en {m0} de {n0}": "sono arrivati con il Treno Maya a {m0} {n0}",
"lugar para dormir": "posto dove dormire",
"lugares para comer": "posti dove mangiare",
"lugares para dormir": "posti dove dormire",
"no hay estadística oficial de turistas": "non ci sono statistiche ufficiali dei turisti",
"sin tormentas registradas en este mes": "nessuna tempesta registrata in questo mese",
"visitantes a sus zonas arqueológicas en {n0}": "visitatori ai suoi siti archeologici nel {n0}",
"{m0} de {n0}: mes normal": "{m0} {n0}: mese normale",
"{m0} de {n0}: mes tranquilo": "{m0} {n0}: mese tranquillo",
"{m0} de {n0}: temporada alta": "{m0} {n0}: alta stagione",
"{n0} días": "{n0} giorni",
"{n0} marisquerías en Calderitas y {n1} visitantes a Oxtankah en {n2}. <small>Fuente: INEGI (DENUE) e INAH</small>": "{n0} ristoranti di pesce a Calderitas e {n1} visitatori a Oxtankah nel {n2}. <small>Fonte: INEGI (DENUE) e INAH</small>",
"{n0} mm": "{n0} mm",
"{n0} museos en {p1} y {p0} según el directorio del INEGI. <small>Fuente: INEGI (DENUE)</small>": "{n0} musei a {p1} e {p0} secondo l'elenco dell'INEGI. <small>Fonte: INEGI (DENUE)</small>",
"{n0} °C": "{n0} °C",
"{n0}. {p0}: ir a su descripción": "{n0}. {p0}: vai alla sua descrizione",
"{p0} en {m0} de {n0}: temporada alta.": "{p0} a {m0} {n0}: alta stagione.",
"{p0} · {m0} de {n0}": "{p0} · {m0} {n0}",
"{p0} · {m0} de {n0} <span>Referencia: la campaña no lo promueve</span>": "{p0} · {m0} {n0} <span>Riferimento: la campagna non lo promuove</span>",
"· {m0} de {n0} (estimado): tranquilo": "· {m0} {n0} (stimato): tranquillo",
"¿Cuándo conviene ir?": "Quando conviene andare?",
"¿Cuánto cuesta ir?": "Quanto costa?",
"¿Cómo llego al sur?": "Come arrivo al sud?",
"¿Cómo lo sabemos?": "Come lo sappiamo?",
"¿De dónde salen los datos?": "Da dove vengono i dati?",
"¿Dónde se queda el dinero?": "Dove resta il denaro?",
"¿Hay espacio en {p0}?": "C'è spazio a {p0}?",
"¿Hay sargazo en el sur?": "C'è sargasso al sud?",
"¿Ibas al norte?": "Andavi al nord?",
"¿Por qué no {p0} o Tulum?": "Perché non {p0} o Tulum?",
"¿Quién hizo esto?": "Chi ha fatto questo?",
"¿Qué hay en {p0}?": "Cosa c'è a {p0}?",
"¿Qué lugares promueve la campaña?": "Quali luoghi promuove la campagna?",
"Modo día": "Modalità giorno",
"<span></span>El Mercado {n0} y los antojitos del centro<small>{n1} km →</small>": "<span></span>Il Mercato {n0} e gli antojitos del centro<small>{n1} km →</small>",
"<span></span>El parque Fundadores y el Portal Maya<small>a pie →</small>": "<span></span>Il parco Fundadores e il Portale Maya<small>a piedi →</small>",
"<span></span>La Quinta Avenida<small>{n0} km →</small>": "<span></span>La Quinta Avenida<small>{n0} km →</small>",
"<span></span>La playa del pueblo": "<span></span>La spiaggia del paese",
"<span></span>La zona arqueológica de El Meco": "<span></span>Il sito archeologico di El Meco",
"<span></span>La zona hotelera y Playa Gaviota Azul<small>{n0} km →</small>": "<span></span>La zona alberghiera e la spiaggia Gaviota Azul<small>{n0} km →</small>",
"<span></span>{p0} o Playa del Carmen: subir al Tren Maya<small>{n0} km →</small>": "<span></span>{p0} o Playa del Carmen: salire sul Treno Maya<small>{n0} km →</small>",
"<span></span>{p0}: el malecón al atardecer<small>{n0} km →</small>": "<span></span>{p0}: il lungomare al tramonto<small>{n0} km →</small>",
"<span>★★★★★</span> {n0} % de los cuartos de hotel son de {n1} estrellas (categoría oficial, {n2})": "<span>★★★★★</span> il {n0} % delle camere d'albergo è a {n1} stelle (categoria ufficiale, {n2})",
"Antojitos y Mercado {n0}": "Antojitos e Mercato {n0}",
"Así se come en {p0}": "Cosa si mangia a {p0}",
"Categoría de hotel: SECTUR-DataTur, Compendio Estadístico del Turismo en México {n0} (tabla {n1}_2). Fuente: INEGI, Directorio Estadístico Nacional de Unidades Económicas (DENUE). El tipo de lugar y el momento del día los sugiere un clasificador de texto que lee el nombre y el giro oficial de cada negocio (acertó {n2} de {n3} en una revisión al azar). Cuando un lugar no tiene algo cerca, se muestra lo más cercano de los otros lugares del sur. \"Ver en Google Maps\" abre Google Maps en otra pestaña; esta página no descarga nada de Google.": "Categoria alberghiera: SECTUR-DataTur, Compendio statistico del turismo in Messico {n0} (tabella {n1}_2). Fonte: INEGI, Directory statistica nazionale delle unità economiche (DENUE). Il tipo di luogo e il momento della giornata li suggerisce un classificatore di testo che legge il nome e l'attività ufficiale di ogni esercizio (ne ha azzeccati {n2} su {n3} in un controllo a campione). Quando un luogo non ha qualcosa vicino, si mostra il più vicino tra gli altri luoghi del sud. «Vedi su Google Maps» apre Google Maps in una nuova scheda; questa pagina non scarica nulla da Google.",
"Cenar en la calle, de noche": "Cenare per strada, di sera",
"Cenar en la calle, de noche<small>Foto: {x0}, {x1}</small>": "Cenare per strada, di sera<small>Foto: {x0}, {x1}</small>",
"Cocina mexicana en la Quinta Avenida": "Cucina messicana sulla Quinta Avenida",
"Cocina mexicana en la Quinta Avenida<small>Foto: {x0}, {x1}</small>": "Cucina messicana sulla Quinta Avenida<small>Foto: {x0}, {x1}</small>",
"Comida de mariscos frente al mar": "Un pranzo di pesce davanti al mare",
"Comida de mariscos frente al mar<small>Foto: {x0}, {x1}</small>": "Un pranzo di pesce davanti al mare<small>Foto: {x0}, {x1}</small>",
"Del Caribe a la selva, en un <em>solo</em> mapa.": "Dai Caraibi alla giungla, in una <em>sola</em> mappa.",
"Del Caribe al sur en Tren Maya": "Dai Caraibi al sud con il Treno Maya",
"Distancias en línea recta (no hay datos abiertos de distancias por carretera). Sin precios: ninguna fuente oficial los publica. Las reseñas se leen en Google Maps.": "Distanze in linea d'aria (non ci sono dati aperti sulle distanze stradali). Niente prezzi: nessuna fonte ufficiale li pubblica. Le recensioni si leggono su Google Maps.",
"El Meco, El Rey y el Museo Maya de {p0}: ciudades mayas entre los hoteles y la laguna.": "El Meco, El Rey e il Museo Maya di {p0}: città maya tra gli hotel e la laguna.",
"El Museo de la Cultura Maya, el planetario y la historia de la ciudad, a pasos de la bahía.": "Il Museo della Cultura Maya, il planetario e la storia della città, a pochi passi dalla baia.",
"El Portal Maya y los Voladores": "Il Portale Maya e i Voladores",
"El clima es el normal de {n0} a {n1}. El riesgo de tormenta cuenta las tormentas que pasaron a {n2} km o menos del lugar desde {n3} ({n4} en el caso de {p0}).": "Il clima è quello normale dal {n0} al {n1}. Il rischio di tempesta conta le tempeste passate a {n2} km o meno dal luogo dal {n3} ({n4} nel caso di {p0}).",
"El parque Fundadores frente al mar, con el Portal Maya y la danza de los Voladores.": "Il parco Fundadores davanti al mare, con il Portale Maya e la danza dei Voladores.",
"El sur: {p3}, {p0}, {p1}. {p4} y la {p2} aparecen como referencia, para quien pensaba ir al norte: si su mes está lleno, te recomendamos un lugar del sur.": "Il sud: {p3}, {p0}, {p1}. {p4} e la {p2} compaiono come riferimento, per chi pensava di andare al nord: se il loro mese è pieno, ti consigliamo un luogo del sud.",
"En el sur · {p0}": "Al sud · {p0}",
"En la costa de {p0} y Calderitas no hay reporte de sargazo. Sí apareció en los canales de entrada de la bahía ({m0} de {n0}), así que se vigila. La ruta de las pirámides está lejos del mar abierto.": "Sulla costa di {p0} e Calderitas non ci sono segnalazioni di sargasso. È comparso nei canali d'ingresso della baia ({m0} {n0}), quindi viene sorvegliato. La via delle piramidi è lontana dal mare aperto.",
"En los municipios del sur que promueve la campaña no hay ningún hospedaje grande: {n0} son chicos (hasta {n1} personas) y {n2} medianos. La derrama económica por destino no se muestra porque la fuente no dice en qué unidad está.": "Nei comuni del sud promossi dalla campagna non c'è nessuna grande struttura ricettiva: {n0} sono piccole (fino a {n1} persone) e {n2} medie. La spesa turistica per destinazione non viene mostrata perché la fonte non indica in che unità è.",
"En {n0} llegaron {n1} pasajeros en avión a {p0}, y el Tren Maya para en {p0}, Bacalar, {p1} y Playa del Carmen. Solo en {m0} de {n2} {n3} personas bajaron del tren en {p0}.": "Nel {n0} sono arrivati {n1} passeggeri in aereo a {p0}, e il Treno Maya ferma a {p0}, Bacalar, {p1} e Playa del Carmen. Solo a {m0} {n2}, {n3} persone sono scese dal treno a {p0}.",
"Fajitas de pollo en Playa del Carmen": "Fajitas di pollo a Playa del Carmen",
"Fajitas de pollo en Playa del Carmen<small>Foto: {x0}, {x1}</small>": "Fajitas di pollo a Playa del Carmen<small>Foto: {x0}, {x1}</small>",
"Fotos del lugar elegido; se pueden recorrer con las flechas": "Foto del luogo scelto; puoi scorrerle con le frecce",
"Guacamole y mojitos": "Guacamole e mojito",
"Guacamole y mojitos<small>Foto: {x0}, {x1}</small>": "Guacamole e mojito<small>Foto: {x0}, {x1}</small>",
"La Quinta Avenida": "La Quinta Avenida",
"La calle peatonal de Playa del Carmen: restaurantes, tiendas y el mar a una cuadra.": "La via pedonale di Playa del Carmen: ristoranti, negozi e il mare a un isolato.",
"La ciudad más visitada del Caribe mexicano: la zona hotelera, la laguna Nichupté y zonas mayas dentro de la ciudad.": "La città più visitata dei Caraibi messicani: la zona alberghiera, la laguna Nichupté e siti maya dentro la città.",
"La ciudad más visitada del Caribe mexicano: la zona hotelera, la laguna Nichupté y zonas mayas dentro de la ciudad. Tiene {n0} lugares para comer y {n1} para dormir. Referencia: la campaña no lo promueve. Tiene sargazo en {n2} y está en temporada alta de {m0} a {m1}.": "La città più visitata dei Caraibi messicani: la zona alberghiera, la laguna Nichupté e siti maya dentro la città. Ci sono {n0} posti dove mangiare e {n1} dove dormire. Riferimento: la campagna non la promuove. Ha sargasso nel {n2} ed è in alta stagione da {m0} a {m1}.",
"La zona hotelera": "La zona alberghiera",
"Las fotos son de Wikimedia Commons, con licencia libre, y cada una se tomó dentro del municipio del lugar (su coordenada se comprobó con el mapa oficial). Las fotos de comida solo existen con licencia libre para {p0} y Playa del Carmen; las del sur las aportará el equipo.": "Le foto vengono da Wikimedia Commons, con licenza libera, e ognuna è stata scattata nel comune del luogo (le sue coordinate sono state verificate sulla mappa ufficiale). Foto di piatti con licenza libera esistono solo per {p0} e Playa del Carmen; quelle del sud arriveranno dal gruppo.",
"Maqueta de Quintana Roo. Arrastra para girarla.": "Plastico del Quintana Roo. Trascina per ruotarlo.",
"Mes menos lleno: <b>{m0}</b> · el menos lleno de los meses secos y sin tormentas; aun así, hoteles al {n0} %": "Mese meno affollato: <b>{m0}</b> · il meno pieno dei mesi secchi e senza tempeste; anche così, hotel al {n0} %",
"Panuchos, el antojito yucateco": "Panuchos, lo spuntino dello Yucatán",
"Panuchos, el antojito yucateco<small>Foto: {x0}, {x1}</small>": "Panuchos, lo spuntino dello Yucatán<small>Foto: {x0}, {x1}</small>",
"Panuchos, salbutes y tacos en el centro, lejos de la zona hotelera.": "Panuchos, salbutes e tacos in centro, lontano dalla zona alberghiera.",
"Playa Gaviota Azul y la punta de {p0}: arena blanca entre el mar y la laguna Nichupté.": "La spiaggia Gaviota Azul e la punta di {p0}: sabbia bianca tra il mare e la laguna Nichupté.",
"Playa del Carmen en un día": "Playa del Carmen in un giorno",
"Playa del Carmen, el centro de la {p0}: la Quinta Avenida, el parque Fundadores y la playa del pueblo.": "Playa del Carmen, il centro della {p0}: la Quinta Avenida, il parco Fundadores e la spiaggia del paese.",
"Playa del Carmen, el centro de la {p0}: la Quinta Avenida, el parque Fundadores y la playa del pueblo. Tiene {n0} lugares para comer y {n1} para dormir. Referencia: la campaña no la promueve. Tiene sargazo en {n2}; su ocupación bajó y se llena en {m0} y {m1}.": "Playa del Carmen, il centro della {p0}: la Quinta Avenida, il parco Fundadores e la spiaggia del paese. Ci sono {n0} posti dove mangiare e {n1} dove dormire. Riferimento: la campagna non la promuove. Ha sargasso nel {n2}; la sua occupazione è calata e si riempie a {m0} e {m1}.",
"Postales de {p0} · fotos tomadas en cada lugar": "Cartoline da {p0} · foto scattate in ogni luogo",
"Primero, lo del lugar que elegiste arriba; después, lo del sur. Lugares reales y una cifra oficial en cada uno. Sin precios: ninguna fuente oficial los publica.": "Prima, ciò che offre il luogo scelto in alto; poi, il sud. Luoghi reali e un dato ufficiale per ciascuno. Niente prezzi: nessuna fonte ufficiale li pubblica.",
"Referencia: la campaña no la promueve. Tiene sargazo en {n0}; su ocupación bajó y se llena en {m0} y {m1}.": "Riferimento: la campagna non la promuove. Ha sargasso nel {n0}; la sua occupazione è calata e si riempie a {m0} e {m1}.",
"Referencia: la campaña no lo promueve": "Riferimento: la campagna non lo promuove",
"Referencia: la campaña no lo promueve. Tiene sargazo en {n0} y está en temporada alta de {m0} a {m1}.": "Riferimento: la campagna non lo promuove. Ha sargasso nel {n0} ed è in alta stagione da {m0} a {m1}.",
"Todavía no tengo esa respuesta. Prueba con una de las preguntas de abajo: solo respondo lo que los datos del proyecto pueden sostener.": "Non ho ancora questa risposta. Prova una delle domande qui sotto: rispondo solo ciò che i dati del progetto possono sostenere.",
"Tres en el sur, con espacio. {p1} y la {p0}, como referencia para quien iba al norte.": "Tre al sud, con spazio. {p1} e la {p0}, come riferimento per chi andava al nord.",
"Un puesto de quesadillas": "Un chiosco di quesadillas",
"Un puesto de quesadillas<small>Foto: {x0}, {x1}</small>": "Un chiosco di quesadillas<small>Foto: {x0}, {x1}</small>",
"Una taquería del centro": "Una taquería del centro",
"Una taquería del centro<small>Foto: {x0}, {x1}</small>": "Una taquería del centro<small>Foto: {x0}, {x1}</small>",
"Zonas mayas dentro de {p0}": "Siti maya dentro {p0}",
"cuartos de hotel ({m0} de {n0})": "camere d'albergo ({m0} {n0})",
"de los cuartos son de {n0} estrellas ({n1})": "delle camere è a {n0} stelle ({n1})",
"sin temporada alta en los cinco lugares": "nessuna alta stagione nei cinque luoghi",
"{m0} de {n0}:": "{m0} {n0}:",
"{n0} % de los cuartos de hotel de Playa del Carmen son de {n1} estrellas, según la categoría oficial ({n2}). <small>Fuente: SECTUR-DataTur (Compendio {n3})</small>": "Il {n0} % delle camere d'albergo di Playa del Carmen è a {n1} stelle, secondo la categoria ufficiale ({n2}). <small>Fonte: SECTUR-DataTur (Compendio {n3})</small>",
"{n0} % de sus cuartos de hotel son de {n1} estrellas, según la categoría oficial ({n2}). <small>Fuente: SECTUR-DataTur (Compendio {n3})</small>": "Il {n0} % delle sue camere d'albergo è a {n1} stelle, secondo la categoria ufficiale ({n2}). <small>Fonte: SECTUR-DataTur (Compendio {n3})</small>",
"{n0} día": "{n0} giorno",
"{n0} lugares de antojitos, tacos y cocina yucateca en la ciudad según el directorio del INEGI. <small>Fuente: INEGI (DENUE)</small>": "{n0} locali di antojitos, tacos e cucina dello Yucatán in città secondo l'elenco dell'INEGI. <small>Fonte: INEGI (DENUE)</small>",
"{n0} lugares para comer en Playa del Carmen según el directorio del INEGI. <small>Fuente: INEGI (DENUE)</small>": "{n0} posti dove mangiare a Playa del Carmen secondo l'elenco dell'INEGI. <small>Fonte: INEGI (DENUE)</small>",
"{n0} museos en {p0} según el directorio del INEGI. <small>Fuente: INEGI (DENUE)</small>": "{n0} musei a {p0} secondo l'elenco dell'INEGI. <small>Fonte: INEGI (DENUE)</small>",
"{n0} visitantes en {n1} entre las tres: unas {n2} al día. <small>Fuente: INAH</small>": "{n0} visitatori nel {n1} nei tre siti: circa {n2} al giorno. <small>Fonte: INAH</small>",
"{p0} <span>Referencia: la campaña no lo promueve</span>": "{p0} <span>Riferimento: la campagna non lo promuove</span>",
"{p0} en {n0} días": "{p0} in {n0} giorni",
"{p0}, temporada alta": "{p0}, alta stagione",
"· Planea tu viaje →": "· Pianifica il tuo viaggio →",
"· {p0}, tranquilo": "· {p0}, tranquillo"
},
"lugares": {
"Ruta de las pirámides": "Via delle piramidi",
"Calderitas y Oxtankah": "Calderitas e Oxtankah",
"Laguna Milagros y Xul-Ha": "Laguna Milagros e Xul-Ha"
}
};
