/* Traducción al idioma «pt» de la parte del viajero. Generado por backend/torre/campana/idiomas.py desde docs/idiomas/pt.tsv: no editar a mano. */
window.IDIOMAS_TRAD = window.IDIOMAS_TRAD || {};
window.IDIOMAS_TRAD["pt"] = {
"frases": {
"<b>Temporada alta.</b> El sur también está lleno ese mes.": "<b>Alta temporada.</b> O sul também está cheio nesse mês.",
"<b>Temporada alta.</b> {p0} está más tranquilo ese mes.": "<b>Alta temporada.</b> {p0} está mais tranquilo nesse mês.",
"<b>Temporada alta</b> quiere decir que ese mes llega {n0} % o más gente que en un mes promedio del año, o que hay {n1} % o más de probabilidad de rebasar el mes más lleno que el lugar ha tenido. Se calcula con los visitantes del INAH a las zonas arqueológicas y, en {p0}, con los cruces desde Belice.": "<b>Alta temporada</b> quer dizer que nesse mês chegam {n0} % de pessoas a mais (ou mais) do que num mês médio do ano, ou que há {n1} % ou mais de probabilidade de superar o mês mais cheio que o lugar já teve. É calculada com os visitantes do INAH às zonas arqueológicas e, em {p0}, com as travessias desde Belize.",
"<b>{p0} en {m0} de {n0}: temporada alta.</b> El sur también está lleno ese mes.": "<b>{p0} em {m0} de {n0}: alta temporada.</b> O sul também está cheio nesse mês.",
"<b>{p0} en {m0} de {n0}: temporada alta.</b> {p1} está más tranquilo ese mes.": "<b>{p0} em {m0} de {n0}: alta temporada.</b> {p1} está mais tranquilo nesse mês.",
"<b>{p1} en {m0} de {n0}: temporada alta.</b> {p0} está más tranquilo ese mes.": "<b>{p1} em {m0} de {n0}: alta temporada.</b> {p0} está mais tranquilo nesse mês.",
"<b>{p1} y {p0}</b> están como referencia, para quien pensaba ir al norte; la campaña no los promueve. Ahí se mide la ocupación de los hoteles: es temporada alta si se espera {n0} % de cuartos ocupados o más, el nivel que el Radar ya cuenta como \"concurrido\". Si el mes está lleno, te recomendamos un lugar del sur. Tómalo con cuidado en la {p0}: su ocupación bajó ({n1} % en {m0} de {n2} contra {n3} % un año antes), el pronóstico supone que sigue así y se equivoca más que solo repetir lo del año anterior; se usa porque es el único cuyo rango sí atrapó el valor real {n4} de cada {n5} veces.": "<b>{p1} e {p0}</b> aparecem como referência, para quem pensava ir ao norte; a campanha não os promove. Lá se mede a ocupação dos hotéis: é alta temporada se se espera {n0} % ou mais de quartos ocupados, o nível que o Radar já conta como \"movimentado\". Se o mês estiver cheio, recomendamos um lugar do sul. Tenha cautela com {p0}: a ocupação caiu ({n1} % em {m0} de {n2} contra {n3} % um ano antes), a previsão supõe que continua assim e erra mais do que simplesmente repetir o ano anterior; é usada porque é a única cuja faixa acertou o valor real {n4} de cada {n5} vezes.",
"<span></span><b>Radar, {m0} de {n0}:</b> {n1} de los {n2} lugares del sur, tranquilos<span> · {p0}, sin dato oficial</span><span> · Ver el Radar →</span>": "<span></span><b>Radar, {m0} de {n0}:</b> {n1} dos {n2} lugares do sul estão tranquilos<span> · {p0}, sem dado oficial</span><span> · Ver o Radar →</span>",
"<span></span>Calderitas: mariscos y la zona de Oxtankah<small>{n0} km →</small>": "<span></span>Calderitas: frutos do mar e a zona de Oxtankah<small>{n0} km →</small>",
"<span></span>Felipe Carrillo Puerto (estación del Tren Maya)<small>{n0} km →</small>": "<span></span>Felipe Carrillo Puerto (estação do Trem Maia)<small>{n0} km →</small>",
"<span></span>Kantemó: la cueva": "<span></span>Kantemó: a caverna",
"<span></span>Kohunlich y Dzibanché, en la selva": "<span></span>Kohunlich e Dzibanché, na selva",
"<span></span>Kohunlich, Dzibanché e Ichkabal": "<span></span>Kohunlich, Dzibanché e Ichkabal",
"<span></span>Laguna Milagros y el cenote de Xul-Ha<small>{n0} km →</small>": "<span></span>A Lagoa Milagros e o cenote de Xul-Ha<small>{n0} km →</small>",
"<span></span>Señor: ecoturismo comunitario<small>{n0} km →</small>": "<span></span>Señor: ecoturismo comunitário<small>{n0} km →</small>",
"<span></span>Tihosuco: el Museo de la Guerra de Castas<small>{n0} km →</small>": "<span></span>Tihosuco: o Museu da Guerra de Castas<small>{n0} km →</small>",
"<span></span>Tranquilo <span></span>Normal <span></span>Temporada alta": "<span></span>Tranquilo <span></span>Normal <span></span>Alta temporada",
"<span></span>{p0}: el malecón y el Museo de la Cultura Maya<small>{n0} km →</small>": "<span></span>{p0}: a orla e o Museu da Cultura Maia<small>{n0} km →</small>",
"<span></span>{p0}: la bahía al atardecer<small>{n0} km →</small>": "<span></span>{p0}: a baía ao pôr do sol<small>{n0} km →</small>",
"<span>★ </span>Reseñas<span> ↗</span><span> en Google Maps (otra pestaña)</span>": "<span>★ </span>Avaliações<span> ↗</span><span> no Google Maps (nova aba)</span>",
"Agencia de viajes y tours · en el centro": "Agência de viagens e passeios · no centro",
"Agencia de viajes y tours · en {p0}, a {n0} km": "Agência de viagens e passeios · em {p0}, a {n0} km",
"Antojitos y tacos para cenar, un bar para cerrar el día y dónde dormir.": "Antojitos e tacos para o jantar, um bar para fechar o dia e onde dormir.",
"Antojitos · a {n0} km del centro": "Antojitos (petiscos mexicanos) · a {n0} km do centro",
"Antojitos · en el centro": "Antojitos (petiscos mexicanos) · no centro",
"Asados y pollos · a {n0} km del centro": "Grelhados e frango · a {n0} km do centro",
"Asados y pollos · en el centro": "Grelhados e frango · no centro",
"Así se ve la {p0}": "Assim é a {p0}",
"Así se ve {p0}": "Assim é {p0}",
"Así va a <em>estar</em>.": "Assim vai <em>estar</em>.",
"Atardecer en el malecón": "Pôr do sol na orla",
"Atardecer en una calle de Calderitas": "Pôr do sol numa rua de Calderitas",
"Atardecer en una calle de Calderitas<small>Foto: {x0}, {x1}</small>": "Pôr do sol numa rua de Calderitas<small>Foto: {x0}, {x1}</small>",
"Atardecer sobre la laguna de {p0}": "Pôr do sol sobre a lagoa de {p0}",
"Atardecer sobre la laguna de {p0}<small>Foto: {x0}, {x1}</small>": "Pôr do sol sobre a lagoa de {p0}<small>Foto: {x0}, {x1}</small>",
"Avenida Constituyentes, en Felipe Carrillo Puerto": "Avenida Constituyentes, em Felipe Carrillo Puerto",
"Aves en un muelle de la Laguna Milagros": "Aves num píer da Lagoa Milagros",
"Bahía y pirámides": "Baía e pirâmides",
"Balneario · a {n0} km del centro": "Lugar para nadar · a {n0} km do centro",
"Balneario · en Calderitas, a {n0} km": "Lugar para nadar · em Calderitas, a {n0} km",
"Balneario · en el centro": "Lugar para nadar · no centro",
"Balneario · en {p0}, a {n0} km": "Lugar para nadar · em {p0}, a {n0} km",
"Bar o cantina · a {n0} km del centro": "Bar ou cantina · a {n0} km do centro",
"Bar o cantina · en el centro": "Bar ou cantina · no centro",
"Bar o cantina · en {p0}, a {n0} km": "Bar ou cantina · em {p0}, a {n0} km",
"Cabañas y villas · a {n0} km del centro": "Cabanas e vilas · a {n0} km do centro",
"Cabañas y villas · en el centro": "Cabanas e vilas · no centro",
"Café, desayunos y postres · a {n0} km del centro": "Café, cafés da manhã e sobremesas · a {n0} km do centro",
"Café, desayunos y postres · en el centro": "Café, cafés da manhã e sobremesas · no centro",
"Café, desayunos y postres · en {p0}, a {n0} km": "Café, cafés da manhã e sobremesas · em {p0}, a {n0} km",
"Cambiar a {p0} en {m0}": "Mudar para {p0} em {m0}",
"Campamento · en Calderitas, a {n0} km": "Camping · em Calderitas, a {n0} km",
"Campamento · en el centro": "Camping · no centro",
"Casa de huéspedes · a {n0} km del centro": "Casa de hóspedes · a {n0} km do centro",
"Casas típicas de madera en el Boulevard Bahía": "Casas típicas de madeira no Boulevard Bahía",
"Casas típicas de madera en el Boulevard Bahía<small>Foto: {x0}, {x1}</small>": "Casas típicas de madeira no Boulevard Bahía<small>Foto: {x0}, {x1}</small>",
"Centro nocturno · a {n0} km del centro": "Casa noturna · a {n0} km do centro",
"Centro nocturno · en el centro": "Casa noturna · no centro",
"Centro nocturno · en {p0}, a {n0} km": "Casa noturna · em {p0}, a {n0} km",
"Cerrar aviso": "Fechar aviso",
"Cerrar preguntas": "Fechar perguntas",
"Cinco lugares": "Cinco lugares",
"Cinco lugares del sur de Quintana Roo: {p4}, {p1}, {p2}, {p3} y {p0}.": "Cinco lugares do sul de Quintana Roo: {p4}, {p1}, {p2}, {p3} e {p0}.",
"Cocina internacional · en el centro": "Cozinha internacional · no centro",
"Cocina yucateca · en el centro": "Cozinha de Yucatán · no centro",
"Comida casera · a {n0} km del centro": "Comida caseira · a {n0} km do centro",
"Comida casera · en el centro": "Comida caseira · no centro",
"Comida para llevar · a {n0} km del centro": "Comida para viagem · a {n0} km do centro",
"Comida para llevar · en el centro": "Comida para viagem · no centro",
"Comida rápida · a {n0} km del centro": "Fast food · a {n0} km do centro",
"Comida rápida · en el centro": "Fast food · no centro",
"Comparte con {p0} la vigilancia del sargazo en la bahía.": "Divide com {p0} a vigilância do sargaço na baía.",
"Con datos oficiales": "Com dados oficiais",
"Cuatro están en el mismo municipio que {p0}.": "Quatro ficam no mesmo município que {p0}.",
"Cómo llega la gente": "Como as pessoas chegam",
"Cómo llegar<span> ↗</span><span> (Google Maps, otra pestaña)</span>": "Como chegar<span> ↗</span><span> (Google Maps, nova aba)</span>",
"De día": "De dia",
"De fuentes oficiales y abiertas: Secretaría de Turismo, gobierno de Quintana Roo, INEGI, INAH, NOAA, Open-Meteo y la Reserva Federal. Las fotos, de Wikimedia Commons con licencia libre.": "De fontes oficiais e abertas: Secretaria de Turismo, governo de Quintana Roo, INEGI, INAH, NOAA, Open-Meteo e o Federal Reserve dos EUA. As fotos são do Wikimedia Commons, com licença livre.",
"De noche": "À noite",
"Del Museo de la Cultura Maya en {p0} al de la Guerra de Castas en Tihosuco: la historia del sur contada desde aquí.": "Do Museu da Cultura Maia em {p0} ao da Guerra de Castas em Tihosuco: a história do sul contada daqui.",
"Del mar a la selva, en un <em>solo</em> viaje.": "Do mar à selva, numa <em>só</em> viagem.",
"Depende del lugar: arriba, en \"Planea tu viaje\", eliges lugar y mes y te decimos cómo va a estar. Por ejemplo, a la {p0} llega {n0} % menos gente que en un mes promedio en {m0}, y {n1} % más en {m1}.": "Depende do lugar: lá em cima, em \"Planeje sua viagem\", você escolhe lugar e mês e nós dizemos como vai estar. Por exemplo, à {p0} chegam {n0} % menos pessoas do que num mês médio em {m0}, e {n1} % mais em {m1}.",
"Distancias en línea recta entre los centros de cada lugar (no hay datos abiertos de distancias por carretera). Sin precios: ninguna fuente oficial los publica. Las reseñas se leen en Google Maps.": "Distâncias em linha reta entre os centros de cada lugar (não há dados abertos de distâncias por estrada). Sem preços: nenhuma fonte oficial os publica. As avaliações se leem no Google Maps.",
"Documento": "Documento",
"Dzibanché: el Templo del Búho": "Dzibanché: o Templo da Coruja",
"Dzibanché: el Templo del Búho, {p0}": "Dzibanché: o Templo da Coruja, {p0}",
"Dzibanché: el Templo del Búho. Foto: {x0}, {x1}, vía Wikimedia Commons.": "Dzibanché: o Templo da Coruja. Foto: {x0}, {x1}, via Wikimedia Commons.",
"Dzibanché: el Templo del Búho<small>Foto: {x0}, {x1}</small>": "Dzibanché: o Templo da Coruja<small>Foto: {x0}, {x1}</small>",
"Dzibanché: la Estructura {n0}": "Dzibanché: a Estrutura {n0}",
"Dzibanché: la Estructura {n0}<small>Foto: {x0}, {x1}</small>": "Dzibanché: a Estrutura {n0}<small>Foto: {x0}, {x1}</small>",
"Dónde comer": "Onde comer",
"Dónde dormir": "Onde dormir",
"El Boulevard Bahía de {p0}: casas de madera, monumentos y el sol bajando sobre el agua.": "O Boulevard Bahía de {p0}: casas de madeira, monumentos e o sol se pondo sobre a água.",
"El Mercado {n0} en el centro de {p0}": "O Mercado {n0}, no centro de {p0}",
"El Mercado {n0} en el centro de {p0}<small>Foto: {x0}, {x1}</small>": "O Mercado {n0}, no centro de {p0}<small>Foto: {x0}, {x1}</small>",
"El Monumento a la Bandera frente a la bahía": "O Monumento à Bandeira de frente para a baía",
"El Monumento a la Bandera frente a la bahía<small>Foto: {x0}, {x1}</small>": "O Monumento à Bandeira de frente para a baía<small>Foto: {x0}, {x1}</small>",
"El Monumento al Pescador al atardecer, en la bahía": "O Monumento ao Pescador ao pôr do sol, na baía",
"El Monumento al Pescador al atardecer, en la bahía, {p0}": "O Monumento ao Pescador ao pôr do sol, na baía, {p0}",
"El Monumento al Pescador al atardecer, en la bahía. Foto: {x0}, {x1}, vía Wikimedia Commons.": "O Monumento ao Pescador ao pôr do sol, na baía. Foto: {x0}, {x1}, via Wikimedia Commons.",
"El Monumento al Pescador al atardecer, en la bahía<small>Foto: {x0}, {x1}</small>": "O Monumento ao Pescador ao pôr do sol, na baía<small>Foto: {x0}, {x1}</small>",
"El Portal Maya del parque Fundadores": "O Portal Maia do parque Fundadores",
"El Portal Maya del parque Fundadores<small>Foto: {x0}, {x1}</small>": "O Portal Maia do parque Fundadores<small>Foto: {x0}, {x1}</small>",
"El Radar": "O Radar",
"El agua turquesa de la Laguna Milagros": "A água turquesa da Lagoa Milagros",
"El cenote de Xul-Ha": "O cenote de Xul-Ha",
"El clima es el normal de {n0} a {n1}. El riesgo de tormenta cuenta las tormentas que pasaron a {n2} km o menos del lugar desde {n3} ({n4} en el caso de {p1}). {p0} y la Laguna Milagros no tienen estadística oficial de visitantes, así que no están en el planeador; los encuentras en \"Los lugares\".": "O clima é o normal de {n0} a {n1}. O risco de tempestade conta as tempestades que passaram a {n2} km ou menos do lugar desde {n3} ({n4} no caso de {p1}). {p0} e a Lagoa Milagros não têm estatística oficial de visitantes, por isso não estão no planejador; você os encontra em \"Os lugares\".",
"El dato": "O dado",
"El dinero": "O dinheiro",
"El kiosco del centro de {p0}": "O coreto do centro de {p0}",
"El kiosco del centro de {p0}<small>Foto: {x0}, {x1}</small>": "O coreto do centro de {p0}<small>Foto: {x0}, {x1}</small>",
"El norte": "O norte",
"El parque y los restaurantes de Calderitas al atardecer": "O parque e os restaurantes de Calderitas ao pôr do sol",
"El parque y los restaurantes de Calderitas al atardecer<small>Foto: {x0}, {x1}</small>": "O parque e os restaurantes de Calderitas ao pôr do sol<small>Foto: {x0}, {x1}</small>",
"El problema": "O problema",
"El sur": "O sul",
"El sur tiene <em>espacio</em>.": "O sul tem <em>espaço</em>.",
"El sur tiene <em>espacio</em>.<br>Y te está esperando.": "O sul tem <em>espaço</em>.<br>E está esperando por você.",
"Elige a dónde y cuándo. Te decimos cómo va a estar.": "Escolha onde e quando. Nós dizemos como vai estar.",
"En Calderitas, a {n0} km de {p0}, se come viendo el agua; al lado está Oxtankah, la ciudad maya de la bahía.": "Em Calderitas, a {n0} km de {p0}, come-se olhando a água; ao lado fica Oxtankah, a cidade maia da baía.",
"En Felipe Carrillo Puerto, Señor y Tihosuco las comunidades mayas reciben a quien llega: selva, historia y su forma de vivir.": "Em Felipe Carrillo Puerto, Señor e Tihosuco, as comunidades maias recebem quem chega: selva, história e seu modo de vida.",
"En la costa de {p1} y Calderitas no hay reporte de sargazo. Sí apareció en los canales de entrada de la bahía ({m0} de {n0}), así que se vigila. La ruta de las pirámides, {p0} y la laguna están lejos del mar abierto.": "Na costa de {p1} e Calderitas não há relatos de sargaço. Ele apareceu nos canais de entrada da baía ({m0} de {n0}), por isso é vigiado. A rota das pirâmides, {p0} e a lagoa ficam longe do mar aberto.",
"En los municipios de los cinco lugares no hay ningún hospedaje grande: {n0} son chicos (hasta {n1} personas) y {n2} medianos. La derrama económica por destino no se muestra porque la fuente no dice en qué unidad está.": "Nos municípios dos cinco lugares não há nenhuma hospedagem grande: {n0} são pequenas (até {n1} pessoas) e {n2} médias. O gasto turístico por destino não é mostrado porque a fonte não diz em que unidade está.",
"En {m0} el sur también tiene temporada alta. Si puedes mover tu viaje, busca los meses en verde.": "Em {m0} o sul também está em alta temporada. Se puder mudar sua viagem, procure os meses em verde.",
"En {m0}, <b>{p0}</b> no está en temporada alta: hay espacio, sin el gentío del norte.": "Em {m0}, <b>{p0}</b> não está em alta temporada: há espaço, sem a multidão do norte.",
"En {m0}, <b>{p1}</b> está más tranquilo. O ve a la {p0} en <b>{m1}</b>: menos gente, poca lluvia y fuera de la temporada de tormentas.": "Em {m0}, <b>{p1}</b> está mais tranquilo. Ou vá à {p0} em <b>{m1}</b>: menos gente, pouca chuva e fora da temporada de tempestades.",
"En {m0}, <b>{p1}</b> está más tranquilo. O ve a {p0} en <b>{m1}</b>: menos gente, poca lluvia y fuera de la temporada de tormentas.": "Em {m0}, <b>{p1}</b> está mais tranquilo. Ou vá a {p0} em <b>{m1}</b>: menos gente, pouca chuva e fora da temporada de tempestades.",
"En {n0} llegaron {n1} pasajeros en avión a {p1}, y el Tren Maya para en {p1}, Bacalar y Felipe Carrillo Puerto ({p0}). Solo en {m0} de {n2} {n3} personas bajaron del tren en {p1}.": "Em {n0} chegaram {n1} passageiros de avião a {p1}, e o Trem Maia para em {p1}, Bacalar e Felipe Carrillo Puerto ({p0}). Só em {m0} de {n2}, {n3} pessoas desceram do trem em {p1}.",
"Enviar pregunta": "Enviar pergunta",
"Escribe tu pregunta": "Escreva sua pergunta",
"Escribe tu pregunta…": "Escreva sua pergunta…",
"Ese mes todavía no está en el pronóstico (llega hasta {m0} de {n0}): en un {m1} típico, de {n1} a {n2} los hoteles estuvieron al <b>{n3} %</b>.": "Esse mês ainda não está na previsão (vai até {m0} de {n0}): num {m1} típico, de {n1} a {n2}, os hotéis estavam a <b>{n3} %</b>.",
"Ese mes todavía no está en el pronóstico (llega hasta {m0} de {n0}): esto es lo típico de {m1}.": "Esse mês ainda não está na previsão (vai até {m0} de {n0}): isto é o típico de {m1}.",
"Esta parte está en español: son los datos técnicos del proyecto.": "Esta parte está em espanhol: são os dados técnicos do projeto.",
"Estructura {n0} de Oxtankah, con pintura original": "Estrutura {n0} de Oxtankah, com a pintura original",
"Estructura {n0} de Oxtankah, con pintura original<small>Foto: {x0}, {x1}</small>": "Estrutura {n0} de Oxtankah, com a pintura original<small>Foto: {x0}, {x1}</small>",
"Fotos de los cinco lugares; se pueden recorrer con las flechas": "Fotos dos cinco lugares; dá para percorrê-las com as setas",
"Fuente: ECOSUR y notas del {n0} de {m0} de {n1}": "Fonte: ECOSUR e notícias de {n0} de {m0} de {n1}",
"Fuente: Gobierno de Quintana Roo (SITUR-Q)": "Fonte: Governo de Quintana Roo (SITUR-Q)",
"Fuente: INAH (BdINAH) y forma del año del proyecto (Fase {n0})": "Fonte: INAH (BdINAH) e forma do ano do projeto (Fase {n0})",
"Fuente: INAH (BdINAH), SITUR-Q (frontera con Belice), SECTUR-DataTur (ocupación hotelera de {p1} y {p0}), NOAA HURDAT2, Open-Meteo (clima {n0}–{n1}) y pronóstico del proyecto (Fase {n2}); negocios: INEGI, DENUE.": "Fonte: INAH (BdINAH), SITUR-Q (fronteira com Belize), SECTUR-DataTur (ocupação hoteleira de {p1} e {p0}), NOAA HURDAT2, Open-Meteo (clima {n0}–{n1}) e previsão do projeto (Fase {n2}); negócios: INEGI, DENUE.",
"Fuente: INEGI (DENUE) y SITUR-Q": "Fonte: INEGI (DENUE) e SITUR-Q",
"Fuente: INEGI y gobierno de Quintana Roo": "Fonte: INEGI e governo de Quintana Roo",
"Fuente: INEGI, Directorio Estadístico Nacional de Unidades Económicas (DENUE). El tipo de lugar y el momento del día los sugiere un clasificador de texto que lee el nombre y el giro oficial de cada negocio (acertó {n0} de {n1} en una revisión al azar). Cuando un lugar no tiene algo cerca, se muestra lo más cercano de los otros lugares del sur. \"Ver en Google Maps\" abre Google Maps en otra pestaña; esta página no descarga nada de Google.": "Fonte: INEGI, Diretório Estatístico Nacional de Unidades Econômicas (DENUE). O tipo de lugar e o momento do dia são sugeridos por um classificador de texto que lê o nome e a atividade oficial de cada negócio (acertou {n0} de {n1} numa verificação aleatória). Quando um lugar não tem algo perto, mostra-se o mais próximo dos outros lugares do sul. \"Ver no Google Maps\" abre o Google Maps em outra aba; esta página não baixa nada do Google.",
"Fuente: Inventario de fuentes del proyecto": "Fonte: inventário de fontes do projeto",
"Fuente: Secretaría de Turismo y notas verificadas de {n0}": "Fonte: Secretaria de Turismo e notícias verificadas de {n0}",
"Fuente: Selección de regiones del proyecto": "Fonte: seleção de regiões do projeto",
"Fuente: Torre del Caribe": "Fonte: Torre del Caribe",
"Girar el mapa solo": "Girar o mapa sozinho",
"Habrá mucha gente: los hoteles suelen pasar del {n0} % de cuartos ocupados, lo que el Radar ya cuenta como \"concurrido\".": "Vai ter muita gente: os hotéis costumam passar de {n0} % de quartos ocupados, o que o Radar já conta como \"movimentado\".",
"Habrá mucha gente: se espera que los hoteles pasen del {n0} % de cuartos ocupados, lo que el Radar ya cuenta como \"concurrido\".": "Vai ter muita gente: espera-se que os hotéis passem de {n0} % de quartos ocupados, o que o Radar já conta como \"movimentado\".",
"Hasta {m0} de {n0} hay un pronóstico con su rango: el valor real cayó dentro de ese rango entre {n1} y {n2} de cada {n3} veces cuando se probó con meses que el modelo nunca vio. Después de esa fecha se muestra lo típico de cada mes.": "Até {m0} de {n0} há uma previsão com sua faixa: o valor real caiu dentro dessa faixa entre {n1} e {n2} de cada {n3} vezes quando foi testada com meses que o modelo nunca viu. Depois dessa data mostra-se o típico de cada mês.",
"Hay espacio: los hoteles suelen quedar debajo del {n0} % de cuartos ocupados, lo que el Radar cuenta como \"concurrido\".": "Há espaço: os hotéis costumam ficar abaixo de {n0} % de quartos ocupados, o que o Radar conta como \"movimentado\".",
"Hay espacio: se espera que los hoteles queden debajo del {n0} % de cuartos ocupados, lo que el Radar cuenta como \"concurrido\".": "Há espaço: espera-se que os hotéis fiquem abaixo de {n0} % de quartos ocupados, o que o Radar conta como \"movimentado\".",
"Hay lugar: {n0} de cada {n1} cuartos de hotel de {p0} se quedaron vacíos en {n2}. <small>Fuente: Gobierno de Quintana Roo (SITUR-Q)</small>": "Há vaga: {n0} de cada {n1} quartos de hotel de {p0} ficaram vazios em {n2}. <small>Fonte: Governo de Quintana Roo (SITUR-Q)</small>",
"Hay pocos cuartos de hotel: la campaña pone un límite de visitantes para no rebasar a los pueblos.": "Há poucos quartos de hotel: a campanha põe um limite de visitantes para não sobrecarregar os povoados.",
"Hola. Pregúntame sobre los cinco lugares, cómo llegar o de dónde salen los datos.": "Olá. Pergunte-me sobre os cinco lugares, como chegar ou de onde vêm os dados.",
"Hospedaje de la gente de aquí: en los municipios de los cinco lugares hay {n0} hospedajes chicos, {n1} medianos y {n2} grandes. <small>Fuente: INEGI (DENUE)</small>": "Hospedagem da gente daqui: nos municípios dos cinco lugares há {n0} hospedagens pequenas, {n1} médias e {n2} grandes. <small>Fonte: INEGI (DENUE)</small>",
"Hostal · en el centro": "Hostel · no centro",
"Hostal · en {p0}, a {n0} km": "Hostel · em {p0}, a {n0} km",
"Hotel · en Xul-ha, a {n0} km": "Hotel · em Xul-Ha, a {n0} km",
"Hotel · en el centro": "Hotel · no centro",
"Hotel · en {p0}, a {n0} km": "Hotel · em {p0}, a {n0} km",
"Idioma": "Idioma",
"Idioma / Language": "Idioma / Language",
"Iglesia en Felipe Carrillo Puerto": "Igreja em Felipe Carrillo Puerto",
"Iglesia en Felipe Carrillo Puerto. Foto: {x0}, {x1}, vía Wikimedia Commons.": "Igreja em Felipe Carrillo Puerto. Foto: {x0}, {x1}, via Wikimedia Commons.",
"Jardín botánico o zoológico · a {n0} km del centro": "Jardim botânico ou zoológico · a {n0} km do centro",
"Jardín botánico o zoológico · en el centro": "Jardim botânico ou zoológico · no centro",
"Jardín botánico o zoológico · en {p0}, a {n0} km": "Jardim botânico ou zoológico · em {p0}, a {n0} km",
"Kohunlich, Dzibanché e Ichkabal: ciudades mayas entre la selva, con sus mascarones y templos.": "Kohunlich, Dzibanché e Ichkabal: cidades maias na selva, com suas máscaras e templos.",
"Kohunlich, Dzibanché e Ichkabal: tres ciudades mayas en la selva, lejos del mar.": "Kohunlich, Dzibanché e Ichkabal: três cidades maias na selva, longe do mar.",
"Kohunlich, Dzibanché e Ichkabal: tres ciudades mayas en la selva, lejos del mar. Tiene {n0} lugares para comer y {n1} para dormir. Cuidado: los poblados cercanos casi no tienen hoteles: la visita se hace desde {p0}.": "Kohunlich, Dzibanché e Ichkabal: três cidades maias na selva, longe do mar. Tem {n0} lugares para comer e {n1} para dormir. Cuidado: os povoados próximos quase não têm hotéis, a visita se faz a partir de {p0}.",
"Kohunlich: detalle de un mascarón": "Kohunlich: detalhe de uma máscara",
"Kohunlich: detalle de un mascarón<small>Foto: {x0}, {x1}</small>": "Kohunlich: detalhe de uma máscara<small>Foto: {x0}, {x1}</small>",
"Kohunlich: el juego de pelota": "Kohunlich: o campo do jogo de bola",
"Kohunlich: el juego de pelota<small>Foto: {x0}, {x1}</small>": "Kohunlich: o campo do jogo de bola<small>Foto: {x0}, {x1}</small>",
"Kohunlich: los mascarones de estuco": "Kohunlich: as máscaras de estuque",
"Kohunlich: los mascarones de estuco<small>Foto: {x0}, {x1}</small>": "Kohunlich: as máscaras de estuque<small>Foto: {x0}, {x1}</small>",
"Kohunlich: una de sus plataformas en la selva": "Kohunlich: uma de suas plataformas na selva",
"Kohunlich: una de sus plataformas en la selva<small>Foto: {x0}, {x1}</small>": "Kohunlich: uma de suas plataformas na selva<small>Foto: {x0}, {x1}</small>",
"La Campana del Bicentenario": "O Sino do Bicentenário",
"La Campana del Bicentenario<small>Foto: {x0}, {x1}</small>": "O Sino do Bicentenário<small>Foto: {x0}, {x1}</small>",
"La Laguna Milagros y el cenote de Xul-Ha, a {n0} km de {p0}. Es frágil: se nada sin bloqueador y sin dejar nada.": "A Lagoa Milagros e o cenote de Xul-Ha, a {n0} km de {p0}. É frágil: nada-se sem protetor solar e sem deixar nada.",
"La Quinta Avenida de Playa del Carmen": "A Quinta Avenida de Playa del Carmen",
"La Quinta Avenida de Playa del Carmen<small>Foto: {x0}, {x1}</small>": "A Quinta Avenida de Playa del Carmen<small>Foto: {x0}, {x1}</small>",
"La bahía de {p0} desde el Boulevard": "A baía de {p0} vista do Boulevard",
"La bahía de {p0} desde el Boulevard. Foto: {x0}, {x1}, vía Wikimedia Commons.": "A baía de {p0} vista do Boulevard. Foto: {x0}, {x1}, via Wikimedia Commons.",
"La bahía frente a Calderitas": "A baía em frente a Calderitas",
"La bahía frente a Calderitas. Foto: {x0}, {x1}, vía Wikimedia Commons.": "A baía em frente a Calderitas. Foto: {x0}, {x1}, via Wikimedia Commons.",
"La bahía vista desde Calderitas": "A baía vista de Calderitas",
"La bahía vista desde Calderitas, {p0}": "A baía vista de Calderitas, {p0}",
"La bahía vista desde Calderitas. Foto: {x0}, {x1}, vía Wikimedia Commons.": "A baía vista de Calderitas. Foto: {x0}, {x1}, via Wikimedia Commons.",
"La bahía vista desde Calderitas<small>Foto: {x0}, {x1}</small>": "A baía vista de Calderitas<small>Foto: {x0}, {x1}</small>",
"La capilla antigua dentro de la zona de Oxtankah": "A antiga capela dentro da zona de Oxtankah",
"La capilla antigua dentro de la zona de Oxtankah<small>Foto: {x0}, {x1}</small>": "A antiga capela dentro da zona de Oxtankah<small>Foto: {x0}, {x1}</small>",
"La capilla de Nuestra Señora del Carmen": "A capela de Nossa Senhora do Carmo",
"La capilla de Nuestra Señora del Carmen<small>Foto: {x0}, {x1}</small>": "A capela de Nossa Senhora do Carmo<small>Foto: {x0}, {x1}</small>",
"La capital del estado, frente a la bahía, con el Museo de la Cultura Maya.": "A capital do estado, de frente para a baía, com o Museu da Cultura Maia.",
"La capital del estado, frente a la bahía, con el Museo de la Cultura Maya. Tiene {n0} lugares para comer y {n1} para dormir; {n2} personas llegaron en el Tren Maya en {m0} de {n3}. Cuidado: se vigila el sargazo que apareció en los canales de entrada de la bahía ({m1} de {n4}).": "A capital do estado, de frente para a baía, com o Museu da Cultura Maia. Tem {n0} lugares para comer e {n1} para dormir; {n2} pessoas chegaram no Trem Maia em {m0} de {n3}. Cuidado: vigia-se o sargaço que apareceu nos canais de entrada da baía ({m1} de {n4}).",
"La gran pirámide de Dzibanché en la selva": "A grande pirâmide de Dzibanché na selva",
"La gran pirámide de Dzibanché en la selva. Foto: {x0}, {x1}, vía Wikimedia Commons.": "A grande pirâmide de Dzibanché na selva. Foto: {x0}, {x1}, via Wikimedia Commons.",
"La laguna Nichupté": "A lagoa Nichupté",
"La laguna Nichupté<small>Foto: {x0}, {x1}</small>": "A lagoa Nichupté<small>Foto: {x0}, {x1}</small>",
"La laguna es frágil: visitas con límite estricto y sin actividades que la dañen.": "A lagoa é frágil: visitas com limite estrito e sem atividades que a prejudiquem.",
"La orilla de la laguna en Huay-Pix": "A margem da lagoa em Huay-Pix",
"La playa del pueblo, en Playa del Carmen": "A praia do povoado, em Playa del Carmen",
"La playa del pueblo, en Playa del Carmen<small>Foto: {x0}, {x1}</small>": "A praia do povoado, em Playa del Carmen<small>Foto: {x0}, {x1}</small>",
"Laguna y selva": "Lagoa e selva",
"Las fases": "As fases",
"Las fotos son de Wikimedia Commons, con licencia libre, y cada una se tomó dentro del municipio del lugar (su coordenada se comprobó con el mapa oficial).": "As fotos são do Wikimedia Commons, com licença livre, e cada uma foi tirada dentro do município do lugar (sua coordenada foi conferida com o mapa oficial).",
"Llega más o menos la gente de un mes promedio.": "Chega mais ou menos a gente de um mês médio.",
"Llega {n0} % menos gente que en un mes promedio: hay espacio.": "{n0} % menos gente do que num mês médio: há espaço.",
"Llega {n0} % más gente que en un mes promedio, y hay {n1} % de probabilidad de rebasar el mes más lleno de su historia.": "{n0} % mais gente do que num mês médio, e {n1} % de probabilidade de superar o mês mais cheio da sua história.",
"Llega {n0} % más gente que en un mes promedio.": "{n0} % mais gente do que num mês médio.",
"Lo que hay <em>detrás</em> del viaje.": "O que há <em>por trás</em> da viagem.",
"Lo que no te <em>cuentan</em> del Caribe.": "O que não te <em>contam</em> sobre o Caribe.",
"Lo que todos <em>preguntan</em>.": "O que todo mundo <em>pergunta</em>.",
"Los Voladores en el parque Fundadores": "Os Voladores no parque Fundadores",
"Los Voladores en el parque Fundadores<small>Foto: {x0}, {x1}</small>": "Os Voladores no parque Fundadores<small>Foto: {x0}, {x1}</small>",
"Los datos": "Os dados",
"Los lugares": "Os lugares",
"Los lugares del sur con estadística están en temporada alta este mes. Mejor ve a la {p0} en <b>{m0}</b>: menos gente, poca lluvia y fuera de la temporada de tormentas.": "Os lugares do sul com estatística estão em alta temporada este mês. Melhor ir à {p0} em <b>{m0}</b>: menos gente, pouca chuva e fora da temporada de tempestades.",
"Los lugares del sur con estadística están en temporada alta este mes. Mejor ve a {p0} en <b>{m0}</b>: menos gente, poca lluvia y fuera de la temporada de tormentas.": "Os lugares do sul com estatística estão em alta temporada este mês. Melhor ir a {p0} em <b>{m0}</b>: menos gente, pouca chuva e fora da temporada de tempestades.",
"Los poblados cercanos casi no tienen hoteles: la visita se hace desde {p0}.": "Os povoados próximos quase não têm hotéis: a visita se faz a partir de {p0}.",
"Lugar": "Lugar",
"Lugares reales del directorio de negocios del INEGI, del más cercano al más lejano. No son reseñas ni anuncios pagados y el directorio no publica horarios: confirma antes de ir.": "Lugares reais do diretório de negócios do INEGI, do mais próximo ao mais distante. Não são avaliações nem anúncios pagos, e o diretório não publica horários: confirme antes de ir.",
"Maqueta del sur de Quintana Roo. Arrastra para girarla.": "Maquete do sul de Quintana Roo. Arraste para girá-la.",
"Mariposa búho cerca de Chunhuhub": "Borboleta-coruja perto de Chunhuhub",
"Mariposa en la selva cerca de Chunhuhub": "Borboleta na selva perto de Chunhuhub",
"Mariscos frente a la bahía": "Frutos do mar de frente para a baía",
"Mariscos y pescado · a {n0} km del centro": "Frutos do mar e peixe · a {n0} km do centro",
"Mariscos y pescado · en el centro": "Frutos do mar e peixe · no centro",
"Mejor mes: <b>{m0}</b> · el mes más seco y sin tormentas (no hay estadística de visitantes)": "Melhor mês: <b>{m0}</b> · o mês mais seco e sem tempestades (não há estatística de visitantes)",
"Mejor mes: <b>{m0}</b> · menos gente, poca lluvia y sin temporada de tormentas": "Melhor mês: <b>{m0}</b> · menos gente, pouca chuva e sem temporada de tempestades",
"Mejor ve al sur": "Melhor ir ao sul",
"Menú": "Menu",
"Mes": "Mês",
"Mes normal": "Mês normal",
"Mes tranquilo": "Mês tranquilo",
"Modo noche": "Modo noturno",
"Museo · a {n0} km del centro": "Museu · a {n0} km do centro",
"Museo · en el centro": "Museu · no centro",
"Museo · en {p0}, a {n0} km": "Museu · em {p0}, a {n0} km",
"Museos de la cultura maya": "Museus da cultura maia",
"Nadar en la Laguna Milagros": "Nadar na Lagoa Milagros",
"No damos precios: ninguna fuente oficial abierta publica tarifas de hotel por lugar, y no las inventamos. Lo que sí sabemos es que en el sur los hoteles son chicos: {n0} cuartos por hotel en {p0} contra {n1} en {p1} ({m0} de {n2}).": "Não damos preços: nenhuma fonte oficial aberta publica tarifas de hotel por lugar, e não as inventamos. O que sabemos é que no sul os hotéis são pequenos: {n0} quartos por hotel em {p0} contra {n1} em {p1} ({m0} de {n2}).",
"No hay estadística oficial de visitantes: por eso se cuida con un límite estricto de gente. <small>Fuente: Selección de regiones del proyecto</small>": "Não há estatística oficial de visitantes: por isso é protegida com um limite estrito de pessoas. <small>Fonte: seleção de regiões do projeto</small>",
"Palapas en Huay-Pix, a la orilla de la laguna": "Palapas em Huay-Pix, à beira da lagoa",
"Parque · a {n0} km del centro": "Parque · a {n0} km do centro",
"Parque · en {p0}, a {n0} km": "Parque · em {p0}, a {n0} km",
"Paseo en lancha · en el centro": "Passeio de barco · no centro",
"Paseo en lancha · en {p0}, a {n0} km": "Passeio de barco · em {p0}, a {n0} km",
"Pirámide de la Tumba {n0} en Oxtankah": "Pirâmide da Tumba {n0} em Oxtankah",
"Pirámide de la Tumba {n0} en Oxtankah<small>Foto: {x0}, {x1}</small>": "Pirâmide da Tumba {n0} em Oxtankah<small>Foto: {x0}, {x1}</small>",
"Pirámides en la selva": "Pirâmides na selva",
"Pizzas y hamburguesas · a {n0} km del centro": "Pizzas e hambúrgueres · a {n0} km do centro",
"Pizzas y hamburguesas · en el centro": "Pizzas e hambúrgueres · no centro",
"Planea tu viaje": "Planeje sua viagem",
"Planea tu viaje · el sur de Quintana Roo": "Planeje sua viagem · o sul de Quintana Roo",
"Playa Gaviota Azul, en la punta de {p0}": "Praia Gaviota Azul, na ponta de {p0}",
"Playa Gaviota Azul, en la punta de {p0}, {p0}": "Praia Gaviota Azul, na ponta de {p0}, {p0}",
"Playa Gaviota Azul, en la punta de {p0}. Foto: {x0}, {x1}, vía Wikimedia Commons.": "Praia Gaviota Azul, na ponta de {p0}. Foto: {x0}, {x1}, via Wikimedia Commons.",
"Playa Gaviota Azul, en la punta de {p0}<small>Foto: {x0}, {x1}</small>": "Praia Gaviota Azul, na ponta de {p0}<small>Foto: {x0}, {x1}</small>",
"Playa de la zona hotelera de {p0}": "Praia da zona hoteleira de {p0}",
"Playa de la zona hotelera de {p0}<small>Foto: {x0}, {x1}</small>": "Praia da zona hoteleira de {p0}<small>Foto: {x0}, {x1}</small>",
"Playa del Carmen desde el aire": "Playa del Carmen vista do alto",
"Playa del Carmen desde el aire, {p0}": "Playa del Carmen vista do alto, {p0}",
"Playa del Carmen desde el aire. Foto: {x0}, {x1}, vía Wikimedia Commons.": "Playa del Carmen vista do alto. Foto: {x0}, {x1}, via Wikimedia Commons.",
"Playa del Carmen desde el aire<small>Foto: {x0}, {x1}</small>": "Playa del Carmen vista do alto<small>Foto: {x0}, {x1}</small>",
"Por la tarde": "À tarde",
"Posada · a {n0} km del centro": "Pousada · a {n0} km do centro",
"Posada · en el centro": "Pousada · no centro",
"Posada · en {p0}, a {n0} km": "Pousada · em {p0}, a {n0} km",
"Postales del sur": "Cartões-postais do sul",
"Postales del sur · fotos tomadas en cada lugar": "Cartões-postais do sul · fotos tiradas em cada lugar",
"Preguntas": "Perguntas",
"Preguntas frecuentes": "Perguntas frequentes",
"Preguntas rápidas": "Perguntas rápidas",
"Pregúntanos": "Pergunte-nos",
"Pueblo de pescadores junto a la bahía y la zona arqueológica de Oxtankah, casi siempre sin filas.": "Vila de pescadores junto à baía e à zona arqueológica de Oxtankah, quase sempre sem filas.",
"Pueblo de pescadores junto a la bahía y la zona arqueológica de Oxtankah, casi siempre sin filas. Tiene {n0} lugares para comer y {n1} para dormir. Cuidado: comparte con {p0} la vigilancia del sargazo en la bahía.": "Vila de pescadores junto à baía e à zona arqueológica de Oxtankah, quase sempre sem filas. Tem {n0} lugares para comer e {n1} para dormir. Cuidado: divide com {p0} a vigilância do sargaço na baía.",
"Pueblos de {p0}": "Povoados de {p0}",
"Pueblos mayas con turismo comunitario y la cueva de Kantemó.": "Povoados maias com turismo comunitário e a caverna de Kantemó.",
"Pueblos mayas con turismo comunitario y la cueva de Kantemó. Tiene {n0} lugares para comer y {n1} para dormir; {n2} personas llegaron en el Tren Maya en {m0} de {n3}. Cuidado: hay pocos cuartos de hotel: la campaña pone un límite de visitantes para no rebasar a los pueblos.": "Povoados maias com turismo comunitário e a caverna de Kantemó. Tem {n0} lugares para comer e {n1} para dormir; {n2} pessoas chegaram no Trem Maia em {m0} de {n3}. Cuidado: há poucos quartos de hotel, por isso a campanha põe um limite de visitantes para não sobrecarregar os povoados.",
"Qué hacer": "O que fazer",
"Radar, {m0} de {n0}:": "Radar, {m0} de {n0}:",
"Recreación · a {n0} km del centro": "Lazer · a {n0} km do centro",
"Recreación · en Xul-ha, a {n0} km": "Lazer · em Xul-Ha, a {n0} km",
"Recreación · en el centro": "Lazer · no centro",
"Recreación · en {p0}, a {n0} km": "Lazer · em {p0}, a {n0} km",
"Respondo con los datos del proyecto. Si no lo sé, lo digo.": "Respondo com os dados do projeto. Se não sei, digo.",
"Restaurante Bahía Villamar, en una casa de madera": "Restaurante Bahía Villamar, numa casa de madeira",
"Restaurante Bahía Villamar, en una casa de madera<small>Foto: {x0}, {x1}</small>": "Restaurante Bahía Villamar, numa casa de madeira<small>Foto: {x0}, {x1}</small>",
"Restaurante a la carta · a {n0} km del centro": "Restaurante à la carte · a {n0} km do centro",
"Restaurante a la carta · en el centro": "Restaurante à la carte · no centro",
"Rutas de {n0} y {n1} días": "Roteiros de {n0} e {n1} dias",
"Saltar al contenido": "Pular para o conteúdo",
"Se espera alrededor de <b>{n0} %</b> de los cuartos de hotel ocupados, muy probablemente entre {n1} y {n2} %.": "Espera-se cerca de <b>{n0} %</b> dos quartos de hotel ocupados, muito provavelmente entre {n1} e {n2} %.",
"Se esperan alrededor de <b>{n0}</b> cruces desde Belice, muy probablemente entre {n1} y {n2}.": "Esperam-se cerca de <b>{n0}</b> travessias desde Belize, muito provavelmente entre {n1} e {n2}.",
"Se esperan alrededor de <b>{n0}</b> visitantes a Kohunlich, Dzibanché e Ichkabal, muy probablemente entre {n1} y {n2}.": "Esperam-se cerca de <b>{n0}</b> visitantes a Kohunlich, Dzibanché e Ichkabal, muito provavelmente entre {n1} e {n2}.",
"Se esperan alrededor de <b>{n0}</b> visitantes a la zona de Oxtankah, muy probablemente entre {n1} y {n2}.": "Esperam-se cerca de <b>{n0}</b> visitantes à zona de Oxtankah, muito provavelmente entre {n1} e {n2}.",
"Se vigila el sargazo que apareció en los canales de entrada de la bahía ({m0} de {n0}).": "Vigia-se o sargaço que apareceu nos canais de entrada da baía ({m0} de {n0}).",
"Secciones": "Seções",
"Seis experiencias con lugares reales y una cifra oficial cada una. Sin precios: ninguna fuente oficial los publica.": "Seis experiências com lugares reais e um dado oficial cada uma. Sem preços: nenhuma fonte oficial os publica.",
"Sin dato": "Sem dado",
"Sin dato oficial": "Sem dado oficial",
"Sí: en {n0} {n1} de cada {n2} cuartos de hotel de {p0} se quedaron vacíos ({n3} de {n4} noches ocupadas).": "Sim: em {n0}, {n1} de cada {n2} quartos de hotel de {p0} ficaram vazios ({n3} de {n4} noites ocupadas).",
"Tacos y tortas · a {n0} km del centro": "Tacos e tortas · a {n0} km do centro",
"Tacos y tortas · en el centro": "Tacos e tortas · no centro",
"Te conviene más": "Vale mais a pena",
"Temporada alta": "Alta temporada",
"Temporada alta.": "Alta temporada.",
"Tienen sargazo y se llenan: en su semana más llena, {p0} tuvo {n0} de cada {n1} cuartos ocupados, y en Tulum se reportaron cierres de negocios en {n2}. La campaña lleva gente a donde sí hay espacio.": "Têm sargaço e lotam: na semana mais cheia, {p0} teve {n0} de cada {n1} quartos ocupados, e em Tulum houve fechamento de negócios em {n2}. A campanha leva as pessoas aonde há espaço de verdade.",
"Todo lo que viste arriba sale de datos oficiales, modelos y pruebas. Esta parte es para quien quiera revisar cómo lo sabemos.": "Tudo o que você viu acima vem de dados oficiais, modelos e testes. Esta parte é para quem quiser conferir como sabemos.",
"Tranquilo": "Tranquilo",
"Tu viaje": "Sua viagem",
"Turismo comunitario maya": "Turismo comunitário maia",
"Un balneario o un parque, y a comer: mariscos, cocina yucateca o comida casera.": "Um lugar para nadar ou um parque, e depois comer: frutos do mar, cozinha de Yucatán ou comida caseira.",
"Un día en <em>{p0}</em>": "Um dia em <em>{p0}</em>",
"Un equipo de estudiantes de Ciencias de Datos para Negocios de la Universidad Nacional Rosario Castellanos (UNRC), como proyecto escolar {n0}-{n1}.": "Uma equipe de estudantes de Ciência de Dados para Negócios da Universidade Nacional Rosario Castellanos (UNRC), como projeto escolar {n0}-{n1}.",
"Un matapalo en la selva de Felipe Carrillo Puerto": "Uma figueira-mata-pau na selva de Felipe Carrillo Puerto",
"Un muelle en la Laguna Milagros": "Um píer na Lagoa Milagros",
"Un muelle en la Laguna Milagros. Foto: {x0}, {x1}, vía Wikimedia Commons.": "Um píer na Lagoa Milagros. Foto: {x0}, {x1}, via Wikimedia Commons.",
"Una laguna del mismo sistema que Bacalar, con pueblos a la orilla.": "Uma lagoa do mesmo sistema de Bacalar, com povoados na margem.",
"Una laguna del mismo sistema que Bacalar, con pueblos a la orilla. Tiene {n0} lugares para comer y {n1} para dormir. Cuidado: la laguna es frágil: visitas con límite estricto y sin actividades que la dañen.": "Uma lagoa do mesmo sistema de Bacalar, com povoados na margem. Tem {n0} lugares para comer e {n1} para dormir. Cuidado: a lagoa é frágil, então as visitas têm limite estrito e nenhuma atividade que a prejudique.",
"Una laguna dulce y un cenote": "Uma lagoa de água doce e um cenote",
"Unas {n0} personas al día entre las tres zonas en {n1}: tienes la pirámide casi para ti. <small>Fuente: INAH</small>": "Umas {n0} pessoas por dia nas três zonas juntas em {n1}: a pirâmide fica quase só para você. <small>Fonte: INAH</small>",
"Ver cómo está en {m0}": "Ver como está em {m0}",
"Ver cómo va a estar": "Ver como vai estar",
"Ver la {p0} en {m0}": "Ver a {p0} em {m0}",
"Ver todo el mapa": "Ver o mapa inteiro",
"Ver {p0} en {m0}": "Ver {p0} em {m0}",
"Vive el sur": "Viva o sul",
"Zona arqueológica (INAH)": "Zona arqueológica (INAH)",
"Zona arqueológica de El Meco": "Zona arqueológica de El Meco",
"Zona arqueológica de El Meco<small>Foto: {x0}, {x1}</small>": "Zona arqueológica de El Meco<small>Foto: {x0}, {x1}</small>",
"Zonas arqueológicas, museos y paseos; para empezar, un café o un desayuno.": "Zonas arqueológicas, museus e passeios; para começar, um café ou um café da manhã.",
"de lluvia en un {m0} normal": "de chuva num {m0} normal",
"de máxima, en promedio": "de máxima, em média",
"de probabilidad de tormenta": "de probabilidade de tempestade",
"llegaron en el Tren Maya en {m0} de {n0}": "chegaram no Trem Maia em {m0} de {n0}",
"lugar para dormir": "lugar para dormir",
"lugares para comer": "lugares para comer",
"lugares para dormir": "lugares para dormir",
"no hay estadística oficial de turistas": "não há estatística oficial de turistas",
"sin tormentas registradas en este mes": "sem tempestades registradas neste mês",
"visitantes a sus zonas arqueológicas en {n0}": "visitantes às suas zonas arqueológicas em {n0}",
"{m0} de {n0}: mes normal": "{m0} de {n0}: mês normal",
"{m0} de {n0}: mes tranquilo": "{m0} de {n0}: mês tranquilo",
"{m0} de {n0}: temporada alta": "{m0} de {n0}: alta temporada",
"{n0} días": "{n0} dias",
"{n0} marisquerías en Calderitas y {n1} visitantes a Oxtankah en {n2}. <small>Fuente: INEGI (DENUE) e INAH</small>": "{n0} marisquerias em Calderitas e {n1} visitantes a Oxtankah em {n2}. <small>Fonte: INEGI (DENUE) e INAH</small>",
"{n0} mm": "{n0} mm",
"{n0} museos en {p1} y {p0} según el directorio del INEGI. <small>Fuente: INEGI (DENUE)</small>": "{n0} museus em {p1} e {p0} segundo o diretório do INEGI. <small>Fonte: INEGI (DENUE)</small>",
"{n0} °C": "{n0} °C",
"{n0}. {p0}: ir a su descripción": "{n0}. {p0}: ir para a descrição",
"{p0} en {m0} de {n0}: temporada alta.": "{p0} em {m0} de {n0}: alta temporada.",
"{p0} · {m0} de {n0}": "{p0} · {m0} de {n0}",
"{p0} · {m0} de {n0} <span>Referencia: la campaña no lo promueve</span>": "{p0} · {m0} de {n0} <span>Referência: a campanha não o promove</span>",
"· {m0} de {n0} (estimado): tranquilo": "· {m0} de {n0} (estimado): tranquilo",
"¿Cuándo conviene ir?": "Quando vale a pena ir?",
"¿Cuánto cuesta ir?": "Quanto custa ir?",
"¿Cómo llego al sur?": "Como chego ao sul?",
"¿Cómo lo sabemos?": "Como sabemos?",
"¿De dónde salen los datos?": "De onde vêm os dados?",
"¿Dónde se queda el dinero?": "Onde fica o dinheiro?",
"¿Hay espacio en {p0}?": "Há espaço em {p0}?",
"¿Hay sargazo en el sur?": "Há sargaço no sul?",
"¿Ibas al norte?": "Você ia para o norte?",
"¿Por qué no {p0} o Tulum?": "Por que não {p0} ou Tulum?",
"¿Quién hizo esto?": "Quem fez isto?",
"¿Qué hay en {p0}?": "O que há em {p0}?",
"¿Qué lugares promueve la campaña?": "Que lugares a campanha promove?",
"Modo día": "Modo diurno",
"<span></span>El Mercado {n0} y los antojitos del centro<small>{n1} km →</small>": "<span></span>O Mercado {n0} e os antojitos do centro<small>{n1} km →</small>",
"<span></span>El parque Fundadores y el Portal Maya<small>a pie →</small>": "<span></span>O parque Fundadores e o Portal Maia<small>a pé →</small>",
"<span></span>La Quinta Avenida<small>{n0} km →</small>": "<span></span>A Quinta Avenida<small>{n0} km →</small>",
"<span></span>La playa del pueblo": "<span></span>A praia do povoado",
"<span></span>La zona arqueológica de El Meco": "<span></span>A zona arqueológica de El Meco",
"<span></span>La zona hotelera y Playa Gaviota Azul<small>{n0} km →</small>": "<span></span>A zona hoteleira e a praia Gaviota Azul<small>{n0} km →</small>",
"<span></span>{p0} o Playa del Carmen: subir al Tren Maya<small>{n0} km →</small>": "<span></span>{p0} ou Playa del Carmen: embarcar no Trem Maia<small>{n0} km →</small>",
"<span></span>{p0}: el malecón al atardecer<small>{n0} km →</small>": "<span></span>{p0}: a orla ao pôr do sol<small>{n0} km →</small>",
"<span>★★★★★</span> {n0} % de los cuartos de hotel son de {n1} estrellas (categoría oficial, {n2})": "<span>★★★★★</span> {n0} % dos quartos de hotel são {n1} estrelas (categoria oficial, {n2})",
"Antojitos y Mercado {n0}": "Antojitos e Mercado {n0}",
"Así se come en {p0}": "O que se come em {p0}",
"Categoría de hotel: SECTUR-DataTur, Compendio Estadístico del Turismo en México {n0} (tabla {n1}_2). Fuente: INEGI, Directorio Estadístico Nacional de Unidades Económicas (DENUE). El tipo de lugar y el momento del día los sugiere un clasificador de texto que lee el nombre y el giro oficial de cada negocio (acertó {n2} de {n3} en una revisión al azar). Cuando un lugar no tiene algo cerca, se muestra lo más cercano de los otros lugares del sur. \"Ver en Google Maps\" abre Google Maps en otra pestaña; esta página no descarga nada de Google.": "Categoria de hotel: SECTUR-DataTur, Compêndio Estatístico do Turismo no México {n0} (tabela {n1}_2). Fonte: INEGI, Diretório Estatístico Nacional de Unidades Econômicas (DENUE). O tipo de lugar e o momento do dia são sugeridos por um classificador de texto que lê o nome e a atividade oficial de cada negócio (acertou {n2} de {n3} numa verificação aleatória). Quando um lugar não tem algo perto, mostra-se o mais próximo dos outros lugares do sul. \"Ver no Google Maps\" abre o Google Maps em outra aba; esta página não baixa nada do Google.",
"Cenar en la calle, de noche": "Jantar na rua, à noite",
"Cenar en la calle, de noche<small>Foto: {x0}, {x1}</small>": "Jantar na rua, à noite<small>Foto: {x0}, {x1}</small>",
"Cocina mexicana en la Quinta Avenida": "Cozinha mexicana na Quinta Avenida",
"Cocina mexicana en la Quinta Avenida<small>Foto: {x0}, {x1}</small>": "Cozinha mexicana na Quinta Avenida<small>Foto: {x0}, {x1}</small>",
"Comida de mariscos frente al mar": "Um almoço de frutos do mar à beira-mar",
"Comida de mariscos frente al mar<small>Foto: {x0}, {x1}</small>": "Um almoço de frutos do mar à beira-mar<small>Foto: {x0}, {x1}</small>",
"Del Caribe a la selva, en un <em>solo</em> mapa.": "Do Caribe à selva, num <em>só</em> mapa.",
"Del Caribe al sur en Tren Maya": "Do Caribe ao sul de Trem Maia",
"Distancias en línea recta (no hay datos abiertos de distancias por carretera). Sin precios: ninguna fuente oficial los publica. Las reseñas se leen en Google Maps.": "Distâncias em linha reta (não há dados abertos de distâncias por estrada). Sem preços: nenhuma fonte oficial os publica. As avaliações se leem no Google Maps.",
"El Meco, El Rey y el Museo Maya de {p0}: ciudades mayas entre los hoteles y la laguna.": "El Meco, El Rey e o Museu Maia de {p0}: cidades maias entre os hotéis e a lagoa.",
"El Museo de la Cultura Maya, el planetario y la historia de la ciudad, a pasos de la bahía.": "O Museu da Cultura Maia, o planetário e a história da cidade, a poucos passos da baía.",
"El Portal Maya y los Voladores": "O Portal Maia e os Voladores",
"El clima es el normal de {n0} a {n1}. El riesgo de tormenta cuenta las tormentas que pasaron a {n2} km o menos del lugar desde {n3} ({n4} en el caso de {p0}).": "O clima é o normal de {n0} a {n1}. O risco de tempestade conta as tempestades que passaram a {n2} km ou menos do lugar desde {n3} ({n4} no caso de {p0}).",
"El parque Fundadores frente al mar, con el Portal Maya y la danza de los Voladores.": "O parque Fundadores de frente para o mar, com o Portal Maia e a dança dos Voladores.",
"El sur: {p3}, {p0}, {p1}. {p4} y la {p2} aparecen como referencia, para quien pensaba ir al norte: si su mes está lleno, te recomendamos un lugar del sur.": "O sul: {p3}, {p0}, {p1}. {p4} e a {p2} aparecem como referência, para quem pensava ir ao norte: se o mês estiver cheio, recomendamos um lugar do sul.",
"En el sur · {p0}": "No sul · {p0}",
"En la costa de {p0} y Calderitas no hay reporte de sargazo. Sí apareció en los canales de entrada de la bahía ({m0} de {n0}), así que se vigila. La ruta de las pirámides está lejos del mar abierto.": "Na costa de {p0} e Calderitas não há relatos de sargaço. Ele apareceu nos canais de entrada da baía ({m0} de {n0}), por isso é vigiado. A rota das pirâmides fica longe do mar aberto.",
"En los municipios del sur que promueve la campaña no hay ningún hospedaje grande: {n0} son chicos (hasta {n1} personas) y {n2} medianos. La derrama económica por destino no se muestra porque la fuente no dice en qué unidad está.": "Nos municípios do sul que a campanha promove não há nenhuma hospedagem grande: {n0} são pequenas (até {n1} pessoas) e {n2} médias. O gasto turístico por destino não é mostrado porque a fonte não diz em que unidade está.",
"En {n0} llegaron {n1} pasajeros en avión a {p0}, y el Tren Maya para en {p0}, Bacalar, {p1} y Playa del Carmen. Solo en {m0} de {n2} {n3} personas bajaron del tren en {p0}.": "Em {n0} chegaram {n1} passageiros de avião a {p0}, e o Trem Maia para em {p0}, Bacalar, {p1} e Playa del Carmen. Só em {m0} de {n2}, {n3} pessoas desceram do trem em {p0}.",
"Fajitas de pollo en Playa del Carmen": "Fajitas de frango em Playa del Carmen",
"Fajitas de pollo en Playa del Carmen<small>Foto: {x0}, {x1}</small>": "Fajitas de frango em Playa del Carmen<small>Foto: {x0}, {x1}</small>",
"Fotos del lugar elegido; se pueden recorrer con las flechas": "Fotos do lugar escolhido; dá para percorrê-las com as setas",
"Guacamole y mojitos": "Guacamole e mojitos",
"Guacamole y mojitos<small>Foto: {x0}, {x1}</small>": "Guacamole e mojitos<small>Foto: {x0}, {x1}</small>",
"La Quinta Avenida": "A Quinta Avenida",
"La calle peatonal de Playa del Carmen: restaurantes, tiendas y el mar a una cuadra.": "A rua de pedestres de Playa del Carmen: restaurantes, lojas e o mar a uma quadra.",
"La ciudad más visitada del Caribe mexicano: la zona hotelera, la laguna Nichupté y zonas mayas dentro de la ciudad.": "A cidade mais visitada do Caribe mexicano: a zona hoteleira, a lagoa Nichupté e zonas maias dentro da cidade.",
"La ciudad más visitada del Caribe mexicano: la zona hotelera, la laguna Nichupté y zonas mayas dentro de la ciudad. Tiene {n0} lugares para comer y {n1} para dormir. Referencia: la campaña no lo promueve. Tiene sargazo en {n2} y está en temporada alta de {m0} a {m1}.": "A cidade mais visitada do Caribe mexicano: a zona hoteleira, a lagoa Nichupté e zonas maias dentro da cidade. Tem {n0} lugares para comer e {n1} para dormir. Referência: a campanha não a promove. Tem sargaço em {n2} e está em alta temporada de {m0} a {m1}.",
"La zona hotelera": "A zona hoteleira",
"Las fotos son de Wikimedia Commons, con licencia libre, y cada una se tomó dentro del municipio del lugar (su coordenada se comprobó con el mapa oficial). Las fotos de comida solo existen con licencia libre para {p0} y Playa del Carmen; las del sur las aportará el equipo.": "As fotos são do Wikimedia Commons, com licença livre, e cada uma foi tirada dentro do município do lugar (sua coordenada foi conferida com o mapa oficial). Fotos de pratos com licença livre só existem para {p0} e Playa del Carmen; as do sul virão da equipe.",
"Maqueta de Quintana Roo. Arrastra para girarla.": "Maquete de Quintana Roo. Arraste para girá-la.",
"Mes menos lleno: <b>{m0}</b> · el menos lleno de los meses secos y sin tormentas; aun así, hoteles al {n0} %": "Mês menos cheio: <b>{m0}</b> · o menos cheio dos meses secos e sem tempestades; mesmo assim, hotéis a {n0} %",
"Panuchos, el antojito yucateco": "Panuchos, o petisco de Yucatán",
"Panuchos, el antojito yucateco<small>Foto: {x0}, {x1}</small>": "Panuchos, o petisco de Yucatán<small>Foto: {x0}, {x1}</small>",
"Panuchos, salbutes y tacos en el centro, lejos de la zona hotelera.": "Panuchos, salbutes e tacos no centro, longe da zona hoteleira.",
"Playa Gaviota Azul y la punta de {p0}: arena blanca entre el mar y la laguna Nichupté.": "A praia Gaviota Azul e a ponta de {p0}: areia branca entre o mar e a lagoa Nichupté.",
"Playa del Carmen en un día": "Playa del Carmen em um dia",
"Playa del Carmen, el centro de la {p0}: la Quinta Avenida, el parque Fundadores y la playa del pueblo.": "Playa del Carmen, o centro da {p0}: a Quinta Avenida, o parque Fundadores e a praia do povoado.",
"Playa del Carmen, el centro de la {p0}: la Quinta Avenida, el parque Fundadores y la playa del pueblo. Tiene {n0} lugares para comer y {n1} para dormir. Referencia: la campaña no la promueve. Tiene sargazo en {n2}; su ocupación bajó y se llena en {m0} y {m1}.": "Playa del Carmen, o centro da {p0}: a Quinta Avenida, o parque Fundadores e a praia do povoado. Tem {n0} lugares para comer e {n1} para dormir. Referência: a campanha não a promove. Tem sargaço em {n2}; a ocupação caiu e lota em {m0} e {m1}.",
"Postales de {p0} · fotos tomadas en cada lugar": "Cartões-postais de {p0} · fotos tiradas em cada lugar",
"Primero, lo del lugar que elegiste arriba; después, lo del sur. Lugares reales y una cifra oficial en cada uno. Sin precios: ninguna fuente oficial los publica.": "Primeiro, o que há no lugar escolhido acima; depois, o sul. Lugares reais e um dado oficial em cada um. Sem preços: nenhuma fonte oficial os publica.",
"Referencia: la campaña no la promueve. Tiene sargazo en {n0}; su ocupación bajó y se llena en {m0} y {m1}.": "Referência: a campanha não a promove. Tem sargaço em {n0}; a ocupação caiu e lota em {m0} e {m1}.",
"Referencia: la campaña no lo promueve": "Referência: a campanha não o promove",
"Referencia: la campaña no lo promueve. Tiene sargazo en {n0} y está en temporada alta de {m0} a {m1}.": "Referência: a campanha não o promove. Tem sargaço em {n0} e está em alta temporada de {m0} a {m1}.",
"Todavía no tengo esa respuesta. Prueba con una de las preguntas de abajo: solo respondo lo que los datos del proyecto pueden sostener.": "Ainda não tenho essa resposta. Tente uma das perguntas abaixo: só respondo o que os dados do projeto podem sustentar.",
"Tres en el sur, con espacio. {p1} y la {p0}, como referencia para quien iba al norte.": "Três no sul, com espaço. {p1} e a {p0}, como referência para quem ia ao norte.",
"Un puesto de quesadillas": "Uma barraca de quesadillas",
"Un puesto de quesadillas<small>Foto: {x0}, {x1}</small>": "Uma barraca de quesadillas<small>Foto: {x0}, {x1}</small>",
"Una taquería del centro": "Uma taqueria do centro",
"Una taquería del centro<small>Foto: {x0}, {x1}</small>": "Uma taqueria do centro<small>Foto: {x0}, {x1}</small>",
"Zonas mayas dentro de {p0}": "Zonas maias dentro de {p0}",
"cuartos de hotel ({m0} de {n0})": "quartos de hotel ({m0} de {n0})",
"de los cuartos son de {n0} estrellas ({n1})": "dos quartos são {n0} estrelas ({n1})",
"sin temporada alta en los cinco lugares": "sem alta temporada nos cinco lugares",
"{m0} de {n0}:": "{m0} de {n0}:",
"{n0} % de los cuartos de hotel de Playa del Carmen son de {n1} estrellas, según la categoría oficial ({n2}). <small>Fuente: SECTUR-DataTur (Compendio {n3})</small>": "{n0} % dos quartos de hotel de Playa del Carmen são {n1} estrelas, segundo a categoria oficial ({n2}). <small>Fonte: SECTUR-DataTur (Compêndio {n3})</small>",
"{n0} % de sus cuartos de hotel son de {n1} estrellas, según la categoría oficial ({n2}). <small>Fuente: SECTUR-DataTur (Compendio {n3})</small>": "{n0} % dos seus quartos de hotel são {n1} estrelas, segundo a categoria oficial ({n2}). <small>Fonte: SECTUR-DataTur (Compêndio {n3})</small>",
"{n0} día": "{n0} dia",
"{n0} lugares de antojitos, tacos y cocina yucateca en la ciudad según el directorio del INEGI. <small>Fuente: INEGI (DENUE)</small>": "{n0} lugares de antojitos, tacos e cozinha de Yucatán na cidade segundo o diretório do INEGI. <small>Fonte: INEGI (DENUE)</small>",
"{n0} lugares para comer en Playa del Carmen según el directorio del INEGI. <small>Fuente: INEGI (DENUE)</small>": "{n0} lugares para comer em Playa del Carmen segundo o diretório do INEGI. <small>Fonte: INEGI (DENUE)</small>",
"{n0} museos en {p0} según el directorio del INEGI. <small>Fuente: INEGI (DENUE)</small>": "{n0} museus em {p0} segundo o diretório do INEGI. <small>Fonte: INEGI (DENUE)</small>",
"{n0} visitantes en {n1} entre las tres: unas {n2} al día. <small>Fuente: INAH</small>": "{n0} visitantes em {n1} nas três: cerca de {n2} por dia. <small>Fonte: INAH</small>",
"{p0} <span>Referencia: la campaña no lo promueve</span>": "{p0} <span>Referência: a campanha não o promove</span>",
"{p0} en {n0} días": "{p0} em {n0} dias",
"{p0}, temporada alta": "{p0}, alta temporada",
"· Planea tu viaje →": "· Planeje sua viagem →",
"· {p0}, tranquilo": "· {p0}, tranquilo"
},
"lugares": {
"Ruta de las pirámides": "Rota das pirâmides",
"Calderitas y Oxtankah": "Calderitas e Oxtankah",
"Laguna Milagros y Xul-Ha": "Lagoa Milagros e Xul-Ha"
}
};
