/* Traducción al idioma «en» de la parte del viajero. Generado por backend/torre/campana/idiomas.py desde docs/idiomas/en.tsv: no editar a mano. */
window.IDIOMAS_TRAD = window.IDIOMAS_TRAD || {};
window.IDIOMAS_TRAD["en"] = {
"frases": {
"<b>Temporada alta.</b> El sur también está lleno ese mes.": "<b>High season.</b> The south is busy that month too.",
"<b>Temporada alta.</b> {p0} está más tranquilo ese mes.": "<b>High season.</b> {p0} is quieter that month.",
"<b>Temporada alta</b> quiere decir que ese mes llega {n0} % o más gente que en un mes promedio del año, o que hay {n1} % o más de probabilidad de rebasar el mes más lleno que el lugar ha tenido. Se calcula con los visitantes del INAH a las zonas arqueológicas y, en {p0}, con los cruces desde Belice.": "<b>High season</b> means that {n0} % or more people arrive that month than in an average month of the year, or that there is a {n1} % or higher chance of exceeding the busiest month the place has ever had. It is calculated with INAH visitors to the archaeological sites and, in {p0}, with border crossings from Belize.",
"<b>{p0} en {m0} de {n0}: temporada alta.</b> El sur también está lleno ese mes.": "<b>{p0} in {m0} {n0}: high season.</b> The south is busy that month too.",
"<b>{p0} en {m0} de {n0}: temporada alta.</b> {p1} está más tranquilo ese mes.": "<b>{p0} in {m0} {n0}: high season.</b> {p1} is quieter that month.",
"<b>{p1} en {m0} de {n0}: temporada alta.</b> {p0} está más tranquilo ese mes.": "<b>{p1} in {m0} {n0}: high season.</b> {p0} is quieter that month.",
"<b>{p1} y {p0}</b> están como referencia, para quien pensaba ir al norte; la campaña no los promueve. Ahí se mide la ocupación de los hoteles: es temporada alta si se espera {n0} % de cuartos ocupados o más, el nivel que el Radar ya cuenta como \"concurrido\". Si el mes está lleno, te recomendamos un lugar del sur. Tómalo con cuidado en la {p0}: su ocupación bajó ({n1} % en {m0} de {n2} contra {n3} % un año antes), el pronóstico supone que sigue así y se equivoca más que solo repetir lo del año anterior; se usa porque es el único cuyo rango sí atrapó el valor real {n4} de cada {n5} veces.": "<b>{p1} and {p0}</b> are shown as a reference, for anyone who was planning to go north; the campaign does not promote them. There we measure hotel occupancy: it is high season if {n0} % or more of rooms are expected to be occupied, the level the Radar already counts as \"busy\". If the month is full, we recommend a place in the south. Take it with caution in {p0}: its occupancy dropped ({n1} % in {m0} {n2} versus {n3} % a year earlier), the forecast assumes it stays that way and it is less accurate than simply repeating last year; it is used because it is the only one whose range did catch the real value {n4} out of {n5} times.",
"<span></span><b>Radar, {m0} de {n0}:</b> {n1} de los {n2} lugares del sur, tranquilos<span> · {p0}, sin dato oficial</span><span> · Ver el Radar →</span>": "<span></span><b>Radar, {m0} {n0}:</b> {n1} of the {n2} places in the south are quiet<span> · {p0}, no official data</span><span> · See the Radar →</span>",
"<span></span>Calderitas: mariscos y la zona de Oxtankah<small>{n0} km →</small>": "<span></span>Calderitas: seafood and the Oxtankah site<small>{n0} km →</small>",
"<span></span>Felipe Carrillo Puerto (estación del Tren Maya)<small>{n0} km →</small>": "<span></span>Felipe Carrillo Puerto (Maya Train station)<small>{n0} km →</small>",
"<span></span>Kantemó: la cueva": "<span></span>Kantemó: the cave",
"<span></span>Kohunlich y Dzibanché, en la selva": "<span></span>Kohunlich and Dzibanché, in the jungle",
"<span></span>Kohunlich, Dzibanché e Ichkabal": "<span></span>Kohunlich, Dzibanché and Ichkabal",
"<span></span>Laguna Milagros y el cenote de Xul-Ha<small>{n0} km →</small>": "<span></span>Milagros Lagoon and the Xul-Ha cenote<small>{n0} km →</small>",
"<span></span>Señor: ecoturismo comunitario<small>{n0} km →</small>": "<span></span>Señor: community ecotourism<small>{n0} km →</small>",
"<span></span>Tihosuco: el Museo de la Guerra de Castas<small>{n0} km →</small>": "<span></span>Tihosuco: the Caste War Museum<small>{n0} km →</small>",
"<span></span>Tranquilo <span></span>Normal <span></span>Temporada alta": "<span></span>Quiet <span></span>Normal <span></span>High season",
"<span></span>{p0}: el malecón y el Museo de la Cultura Maya<small>{n0} km →</small>": "<span></span>{p0}: the waterfront and the Museum of Maya Culture<small>{n0} km →</small>",
"<span></span>{p0}: la bahía al atardecer<small>{n0} km →</small>": "<span></span>{p0}: the bay at sunset<small>{n0} km →</small>",
"<span>★ </span>Reseñas<span> ↗</span><span> en Google Maps (otra pestaña)</span>": "<span>★ </span>Reviews<span> ↗</span><span> on Google Maps (new tab)</span>",
"Agencia de viajes y tours · en el centro": "Travel agency and tours · downtown",
"Agencia de viajes y tours · en {p0}, a {n0} km": "Travel agency and tours · in {p0}, {n0} km away",
"Antojitos y tacos para cenar, un bar para cerrar el día y dónde dormir.": "Street food and tacos for dinner, a bar to end the day and a place to sleep.",
"Antojitos · a {n0} km del centro": "Mexican street food · {n0} km from downtown",
"Antojitos · en el centro": "Mexican street food · downtown",
"Asados y pollos · a {n0} km del centro": "Grilled meat and chicken · {n0} km from downtown",
"Asados y pollos · en el centro": "Grilled meat and chicken · downtown",
"Así se ve la {p0}": "This is what {p0} looks like",
"Así se ve {p0}": "This is what {p0} looks like",
"Así va a <em>estar</em>.": "This is how it <em>will be</em>.",
"Atardecer en el malecón": "Sunset on the waterfront",
"Atardecer en una calle de Calderitas": "Sunset on a street in Calderitas",
"Atardecer en una calle de Calderitas<small>Foto: {x0}, {x1}</small>": "Sunset on a street in Calderitas<small>Photo: {x0}, {x1}</small>",
"Atardecer sobre la laguna de {p0}": "Sunset over the lagoon in {p0}",
"Atardecer sobre la laguna de {p0}<small>Foto: {x0}, {x1}</small>": "Sunset over the lagoon in {p0}<small>Photo: {x0}, {x1}</small>",
"Avenida Constituyentes, en Felipe Carrillo Puerto": "Avenida Constituyentes, in Felipe Carrillo Puerto",
"Aves en un muelle de la Laguna Milagros": "Birds on a pier at Milagros Lagoon",
"Bahía y pirámides": "Bay and pyramids",
"Balneario · a {n0} km del centro": "Swimming spot · {n0} km from downtown",
"Balneario · en Calderitas, a {n0} km": "Swimming spot · in Calderitas, {n0} km away",
"Balneario · en el centro": "Swimming spot · downtown",
"Balneario · en {p0}, a {n0} km": "Swimming spot · in {p0}, {n0} km away",
"Bar o cantina · a {n0} km del centro": "Bar or cantina · {n0} km from downtown",
"Bar o cantina · en el centro": "Bar or cantina · downtown",
"Bar o cantina · en {p0}, a {n0} km": "Bar or cantina · in {p0}, {n0} km away",
"Cabañas y villas · a {n0} km del centro": "Cabins and villas · {n0} km from downtown",
"Cabañas y villas · en el centro": "Cabins and villas · downtown",
"Café, desayunos y postres · a {n0} km del centro": "Coffee, breakfast and desserts · {n0} km from downtown",
"Café, desayunos y postres · en el centro": "Coffee, breakfast and desserts · downtown",
"Café, desayunos y postres · en {p0}, a {n0} km": "Coffee, breakfast and desserts · in {p0}, {n0} km away",
"Cambiar a {p0} en {m0}": "Switch to {p0} in {m0}",
"Campamento · en Calderitas, a {n0} km": "Campsite · in Calderitas, {n0} km away",
"Campamento · en el centro": "Campsite · downtown",
"Casa de huéspedes · a {n0} km del centro": "Guesthouse · {n0} km from downtown",
"Casas típicas de madera en el Boulevard Bahía": "Traditional wooden houses on Boulevard Bahía",
"Casas típicas de madera en el Boulevard Bahía<small>Foto: {x0}, {x1}</small>": "Traditional wooden houses on Boulevard Bahía<small>Photo: {x0}, {x1}</small>",
"Centro nocturno · a {n0} km del centro": "Nightclub · {n0} km from downtown",
"Centro nocturno · en el centro": "Nightclub · downtown",
"Centro nocturno · en {p0}, a {n0} km": "Nightclub · in {p0}, {n0} km away",
"Cerrar aviso": "Close notice",
"Cerrar preguntas": "Close questions",
"Cinco lugares": "Five places",
"Cinco lugares del sur de Quintana Roo: {p4}, {p1}, {p2}, {p3} y {p0}.": "Five places in southern Quintana Roo: {p4}, {p1}, {p2}, {p3} and {p0}.",
"Cocina internacional · en el centro": "International food · downtown",
"Cocina yucateca · en el centro": "Yucatecan food · downtown",
"Comida casera · a {n0} km del centro": "Home cooking · {n0} km from downtown",
"Comida casera · en el centro": "Home cooking · downtown",
"Comida para llevar · a {n0} km del centro": "Takeaway food · {n0} km from downtown",
"Comida para llevar · en el centro": "Takeaway food · downtown",
"Comida rápida · a {n0} km del centro": "Fast food · {n0} km from downtown",
"Comida rápida · en el centro": "Fast food · downtown",
"Comparte con {p0} la vigilancia del sargazo en la bahía.": "It shares with {p0} the sargassum watch in the bay.",
"Con datos oficiales": "With official data",
"Cuatro están en el mismo municipio que {p0}.": "Four of them are in the same municipality as {p0}.",
"Cómo llega la gente": "How people arrive",
"Cómo llegar<span> ↗</span><span> (Google Maps, otra pestaña)</span>": "Directions<span> ↗</span><span> (Google Maps, new tab)</span>",
"De día": "By day",
"De fuentes oficiales y abiertas: Secretaría de Turismo, gobierno de Quintana Roo, INEGI, INAH, NOAA, Open-Meteo y la Reserva Federal. Las fotos, de Wikimedia Commons con licencia libre.": "From official and open sources: the Tourism Ministry, the government of Quintana Roo, INEGI, INAH, NOAA, Open-Meteo and the US Federal Reserve. Photos from Wikimedia Commons with free licenses.",
"De noche": "At night",
"Del Museo de la Cultura Maya en {p0} al de la Guerra de Castas en Tihosuco: la historia del sur contada desde aquí.": "From the Museum of Maya Culture in {p0} to the Caste War Museum in Tihosuco: the history of the south told from here.",
"Del mar a la selva, en un <em>solo</em> viaje.": "From the sea to the jungle, in a <em>single</em> trip.",
"Depende del lugar: arriba, en \"Planea tu viaje\", eliges lugar y mes y te decimos cómo va a estar. Por ejemplo, a la {p0} llega {n0} % menos gente que en un mes promedio en {m0}, y {n1} % más en {m1}.": "It depends on the place: above, in \"Plan your trip\", you choose a place and a month and we tell you what it will be like. For example, {n0} % fewer people than in an average month visit {p0} in {m0}, and {n1} % more in {m1}.",
"Distancias en línea recta entre los centros de cada lugar (no hay datos abiertos de distancias por carretera). Sin precios: ninguna fuente oficial los publica. Las reseñas se leen en Google Maps.": "Straight-line distances between the centers of each place (there is no open data on road distances). No prices: no official source publishes them. Reviews can be read on Google Maps.",
"Documento": "Report",
"Dzibanché: el Templo del Búho": "Dzibanché: the Temple of the Owl",
"Dzibanché: el Templo del Búho, {p0}": "Dzibanché: the Temple of the Owl, {p0}",
"Dzibanché: el Templo del Búho. Foto: {x0}, {x1}, vía Wikimedia Commons.": "Dzibanché: the Temple of the Owl. Photo: {x0}, {x1}, via Wikimedia Commons.",
"Dzibanché: el Templo del Búho<small>Foto: {x0}, {x1}</small>": "Dzibanché: the Temple of the Owl<small>Photo: {x0}, {x1}</small>",
"Dzibanché: la Estructura {n0}": "Dzibanché: Structure {n0}",
"Dzibanché: la Estructura {n0}<small>Foto: {x0}, {x1}</small>": "Dzibanché: Structure {n0}<small>Photo: {x0}, {x1}</small>",
"Dónde comer": "Where to eat",
"Dónde dormir": "Where to sleep",
"El Boulevard Bahía de {p0}: casas de madera, monumentos y el sol bajando sobre el agua.": "Boulevard Bahía in {p0}: wooden houses, monuments and the sun setting over the water.",
"El Mercado {n0} en el centro de {p0}": "Market {n0} in downtown {p0}",
"El Mercado {n0} en el centro de {p0}<small>Foto: {x0}, {x1}</small>": "Market {n0} in downtown {p0}<small>Photo: {x0}, {x1}</small>",
"El Monumento a la Bandera frente a la bahía": "The Flag Monument facing the bay",
"El Monumento a la Bandera frente a la bahía<small>Foto: {x0}, {x1}</small>": "The Flag Monument facing the bay<small>Photo: {x0}, {x1}</small>",
"El Monumento al Pescador al atardecer, en la bahía": "The Fisherman Monument at sunset, on the bay",
"El Monumento al Pescador al atardecer, en la bahía, {p0}": "The Fisherman Monument at sunset, on the bay, {p0}",
"El Monumento al Pescador al atardecer, en la bahía. Foto: {x0}, {x1}, vía Wikimedia Commons.": "The Fisherman Monument at sunset, on the bay. Photo: {x0}, {x1}, via Wikimedia Commons.",
"El Monumento al Pescador al atardecer, en la bahía<small>Foto: {x0}, {x1}</small>": "The Fisherman Monument at sunset, on the bay<small>Photo: {x0}, {x1}</small>",
"El Portal Maya del parque Fundadores": "The Maya Portal in Fundadores Park",
"El Portal Maya del parque Fundadores<small>Foto: {x0}, {x1}</small>": "The Maya Portal in Fundadores Park<small>Photo: {x0}, {x1}</small>",
"El Radar": "The Radar",
"El agua turquesa de la Laguna Milagros": "The turquoise water of Milagros Lagoon",
"El cenote de Xul-Ha": "The Xul-Ha cenote",
"El clima es el normal de {n0} a {n1}. El riesgo de tormenta cuenta las tormentas que pasaron a {n2} km o menos del lugar desde {n3} ({n4} en el caso de {p1}). {p0} y la Laguna Milagros no tienen estadística oficial de visitantes, así que no están en el planeador; los encuentras en \"Los lugares\".": "The weather is the normal for {n0} to {n1}. The storm risk counts the storms that passed {n2} km or less from the place since {n3} ({n4} in the case of {p1}). {p0} and Milagros Lagoon have no official visitor statistics, so they are not in the planner; you can find them in \"The places\".",
"El dato": "The key fact",
"El dinero": "The money",
"El kiosco del centro de {p0}": "The kiosk in downtown {p0}",
"El kiosco del centro de {p0}<small>Foto: {x0}, {x1}</small>": "The kiosk in downtown {p0}<small>Photo: {x0}, {x1}</small>",
"El norte": "The north",
"El parque y los restaurantes de Calderitas al atardecer": "The park and the restaurants of Calderitas at sunset",
"El parque y los restaurantes de Calderitas al atardecer<small>Foto: {x0}, {x1}</small>": "The park and the restaurants of Calderitas at sunset<small>Photo: {x0}, {x1}</small>",
"El problema": "The problem",
"El sur": "The south",
"El sur tiene <em>espacio</em>.": "The south has <em>room</em>.",
"El sur tiene <em>espacio</em>.<br>Y te está esperando.": "The south has <em>room</em>.<br>And it is waiting for you.",
"Elige a dónde y cuándo. Te decimos cómo va a estar.": "Choose where and when. We tell you what it will be like.",
"En Calderitas, a {n0} km de {p0}, se come viendo el agua; al lado está Oxtankah, la ciudad maya de la bahía.": "In Calderitas, {n0} km from {p0}, you eat looking at the water; next door is Oxtankah, the Maya city of the bay.",
"En Felipe Carrillo Puerto, Señor y Tihosuco las comunidades mayas reciben a quien llega: selva, historia y su forma de vivir.": "In Felipe Carrillo Puerto, Señor and Tihosuco, Maya communities welcome visitors: jungle, history and their way of life.",
"En la costa de {p1} y Calderitas no hay reporte de sargazo. Sí apareció en los canales de entrada de la bahía ({m0} de {n0}), así que se vigila. La ruta de las pirámides, {p0} y la laguna están lejos del mar abierto.": "There are no sargassum reports on the coast of {p1} and Calderitas. It did appear in the channels that lead into the bay ({m0} {n0}), so it is being watched. The pyramid route, {p0} and the lagoon are far from the open sea.",
"En los municipios de los cinco lugares no hay ningún hospedaje grande: {n0} son chicos (hasta {n1} personas) y {n2} medianos. La derrama económica por destino no se muestra porque la fuente no dice en qué unidad está.": "In the municipalities of the five places there is no large lodging: {n0} are small (up to {n1} people) and {n2} are medium-sized. Tourist spending by destination is not shown because the source does not say what unit it is in.",
"En {m0} el sur también tiene temporada alta. Si puedes mover tu viaje, busca los meses en verde.": "In {m0} the south is also in high season. If you can move your trip, look for the months in green.",
"En {m0}, <b>{p0}</b> no está en temporada alta: hay espacio, sin el gentío del norte.": "In {m0}, <b>{p0}</b> is not in high season: there is room, without the crowds of the north.",
"En {m0}, <b>{p1}</b> está más tranquilo. O ve a la {p0} en <b>{m1}</b>: menos gente, poca lluvia y fuera de la temporada de tormentas.": "In {m0}, <b>{p1}</b> is quieter. Or go to {p0} in <b>{m1}</b>: fewer people, little rain and outside the storm season.",
"En {m0}, <b>{p1}</b> está más tranquilo. O ve a {p0} en <b>{m1}</b>: menos gente, poca lluvia y fuera de la temporada de tormentas.": "In {m0}, <b>{p1}</b> is quieter. Or go to {p0} in <b>{m1}</b>: fewer people, little rain and outside the storm season.",
"En {n0} llegaron {n1} pasajeros en avión a {p1}, y el Tren Maya para en {p1}, Bacalar y Felipe Carrillo Puerto ({p0}). Solo en {m0} de {n2} {n3} personas bajaron del tren en {p1}.": "In {n0}, {n1} passengers arrived by plane in {p1}, and the Maya Train stops in {p1}, Bacalar and Felipe Carrillo Puerto ({p0}). In {m0} {n2} alone, {n3} people got off the train in {p1}.",
"Enviar pregunta": "Send question",
"Escribe tu pregunta": "Type your question",
"Escribe tu pregunta…": "Type your question…",
"Ese mes todavía no está en el pronóstico (llega hasta {m0} de {n0}): en un {m1} típico, de {n1} a {n2} los hoteles estuvieron al <b>{n3} %</b>.": "That month is not in the forecast yet (it runs to {m0} {n0}): in a typical {m1}, from {n1} to {n2}, hotels were at <b>{n3} %</b>.",
"Ese mes todavía no está en el pronóstico (llega hasta {m0} de {n0}): esto es lo típico de {m1}.": "That month is not in the forecast yet (it runs to {m0} {n0}): this is what is typical for {m1}.",
"Esta parte está en español: son los datos técnicos del proyecto.": "This part is in Spanish: it holds the project's technical data.",
"Estructura {n0} de Oxtankah, con pintura original": "Structure {n0} at Oxtankah, with original paint",
"Estructura {n0} de Oxtankah, con pintura original<small>Foto: {x0}, {x1}</small>": "Structure {n0} at Oxtankah, with original paint<small>Photo: {x0}, {x1}</small>",
"Fotos de los cinco lugares; se pueden recorrer con las flechas": "Photos of the five places; you can browse them with the arrow keys",
"Fuente: ECOSUR y notas del {n0} de {m0} de {n1}": "Source: ECOSUR and news reports of {m0} {n0}, {n1}",
"Fuente: Gobierno de Quintana Roo (SITUR-Q)": "Source: Government of Quintana Roo (SITUR-Q)",
"Fuente: INAH (BdINAH) y forma del año del proyecto (Fase {n0})": "Source: INAH (BdINAH) and the project's shape-of-the-year analysis (Phase {n0})",
"Fuente: INAH (BdINAH), SITUR-Q (frontera con Belice), SECTUR-DataTur (ocupación hotelera de {p1} y {p0}), NOAA HURDAT2, Open-Meteo (clima {n0}–{n1}) y pronóstico del proyecto (Fase {n2}); negocios: INEGI, DENUE.": "Source: INAH (BdINAH), SITUR-Q (Belize border), SECTUR-DataTur (hotel occupancy in {p1} and {p0}), NOAA HURDAT2, Open-Meteo (weather {n0}–{n1}) and the project's forecast (Phase {n2}); businesses: INEGI, DENUE.",
"Fuente: INEGI (DENUE) y SITUR-Q": "Source: INEGI (DENUE) and SITUR-Q",
"Fuente: INEGI y gobierno de Quintana Roo": "Source: INEGI and the government of Quintana Roo",
"Fuente: INEGI, Directorio Estadístico Nacional de Unidades Económicas (DENUE). El tipo de lugar y el momento del día los sugiere un clasificador de texto que lee el nombre y el giro oficial de cada negocio (acertó {n0} de {n1} en una revisión al azar). Cuando un lugar no tiene algo cerca, se muestra lo más cercano de los otros lugares del sur. \"Ver en Google Maps\" abre Google Maps en otra pestaña; esta página no descarga nada de Google.": "Source: INEGI, National Statistical Directory of Economic Units (DENUE). The type of place and the time of day are suggested by a text classifier that reads each business's name and official activity (it got {n0} out of {n1} right in a random check). When a place has nothing of a kind nearby, the closest one from the other places in the south is shown. \"See on Google Maps\" opens Google Maps in a new tab; this page downloads nothing from Google.",
"Fuente: Inventario de fuentes del proyecto": "Source: the project's inventory of sources",
"Fuente: Secretaría de Turismo y notas verificadas de {n0}": "Source: Tourism Ministry and news verified in {n0}",
"Fuente: Selección de regiones del proyecto": "Source: the project's selection of regions",
"Fuente: Torre del Caribe": "Source: Torre del Caribe",
"Girar el mapa solo": "Rotate the map by itself",
"Habrá mucha gente: los hoteles suelen pasar del {n0} % de cuartos ocupados, lo que el Radar ya cuenta como \"concurrido\".": "It will be crowded: hotels usually go above {n0} % of rooms occupied, which the Radar already counts as \"busy\".",
"Habrá mucha gente: se espera que los hoteles pasen del {n0} % de cuartos ocupados, lo que el Radar ya cuenta como \"concurrido\".": "It will be crowded: hotels are expected to go above {n0} % of rooms occupied, which the Radar already counts as \"busy\".",
"Hasta {m0} de {n0} hay un pronóstico con su rango: el valor real cayó dentro de ese rango entre {n1} y {n2} de cada {n3} veces cuando se probó con meses que el modelo nunca vio. Después de esa fecha se muestra lo típico de cada mes.": "Until {m0} {n0} there is a forecast with its range: the real value fell inside that range between {n1} and {n2} out of {n3} times when it was tested on months the model had never seen. After that date, what is typical for each month is shown.",
"Hay espacio: los hoteles suelen quedar debajo del {n0} % de cuartos ocupados, lo que el Radar cuenta como \"concurrido\".": "There is room: hotels usually stay below {n0} % of rooms occupied, which the Radar counts as \"busy\".",
"Hay espacio: se espera que los hoteles queden debajo del {n0} % de cuartos ocupados, lo que el Radar cuenta como \"concurrido\".": "There is room: hotels are expected to stay below {n0} % of rooms occupied, which the Radar counts as \"busy\".",
"Hay lugar: {n0} de cada {n1} cuartos de hotel de {p0} se quedaron vacíos en {n2}. <small>Fuente: Gobierno de Quintana Roo (SITUR-Q)</small>": "There is room: {n0} out of {n1} hotel rooms in {p0} were empty in {n2}. <small>Source: Government of Quintana Roo (SITUR-Q)</small>",
"Hay pocos cuartos de hotel: la campaña pone un límite de visitantes para no rebasar a los pueblos.": "There are few hotel rooms: the campaign sets a visitor limit so as not to overwhelm the villages.",
"Hola. Pregúntame sobre los cinco lugares, cómo llegar o de dónde salen los datos.": "Hello. Ask me about the five places, how to get there or where the data comes from.",
"Hospedaje de la gente de aquí: en los municipios de los cinco lugares hay {n0} hospedajes chicos, {n1} medianos y {n2} grandes. <small>Fuente: INEGI (DENUE)</small>": "Lodging run by local people: in the municipalities of the five places there are {n0} small lodgings, {n1} medium and {n2} large. <small>Source: INEGI (DENUE)</small>",
"Hostal · en el centro": "Hostel · downtown",
"Hostal · en {p0}, a {n0} km": "Hostel · in {p0}, {n0} km away",
"Hotel · en Xul-ha, a {n0} km": "Hotel · in Xul-Ha, {n0} km away",
"Hotel · en el centro": "Hotel · downtown",
"Hotel · en {p0}, a {n0} km": "Hotel · in {p0}, {n0} km away",
"Idioma": "Language",
"Idioma / Language": "Language / Idioma",
"Iglesia en Felipe Carrillo Puerto": "Church in Felipe Carrillo Puerto",
"Iglesia en Felipe Carrillo Puerto. Foto: {x0}, {x1}, vía Wikimedia Commons.": "Church in Felipe Carrillo Puerto. Photo: {x0}, {x1}, via Wikimedia Commons.",
"Jardín botánico o zoológico · a {n0} km del centro": "Botanical garden or zoo · {n0} km from downtown",
"Jardín botánico o zoológico · en el centro": "Botanical garden or zoo · downtown",
"Jardín botánico o zoológico · en {p0}, a {n0} km": "Botanical garden or zoo · in {p0}, {n0} km away",
"Kohunlich, Dzibanché e Ichkabal: ciudades mayas entre la selva, con sus mascarones y templos.": "Kohunlich, Dzibanché and Ichkabal: Maya cities in the jungle, with their masks and temples.",
"Kohunlich, Dzibanché e Ichkabal: tres ciudades mayas en la selva, lejos del mar.": "Kohunlich, Dzibanché and Ichkabal: three Maya cities in the jungle, far from the sea.",
"Kohunlich, Dzibanché e Ichkabal: tres ciudades mayas en la selva, lejos del mar. Tiene {n0} lugares para comer y {n1} para dormir. Cuidado: los poblados cercanos casi no tienen hoteles: la visita se hace desde {p0}.": "Kohunlich, Dzibanché and Ichkabal: three Maya cities in the jungle, far from the sea. It has {n0} places to eat and {n1} to sleep. Careful: the nearby villages have almost no hotels, so visits start from {p0}.",
"Kohunlich: detalle de un mascarón": "Kohunlich: detail of a mask",
"Kohunlich: detalle de un mascarón<small>Foto: {x0}, {x1}</small>": "Kohunlich: detail of a mask<small>Photo: {x0}, {x1}</small>",
"Kohunlich: el juego de pelota": "Kohunlich: the ball court",
"Kohunlich: el juego de pelota<small>Foto: {x0}, {x1}</small>": "Kohunlich: the ball court<small>Photo: {x0}, {x1}</small>",
"Kohunlich: los mascarones de estuco": "Kohunlich: the stucco masks",
"Kohunlich: los mascarones de estuco<small>Foto: {x0}, {x1}</small>": "Kohunlich: the stucco masks<small>Photo: {x0}, {x1}</small>",
"Kohunlich: una de sus plataformas en la selva": "Kohunlich: one of its platforms in the jungle",
"Kohunlich: una de sus plataformas en la selva<small>Foto: {x0}, {x1}</small>": "Kohunlich: one of its platforms in the jungle<small>Photo: {x0}, {x1}</small>",
"La Campana del Bicentenario": "The Bicentennial Bell",
"La Campana del Bicentenario<small>Foto: {x0}, {x1}</small>": "The Bicentennial Bell<small>Photo: {x0}, {x1}</small>",
"La Laguna Milagros y el cenote de Xul-Ha, a {n0} km de {p0}. Es frágil: se nada sin bloqueador y sin dejar nada.": "Milagros Lagoon and the Xul-Ha cenote, {n0} km from {p0}. It is fragile: swim without sunscreen and leave nothing behind.",
"La Quinta Avenida de Playa del Carmen": "Fifth Avenue in Playa del Carmen",
"La Quinta Avenida de Playa del Carmen<small>Foto: {x0}, {x1}</small>": "Fifth Avenue in Playa del Carmen<small>Photo: {x0}, {x1}</small>",
"La bahía de {p0} desde el Boulevard": "The bay of {p0} from the Boulevard",
"La bahía de {p0} desde el Boulevard. Foto: {x0}, {x1}, vía Wikimedia Commons.": "The bay of {p0} from the Boulevard. Photo: {x0}, {x1}, via Wikimedia Commons.",
"La bahía frente a Calderitas": "The bay in front of Calderitas",
"La bahía frente a Calderitas. Foto: {x0}, {x1}, vía Wikimedia Commons.": "The bay in front of Calderitas. Photo: {x0}, {x1}, via Wikimedia Commons.",
"La bahía vista desde Calderitas": "The bay seen from Calderitas",
"La bahía vista desde Calderitas, {p0}": "The bay seen from Calderitas, {p0}",
"La bahía vista desde Calderitas. Foto: {x0}, {x1}, vía Wikimedia Commons.": "The bay seen from Calderitas. Photo: {x0}, {x1}, via Wikimedia Commons.",
"La bahía vista desde Calderitas<small>Foto: {x0}, {x1}</small>": "The bay seen from Calderitas<small>Photo: {x0}, {x1}</small>",
"La capilla antigua dentro de la zona de Oxtankah": "The old chapel inside the Oxtankah site",
"La capilla antigua dentro de la zona de Oxtankah<small>Foto: {x0}, {x1}</small>": "The old chapel inside the Oxtankah site<small>Photo: {x0}, {x1}</small>",
"La capilla de Nuestra Señora del Carmen": "The chapel of Our Lady of Carmen",
"La capilla de Nuestra Señora del Carmen<small>Foto: {x0}, {x1}</small>": "The chapel of Our Lady of Carmen<small>Photo: {x0}, {x1}</small>",
"La capital del estado, frente a la bahía, con el Museo de la Cultura Maya.": "The state capital, on the bay, with the Museum of Maya Culture.",
"La capital del estado, frente a la bahía, con el Museo de la Cultura Maya. Tiene {n0} lugares para comer y {n1} para dormir; {n2} personas llegaron en el Tren Maya en {m0} de {n3}. Cuidado: se vigila el sargazo que apareció en los canales de entrada de la bahía ({m1} de {n4}).": "The state capital, on the bay, with the Museum of Maya Culture. It has {n0} places to eat and {n1} to sleep; {n2} people arrived on the Maya Train in {m0} {n3}. Careful: the sargassum that appeared in the channels into the bay is being watched ({m1} {n4}).",
"La gran pirámide de Dzibanché en la selva": "The great pyramid of Dzibanché in the jungle",
"La gran pirámide de Dzibanché en la selva. Foto: {x0}, {x1}, vía Wikimedia Commons.": "The great pyramid of Dzibanché in the jungle. Photo: {x0}, {x1}, via Wikimedia Commons.",
"La laguna Nichupté": "Nichupté Lagoon",
"La laguna Nichupté<small>Foto: {x0}, {x1}</small>": "Nichupté Lagoon<small>Photo: {x0}, {x1}</small>",
"La laguna es frágil: visitas con límite estricto y sin actividades que la dañen.": "The lagoon is fragile: visits with a strict limit and no activities that harm it.",
"La orilla de la laguna en Huay-Pix": "The shore of the lagoon at Huay-Pix",
"La playa del pueblo, en Playa del Carmen": "The town beach in Playa del Carmen",
"La playa del pueblo, en Playa del Carmen<small>Foto: {x0}, {x1}</small>": "The town beach in Playa del Carmen<small>Photo: {x0}, {x1}</small>",
"Laguna y selva": "Lagoon and jungle",
"Las fases": "The phases",
"Las fotos son de Wikimedia Commons, con licencia libre, y cada una se tomó dentro del municipio del lugar (su coordenada se comprobó con el mapa oficial).": "The photos are from Wikimedia Commons, with free licenses, and each one was taken within the municipality of the place (its coordinates were checked against the official map).",
"Llega más o menos la gente de un mes promedio.": "About the same number of people as in an average month.",
"Llega {n0} % menos gente que en un mes promedio: hay espacio.": "{n0} % fewer people than in an average month: there is room.",
"Llega {n0} % más gente que en un mes promedio, y hay {n1} % de probabilidad de rebasar el mes más lleno de su historia.": "{n0} % more people than in an average month, and a {n1} % chance of exceeding the busiest month in its history.",
"Llega {n0} % más gente que en un mes promedio.": "{n0} % more people than in an average month.",
"Lo que hay <em>detrás</em> del viaje.": "What lies <em>behind</em> the trip.",
"Lo que no te <em>cuentan</em> del Caribe.": "What they don't <em>tell</em> you about the Caribbean.",
"Lo que todos <em>preguntan</em>.": "What everyone <em>asks</em>.",
"Los Voladores en el parque Fundadores": "The Voladores in Fundadores Park",
"Los Voladores en el parque Fundadores<small>Foto: {x0}, {x1}</small>": "The Voladores in Fundadores Park<small>Photo: {x0}, {x1}</small>",
"Los datos": "The data",
"Los lugares": "The places",
"Los lugares del sur con estadística están en temporada alta este mes. Mejor ve a la {p0} en <b>{m0}</b>: menos gente, poca lluvia y fuera de la temporada de tormentas.": "The places in the south with statistics are in high season this month. Better go to {p0} in <b>{m0}</b>: fewer people, little rain and outside the storm season.",
"Los lugares del sur con estadística están en temporada alta este mes. Mejor ve a {p0} en <b>{m0}</b>: menos gente, poca lluvia y fuera de la temporada de tormentas.": "The places in the south with statistics are in high season this month. Better go to {p0} in <b>{m0}</b>: fewer people, little rain and outside the storm season.",
"Los poblados cercanos casi no tienen hoteles: la visita se hace desde {p0}.": "The nearby villages have almost no hotels: visits start from {p0}.",
"Lugar": "Place",
"Lugares reales del directorio de negocios del INEGI, del más cercano al más lejano. No son reseñas ni anuncios pagados y el directorio no publica horarios: confirma antes de ir.": "Real places from INEGI's business directory, from the closest to the farthest. They are not reviews or paid ads, and the directory does not publish opening hours: check before you go.",
"Maqueta del sur de Quintana Roo. Arrastra para girarla.": "Model of southern Quintana Roo. Drag to rotate it.",
"Mariposa búho cerca de Chunhuhub": "Owl butterfly near Chunhuhub",
"Mariposa en la selva cerca de Chunhuhub": "Butterfly in the jungle near Chunhuhub",
"Mariscos frente a la bahía": "Seafood by the bay",
"Mariscos y pescado · a {n0} km del centro": "Seafood and fish · {n0} km from downtown",
"Mariscos y pescado · en el centro": "Seafood and fish · downtown",
"Mejor mes: <b>{m0}</b> · el mes más seco y sin tormentas (no hay estadística de visitantes)": "Best month: <b>{m0}</b> · the driest month with no storms (there are no visitor statistics)",
"Mejor mes: <b>{m0}</b> · menos gente, poca lluvia y sin temporada de tormentas": "Best month: <b>{m0}</b> · fewer people, little rain and no storm season",
"Mejor ve al sur": "Better go south",
"Menú": "Menu",
"Mes": "Month",
"Mes normal": "Normal month",
"Mes tranquilo": "Quiet month",
"Modo noche": "Night mode",
"Museo · a {n0} km del centro": "Museum · {n0} km from downtown",
"Museo · en el centro": "Museum · downtown",
"Museo · en {p0}, a {n0} km": "Museum · in {p0}, {n0} km away",
"Museos de la cultura maya": "Museums of Maya culture",
"Nadar en la Laguna Milagros": "Swimming in Milagros Lagoon",
"No damos precios: ninguna fuente oficial abierta publica tarifas de hotel por lugar, y no las inventamos. Lo que sí sabemos es que en el sur los hoteles son chicos: {n0} cuartos por hotel en {p0} contra {n1} en {p1} ({m0} de {n2}).": "We don't give prices: no official open source publishes hotel rates by place, and we don't make them up. What we do know is that hotels in the south are small: {n0} rooms per hotel in {p0} versus {n1} in {p1} ({m0} {n2}).",
"No hay estadística oficial de visitantes: por eso se cuida con un límite estricto de gente. <small>Fuente: Selección de regiones del proyecto</small>": "There are no official visitor statistics: that is why it is protected with a strict limit on people. <small>Source: the project's selection of regions</small>",
"Palapas en Huay-Pix, a la orilla de la laguna": "Palapas in Huay-Pix, on the shore of the lagoon",
"Parque · a {n0} km del centro": "Park · {n0} km from downtown",
"Parque · en {p0}, a {n0} km": "Park · in {p0}, {n0} km away",
"Paseo en lancha · en el centro": "Boat trip · downtown",
"Paseo en lancha · en {p0}, a {n0} km": "Boat trip · in {p0}, {n0} km away",
"Pirámide de la Tumba {n0} en Oxtankah": "Pyramid of Tomb {n0} at Oxtankah",
"Pirámide de la Tumba {n0} en Oxtankah<small>Foto: {x0}, {x1}</small>": "Pyramid of Tomb {n0} at Oxtankah<small>Photo: {x0}, {x1}</small>",
"Pirámides en la selva": "Pyramids in the jungle",
"Pizzas y hamburguesas · a {n0} km del centro": "Pizza and burgers · {n0} km from downtown",
"Pizzas y hamburguesas · en el centro": "Pizza and burgers · downtown",
"Planea tu viaje": "Plan your trip",
"Planea tu viaje · el sur de Quintana Roo": "Plan your trip · southern Quintana Roo",
"Playa Gaviota Azul, en la punta de {p0}": "Gaviota Azul Beach, at the tip of {p0}",
"Playa Gaviota Azul, en la punta de {p0}, {p0}": "Gaviota Azul Beach, at the tip of {p0}, {p0}",
"Playa Gaviota Azul, en la punta de {p0}. Foto: {x0}, {x1}, vía Wikimedia Commons.": "Gaviota Azul Beach, at the tip of {p0}. Photo: {x0}, {x1}, via Wikimedia Commons.",
"Playa Gaviota Azul, en la punta de {p0}<small>Foto: {x0}, {x1}</small>": "Gaviota Azul Beach, at the tip of {p0}<small>Photo: {x0}, {x1}</small>",
"Playa de la zona hotelera de {p0}": "Beach in the hotel zone of {p0}",
"Playa de la zona hotelera de {p0}<small>Foto: {x0}, {x1}</small>": "Beach in the hotel zone of {p0}<small>Photo: {x0}, {x1}</small>",
"Playa del Carmen desde el aire": "Playa del Carmen from the air",
"Playa del Carmen desde el aire, {p0}": "Playa del Carmen from the air, {p0}",
"Playa del Carmen desde el aire. Foto: {x0}, {x1}, vía Wikimedia Commons.": "Playa del Carmen from the air. Photo: {x0}, {x1}, via Wikimedia Commons.",
"Playa del Carmen desde el aire<small>Foto: {x0}, {x1}</small>": "Playa del Carmen from the air<small>Photo: {x0}, {x1}</small>",
"Por la tarde": "In the afternoon",
"Posada · a {n0} km del centro": "Inn · {n0} km from downtown",
"Posada · en el centro": "Inn · downtown",
"Posada · en {p0}, a {n0} km": "Inn · in {p0}, {n0} km away",
"Postales del sur": "Postcards from the south",
"Postales del sur · fotos tomadas en cada lugar": "Postcards from the south · photos taken in each place",
"Preguntas": "Questions",
"Preguntas frecuentes": "Frequently asked questions",
"Preguntas rápidas": "Quick questions",
"Pregúntanos": "Ask us",
"Pueblo de pescadores junto a la bahía y la zona arqueológica de Oxtankah, casi siempre sin filas.": "Fishing village by the bay and the Oxtankah archaeological site, almost always without queues.",
"Pueblo de pescadores junto a la bahía y la zona arqueológica de Oxtankah, casi siempre sin filas. Tiene {n0} lugares para comer y {n1} para dormir. Cuidado: comparte con {p0} la vigilancia del sargazo en la bahía.": "Fishing village by the bay and the Oxtankah archaeological site, almost always without queues. It has {n0} places to eat and {n1} to sleep. Careful: it shares with {p0} the sargassum watch in the bay.",
"Pueblos de {p0}": "Villages of {p0}",
"Pueblos mayas con turismo comunitario y la cueva de Kantemó.": "Maya villages with community tourism and the Kantemó cave.",
"Pueblos mayas con turismo comunitario y la cueva de Kantemó. Tiene {n0} lugares para comer y {n1} para dormir; {n2} personas llegaron en el Tren Maya en {m0} de {n3}. Cuidado: hay pocos cuartos de hotel: la campaña pone un límite de visitantes para no rebasar a los pueblos.": "Maya villages with community tourism and the Kantemó cave. It has {n0} places to eat and {n1} to sleep; {n2} people arrived on the Maya Train in {m0} {n3}. Careful: there are few hotel rooms, so the campaign sets a visitor limit so as not to overwhelm the villages.",
"Qué hacer": "Things to do",
"Radar, {m0} de {n0}:": "Radar, {m0} {n0}:",
"Recreación · a {n0} km del centro": "Recreation · {n0} km from downtown",
"Recreación · en Xul-ha, a {n0} km": "Recreation · in Xul-Ha, {n0} km away",
"Recreación · en el centro": "Recreation · downtown",
"Recreación · en {p0}, a {n0} km": "Recreation · in {p0}, {n0} km away",
"Respondo con los datos del proyecto. Si no lo sé, lo digo.": "I answer with the project's data. If I don't know, I say so.",
"Restaurante Bahía Villamar, en una casa de madera": "Bahía Villamar restaurant, in a wooden house",
"Restaurante Bahía Villamar, en una casa de madera<small>Foto: {x0}, {x1}</small>": "Bahía Villamar restaurant, in a wooden house<small>Photo: {x0}, {x1}</small>",
"Restaurante a la carta · a {n0} km del centro": "À la carte restaurant · {n0} km from downtown",
"Restaurante a la carta · en el centro": "À la carte restaurant · downtown",
"Rutas de {n0} y {n1} días": "{n0}- and {n1}-day routes",
"Saltar al contenido": "Skip to content",
"Se espera alrededor de <b>{n0} %</b> de los cuartos de hotel ocupados, muy probablemente entre {n1} y {n2} %.": "About <b>{n0} %</b> of hotel rooms are expected to be occupied, most likely between {n1} and {n2} %.",
"Se esperan alrededor de <b>{n0}</b> cruces desde Belice, muy probablemente entre {n1} y {n2}.": "About <b>{n0}</b> crossings from Belize are expected, most likely between {n1} and {n2}.",
"Se esperan alrededor de <b>{n0}</b> visitantes a Kohunlich, Dzibanché e Ichkabal, muy probablemente entre {n1} y {n2}.": "About <b>{n0}</b> visitors to Kohunlich, Dzibanché and Ichkabal are expected, most likely between {n1} and {n2}.",
"Se esperan alrededor de <b>{n0}</b> visitantes a la zona de Oxtankah, muy probablemente entre {n1} y {n2}.": "About <b>{n0}</b> visitors to the Oxtankah site are expected, most likely between {n1} and {n2}.",
"Se vigila el sargazo que apareció en los canales de entrada de la bahía ({m0} de {n0}).": "The sargassum that appeared in the channels into the bay is being watched ({m0} {n0}).",
"Secciones": "Sections",
"Seis experiencias con lugares reales y una cifra oficial cada una. Sin precios: ninguna fuente oficial los publica.": "Six experiences with real places and one official figure each. No prices: no official source publishes them.",
"Sin dato": "No data",
"Sin dato oficial": "No official data",
"Sí: en {n0} {n1} de cada {n2} cuartos de hotel de {p0} se quedaron vacíos ({n3} de {n4} noches ocupadas).": "Yes: in {n0}, {n1} out of {n2} hotel rooms in {p0} were empty ({n3} of {n4} nights occupied).",
"Tacos y tortas · a {n0} km del centro": "Tacos and tortas · {n0} km from downtown",
"Tacos y tortas · en el centro": "Tacos and tortas · downtown",
"Te conviene más": "A better choice",
"Temporada alta": "High season",
"Temporada alta.": "High season.",
"Tienen sargazo y se llenan: en su semana más llena, {p0} tuvo {n0} de cada {n1} cuartos ocupados, y en Tulum se reportaron cierres de negocios en {n2}. La campaña lleva gente a donde sí hay espacio.": "They have sargassum and fill up: in its busiest week, {p0} had {n0} out of {n1} rooms occupied, and business closures were reported in Tulum in {n2}. The campaign takes people where there really is room.",
"Todo lo que viste arriba sale de datos oficiales, modelos y pruebas. Esta parte es para quien quiera revisar cómo lo sabemos.": "Everything you saw above comes from official data, models and tests. This part is for anyone who wants to check how we know it.",
"Tranquilo": "Quiet",
"Tu viaje": "Your trip",
"Turismo comunitario maya": "Maya community tourism",
"Un balneario o un parque, y a comer: mariscos, cocina yucateca o comida casera.": "A swimming spot or a park, and lunch: seafood, Yucatecan food or home cooking.",
"Un día en <em>{p0}</em>": "A day in <em>{p0}</em>",
"Un equipo de estudiantes de Ciencias de Datos para Negocios de la Universidad Nacional Rosario Castellanos (UNRC), como proyecto escolar {n0}-{n1}.": "A team of Business Data Science students from the Rosario Castellanos National University (UNRC), as a {n0}-{n1} school project.",
"Un matapalo en la selva de Felipe Carrillo Puerto": "A strangler fig in the jungle of Felipe Carrillo Puerto",
"Un muelle en la Laguna Milagros": "A pier on Milagros Lagoon",
"Un muelle en la Laguna Milagros. Foto: {x0}, {x1}, vía Wikimedia Commons.": "A pier on Milagros Lagoon. Photo: {x0}, {x1}, via Wikimedia Commons.",
"Una laguna del mismo sistema que Bacalar, con pueblos a la orilla.": "A lagoon in the same system as Bacalar, with villages on its shore.",
"Una laguna del mismo sistema que Bacalar, con pueblos a la orilla. Tiene {n0} lugares para comer y {n1} para dormir. Cuidado: la laguna es frágil: visitas con límite estricto y sin actividades que la dañen.": "A lagoon in the same system as Bacalar, with villages on its shore. It has {n0} places to eat and {n1} to sleep. Careful: the lagoon is fragile, so visits have a strict limit and no activities that harm it.",
"Una laguna dulce y un cenote": "A freshwater lagoon and a cenote",
"Unas {n0} personas al día entre las tres zonas en {n1}: tienes la pirámide casi para ti. <small>Fuente: INAH</small>": "About {n0} people a day across the three sites in {n1}: you almost have the pyramid to yourself. <small>Source: INAH</small>",
"Ver cómo está en {m0}": "See what it's like in {m0}",
"Ver cómo va a estar": "See what it will be like",
"Ver la {p0} en {m0}": "See {p0} in {m0}",
"Ver todo el mapa": "See the whole map",
"Ver {p0} en {m0}": "See {p0} in {m0}",
"Vive el sur": "Experience the south",
"Zona arqueológica (INAH)": "Archaeological site (INAH)",
"Zona arqueológica de El Meco": "El Meco archaeological site",
"Zona arqueológica de El Meco<small>Foto: {x0}, {x1}</small>": "El Meco archaeological site<small>Photo: {x0}, {x1}</small>",
"Zonas arqueológicas, museos y paseos; para empezar, un café o un desayuno.": "Archaeological sites, museums and outings; to start, a coffee or breakfast.",
"de lluvia en un {m0} normal": "of rain in a normal {m0}",
"de máxima, en promedio": "average high",
"de probabilidad de tormenta": "chance of a storm",
"llegaron en el Tren Maya en {m0} de {n0}": "arrived on the Maya Train in {m0} {n0}",
"lugar para dormir": "place to sleep",
"lugares para comer": "places to eat",
"lugares para dormir": "places to sleep",
"no hay estadística oficial de turistas": "there are no official tourist statistics",
"sin tormentas registradas en este mes": "no storms recorded in this month",
"visitantes a sus zonas arqueológicas en {n0}": "visitors to its archaeological sites in {n0}",
"{m0} de {n0}: mes normal": "{m0} {n0}: normal month",
"{m0} de {n0}: mes tranquilo": "{m0} {n0}: quiet month",
"{m0} de {n0}: temporada alta": "{m0} {n0}: high season",
"{n0} días": "{n0} days",
"{n0} marisquerías en Calderitas y {n1} visitantes a Oxtankah en {n2}. <small>Fuente: INEGI (DENUE) e INAH</small>": "{n0} seafood restaurants in Calderitas and {n1} visitors to Oxtankah in {n2}. <small>Source: INEGI (DENUE) and INAH</small>",
"{n0} mm": "{n0} mm",
"{n0} museos en {p1} y {p0} según el directorio del INEGI. <small>Fuente: INEGI (DENUE)</small>": "{n0} museums in {p1} and {p0} according to INEGI's directory. <small>Source: INEGI (DENUE)</small>",
"{n0} °C": "{n0} °C",
"{n0}. {p0}: ir a su descripción": "{n0}. {p0}: go to its description",
"{p0} en {m0} de {n0}: temporada alta.": "{p0} in {m0} {n0}: high season.",
"{p0} · {m0} de {n0}": "{p0} · {m0} {n0}",
"{p0} · {m0} de {n0} <span>Referencia: la campaña no lo promueve</span>": "{p0} · {m0} {n0} <span>Reference: not promoted by the campaign</span>",
"· {m0} de {n0} (estimado): tranquilo": "· {m0} {n0} (estimated): quiet",
"¿Cuándo conviene ir?": "When is the best time to go?",
"¿Cuánto cuesta ir?": "How much does it cost?",
"¿Cómo llego al sur?": "How do I get to the south?",
"¿Cómo lo sabemos?": "How do we know?",
"¿De dónde salen los datos?": "Where does the data come from?",
"¿Dónde se queda el dinero?": "Where does the money stay?",
"¿Hay espacio en {p0}?": "Is there room in {p0}?",
"¿Hay sargazo en el sur?": "Is there sargassum in the south?",
"¿Ibas al norte?": "Were you heading north?",
"¿Por qué no {p0} o Tulum?": "Why not {p0} or Tulum?",
"¿Quién hizo esto?": "Who made this?",
"¿Qué hay en {p0}?": "What is there in {p0}?",
"¿Qué lugares promueve la campaña?": "Which places does the campaign promote?",
"Modo día": "Day mode"
},
"lugares": {
"Ruta de las pirámides": "Pyramid Route",
"Calderitas y Oxtankah": "Calderitas and Oxtankah",
"Laguna Milagros y Xul-Ha": "Milagros Lagoon and Xul-Ha"
}
};
