/* Traducción al idioma «fr» de la parte del viajero. Generado por backend/torre/campana/idiomas.py desde docs/idiomas/fr.tsv: no editar a mano. */
window.IDIOMAS_TRAD = window.IDIOMAS_TRAD || {};
window.IDIOMAS_TRAD["fr"] = {
"frases": {
"<b>Temporada alta.</b> El sur también está lleno ese mes.": "<b>Haute saison.</b> Le sud est aussi très fréquenté ce mois-ci.",
"<b>Temporada alta.</b> {p0} está más tranquilo ese mes.": "<b>Haute saison.</b> {p0} est plus calme ce mois-ci.",
"<b>Temporada alta</b> quiere decir que ese mes llega {n0} % o más gente que en un mes promedio del año, o que hay {n1} % o más de probabilidad de rebasar el mes más lleno que el lugar ha tenido. Se calcula con los visitantes del INAH a las zonas arqueológicas y, en {p0}, con los cruces desde Belice.": "<b>Haute saison</b> signifie que ce mois-ci il vient {n0} % de monde en plus ou davantage qu'un mois moyen de l'année, ou qu'il y a {n1} % de probabilité ou plus de dépasser le mois le plus chargé qu'ait connu le lieu. C'est calculé avec les visiteurs de l'INAH aux sites archéologiques et, à {p0}, avec les passages depuis le Belize.",
"<b>{p0} en {m0} de {n0}: temporada alta.</b> El sur también está lleno ese mes.": "<b>{p0} en {m0} {n0} : haute saison.</b> Le sud est aussi très fréquenté ce mois-ci.",
"<b>{p0} en {m0} de {n0}: temporada alta.</b> {p1} está más tranquilo ese mes.": "<b>{p0} en {m0} {n0} : haute saison.</b> {p1} est plus calme ce mois-ci.",
"<b>{p1} en {m0} de {n0}: temporada alta.</b> {p0} está más tranquilo ese mes.": "<b>{p1} en {m0} {n0} : haute saison.</b> {p0} est plus calme ce mois-ci.",
"<b>{p1} y {p0}</b> están como referencia, para quien pensaba ir al norte; la campaña no los promueve. Ahí se mide la ocupación de los hoteles: es temporada alta si se espera {n0} % de cuartos ocupados o más, el nivel que el Radar ya cuenta como \"concurrido\". Si el mes está lleno, te recomendamos un lugar del sur. Tómalo con cuidado en la {p0}: su ocupación bajó ({n1} % en {m0} de {n2} contra {n3} % un año antes), el pronóstico supone que sigue así y se equivoca más que solo repetir lo del año anterior; se usa porque es el único cuyo rango sí atrapó el valor real {n4} de cada {n5} veces.": "<b>{p1} et {p0}</b> sont là comme référence, pour ceux qui pensaient aller au nord ; la campagne ne les promeut pas. On y mesure l'occupation des hôtels : c'est la haute saison si l'on attend {n0} % de chambres occupées ou plus, le niveau que le Radar considère déjà comme « fréquenté ». Si le mois est plein, nous vous recommandons un lieu du sud. Prudence pour {p0} : son occupation a baissé ({n1} % en {m0} {n2} contre {n3} % un an plus tôt), la prévision suppose que cela continue et se trompe davantage que de simplement répéter l'année précédente ; on l'utilise parce que c'est la seule dont la fourchette a bien capté la valeur réelle {n4} fois sur {n5}.",
"<span></span><b>Radar, {m0} de {n0}:</b> {n1} de los {n2} lugares del sur, tranquilos<span> · {p0}, sin dato oficial</span><span> · Ver el Radar →</span>": "<span></span><b>Radar, {m0} {n0} :</b> {n1} des {n2} lieux du sud sont calmes<span> · {p0}, sans donnée officielle</span><span> · Voir le Radar →</span>",
"<span></span>Calderitas: mariscos y la zona de Oxtankah<small>{n0} km →</small>": "<span></span>Calderitas : fruits de mer et le site d'Oxtankah<small>{n0} km →</small>",
"<span></span>Felipe Carrillo Puerto (estación del Tren Maya)<small>{n0} km →</small>": "<span></span>Felipe Carrillo Puerto (gare du Train maya)<small>{n0} km →</small>",
"<span></span>Kantemó: la cueva": "<span></span>Kantemó : la grotte",
"<span></span>Kohunlich y Dzibanché, en la selva": "<span></span>Kohunlich et Dzibanché, dans la jungle",
"<span></span>Kohunlich, Dzibanché e Ichkabal": "<span></span>Kohunlich, Dzibanché et Ichkabal",
"<span></span>Laguna Milagros y el cenote de Xul-Ha<small>{n0} km →</small>": "<span></span>La lagune Milagros et le cénote de Xul-Ha<small>{n0} km →</small>",
"<span></span>Señor: ecoturismo comunitario<small>{n0} km →</small>": "<span></span>Señor : écotourisme communautaire<small>{n0} km →</small>",
"<span></span>Tihosuco: el Museo de la Guerra de Castas<small>{n0} km →</small>": "<span></span>Tihosuco : le musée de la guerre des Castes<small>{n0} km →</small>",
"<span></span>Tranquilo <span></span>Normal <span></span>Temporada alta": "<span></span>Calme <span></span>Normal <span></span>Haute saison",
"<span></span>{p0}: el malecón y el Museo de la Cultura Maya<small>{n0} km →</small>": "<span></span>{p0} : le front de mer et le musée de la Culture maya<small>{n0} km →</small>",
"<span></span>{p0}: la bahía al atardecer<small>{n0} km →</small>": "<span></span>{p0} : la baie au coucher du soleil<small>{n0} km →</small>",
"<span>★ </span>Reseñas<span> ↗</span><span> en Google Maps (otra pestaña)</span>": "<span>★ </span>Avis<span> ↗</span><span> sur Google Maps (nouvel onglet)</span>",
"Agencia de viajes y tours · en el centro": "Agence de voyages et excursions · au centre",
"Agencia de viajes y tours · en {p0}, a {n0} km": "Agence de voyages et excursions · à {p0}, à {n0} km",
"Antojitos y tacos para cenar, un bar para cerrar el día y dónde dormir.": "Antojitos et tacos pour dîner, un bar pour finir la journée et où dormir.",
"Antojitos · a {n0} km del centro": "Antojitos (en-cas mexicains) · à {n0} km du centre",
"Antojitos · en el centro": "Antojitos (en-cas mexicains) · au centre",
"Asados y pollos · a {n0} km del centro": "Grillades et poulet · à {n0} km du centre",
"Asados y pollos · en el centro": "Grillades et poulet · au centre",
"Así se ve la {p0}": "Voici à quoi ressemble la {p0}",
"Así se ve {p0}": "Voici à quoi ressemble {p0}",
"Así va a <em>estar</em>.": "Voici comment ce <em>sera</em>.",
"Atardecer en el malecón": "Coucher de soleil sur le front de mer",
"Atardecer en una calle de Calderitas": "Coucher de soleil dans une rue de Calderitas",
"Atardecer en una calle de Calderitas<small>Foto: {x0}, {x1}</small>": "Coucher de soleil dans une rue de Calderitas<small>Photo: {x0}, {x1}</small>",
"Atardecer sobre la laguna de {p0}": "Coucher de soleil sur la lagune de {p0}",
"Atardecer sobre la laguna de {p0}<small>Foto: {x0}, {x1}</small>": "Coucher de soleil sur la lagune de {p0}<small>Photo: {x0}, {x1}</small>",
"Avenida Constituyentes, en Felipe Carrillo Puerto": "Avenida Constituyentes, à Felipe Carrillo Puerto",
"Aves en un muelle de la Laguna Milagros": "Oiseaux sur un ponton de la lagune Milagros",
"Bahía y pirámides": "Baie et pyramides",
"Balneario · a {n0} km del centro": "Lieu de baignade · à {n0} km du centre",
"Balneario · en Calderitas, a {n0} km": "Lieu de baignade · à Calderitas, à {n0} km",
"Balneario · en el centro": "Lieu de baignade · au centre",
"Balneario · en {p0}, a {n0} km": "Lieu de baignade · à {p0}, à {n0} km",
"Bar o cantina · a {n0} km del centro": "Bar ou cantina · à {n0} km du centre",
"Bar o cantina · en el centro": "Bar ou cantina · au centre",
"Bar o cantina · en {p0}, a {n0} km": "Bar ou cantina · à {p0}, à {n0} km",
"Cabañas y villas · a {n0} km del centro": "Cabanes et villas · à {n0} km du centre",
"Cabañas y villas · en el centro": "Cabanes et villas · au centre",
"Café, desayunos y postres · a {n0} km del centro": "Café, petits-déjeuners et desserts · à {n0} km du centre",
"Café, desayunos y postres · en el centro": "Café, petits-déjeuners et desserts · au centre",
"Café, desayunos y postres · en {p0}, a {n0} km": "Café, petits-déjeuners et desserts · à {p0}, à {n0} km",
"Cambiar a {p0} en {m0}": "Passer à {p0} en {m0}",
"Campamento · en Calderitas, a {n0} km": "Camping · à Calderitas, à {n0} km",
"Campamento · en el centro": "Camping · au centre",
"Casa de huéspedes · a {n0} km del centro": "Maison d'hôtes · à {n0} km du centre",
"Casas típicas de madera en el Boulevard Bahía": "Maisons typiques en bois sur le Boulevard Bahía",
"Casas típicas de madera en el Boulevard Bahía<small>Foto: {x0}, {x1}</small>": "Maisons typiques en bois sur le Boulevard Bahía<small>Photo: {x0}, {x1}</small>",
"Centro nocturno · a {n0} km del centro": "Boîte de nuit · à {n0} km du centre",
"Centro nocturno · en el centro": "Boîte de nuit · au centre",
"Centro nocturno · en {p0}, a {n0} km": "Boîte de nuit · à {p0}, à {n0} km",
"Cerrar aviso": "Fermer l'avis",
"Cerrar preguntas": "Fermer les questions",
"Cinco lugares": "Cinq lieux",
"Cinco lugares del sur de Quintana Roo: {p4}, {p1}, {p2}, {p3} y {p0}.": "Cinq lieux du sud du Quintana Roo : {p4}, {p1}, {p2}, {p3} et {p0}.",
"Cocina internacional · en el centro": "Cuisine internationale · au centre",
"Cocina yucateca · en el centro": "Cuisine du Yucatán · au centre",
"Comida casera · a {n0} km del centro": "Cuisine maison · à {n0} km du centre",
"Comida casera · en el centro": "Cuisine maison · au centre",
"Comida para llevar · a {n0} km del centro": "Plats à emporter · à {n0} km du centre",
"Comida para llevar · en el centro": "Plats à emporter · au centre",
"Comida rápida · a {n0} km del centro": "Restauration rapide · à {n0} km du centre",
"Comida rápida · en el centro": "Restauration rapide · au centre",
"Comparte con {p0} la vigilancia del sargazo en la bahía.": "Partage avec {p0} la surveillance des sargasses dans la baie.",
"Con datos oficiales": "Avec des données officielles",
"Cuatro están en el mismo municipio que {p0}.": "Quatre se trouvent dans la même municipalité que {p0}.",
"Cómo llega la gente": "Comment les gens arrivent",
"Cómo llegar<span> ↗</span><span> (Google Maps, otra pestaña)</span>": "Itinéraire<span> ↗</span><span> (Google Maps, nouvel onglet)</span>",
"De día": "Le jour",
"De fuentes oficiales y abiertas: Secretaría de Turismo, gobierno de Quintana Roo, INEGI, INAH, NOAA, Open-Meteo y la Reserva Federal. Las fotos, de Wikimedia Commons con licencia libre.": "De sources officielles et ouvertes : ministère du Tourisme, gouvernement du Quintana Roo, INEGI, INAH, NOAA, Open-Meteo et la Réserve fédérale des États-Unis. Les photos viennent de Wikimedia Commons, sous licence libre.",
"De noche": "La nuit",
"Del Museo de la Cultura Maya en {p0} al de la Guerra de Castas en Tihosuco: la historia del sur contada desde aquí.": "Du musée de la Culture maya à {p0} à celui de la guerre des Castes à Tihosuco : l'histoire du sud racontée d'ici.",
"Del mar a la selva, en un <em>solo</em> viaje.": "De la mer à la jungle, en un <em>seul</em> voyage.",
"Depende del lugar: arriba, en \"Planea tu viaje\", eliges lugar y mes y te decimos cómo va a estar. Por ejemplo, a la {p0} llega {n0} % menos gente que en un mes promedio en {m0}, y {n1} % más en {m1}.": "Cela dépend du lieu : en haut, dans « Planifiez votre voyage », vous choisissez un lieu et un mois et nous vous disons comment ce sera. Par exemple, {p0} reçoit {n0} % de monde en moins qu'un mois moyen en {m0}, et {n1} % de plus en {m1}.",
"Distancias en línea recta entre los centros de cada lugar (no hay datos abiertos de distancias por carretera). Sin precios: ninguna fuente oficial los publica. Las reseñas se leen en Google Maps.": "Distances à vol d'oiseau entre les centres de chaque lieu (il n'existe pas de données ouvertes sur les distances routières). Pas de prix : aucune source officielle ne les publie. Les avis se lisent sur Google Maps.",
"Documento": "Document",
"Dzibanché: el Templo del Búho": "Dzibanché : le temple du Hibou",
"Dzibanché: el Templo del Búho, {p0}": "Dzibanché : le temple du Hibou, {p0}",
"Dzibanché: el Templo del Búho. Foto: {x0}, {x1}, vía Wikimedia Commons.": "Dzibanché : le temple du Hibou. Photo: {x0}, {x1}, via Wikimedia Commons.",
"Dzibanché: el Templo del Búho<small>Foto: {x0}, {x1}</small>": "Dzibanché : le temple du Hibou<small>Photo: {x0}, {x1}</small>",
"Dzibanché: la Estructura {n0}": "Dzibanché : la Structure {n0}",
"Dzibanché: la Estructura {n0}<small>Foto: {x0}, {x1}</small>": "Dzibanché : la Structure {n0}<small>Photo: {x0}, {x1}</small>",
"Dónde comer": "Où manger",
"Dónde dormir": "Où dormir",
"El Boulevard Bahía de {p0}: casas de madera, monumentos y el sol bajando sobre el agua.": "Le Boulevard Bahía de {p0} : maisons en bois, monuments et soleil qui se couche sur l'eau.",
"El Mercado {n0} en el centro de {p0}": "Le marché {n0}, au centre de {p0}",
"El Mercado {n0} en el centro de {p0}<small>Foto: {x0}, {x1}</small>": "Le marché {n0}, au centre de {p0}<small>Photo: {x0}, {x1}</small>",
"El Monumento a la Bandera frente a la bahía": "Le monument au Drapeau face à la baie",
"El Monumento a la Bandera frente a la bahía<small>Foto: {x0}, {x1}</small>": "Le monument au Drapeau face à la baie<small>Photo: {x0}, {x1}</small>",
"El Monumento al Pescador al atardecer, en la bahía": "Le monument au Pêcheur au coucher du soleil, sur la baie",
"El Monumento al Pescador al atardecer, en la bahía, {p0}": "Le monument au Pêcheur au coucher du soleil, sur la baie, {p0}",
"El Monumento al Pescador al atardecer, en la bahía. Foto: {x0}, {x1}, vía Wikimedia Commons.": "Le monument au Pêcheur au coucher du soleil, sur la baie. Photo: {x0}, {x1}, via Wikimedia Commons.",
"El Monumento al Pescador al atardecer, en la bahía<small>Foto: {x0}, {x1}</small>": "Le monument au Pêcheur au coucher du soleil, sur la baie<small>Photo: {x0}, {x1}</small>",
"El Portal Maya del parque Fundadores": "Le Portail maya du parc Fundadores",
"El Portal Maya del parque Fundadores<small>Foto: {x0}, {x1}</small>": "Le Portail maya du parc Fundadores<small>Photo: {x0}, {x1}</small>",
"El Radar": "Le Radar",
"El agua turquesa de la Laguna Milagros": "L'eau turquoise de la lagune Milagros",
"El cenote de Xul-Ha": "Le cénote de Xul-Ha",
"El clima es el normal de {n0} a {n1}. El riesgo de tormenta cuenta las tormentas que pasaron a {n2} km o menos del lugar desde {n3} ({n4} en el caso de {p1}). {p0} y la Laguna Milagros no tienen estadística oficial de visitantes, así que no están en el planeador; los encuentras en \"Los lugares\".": "Le climat est la normale de {n0} à {n1}. Le risque de tempête compte les tempêtes passées à {n2} km ou moins du lieu depuis {n3} ({n4} dans le cas de {p1}). {p0} et la lagune Milagros n'ont pas de statistiques officielles de visiteurs, ils ne sont donc pas dans le planificateur ; vous les trouverez dans « Les lieux ».",
"El dato": "Le chiffre",
"El dinero": "L'argent",
"El kiosco del centro de {p0}": "Le kiosque du centre de {p0}",
"El kiosco del centro de {p0}<small>Foto: {x0}, {x1}</small>": "Le kiosque du centre de {p0}<small>Photo: {x0}, {x1}</small>",
"El norte": "Le nord",
"El parque y los restaurantes de Calderitas al atardecer": "Le parc et les restaurants de Calderitas au coucher du soleil",
"El parque y los restaurantes de Calderitas al atardecer<small>Foto: {x0}, {x1}</small>": "Le parc et les restaurants de Calderitas au coucher du soleil<small>Photo: {x0}, {x1}</small>",
"El problema": "Le problème",
"El sur": "Le sud",
"El sur tiene <em>espacio</em>.": "Le sud a de la <em>place</em>.",
"El sur tiene <em>espacio</em>.<br>Y te está esperando.": "Le sud a de la <em>place</em>.<br>Et il vous attend.",
"Elige a dónde y cuándo. Te decimos cómo va a estar.": "Choisissez où et quand. Nous vous disons comment ce sera.",
"En Calderitas, a {n0} km de {p0}, se come viendo el agua; al lado está Oxtankah, la ciudad maya de la bahía.": "À Calderitas, à {n0} km de {p0}, on mange face à l'eau ; juste à côté se trouve Oxtankah, la cité maya de la baie.",
"En Felipe Carrillo Puerto, Señor y Tihosuco las comunidades mayas reciben a quien llega: selva, historia y su forma de vivir.": "À Felipe Carrillo Puerto, Señor et Tihosuco, les communautés mayas accueillent les visiteurs : jungle, histoire et leur façon de vivre.",
"En la costa de {p1} y Calderitas no hay reporte de sargazo. Sí apareció en los canales de entrada de la bahía ({m0} de {n0}), así que se vigila. La ruta de las pirámides, {p0} y la laguna están lejos del mar abierto.": "Sur la côte de {p1} et de Calderitas, aucune sargasse n'est signalée. Elle est apparue dans les chenaux d'entrée de la baie ({m0} {n0}), elle est donc surveillée. La route des pyramides, {p0} et la lagune sont loin de la haute mer.",
"En los municipios de los cinco lugares no hay ningún hospedaje grande: {n0} son chicos (hasta {n1} personas) y {n2} medianos. La derrama económica por destino no se muestra porque la fuente no dice en qué unidad está.": "Dans les municipalités des cinq lieux, il n'y a aucun grand hébergement : {n0} sont petits (jusqu'à {n1} personnes) et {n2} moyens. Les dépenses touristiques par destination ne sont pas affichées car la source ne précise pas leur unité.",
"En {m0} el sur también tiene temporada alta. Si puedes mover tu viaje, busca los meses en verde.": "En {m0}, le sud est aussi en haute saison. Si vous pouvez décaler votre voyage, cherchez les mois en vert.",
"En {m0}, <b>{p0}</b> no está en temporada alta: hay espacio, sin el gentío del norte.": "En {m0}, <b>{p0}</b> n'est pas en haute saison : il y a de la place, sans la foule du nord.",
"En {m0}, <b>{p1}</b> está más tranquilo. O ve a la {p0} en <b>{m1}</b>: menos gente, poca lluvia y fuera de la temporada de tormentas.": "En {m0}, <b>{p1}</b> est plus calme. Ou allez à la {p0} en <b>{m1}</b> : moins de monde, peu de pluie et hors de la saison des tempêtes.",
"En {m0}, <b>{p1}</b> está más tranquilo. O ve a {p0} en <b>{m1}</b>: menos gente, poca lluvia y fuera de la temporada de tormentas.": "En {m0}, <b>{p1}</b> est plus calme. Ou allez à {p0} en <b>{m1}</b> : moins de monde, peu de pluie et hors de la saison des tempêtes.",
"En {n0} llegaron {n1} pasajeros en avión a {p1}, y el Tren Maya para en {p1}, Bacalar y Felipe Carrillo Puerto ({p0}). Solo en {m0} de {n2} {n3} personas bajaron del tren en {p1}.": "En {n0}, {n1} passagers sont arrivés en avion à {p1}, et le Train maya s'arrête à {p1}, Bacalar et Felipe Carrillo Puerto ({p0}). Rien qu'en {m0} {n2}, {n3} personnes sont descendues du train à {p1}.",
"Enviar pregunta": "Envoyer la question",
"Escribe tu pregunta": "Écrivez votre question",
"Escribe tu pregunta…": "Écrivez votre question…",
"Ese mes todavía no está en el pronóstico (llega hasta {m0} de {n0}): en un {m1} típico, de {n1} a {n2} los hoteles estuvieron al <b>{n3} %</b>.": "Ce mois-là n'est pas encore dans la prévision (elle va jusqu'à {m0} {n0}) : un mois de {m1} typique, de {n1} à {n2}, les hôtels étaient à <b>{n3} %</b>.",
"Ese mes todavía no está en el pronóstico (llega hasta {m0} de {n0}): esto es lo típico de {m1}.": "Ce mois-là n'est pas encore dans la prévision (elle va jusqu'à {m0} {n0}) : voici ce qui est typique pour {m1}.",
"Esta parte está en español: son los datos técnicos del proyecto.": "Cette partie est en espagnol : ce sont les données techniques du projet.",
"Estructura {n0} de Oxtankah, con pintura original": "Structure {n0} d'Oxtankah, avec sa peinture d'origine",
"Estructura {n0} de Oxtankah, con pintura original<small>Foto: {x0}, {x1}</small>": "Structure {n0} d'Oxtankah, avec sa peinture d'origine<small>Photo: {x0}, {x1}</small>",
"Fotos de los cinco lugares; se pueden recorrer con las flechas": "Photos des cinq lieux ; vous pouvez les parcourir avec les flèches",
"Fuente: ECOSUR y notas del {n0} de {m0} de {n1}": "Source : ECOSUR et articles de presse de {m0} {n0}, {n1}",
"Fuente: Gobierno de Quintana Roo (SITUR-Q)": "Source : gouvernement du Quintana Roo (SITUR-Q)",
"Fuente: INAH (BdINAH) y forma del año del proyecto (Fase {n0})": "Source : INAH (BdINAH) et forme de l'année du projet (phase {n0})",
"Fuente: INAH (BdINAH), SITUR-Q (frontera con Belice), SECTUR-DataTur (ocupación hotelera de {p1} y {p0}), NOAA HURDAT2, Open-Meteo (clima {n0}–{n1}) y pronóstico del proyecto (Fase {n2}); negocios: INEGI, DENUE.": "Source : INAH (BdINAH), SITUR-Q (frontière avec le Belize), SECTUR-DataTur (occupation hôtelière de {p1} et {p0}), NOAA HURDAT2, Open-Meteo (climat {n0}–{n1}) et prévision du projet (phase {n2}) ; commerces : INEGI, DENUE.",
"Fuente: INEGI (DENUE) y SITUR-Q": "Source : INEGI (DENUE) et SITUR-Q",
"Fuente: INEGI y gobierno de Quintana Roo": "Source : INEGI et gouvernement du Quintana Roo",
"Fuente: INEGI, Directorio Estadístico Nacional de Unidades Económicas (DENUE). El tipo de lugar y el momento del día los sugiere un clasificador de texto que lee el nombre y el giro oficial de cada negocio (acertó {n0} de {n1} en una revisión al azar). Cuando un lugar no tiene algo cerca, se muestra lo más cercano de los otros lugares del sur. \"Ver en Google Maps\" abre Google Maps en otra pestaña; esta página no descarga nada de Google.": "Source : INEGI, Répertoire statistique national des unités économiques (DENUE). Le type de lieu et le moment de la journée sont suggérés par un classificateur de texte qui lit le nom et l'activité officielle de chaque commerce (il a eu juste {n0} fois sur {n1} lors d'une vérification au hasard). Quand un lieu n'a rien de proche, on affiche le plus proche parmi les autres lieux du sud. « Voir sur Google Maps » ouvre Google Maps dans un nouvel onglet ; cette page ne télécharge rien de Google.",
"Fuente: Inventario de fuentes del proyecto": "Source : inventaire des sources du projet",
"Fuente: Secretaría de Turismo y notas verificadas de {n0}": "Source : ministère du Tourisme et articles vérifiés de {n0}",
"Fuente: Selección de regiones del proyecto": "Source : sélection des régions du projet",
"Fuente: Torre del Caribe": "Source : Torre del Caribe",
"Girar el mapa solo": "Faire tourner la carte toute seule",
"Habrá mucha gente: los hoteles suelen pasar del {n0} % de cuartos ocupados, lo que el Radar ya cuenta como \"concurrido\".": "Il y aura beaucoup de monde : les hôtels dépassent en général {n0} % de chambres occupées, ce que le Radar considère déjà comme « fréquenté ».",
"Habrá mucha gente: se espera que los hoteles pasen del {n0} % de cuartos ocupados, lo que el Radar ya cuenta como \"concurrido\".": "Il y aura beaucoup de monde : on s'attend à ce que les hôtels dépassent {n0} % de chambres occupées, ce que le Radar considère déjà comme « fréquenté ».",
"Hasta {m0} de {n0} hay un pronóstico con su rango: el valor real cayó dentro de ese rango entre {n1} y {n2} de cada {n3} veces cuando se probó con meses que el modelo nunca vio. Después de esa fecha se muestra lo típico de cada mes.": "Jusqu'en {m0} {n0}, il existe une prévision avec sa fourchette : la valeur réelle est tombée dans cette fourchette entre {n1} et {n2} fois sur {n3} lorsqu'on l'a testée sur des mois que le modèle n'avait jamais vus. Après cette date, on affiche ce qui est typique de chaque mois.",
"Hay espacio: los hoteles suelen quedar debajo del {n0} % de cuartos ocupados, lo que el Radar cuenta como \"concurrido\".": "Il y a de la place : les hôtels restent en général sous {n0} % de chambres occupées, ce que le Radar considère comme « fréquenté ».",
"Hay espacio: se espera que los hoteles queden debajo del {n0} % de cuartos ocupados, lo que el Radar cuenta como \"concurrido\".": "Il y a de la place : on s'attend à ce que les hôtels restent sous {n0} % de chambres occupées, ce que le Radar considère comme « fréquenté ».",
"Hay lugar: {n0} de cada {n1} cuartos de hotel de {p0} se quedaron vacíos en {n2}. <small>Fuente: Gobierno de Quintana Roo (SITUR-Q)</small>": "Il y a de la place : {n0} chambres d'hôtel sur {n1} à {p0} sont restées vides en {n2}. <small>Source : gouvernement du Quintana Roo (SITUR-Q)</small>",
"Hay pocos cuartos de hotel: la campaña pone un límite de visitantes para no rebasar a los pueblos.": "Il y a peu de chambres d'hôtel : la campagne fixe une limite de visiteurs pour ne pas déborder les villages.",
"Hola. Pregúntame sobre los cinco lugares, cómo llegar o de dónde salen los datos.": "Bonjour. Posez-moi des questions sur les cinq lieux, comment y aller ou d'où viennent les données.",
"Hospedaje de la gente de aquí: en los municipios de los cinco lugares hay {n0} hospedajes chicos, {n1} medianos y {n2} grandes. <small>Fuente: INEGI (DENUE)</small>": "Des hébergements tenus par les gens d'ici : dans les municipalités des cinq lieux, il y a {n0} petits hébergements, {n1} moyens et {n2} grands. <small>Source : INEGI (DENUE)</small>",
"Hostal · en el centro": "Auberge de jeunesse · au centre",
"Hostal · en {p0}, a {n0} km": "Auberge de jeunesse · à {p0}, à {n0} km",
"Hotel · en Xul-ha, a {n0} km": "Hôtel · à Xul-Ha, à {n0} km",
"Hotel · en el centro": "Hôtel · au centre",
"Hotel · en {p0}, a {n0} km": "Hôtel · à {p0}, à {n0} km",
"Idioma": "Langue",
"Idioma / Language": "Langue / Language",
"Iglesia en Felipe Carrillo Puerto": "Église de Felipe Carrillo Puerto",
"Iglesia en Felipe Carrillo Puerto. Foto: {x0}, {x1}, vía Wikimedia Commons.": "Église de Felipe Carrillo Puerto. Photo: {x0}, {x1}, via Wikimedia Commons.",
"Jardín botánico o zoológico · a {n0} km del centro": "Jardin botanique ou zoo · à {n0} km du centre",
"Jardín botánico o zoológico · en el centro": "Jardin botanique ou zoo · au centre",
"Jardín botánico o zoológico · en {p0}, a {n0} km": "Jardin botanique ou zoo · à {p0}, à {n0} km",
"Kohunlich, Dzibanché e Ichkabal: ciudades mayas entre la selva, con sus mascarones y templos.": "Kohunlich, Dzibanché et Ichkabal : des cités mayas dans la jungle, avec leurs masques et leurs temples.",
"Kohunlich, Dzibanché e Ichkabal: tres ciudades mayas en la selva, lejos del mar.": "Kohunlich, Dzibanché et Ichkabal : trois cités mayas dans la jungle, loin de la mer.",
"Kohunlich, Dzibanché e Ichkabal: tres ciudades mayas en la selva, lejos del mar. Tiene {n0} lugares para comer y {n1} para dormir. Cuidado: los poblados cercanos casi no tienen hoteles: la visita se hace desde {p0}.": "Kohunlich, Dzibanché et Ichkabal : trois cités mayas dans la jungle, loin de la mer. On y trouve {n0} endroits où manger et {n1} où dormir. Attention : les villages proches n'ont presque pas d'hôtels, la visite se fait depuis {p0}.",
"Kohunlich: detalle de un mascarón": "Kohunlich : détail d'un masque",
"Kohunlich: detalle de un mascarón<small>Foto: {x0}, {x1}</small>": "Kohunlich : détail d'un masque<small>Photo: {x0}, {x1}</small>",
"Kohunlich: el juego de pelota": "Kohunlich : le jeu de balle",
"Kohunlich: el juego de pelota<small>Foto: {x0}, {x1}</small>": "Kohunlich : le jeu de balle<small>Photo: {x0}, {x1}</small>",
"Kohunlich: los mascarones de estuco": "Kohunlich : les masques en stuc",
"Kohunlich: los mascarones de estuco<small>Foto: {x0}, {x1}</small>": "Kohunlich : les masques en stuc<small>Photo: {x0}, {x1}</small>",
"Kohunlich: una de sus plataformas en la selva": "Kohunlich : l'une de ses plateformes dans la jungle",
"Kohunlich: una de sus plataformas en la selva<small>Foto: {x0}, {x1}</small>": "Kohunlich : l'une de ses plateformes dans la jungle<small>Photo: {x0}, {x1}</small>",
"La Campana del Bicentenario": "La cloche du Bicentenaire",
"La Campana del Bicentenario<small>Foto: {x0}, {x1}</small>": "La cloche du Bicentenaire<small>Photo: {x0}, {x1}</small>",
"La Laguna Milagros y el cenote de Xul-Ha, a {n0} km de {p0}. Es frágil: se nada sin bloqueador y sin dejar nada.": "La lagune Milagros et le cénote de Xul-Ha, à {n0} km de {p0}. C'est fragile : on s'y baigne sans crème solaire et sans rien laisser.",
"La Quinta Avenida de Playa del Carmen": "La Cinquième Avenue de Playa del Carmen",
"La Quinta Avenida de Playa del Carmen<small>Foto: {x0}, {x1}</small>": "La Cinquième Avenue de Playa del Carmen<small>Photo: {x0}, {x1}</small>",
"La bahía de {p0} desde el Boulevard": "La baie de {p0} depuis le Boulevard",
"La bahía de {p0} desde el Boulevard. Foto: {x0}, {x1}, vía Wikimedia Commons.": "La baie de {p0} depuis le Boulevard. Photo: {x0}, {x1}, via Wikimedia Commons.",
"La bahía frente a Calderitas": "La baie face à Calderitas",
"La bahía frente a Calderitas. Foto: {x0}, {x1}, vía Wikimedia Commons.": "La baie face à Calderitas. Photo: {x0}, {x1}, via Wikimedia Commons.",
"La bahía vista desde Calderitas": "La baie vue depuis Calderitas",
"La bahía vista desde Calderitas, {p0}": "La baie vue depuis Calderitas, {p0}",
"La bahía vista desde Calderitas. Foto: {x0}, {x1}, vía Wikimedia Commons.": "La baie vue depuis Calderitas. Photo: {x0}, {x1}, via Wikimedia Commons.",
"La bahía vista desde Calderitas<small>Foto: {x0}, {x1}</small>": "La baie vue depuis Calderitas<small>Photo: {x0}, {x1}</small>",
"La capilla antigua dentro de la zona de Oxtankah": "L'ancienne chapelle dans le site d'Oxtankah",
"La capilla antigua dentro de la zona de Oxtankah<small>Foto: {x0}, {x1}</small>": "L'ancienne chapelle dans le site d'Oxtankah<small>Photo: {x0}, {x1}</small>",
"La capilla de Nuestra Señora del Carmen": "La chapelle Notre-Dame-du-Carmel",
"La capilla de Nuestra Señora del Carmen<small>Foto: {x0}, {x1}</small>": "La chapelle Notre-Dame-du-Carmel<small>Photo: {x0}, {x1}</small>",
"La capital del estado, frente a la bahía, con el Museo de la Cultura Maya.": "La capitale de l'État, face à la baie, avec le musée de la Culture maya.",
"La capital del estado, frente a la bahía, con el Museo de la Cultura Maya. Tiene {n0} lugares para comer y {n1} para dormir; {n2} personas llegaron en el Tren Maya en {m0} de {n3}. Cuidado: se vigila el sargazo que apareció en los canales de entrada de la bahía ({m1} de {n4}).": "La capitale de l'État, face à la baie, avec le musée de la Culture maya. On y trouve {n0} endroits où manger et {n1} où dormir ; {n2} personnes sont arrivées en Train maya en {m0} {n3}. Attention : on surveille les sargasses apparues dans les chenaux d'entrée de la baie ({m1} {n4}).",
"La gran pirámide de Dzibanché en la selva": "La grande pyramide de Dzibanché dans la jungle",
"La gran pirámide de Dzibanché en la selva. Foto: {x0}, {x1}, vía Wikimedia Commons.": "La grande pyramide de Dzibanché dans la jungle. Photo: {x0}, {x1}, via Wikimedia Commons.",
"La laguna Nichupté": "La lagune Nichupté",
"La laguna Nichupté<small>Foto: {x0}, {x1}</small>": "La lagune Nichupté<small>Photo: {x0}, {x1}</small>",
"La laguna es frágil: visitas con límite estricto y sin actividades que la dañen.": "La lagune est fragile : visites avec une limite stricte et sans activités qui l'abîment.",
"La orilla de la laguna en Huay-Pix": "La rive de la lagune à Huay-Pix",
"La playa del pueblo, en Playa del Carmen": "La plage du village, à Playa del Carmen",
"La playa del pueblo, en Playa del Carmen<small>Foto: {x0}, {x1}</small>": "La plage du village, à Playa del Carmen<small>Photo: {x0}, {x1}</small>",
"Laguna y selva": "Lagune et jungle",
"Las fases": "Les phases",
"Las fotos son de Wikimedia Commons, con licencia libre, y cada una se tomó dentro del municipio del lugar (su coordenada se comprobó con el mapa oficial).": "Les photos viennent de Wikimedia Commons, sous licence libre, et chacune a été prise dans la municipalité du lieu (ses coordonnées ont été vérifiées sur la carte officielle).",
"Llega más o menos la gente de un mes promedio.": "À peu près autant de monde qu'un mois moyen.",
"Llega {n0} % menos gente que en un mes promedio: hay espacio.": "{n0} % de monde en moins qu'un mois moyen : il y a de la place.",
"Llega {n0} % más gente que en un mes promedio, y hay {n1} % de probabilidad de rebasar el mes más lleno de su historia.": "{n0} % de monde en plus qu'un mois moyen, et {n1} % de probabilité de dépasser le mois le plus chargé de son histoire.",
"Llega {n0} % más gente que en un mes promedio.": "{n0} % de monde en plus qu'un mois moyen.",
"Lo que hay <em>detrás</em> del viaje.": "Ce qu'il y a <em>derrière</em> le voyage.",
"Lo que no te <em>cuentan</em> del Caribe.": "Ce qu'on ne vous <em>dit</em> pas sur les Caraïbes.",
"Lo que todos <em>preguntan</em>.": "Ce que tout le monde <em>demande</em>.",
"Los Voladores en el parque Fundadores": "Les Voladores au parc Fundadores",
"Los Voladores en el parque Fundadores<small>Foto: {x0}, {x1}</small>": "Les Voladores au parc Fundadores<small>Photo: {x0}, {x1}</small>",
"Los datos": "Les données",
"Los lugares": "Les lieux",
"Los lugares del sur con estadística están en temporada alta este mes. Mejor ve a la {p0} en <b>{m0}</b>: menos gente, poca lluvia y fuera de la temporada de tormentas.": "Les lieux du sud avec statistiques sont en haute saison ce mois-ci. Allez plutôt à la {p0} en <b>{m0}</b> : moins de monde, peu de pluie et hors de la saison des tempêtes.",
"Los lugares del sur con estadística están en temporada alta este mes. Mejor ve a {p0} en <b>{m0}</b>: menos gente, poca lluvia y fuera de la temporada de tormentas.": "Les lieux du sud avec statistiques sont en haute saison ce mois-ci. Allez plutôt à {p0} en <b>{m0}</b> : moins de monde, peu de pluie et hors de la saison des tempêtes.",
"Los poblados cercanos casi no tienen hoteles: la visita se hace desde {p0}.": "Les villages proches n'ont presque pas d'hôtels : la visite se fait depuis {p0}.",
"Lugar": "Lieu",
"Lugares reales del directorio de negocios del INEGI, del más cercano al más lejano. No son reseñas ni anuncios pagados y el directorio no publica horarios: confirma antes de ir.": "De vrais lieux de l'annuaire des commerces de l'INEGI, du plus proche au plus éloigné. Ce ne sont ni des avis ni des publicités payantes, et l'annuaire ne publie pas d'horaires : vérifiez avant d'y aller.",
"Maqueta del sur de Quintana Roo. Arrastra para girarla.": "Maquette du sud du Quintana Roo. Faites-la glisser pour la tourner.",
"Mariposa búho cerca de Chunhuhub": "Papillon hibou près de Chunhuhub",
"Mariposa en la selva cerca de Chunhuhub": "Papillon dans la jungle près de Chunhuhub",
"Mariscos frente a la bahía": "Fruits de mer face à la baie",
"Mariscos y pescado · a {n0} km del centro": "Fruits de mer et poisson · à {n0} km du centre",
"Mariscos y pescado · en el centro": "Fruits de mer et poisson · au centre",
"Mejor mes: <b>{m0}</b> · el mes más seco y sin tormentas (no hay estadística de visitantes)": "Meilleur mois : <b>{m0}</b> · le mois le plus sec et sans tempêtes (pas de statistiques de visiteurs)",
"Mejor mes: <b>{m0}</b> · menos gente, poca lluvia y sin temporada de tormentas": "Meilleur mois : <b>{m0}</b> · moins de monde, peu de pluie et hors saison des tempêtes",
"Mejor ve al sur": "Allez plutôt au sud",
"Menú": "Menu",
"Mes": "Mois",
"Mes normal": "Mois normal",
"Mes tranquilo": "Mois calme",
"Modo noche": "Mode nuit",
"Museo · a {n0} km del centro": "Musée · à {n0} km du centre",
"Museo · en el centro": "Musée · au centre",
"Museo · en {p0}, a {n0} km": "Musée · à {p0}, à {n0} km",
"Museos de la cultura maya": "Musées de la culture maya",
"Nadar en la Laguna Milagros": "Se baigner dans la lagune Milagros",
"No damos precios: ninguna fuente oficial abierta publica tarifas de hotel por lugar, y no las inventamos. Lo que sí sabemos es que en el sur los hoteles son chicos: {n0} cuartos por hotel en {p0} contra {n1} en {p1} ({m0} de {n2}).": "Nous ne donnons pas de prix : aucune source officielle ouverte ne publie les tarifs hôteliers par lieu, et nous ne les inventons pas. Ce que nous savons, c'est que dans le sud les hôtels sont petits : {n0} chambres par hôtel à {p0} contre {n1} à {p1} ({m0} {n2}).",
"No hay estadística oficial de visitantes: por eso se cuida con un límite estricto de gente. <small>Fuente: Selección de regiones del proyecto</small>": "Il n'y a pas de statistiques officielles de visiteurs : c'est pourquoi on la protège avec une limite stricte de personnes. <small>Source : sélection des régions du projet</small>",
"Palapas en Huay-Pix, a la orilla de la laguna": "Palapas à Huay-Pix, au bord de la lagune",
"Parque · a {n0} km del centro": "Parc · à {n0} km du centre",
"Parque · en {p0}, a {n0} km": "Parc · à {p0}, à {n0} km",
"Paseo en lancha · en el centro": "Balade en bateau · au centre",
"Paseo en lancha · en {p0}, a {n0} km": "Balade en bateau · à {p0}, à {n0} km",
"Pirámide de la Tumba {n0} en Oxtankah": "Pyramide de la Tombe {n0} à Oxtankah",
"Pirámide de la Tumba {n0} en Oxtankah<small>Foto: {x0}, {x1}</small>": "Pyramide de la Tombe {n0} à Oxtankah<small>Photo: {x0}, {x1}</small>",
"Pirámides en la selva": "Des pyramides dans la jungle",
"Pizzas y hamburguesas · a {n0} km del centro": "Pizzas et hamburgers · à {n0} km du centre",
"Pizzas y hamburguesas · en el centro": "Pizzas et hamburgers · au centre",
"Planea tu viaje": "Planifiez votre voyage",
"Planea tu viaje · el sur de Quintana Roo": "Planifiez votre voyage · le sud du Quintana Roo",
"Playa Gaviota Azul, en la punta de {p0}": "Plage Gaviota Azul, à la pointe de {p0}",
"Playa Gaviota Azul, en la punta de {p0}, {p0}": "Plage Gaviota Azul, à la pointe de {p0}, {p0}",
"Playa Gaviota Azul, en la punta de {p0}. Foto: {x0}, {x1}, vía Wikimedia Commons.": "Plage Gaviota Azul, à la pointe de {p0}. Photo: {x0}, {x1}, via Wikimedia Commons.",
"Playa Gaviota Azul, en la punta de {p0}<small>Foto: {x0}, {x1}</small>": "Plage Gaviota Azul, à la pointe de {p0}<small>Photo: {x0}, {x1}</small>",
"Playa de la zona hotelera de {p0}": "Plage de la zone hôtelière de {p0}",
"Playa de la zona hotelera de {p0}<small>Foto: {x0}, {x1}</small>": "Plage de la zone hôtelière de {p0}<small>Photo: {x0}, {x1}</small>",
"Playa del Carmen desde el aire": "Playa del Carmen vue du ciel",
"Playa del Carmen desde el aire, {p0}": "Playa del Carmen vue du ciel, {p0}",
"Playa del Carmen desde el aire. Foto: {x0}, {x1}, vía Wikimedia Commons.": "Playa del Carmen vue du ciel. Photo: {x0}, {x1}, via Wikimedia Commons.",
"Playa del Carmen desde el aire<small>Foto: {x0}, {x1}</small>": "Playa del Carmen vue du ciel<small>Photo: {x0}, {x1}</small>",
"Por la tarde": "L'après-midi",
"Posada · a {n0} km del centro": "Auberge · à {n0} km du centre",
"Posada · en el centro": "Auberge · au centre",
"Posada · en {p0}, a {n0} km": "Auberge · à {p0}, à {n0} km",
"Postales del sur": "Cartes postales du sud",
"Postales del sur · fotos tomadas en cada lugar": "Cartes postales du sud · photos prises sur place",
"Preguntas": "Questions",
"Preguntas frecuentes": "Questions fréquentes",
"Preguntas rápidas": "Questions rapides",
"Pregúntanos": "Demandez-nous",
"Pueblo de pescadores junto a la bahía y la zona arqueológica de Oxtankah, casi siempre sin filas.": "Village de pêcheurs au bord de la baie, avec le site archéologique d'Oxtankah, presque toujours sans file d'attente.",
"Pueblo de pescadores junto a la bahía y la zona arqueológica de Oxtankah, casi siempre sin filas. Tiene {n0} lugares para comer y {n1} para dormir. Cuidado: comparte con {p0} la vigilancia del sargazo en la bahía.": "Village de pêcheurs au bord de la baie, avec le site archéologique d'Oxtankah, presque toujours sans file d'attente. On y trouve {n0} endroits où manger et {n1} où dormir. Attention : il partage avec {p0} la surveillance des sargasses dans la baie.",
"Pueblos de {p0}": "Villages de {p0}",
"Pueblos mayas con turismo comunitario y la cueva de Kantemó.": "Villages mayas avec tourisme communautaire et la grotte de Kantemó.",
"Pueblos mayas con turismo comunitario y la cueva de Kantemó. Tiene {n0} lugares para comer y {n1} para dormir; {n2} personas llegaron en el Tren Maya en {m0} de {n3}. Cuidado: hay pocos cuartos de hotel: la campaña pone un límite de visitantes para no rebasar a los pueblos.": "Villages mayas avec tourisme communautaire et la grotte de Kantemó. On y trouve {n0} endroits où manger et {n1} où dormir ; {n2} personnes sont arrivées en Train maya en {m0} {n3}. Attention : il y a peu de chambres d'hôtel, la campagne fixe donc une limite de visiteurs pour ne pas déborder les villages.",
"Qué hacer": "Que faire",
"Radar, {m0} de {n0}:": "Radar, {m0} {n0} :",
"Recreación · a {n0} km del centro": "Loisirs · à {n0} km du centre",
"Recreación · en Xul-ha, a {n0} km": "Loisirs · à Xul-Ha, à {n0} km",
"Recreación · en el centro": "Loisirs · au centre",
"Recreación · en {p0}, a {n0} km": "Loisirs · à {p0}, à {n0} km",
"Respondo con los datos del proyecto. Si no lo sé, lo digo.": "Je réponds avec les données du projet. Si je ne sais pas, je le dis.",
"Restaurante Bahía Villamar, en una casa de madera": "Restaurant Bahía Villamar, dans une maison en bois",
"Restaurante Bahía Villamar, en una casa de madera<small>Foto: {x0}, {x1}</small>": "Restaurant Bahía Villamar, dans une maison en bois<small>Photo: {x0}, {x1}</small>",
"Restaurante a la carta · a {n0} km del centro": "Restaurant à la carte · à {n0} km du centre",
"Restaurante a la carta · en el centro": "Restaurant à la carte · au centre",
"Rutas de {n0} y {n1} días": "Itinéraires de {n0} et {n1} jours",
"Saltar al contenido": "Aller au contenu",
"Se espera alrededor de <b>{n0} %</b> de los cuartos de hotel ocupados, muy probablemente entre {n1} y {n2} %.": "On attend environ <b>{n0} %</b> de chambres d'hôtel occupées, très probablement entre {n1} et {n2} %.",
"Se esperan alrededor de <b>{n0}</b> cruces desde Belice, muy probablemente entre {n1} y {n2}.": "On attend environ <b>{n0}</b> passages depuis le Belize, très probablement entre {n1} et {n2}.",
"Se esperan alrededor de <b>{n0}</b> visitantes a Kohunlich, Dzibanché e Ichkabal, muy probablemente entre {n1} y {n2}.": "On attend environ <b>{n0}</b> visiteurs à Kohunlich, Dzibanché et Ichkabal, très probablement entre {n1} et {n2}.",
"Se esperan alrededor de <b>{n0}</b> visitantes a la zona de Oxtankah, muy probablemente entre {n1} y {n2}.": "On attend environ <b>{n0}</b> visiteurs au site d'Oxtankah, très probablement entre {n1} et {n2}.",
"Se vigila el sargazo que apareció en los canales de entrada de la bahía ({m0} de {n0}).": "On surveille les sargasses apparues dans les chenaux d'entrée de la baie ({m0} {n0}).",
"Secciones": "Sections",
"Seis experiencias con lugares reales y una cifra oficial cada una. Sin precios: ninguna fuente oficial los publica.": "Six expériences avec de vrais lieux et un chiffre officiel pour chacune. Pas de prix : aucune source officielle ne les publie.",
"Sin dato": "Pas de donnée",
"Sin dato oficial": "Pas de donnée officielle",
"Sí: en {n0} {n1} de cada {n2} cuartos de hotel de {p0} se quedaron vacíos ({n3} de {n4} noches ocupadas).": "Oui : en {n0}, {n1} chambres d'hôtel sur {n2} à {p0} sont restées vides ({n3} nuits occupées sur {n4}).",
"Tacos y tortas · a {n0} km del centro": "Tacos et tortas · à {n0} km du centre",
"Tacos y tortas · en el centro": "Tacos et tortas · au centre",
"Te conviene más": "Mieux vaut",
"Temporada alta": "Haute saison",
"Temporada alta.": "Haute saison.",
"Tienen sargazo y se llenan: en su semana más llena, {p0} tuvo {n0} de cada {n1} cuartos ocupados, y en Tulum se reportaron cierres de negocios en {n2}. La campaña lleva gente a donde sí hay espacio.": "Elles ont des sargasses et se remplissent : lors de sa semaine la plus chargée, {p0} a eu {n0} chambres occupées sur {n1}, et des fermetures de commerces ont été signalées à Tulum en {n2}. La campagne emmène les gens là où il y a vraiment de la place.",
"Todo lo que viste arriba sale de datos oficiales, modelos y pruebas. Esta parte es para quien quiera revisar cómo lo sabemos.": "Tout ce que vous avez vu plus haut vient de données officielles, de modèles et de tests. Cette partie est pour ceux qui veulent vérifier comment nous le savons.",
"Tranquilo": "Calme",
"Tu viaje": "Votre voyage",
"Turismo comunitario maya": "Tourisme communautaire maya",
"Un balneario o un parque, y a comer: mariscos, cocina yucateca o comida casera.": "Un lieu de baignade ou un parc, puis à table : fruits de mer, cuisine du Yucatán ou cuisine maison.",
"Un día en <em>{p0}</em>": "Une journée à <em>{p0}</em>",
"Un equipo de estudiantes de Ciencias de Datos para Negocios de la Universidad Nacional Rosario Castellanos (UNRC), como proyecto escolar {n0}-{n1}.": "Une équipe d'étudiants en science des données pour les affaires de l'Université nationale Rosario Castellanos (UNRC), dans le cadre d'un projet scolaire {n0}-{n1}.",
"Un matapalo en la selva de Felipe Carrillo Puerto": "Un figuier étrangleur dans la jungle de Felipe Carrillo Puerto",
"Un muelle en la Laguna Milagros": "Un ponton sur la lagune Milagros",
"Un muelle en la Laguna Milagros. Foto: {x0}, {x1}, vía Wikimedia Commons.": "Un ponton sur la lagune Milagros. Photo: {x0}, {x1}, via Wikimedia Commons.",
"Una laguna del mismo sistema que Bacalar, con pueblos a la orilla.": "Une lagune du même système que Bacalar, avec des villages sur ses rives.",
"Una laguna del mismo sistema que Bacalar, con pueblos a la orilla. Tiene {n0} lugares para comer y {n1} para dormir. Cuidado: la laguna es frágil: visitas con límite estricto y sin actividades que la dañen.": "Une lagune du même système que Bacalar, avec des villages sur ses rives. On y trouve {n0} endroits où manger et {n1} où dormir. Attention : la lagune est fragile, visites avec une limite stricte et sans activités qui l'abîment.",
"Una laguna dulce y un cenote": "Une lagune d'eau douce et un cénote",
"Unas {n0} personas al día entre las tres zonas en {n1}: tienes la pirámide casi para ti. <small>Fuente: INAH</small>": "Environ {n0} personnes par jour pour les trois sites en {n1} : vous avez presque la pyramide pour vous. <small>Source : INAH</small>",
"Ver cómo está en {m0}": "Voir comment c'est en {m0}",
"Ver cómo va a estar": "Voir comment ce sera",
"Ver la {p0} en {m0}": "Voir la {p0} en {m0}",
"Ver todo el mapa": "Voir toute la carte",
"Ver {p0} en {m0}": "Voir {p0} en {m0}",
"Vive el sur": "Vivez le sud",
"Zona arqueológica (INAH)": "Site archéologique (INAH)",
"Zona arqueológica de El Meco": "Site archéologique d'El Meco",
"Zona arqueológica de El Meco<small>Foto: {x0}, {x1}</small>": "Site archéologique d'El Meco<small>Photo: {x0}, {x1}</small>",
"Zonas arqueológicas, museos y paseos; para empezar, un café o un desayuno.": "Sites archéologiques, musées et balades ; pour commencer, un café ou un petit-déjeuner.",
"de lluvia en un {m0} normal": "de pluie un mois de {m0} normal",
"de máxima, en promedio": "de maximale, en moyenne",
"de probabilidad de tormenta": "de probabilité de tempête",
"llegaron en el Tren Maya en {m0} de {n0}": "sont arrivés en Train maya en {m0} {n0}",
"lugar para dormir": "endroit où dormir",
"lugares para comer": "endroits où manger",
"lugares para dormir": "endroits où dormir",
"no hay estadística oficial de turistas": "il n'y a pas de statistiques officielles de touristes",
"sin tormentas registradas en este mes": "aucune tempête enregistrée ce mois-ci",
"visitantes a sus zonas arqueológicas en {n0}": "visiteurs à ses sites archéologiques en {n0}",
"{m0} de {n0}: mes normal": "{m0} {n0} : mois normal",
"{m0} de {n0}: mes tranquilo": "{m0} {n0} : mois calme",
"{m0} de {n0}: temporada alta": "{m0} {n0} : haute saison",
"{n0} días": "{n0} jours",
"{n0} marisquerías en Calderitas y {n1} visitantes a Oxtankah en {n2}. <small>Fuente: INEGI (DENUE) e INAH</small>": "{n0} restaurants de fruits de mer à Calderitas et {n1} visiteurs à Oxtankah en {n2}. <small>Source : INEGI (DENUE) et INAH</small>",
"{n0} mm": "{n0} mm",
"{n0} museos en {p1} y {p0} según el directorio del INEGI. <small>Fuente: INEGI (DENUE)</small>": "{n0} musées à {p1} et {p0} selon l'annuaire de l'INEGI. <small>Source : INEGI (DENUE)</small>",
"{n0} °C": "{n0} °C",
"{n0}. {p0}: ir a su descripción": "{n0}. {p0} : aller à sa description",
"{p0} en {m0} de {n0}: temporada alta.": "{p0} en {m0} {n0} : haute saison.",
"{p0} · {m0} de {n0}": "{p0} · {m0} {n0}",
"{p0} · {m0} de {n0} <span>Referencia: la campaña no lo promueve</span>": "{p0} · {m0} {n0} <span>Référence : la campagne ne le promeut pas</span>",
"· {m0} de {n0} (estimado): tranquilo": "· {m0} {n0} (estimé) : calme",
"¿Cuándo conviene ir?": "Quand vaut-il mieux y aller ?",
"¿Cuánto cuesta ir?": "Combien ça coûte ?",
"¿Cómo llego al sur?": "Comment aller dans le sud ?",
"¿Cómo lo sabemos?": "Comment le savons-nous ?",
"¿De dónde salen los datos?": "D'où viennent les données ?",
"¿Dónde se queda el dinero?": "Où reste l'argent ?",
"¿Hay espacio en {p0}?": "Y a-t-il de la place à {p0} ?",
"¿Hay sargazo en el sur?": "Y a-t-il des sargasses dans le sud ?",
"¿Ibas al norte?": "Vous alliez au nord ?",
"¿Por qué no {p0} o Tulum?": "Pourquoi pas {p0} ou Tulum ?",
"¿Quién hizo esto?": "Qui a fait cela ?",
"¿Qué hay en {p0}?": "Qu'y a-t-il à {p0} ?",
"¿Qué lugares promueve la campaña?": "Quels lieux la campagne promeut-elle ?",
"Modo día": "Mode jour"
},
"lugares": {
"Ruta de las pirámides": "Route des pyramides",
"Calderitas y Oxtankah": "Calderitas et Oxtankah",
"Laguna Milagros y Xul-Ha": "Lagune Milagros et Xul-Ha"
}
};
