/* Traducción al idioma «ja» de la parte del viajero. Generado por backend/torre/campana/idiomas.py desde docs/idiomas/ja.tsv: no editar a mano. */
window.IDIOMAS_TRAD = window.IDIOMAS_TRAD || {};
window.IDIOMAS_TRAD["ja"] = {
"frases": {
"<b>Temporada alta.</b> El sur también está lleno ese mes.": "<b>ハイシーズン。</b>その月は南部も混み合います。",
"<b>Temporada alta.</b> {p0} está más tranquilo ese mes.": "<b>ハイシーズン。</b>その月は{p0}の方が落ち着いています。",
"<b>Temporada alta</b> quiere decir que ese mes llega {n0} % o más gente que en un mes promedio del año, o que hay {n1} % o más de probabilidad de rebasar el mes más lleno que el lugar ha tenido. Se calcula con los visitantes del INAH a las zonas arqueológicas y, en {p0}, con los cruces desde Belice.": "<b>ハイシーズン</b>とは、その月の来訪者が年間の平均的な月より {n0} % 以上多いこと、またはその場所の過去最多の月を上回る確率が {n1} % 以上あることを意味します。INAH の遺跡来訪者数と、{p0}ではベリーズからの越境者数をもとに計算しています。",
"<b>{p0} en {m0} de {n0}: temporada alta.</b> El sur también está lleno ese mes.": "<b>{p0}・{n0}年{m0}：ハイシーズン。</b>その月は南部も混み合います。",
"<b>{p0} en {m0} de {n0}: temporada alta.</b> {p1} está más tranquilo ese mes.": "<b>{p0}・{n0}年{m0}：ハイシーズン。</b>その月は{p1}の方が落ち着いています。",
"<b>{p1} en {m0} de {n0}: temporada alta.</b> {p0} está más tranquilo ese mes.": "<b>{p1}・{n0}年{m0}：ハイシーズン。</b>その月は{p0}の方が落ち着いています。",
"<b>{p1} y {p0}</b> están como referencia, para quien pensaba ir al norte; la campaña no los promueve. Ahí se mide la ocupación de los hoteles: es temporada alta si se espera {n0} % de cuartos ocupados o más, el nivel que el Radar ya cuenta como \"concurrido\". Si el mes está lleno, te recomendamos un lugar del sur. Tómalo con cuidado en la {p0}: su ocupación bajó ({n1} % en {m0} de {n2} contra {n3} % un año antes), el pronóstico supone que sigue así y se equivoca más que solo repetir lo del año anterior; se usa porque es el único cuyo rango sí atrapó el valor real {n4} de cada {n5} veces.": "<b>{p1}と{p0}</b>は、北部へ行くつもりだった方のための参考として表示しています。このキャンペーンではこれらを宣伝していません。ここではホテルの稼働率を測っています。客室の {n0} % 以上が埋まる見込みならハイシーズンで、これはレーダーがすでに「混雑」とみなす水準です。その月が満杯なら、南部の場所をおすすめします。{p0}は慎重に見てください。稼働率が下がっており（{n2}年{m0}は {n1} %、1年前は {n3} %）、予測はこの状態が続くと想定していて、前年をそのまま繰り返すよりも誤差が大きくなります。それでも使うのは、範囲が実際の値を {n5} 回中 {n4} 回きちんと捉えた唯一の予測だからです。",
"<span></span><b>Radar, {m0} de {n0}:</b> {n1} de los {n2} lugares del sur, tranquilos<span> · {p0}, sin dato oficial</span><span> · Ver el Radar →</span>": "<span></span><b>レーダー、{n0}年{m0}：</b>南部 {n2} か所中 {n1} か所が落ち着いています<span> · {p0}、公式データなし</span><span> · レーダーを見る →</span>",
"<span></span>Calderitas: mariscos y la zona de Oxtankah<small>{n0} km →</small>": "<span></span>カルデリタス：シーフードとオシュタンカ遺跡<small>{n0} km →</small>",
"<span></span>Felipe Carrillo Puerto (estación del Tren Maya)<small>{n0} km →</small>": "<span></span>フェリペ・カリージョ・プエルト（マヤ・トレイン駅）<small>{n0} km →</small>",
"<span></span>Kantemó: la cueva": "<span></span>カンテモ：洞窟",
"<span></span>Kohunlich y Dzibanché, en la selva": "<span></span>コフンリッチとジバンチェ、ジャングルの中",
"<span></span>Kohunlich, Dzibanché e Ichkabal": "<span></span>コフンリッチ、ジバンチェ、イチカバル",
"<span></span>Laguna Milagros y el cenote de Xul-Ha<small>{n0} km →</small>": "<span></span>ミラグロス湖とシュルハのセノーテ<small>{n0} km →</small>",
"<span></span>Señor: ecoturismo comunitario<small>{n0} km →</small>": "<span></span>セニョール：地域主体のエコツーリズム<small>{n0} km →</small>",
"<span></span>Tihosuco: el Museo de la Guerra de Castas<small>{n0} km →</small>": "<span></span>ティオスコ：カスタ戦争博物館<small>{n0} km →</small>",
"<span></span>Tranquilo <span></span>Normal <span></span>Temporada alta": "<span></span>落ち着いている <span></span>普通 <span></span>ハイシーズン",
"<span></span>{p0}: el malecón y el Museo de la Cultura Maya<small>{n0} km →</small>": "<span></span>{p0}：海沿いの遊歩道とマヤ文化博物館<small>{n0} km →</small>",
"<span></span>{p0}: la bahía al atardecer<small>{n0} km →</small>": "<span></span>{p0}：夕暮れの湾<small>{n0} km →</small>",
"<span>★ </span>Reseñas<span> ↗</span><span> en Google Maps (otra pestaña)</span>": "<span>★ </span>口コミ<span> ↗</span><span>（Google マップ・新しいタブ）</span>",
"Agencia de viajes y tours · en el centro": "旅行代理店・ツアー · 中心部",
"Agencia de viajes y tours · en {p0}, a {n0} km": "旅行代理店・ツアー · {p0}、{n0} km 先",
"Antojitos y tacos para cenar, un bar para cerrar el día y dónde dormir.": "夕食はメキシコの軽食とタコス、一日の締めにバー、そして泊まる場所。",
"Antojitos · a {n0} km del centro": "メキシコの軽食 · 中心部から {n0} km",
"Antojitos · en el centro": "メキシコの軽食 · 中心部",
"Asados y pollos · a {n0} km del centro": "グリル料理・チキン · 中心部から {n0} km",
"Asados y pollos · en el centro": "グリル料理・チキン · 中心部",
"Así se ve la {p0}": "{p0}の風景",
"Así se ve {p0}": "{p0}の風景",
"Así va a <em>estar</em>.": "こんな<em>感じ</em>になります。",
"Atardecer en el malecón": "海沿いの遊歩道の夕日",
"Atardecer en una calle de Calderitas": "カルデリタスの通りの夕日",
"Atardecer en una calle de Calderitas<small>Foto: {x0}, {x1}</small>": "カルデリタスの通りの夕日<small>写真: {x0}, {x1}</small>",
"Atardecer sobre la laguna de {p0}": "{p0}のラグーンに沈む夕日",
"Atardecer sobre la laguna de {p0}<small>Foto: {x0}, {x1}</small>": "{p0}のラグーンに沈む夕日<small>写真: {x0}, {x1}</small>",
"Avenida Constituyentes, en Felipe Carrillo Puerto": "フェリペ・カリージョ・プエルトのコンスティトゥジェンテス通り",
"Aves en un muelle de la Laguna Milagros": "ミラグロス湖の桟橋の鳥たち",
"Bahía y pirámides": "湾とピラミッド",
"Balneario · a {n0} km del centro": "水浴び場 · 中心部から {n0} km",
"Balneario · en Calderitas, a {n0} km": "水浴び場 · カルデリタス、{n0} km 先",
"Balneario · en el centro": "水浴び場 · 中心部",
"Balneario · en {p0}, a {n0} km": "水浴び場 · {p0}、{n0} km 先",
"Bar o cantina · a {n0} km del centro": "バー・カンティーナ · 中心部から {n0} km",
"Bar o cantina · en el centro": "バー・カンティーナ · 中心部",
"Bar o cantina · en {p0}, a {n0} km": "バー・カンティーナ · {p0}、{n0} km 先",
"Cabañas y villas · a {n0} km del centro": "コテージ・ヴィラ · 中心部から {n0} km",
"Cabañas y villas · en el centro": "コテージ・ヴィラ · 中心部",
"Café, desayunos y postres · a {n0} km del centro": "カフェ・朝食・デザート · 中心部から {n0} km",
"Café, desayunos y postres · en el centro": "カフェ・朝食・デザート · 中心部",
"Café, desayunos y postres · en {p0}, a {n0} km": "カフェ・朝食・デザート · {p0}、{n0} km 先",
"Cambiar a {p0} en {m0}": "{m0}の{p0}に切り替える",
"Campamento · en Calderitas, a {n0} km": "キャンプ場 · カルデリタス、{n0} km 先",
"Campamento · en el centro": "キャンプ場 · 中心部",
"Casa de huéspedes · a {n0} km del centro": "ゲストハウス · 中心部から {n0} km",
"Casas típicas de madera en el Boulevard Bahía": "バイア大通りの伝統的な木造家屋",
"Casas típicas de madera en el Boulevard Bahía<small>Foto: {x0}, {x1}</small>": "バイア大通りの伝統的な木造家屋<small>写真: {x0}, {x1}</small>",
"Centro nocturno · a {n0} km del centro": "ナイトクラブ · 中心部から {n0} km",
"Centro nocturno · en el centro": "ナイトクラブ · 中心部",
"Centro nocturno · en {p0}, a {n0} km": "ナイトクラブ · {p0}、{n0} km 先",
"Cerrar aviso": "お知らせを閉じる",
"Cerrar preguntas": "質問を閉じる",
"Cinco lugares": "5つの場所",
"Cinco lugares del sur de Quintana Roo: {p4}, {p1}, {p2}, {p3} y {p0}.": "キンタナ・ロー州南部の5つの場所：{p4}、{p1}、{p2}、{p3}、{p0}。",
"Cocina internacional · en el centro": "各国料理 · 中心部",
"Cocina yucateca · en el centro": "ユカタン料理 · 中心部",
"Comida casera · a {n0} km del centro": "家庭料理 · 中心部から {n0} km",
"Comida casera · en el centro": "家庭料理 · 中心部",
"Comida para llevar · a {n0} km del centro": "テイクアウト · 中心部から {n0} km",
"Comida para llevar · en el centro": "テイクアウト · 中心部",
"Comida rápida · a {n0} km del centro": "ファストフード · 中心部から {n0} km",
"Comida rápida · en el centro": "ファストフード · 中心部",
"Comparte con {p0} la vigilancia del sargazo en la bahía.": "湾内のサルガッサム監視を{p0}と共有しています。",
"Con datos oficiales": "公式データで",
"Cuatro están en el mismo municipio que {p0}.": "4か所は{p0}と同じ市にあります。",
"Cómo llega la gente": "人々の訪れ方",
"Cómo llegar<span> ↗</span><span> (Google Maps, otra pestaña)</span>": "行き方<span> ↗</span><span>（Google マップ・新しいタブ）</span>",
"De día": "昼",
"De fuentes oficiales y abiertas: Secretaría de Turismo, gobierno de Quintana Roo, INEGI, INAH, NOAA, Open-Meteo y la Reserva Federal. Las fotos, de Wikimedia Commons con licencia libre.": "公式・オープンな情報源から：観光省、キンタナ・ロー州政府、INEGI、INAH、NOAA、Open-Meteo、米連邦準備制度。写真は Wikimedia Commons の自由ライセンスのものです。",
"De noche": "夜",
"Del Museo de la Cultura Maya en {p0} al de la Guerra de Castas en Tihosuco: la historia del sur contada desde aquí.": "{p0}のマヤ文化博物館からティオスコのカスタ戦争博物館まで：南部の歴史を、この地から伝えます。",
"Del mar a la selva, en un <em>solo</em> viaje.": "海からジャングルまで、<em>一度</em>の旅で。",
"Depende del lugar: arriba, en \"Planea tu viaje\", eliges lugar y mes y te decimos cómo va a estar. Por ejemplo, a la {p0} llega {n0} % menos gente que en un mes promedio en {m0}, y {n1} % más en {m1}.": "場所によります。上の「旅の計画」で場所と月を選ぶと、どんな様子かお知らせします。たとえば{p0}は、{m0}には平均的な月より {n0} % 人が少なく、{m1}には {n1} % 多くなります。",
"Distancias en línea recta entre los centros de cada lugar (no hay datos abiertos de distancias por carretera). Sin precios: ninguna fuente oficial los publica. Las reseñas se leen en Google Maps.": "距離は各場所の中心どうしの直線距離です（道路距離のオープンデータはありません）。料金は表示しません：公式な情報源が公表していないためです。口コミは Google マップでご覧ください。",
"Documento": "資料",
"Dzibanché: el Templo del Búho": "ジバンチェ：フクロウの神殿",
"Dzibanché: el Templo del Búho, {p0}": "ジバンチェ：フクロウの神殿, {p0}",
"Dzibanché: el Templo del Búho. Foto: {x0}, {x1}, vía Wikimedia Commons.": "ジバンチェ：フクロウの神殿. 写真: {x0}, {x1}, 出典 Wikimedia Commons.",
"Dzibanché: el Templo del Búho<small>Foto: {x0}, {x1}</small>": "ジバンチェ：フクロウの神殿<small>写真: {x0}, {x1}</small>",
"Dzibanché: la Estructura {n0}": "ジバンチェ：建造物 {n0}",
"Dzibanché: la Estructura {n0}<small>Foto: {x0}, {x1}</small>": "ジバンチェ：建造物 {n0}<small>写真: {x0}, {x1}</small>",
"Dónde comer": "食事",
"Dónde dormir": "宿泊",
"El Boulevard Bahía de {p0}: casas de madera, monumentos y el sol bajando sobre el agua.": "{p0}のバイア大通り：木造の家、記念碑、そして水面に沈む夕日。",
"El Mercado {n0} en el centro de {p0}": "{p0}中心部の第 {n0} 市場",
"El Mercado {n0} en el centro de {p0}<small>Foto: {x0}, {x1}</small>": "{p0}中心部の第 {n0} 市場<small>写真: {x0}, {x1}</small>",
"El Monumento a la Bandera frente a la bahía": "湾に面した国旗記念碑",
"El Monumento a la Bandera frente a la bahía<small>Foto: {x0}, {x1}</small>": "湾に面した国旗記念碑<small>写真: {x0}, {x1}</small>",
"El Monumento al Pescador al atardecer, en la bahía": "夕暮れの湾に立つ漁師の記念碑",
"El Monumento al Pescador al atardecer, en la bahía, {p0}": "夕暮れの湾に立つ漁師の記念碑, {p0}",
"El Monumento al Pescador al atardecer, en la bahía. Foto: {x0}, {x1}, vía Wikimedia Commons.": "夕暮れの湾に立つ漁師の記念碑. 写真: {x0}, {x1}, 出典 Wikimedia Commons.",
"El Monumento al Pescador al atardecer, en la bahía<small>Foto: {x0}, {x1}</small>": "夕暮れの湾に立つ漁師の記念碑<small>写真: {x0}, {x1}</small>",
"El Portal Maya del parque Fundadores": "フンダドレス公園のマヤのポータル",
"El Portal Maya del parque Fundadores<small>Foto: {x0}, {x1}</small>": "フンダドレス公園のマヤのポータル<small>写真: {x0}, {x1}</small>",
"El Radar": "レーダー",
"El agua turquesa de la Laguna Milagros": "ミラグロス湖のターコイズ色の水",
"El cenote de Xul-Ha": "シュルハのセノーテ",
"El clima es el normal de {n0} a {n1}. El riesgo de tormenta cuenta las tormentas que pasaron a {n2} km o menos del lugar desde {n3} ({n4} en el caso de {p1}). {p0} y la Laguna Milagros no tienen estadística oficial de visitantes, así que no están en el planeador; los encuentras en \"Los lugares\".": "気候は {n0}〜{n1} 年の平年値です。嵐のリスクは、{n3} 年以降にその場所から {n2} km 以内を通過した嵐を数えたものです（{p1}では {n4} 回）。{p0}とミラグロス湖には公式の来訪者統計がないため、プランナーには含まれていません。「場所」でご覧いただけます。",
"El dato": "注目の数字",
"El dinero": "お金",
"El kiosco del centro de {p0}": "{p0}中心部のキオスク",
"El kiosco del centro de {p0}<small>Foto: {x0}, {x1}</small>": "{p0}中心部のキオスク<small>写真: {x0}, {x1}</small>",
"El norte": "北部",
"El parque y los restaurantes de Calderitas al atardecer": "夕暮れのカルデリタスの公園とレストラン",
"El parque y los restaurantes de Calderitas al atardecer<small>Foto: {x0}, {x1}</small>": "夕暮れのカルデリタスの公園とレストラン<small>写真: {x0}, {x1}</small>",
"El problema": "課題",
"El sur": "南部",
"El sur tiene <em>espacio</em>.": "南部には<em>余裕</em>があります。",
"El sur tiene <em>espacio</em>.<br>Y te está esperando.": "南部には<em>余裕</em>があります。<br>あなたを待っています。",
"Elige a dónde y cuándo. Te decimos cómo va a estar.": "行き先と時期を選んでください。どんな様子かお知らせします。",
"En Calderitas, a {n0} km de {p0}, se come viendo el agua; al lado está Oxtankah, la ciudad maya de la bahía.": "{p0}から {n0} km のカルデリタスでは、水辺を眺めながら食事ができます。すぐ隣には湾のマヤ都市オシュタンカがあります。",
"En Felipe Carrillo Puerto, Señor y Tihosuco las comunidades mayas reciben a quien llega: selva, historia y su forma de vivir.": "フェリペ・カリージョ・プエルト、セニョール、ティオスコでは、マヤの共同体が訪れる人を迎えます：ジャングル、歴史、そして彼らの暮らし方。",
"En la costa de {p1} y Calderitas no hay reporte de sargazo. Sí apareció en los canales de entrada de la bahía ({m0} de {n0}), así que se vigila. La ruta de las pirámides, {p0} y la laguna están lejos del mar abierto.": "{p1}とカルデリタスの海岸ではサルガッサムの報告はありません。湾へ続く水路では確認されたため（{n0}年{m0}）、監視が続いています。ピラミッドの道、{p0}、ラグーンは外海から遠く離れています。",
"En los municipios de los cinco lugares no hay ningún hospedaje grande: {n0} son chicos (hasta {n1} personas) y {n2} medianos. La derrama económica por destino no se muestra porque la fuente no dice en qué unidad está.": "5つの場所がある市には大規模な宿泊施設はありません：{n0} 軒が小規模（{n1} 人まで）、{n2} 軒が中規模です。目的地別の観光消費額は、情報源が単位を示していないため表示していません。",
"En {m0} el sur también tiene temporada alta. Si puedes mover tu viaje, busca los meses en verde.": "{m0}は南部もハイシーズンです。旅程をずらせるなら、緑色の月を探してください。",
"En {m0}, <b>{p0}</b> no está en temporada alta: hay espacio, sin el gentío del norte.": "{m0}の<b>{p0}</b>はハイシーズンではありません：余裕があり、北部のような人混みもありません。",
"En {m0}, <b>{p1}</b> está más tranquilo. O ve a la {p0} en <b>{m1}</b>: menos gente, poca lluvia y fuera de la temporada de tormentas.": "{m0}は<b>{p1}</b>の方が落ち着いています。または<b>{m1}</b>に{p0}へ：人が少なく、雨も少なく、嵐の季節の外です。",
"En {m0}, <b>{p1}</b> está más tranquilo. O ve a {p0} en <b>{m1}</b>: menos gente, poca lluvia y fuera de la temporada de tormentas.": "{m0}は<b>{p1}</b>の方が落ち着いています。または<b>{m1}</b>に{p0}へ：人が少なく、雨も少なく、嵐の季節の外です。",
"En {n0} llegaron {n1} pasajeros en avión a {p1}, y el Tren Maya para en {p1}, Bacalar y Felipe Carrillo Puerto ({p0}). Solo en {m0} de {n2} {n3} personas bajaron del tren en {p1}.": "{n0} 年には {n1} 人の乗客が飛行機で{p1}に到着しました。マヤ・トレインは{p1}、バカラル、フェリペ・カリージョ・プエルト（{p0}）に停車します。{n2}年{m0}だけで、{n3} 人が{p1}で列車を降りました。",
"Enviar pregunta": "質問を送信",
"Escribe tu pregunta": "質問を入力",
"Escribe tu pregunta…": "質問を入力…",
"Ese mes todavía no está en el pronóstico (llega hasta {m0} de {n0}): en un {m1} típico, de {n1} a {n2} los hoteles estuvieron al <b>{n3} %</b>.": "その月はまだ予測に入っていません（予測は {n0}年{m0}まで）：例年の{m1}（{n1}〜{n2} 年）、ホテルの稼働率は <b>{n3} %</b> でした。",
"Ese mes todavía no está en el pronóstico (llega hasta {m0} de {n0}): esto es lo típico de {m1}.": "その月はまだ予測に入っていません（予測は {n0}年{m0}まで）：これは{m1}の例年の様子です。",
"Esta parte está en español: son los datos técnicos del proyecto.": "この部分はスペイン語です：プロジェクトの技術データです。",
"Estructura {n0} de Oxtankah, con pintura original": "オシュタンカの建造物 {n0}、当時の彩色が残る",
"Estructura {n0} de Oxtankah, con pintura original<small>Foto: {x0}, {x1}</small>": "オシュタンカの建造物 {n0}、当時の彩色が残る<small>写真: {x0}, {x1}</small>",
"Fotos de los cinco lugares; se pueden recorrer con las flechas": "5つの場所の写真。矢印キーで見られます",
"Fuente: ECOSUR y notas del {n0} de {m0} de {n1}": "出典：ECOSUR と {n1}年{m0}{n0}日の報道",
"Fuente: Gobierno de Quintana Roo (SITUR-Q)": "出典：キンタナ・ロー州政府（SITUR-Q）",
"Fuente: INAH (BdINAH) y forma del año del proyecto (Fase {n0})": "出典：INAH（BdINAH）とプロジェクトの年間パターン分析（フェーズ {n0}）",
"Fuente: INAH (BdINAH), SITUR-Q (frontera con Belice), SECTUR-DataTur (ocupación hotelera de {p1} y {p0}), NOAA HURDAT2, Open-Meteo (clima {n0}–{n1}) y pronóstico del proyecto (Fase {n2}); negocios: INEGI, DENUE.": "出典：INAH（BdINAH）、SITUR-Q（ベリーズ国境）、SECTUR-DataTur（{p1}と{p0}のホテル稼働率）、NOAA HURDAT2、Open-Meteo（{n0}〜{n1} 年の気候）、プロジェクトの予測（フェーズ {n2}）。店舗：INEGI、DENUE。",
"Fuente: INEGI (DENUE) y SITUR-Q": "出典：INEGI（DENUE）と SITUR-Q",
"Fuente: INEGI y gobierno de Quintana Roo": "出典：INEGI とキンタナ・ロー州政府",
"Fuente: INEGI, Directorio Estadístico Nacional de Unidades Económicas (DENUE). El tipo de lugar y el momento del día los sugiere un clasificador de texto que lee el nombre y el giro oficial de cada negocio (acertó {n0} de {n1} en una revisión al azar). Cuando un lugar no tiene algo cerca, se muestra lo más cercano de los otros lugares del sur. \"Ver en Google Maps\" abre Google Maps en otra pestaña; esta página no descarga nada de Google.": "出典：INEGI、全国経済単位統計名簿（DENUE）。場所の種類と時間帯は、各店舗の名称と公式業種を読み取るテキスト分類器が提案しています（無作為の確認で {n1} 件中 {n0} 件が正解）。近くにない種類の場所は、南部のほかの場所からいちばん近いものを表示しています。「Google マップで見る」は新しいタブで Google マップを開きます。このページは Google から何もダウンロードしません。",
"Fuente: Inventario de fuentes del proyecto": "出典：プロジェクトの情報源一覧",
"Fuente: Secretaría de Turismo y notas verificadas de {n0}": "出典：観光省と {n0} 年の検証済み報道",
"Fuente: Selección de regiones del proyecto": "出典：プロジェクトの地域選定",
"Fuente: Torre del Caribe": "出典：Torre del Caribe",
"Girar el mapa solo": "地図を自動で回転",
"Habrá mucha gente: los hoteles suelen pasar del {n0} % de cuartos ocupados, lo que el Radar ya cuenta como \"concurrido\".": "混雑します：ホテルの稼働率は通常 {n0} % を超え、レーダーではすでに「混雑」とみなす水準です。",
"Habrá mucha gente: se espera que los hoteles pasen del {n0} % de cuartos ocupados, lo que el Radar ya cuenta como \"concurrido\".": "混雑します：ホテルの稼働率は {n0} % を超える見込みで、レーダーではすでに「混雑」とみなす水準です。",
"Hasta {m0} de {n0} hay un pronóstico con su rango: el valor real cayó dentro de ese rango entre {n1} y {n2} de cada {n3} veces cuando se probó con meses que el modelo nunca vio. Después de esa fecha se muestra lo típico de cada mes.": "{n0}年{m0}までは範囲つきの予測があります：モデルが一度も見たことのない月で検証したところ、実際の値は {n3} 回中 {n1}〜{n2} 回その範囲に入りました。それ以降は各月の例年の様子を表示します。",
"Hay espacio: los hoteles suelen quedar debajo del {n0} % de cuartos ocupados, lo que el Radar cuenta como \"concurrido\".": "余裕があります：ホテルの稼働率は通常 {n0} % を下回り、レーダーが「混雑」とみなす水準より低いです。",
"Hay espacio: se espera que los hoteles queden debajo del {n0} % de cuartos ocupados, lo que el Radar cuenta como \"concurrido\".": "余裕があります：ホテルの稼働率は {n0} % を下回る見込みで、レーダーが「混雑」とみなす水準より低いです。",
"Hay lugar: {n0} de cada {n1} cuartos de hotel de {p0} se quedaron vacíos en {n2}. <small>Fuente: Gobierno de Quintana Roo (SITUR-Q)</small>": "空きがあります：{n2} 年、{p0}のホテル客室は {n1} 室中 {n0} 室が空いていました。<small>出典：キンタナ・ロー州政府（SITUR-Q）</small>",
"Hay pocos cuartos de hotel: la campaña pone un límite de visitantes para no rebasar a los pueblos.": "ホテルの客室が少ないため、キャンペーンでは村に負担をかけないよう来訪者数に上限を設けています。",
"Hola. Pregúntame sobre los cinco lugares, cómo llegar o de dónde salen los datos.": "こんにちは。5つの場所のこと、行き方、データの出どころについて質問してください。",
"Hospedaje de la gente de aquí: en los municipios de los cinco lugares hay {n0} hospedajes chicos, {n1} medianos y {n2} grandes. <small>Fuente: INEGI (DENUE)</small>": "地元の人が営む宿：5つの場所がある市には、小規模 {n0} 軒、中規模 {n1} 軒、大規模 {n2} 軒の宿泊施設があります。<small>出典：INEGI（DENUE）</small>",
"Hostal · en el centro": "ホステル · 中心部",
"Hostal · en {p0}, a {n0} km": "ホステル · {p0}、{n0} km 先",
"Hotel · en Xul-ha, a {n0} km": "ホテル · シュルハ、{n0} km 先",
"Hotel · en el centro": "ホテル · 中心部",
"Hotel · en {p0}, a {n0} km": "ホテル · {p0}、{n0} km 先",
"Idioma": "言語",
"Idioma / Language": "言語 / Language",
"Iglesia en Felipe Carrillo Puerto": "フェリペ・カリージョ・プエルトの教会",
"Iglesia en Felipe Carrillo Puerto. Foto: {x0}, {x1}, vía Wikimedia Commons.": "フェリペ・カリージョ・プエルトの教会. 写真: {x0}, {x1}, 出典 Wikimedia Commons.",
"Jardín botánico o zoológico · a {n0} km del centro": "植物園・動物園 · 中心部から {n0} km",
"Jardín botánico o zoológico · en el centro": "植物園・動物園 · 中心部",
"Jardín botánico o zoológico · en {p0}, a {n0} km": "植物園・動物園 · {p0}、{n0} km 先",
"Kohunlich, Dzibanché e Ichkabal: ciudades mayas entre la selva, con sus mascarones y templos.": "コフンリッチ、ジバンチェ、イチカバル：仮面と神殿が残る、ジャングルの中のマヤ都市。",
"Kohunlich, Dzibanché e Ichkabal: tres ciudades mayas en la selva, lejos del mar.": "コフンリッチ、ジバンチェ、イチカバル：海から遠く離れたジャングルの中の3つのマヤ都市。",
"Kohunlich, Dzibanché e Ichkabal: tres ciudades mayas en la selva, lejos del mar. Tiene {n0} lugares para comer y {n1} para dormir. Cuidado: los poblados cercanos casi no tienen hoteles: la visita se hace desde {p0}.": "コフンリッチ、ジバンチェ、イチカバル：海から遠く離れたジャングルの中の3つのマヤ都市。食事できる場所が {n0} か所、泊まれる場所が {n1} か所あります。注意：近くの村にはほとんどホテルがないため、{p0}から訪れます。",
"Kohunlich: detalle de un mascarón": "コフンリッチ：仮面の細部",
"Kohunlich: detalle de un mascarón<small>Foto: {x0}, {x1}</small>": "コフンリッチ：仮面の細部<small>写真: {x0}, {x1}</small>",
"Kohunlich: el juego de pelota": "コフンリッチ：球技場",
"Kohunlich: el juego de pelota<small>Foto: {x0}, {x1}</small>": "コフンリッチ：球技場<small>写真: {x0}, {x1}</small>",
"Kohunlich: los mascarones de estuco": "コフンリッチ：漆喰の仮面",
"Kohunlich: los mascarones de estuco<small>Foto: {x0}, {x1}</small>": "コフンリッチ：漆喰の仮面<small>写真: {x0}, {x1}</small>",
"Kohunlich: una de sus plataformas en la selva": "コフンリッチ：ジャングルの中の基壇のひとつ",
"Kohunlich: una de sus plataformas en la selva<small>Foto: {x0}, {x1}</small>": "コフンリッチ：ジャングルの中の基壇のひとつ<small>写真: {x0}, {x1}</small>",
"La Campana del Bicentenario": "独立200周年の鐘",
"La Campana del Bicentenario<small>Foto: {x0}, {x1}</small>": "独立200周年の鐘<small>写真: {x0}, {x1}</small>",
"La Laguna Milagros y el cenote de Xul-Ha, a {n0} km de {p0}. Es frágil: se nada sin bloqueador y sin dejar nada.": "{p0}から {n0} km のミラグロス湖とシュルハのセノーテ。繊細な場所です：日焼け止めを塗らずに泳ぎ、何も残さないでください。",
"La Quinta Avenida de Playa del Carmen": "プラヤ・デル・カルメンの5番街",
"La Quinta Avenida de Playa del Carmen<small>Foto: {x0}, {x1}</small>": "プラヤ・デル・カルメンの5番街<small>写真: {x0}, {x1}</small>",
"La bahía de {p0} desde el Boulevard": "大通りから見た{p0}の湾",
"La bahía de {p0} desde el Boulevard. Foto: {x0}, {x1}, vía Wikimedia Commons.": "大通りから見た{p0}の湾. 写真: {x0}, {x1}, 出典 Wikimedia Commons.",
"La bahía frente a Calderitas": "カルデリタス沖の湾",
"La bahía frente a Calderitas. Foto: {x0}, {x1}, vía Wikimedia Commons.": "カルデリタス沖の湾. 写真: {x0}, {x1}, 出典 Wikimedia Commons.",
"La bahía vista desde Calderitas": "カルデリタスから見た湾",
"La bahía vista desde Calderitas, {p0}": "カルデリタスから見た湾, {p0}",
"La bahía vista desde Calderitas. Foto: {x0}, {x1}, vía Wikimedia Commons.": "カルデリタスから見た湾. 写真: {x0}, {x1}, 出典 Wikimedia Commons.",
"La bahía vista desde Calderitas<small>Foto: {x0}, {x1}</small>": "カルデリタスから見た湾<small>写真: {x0}, {x1}</small>",
"La capilla antigua dentro de la zona de Oxtankah": "オシュタンカ遺跡内の古い礼拝堂",
"La capilla antigua dentro de la zona de Oxtankah<small>Foto: {x0}, {x1}</small>": "オシュタンカ遺跡内の古い礼拝堂<small>写真: {x0}, {x1}</small>",
"La capilla de Nuestra Señora del Carmen": "カルメンの聖母礼拝堂",
"La capilla de Nuestra Señora del Carmen<small>Foto: {x0}, {x1}</small>": "カルメンの聖母礼拝堂<small>写真: {x0}, {x1}</small>",
"La capital del estado, frente a la bahía, con el Museo de la Cultura Maya.": "湾に面した州都。マヤ文化博物館があります。",
"La capital del estado, frente a la bahía, con el Museo de la Cultura Maya. Tiene {n0} lugares para comer y {n1} para dormir; {n2} personas llegaron en el Tren Maya en {m0} de {n3}. Cuidado: se vigila el sargazo que apareció en los canales de entrada de la bahía ({m1} de {n4}).": "湾に面した州都。マヤ文化博物館があります。食事できる場所が {n0} か所、泊まれる場所が {n1} か所あり、{n3}年{m0}には {n2} 人がマヤ・トレインで到着しました。注意：湾へ続く水路で確認されたサルガッサムを監視しています（{n4}年{m1}）。",
"La gran pirámide de Dzibanché en la selva": "ジャングルの中のジバンチェの大ピラミッド",
"La gran pirámide de Dzibanché en la selva. Foto: {x0}, {x1}, vía Wikimedia Commons.": "ジャングルの中のジバンチェの大ピラミッド. 写真: {x0}, {x1}, 出典 Wikimedia Commons.",
"La laguna Nichupté": "ニチュプテ湖",
"La laguna Nichupté<small>Foto: {x0}, {x1}</small>": "ニチュプテ湖<small>写真: {x0}, {x1}</small>",
"La laguna es frágil: visitas con límite estricto y sin actividades que la dañen.": "ラグーンは繊細です：厳しい人数制限があり、傷つける活動は行いません。",
"La orilla de la laguna en Huay-Pix": "ワイピシュのラグーンのほとり",
"La playa del pueblo, en Playa del Carmen": "プラヤ・デル・カルメンの町のビーチ",
"La playa del pueblo, en Playa del Carmen<small>Foto: {x0}, {x1}</small>": "プラヤ・デル・カルメンの町のビーチ<small>写真: {x0}, {x1}</small>",
"Laguna y selva": "ラグーンとジャングル",
"Las fases": "フェーズ",
"Las fotos son de Wikimedia Commons, con licencia libre, y cada una se tomó dentro del municipio del lugar (su coordenada se comprobó con el mapa oficial).": "写真は Wikimedia Commons の自由ライセンスのもので、どれもその場所の市内で撮影されています（座標を公式地図と照合済み）。",
"Llega más o menos la gente de un mes promedio.": "人の数は平均的な月とほぼ同じです。",
"Llega {n0} % menos gente que en un mes promedio: hay espacio.": "平均的な月より {n0} % 人が少なく、余裕があります。",
"Llega {n0} % más gente que en un mes promedio, y hay {n1} % de probabilidad de rebasar el mes más lleno de su historia.": "平均的な月より {n0} % 人が多く、過去最多の月を上回る確率は {n1} % です。",
"Llega {n0} % más gente que en un mes promedio.": "平均的な月より {n0} % 人が多くなります。",
"Lo que hay <em>detrás</em> del viaje.": "旅の<em>裏側</em>にあるもの。",
"Lo que no te <em>cuentan</em> del Caribe.": "カリブについて誰も<em>教えてくれない</em>こと。",
"Lo que todos <em>preguntan</em>.": "みんなが<em>聞く</em>こと。",
"Los Voladores en el parque Fundadores": "フンダドレス公園のボラドーレス",
"Los Voladores en el parque Fundadores<small>Foto: {x0}, {x1}</small>": "フンダドレス公園のボラドーレス<small>写真: {x0}, {x1}</small>",
"Los datos": "データ",
"Los lugares": "場所",
"Los lugares del sur con estadística están en temporada alta este mes. Mejor ve a la {p0} en <b>{m0}</b>: menos gente, poca lluvia y fuera de la temporada de tormentas.": "統計のある南部の場所は今月すべてハイシーズンです。<b>{m0}</b>に{p0}へ行く方がおすすめです：人が少なく、雨も少なく、嵐の季節の外です。",
"Los lugares del sur con estadística están en temporada alta este mes. Mejor ve a {p0} en <b>{m0}</b>: menos gente, poca lluvia y fuera de la temporada de tormentas.": "統計のある南部の場所は今月すべてハイシーズンです。<b>{m0}</b>に{p0}へ行く方がおすすめです：人が少なく、雨も少なく、嵐の季節の外です。",
"Los poblados cercanos casi no tienen hoteles: la visita se hace desde {p0}.": "近くの村にはほとんどホテルがないため、{p0}から訪れます。",
"Lugar": "場所",
"Lugares reales del directorio de negocios del INEGI, del más cercano al más lejano. No son reseñas ni anuncios pagados y el directorio no publica horarios: confirma antes de ir.": "INEGI の事業所名簿に載っている実在の場所を、近い順に並べています。口コミでも有料広告でもなく、名簿には営業時間が載っていません：お出かけ前にご確認ください。",
"Maqueta del sur de Quintana Roo. Arrastra para girarla.": "キンタナ・ロー州南部の模型。ドラッグして回転できます。",
"Mariposa búho cerca de Chunhuhub": "チュンフフブ近くのフクロウチョウ",
"Mariposa en la selva cerca de Chunhuhub": "チュンフフブ近くのジャングルの蝶",
"Mariscos frente a la bahía": "湾を望むシーフード",
"Mariscos y pescado · a {n0} km del centro": "シーフード・魚料理 · 中心部から {n0} km",
"Mariscos y pescado · en el centro": "シーフード・魚料理 · 中心部",
"Mejor mes: <b>{m0}</b> · el mes más seco y sin tormentas (no hay estadística de visitantes)": "ベストシーズン：<b>{m0}</b> · 最も乾燥し嵐のない月（来訪者統計はありません）",
"Mejor mes: <b>{m0}</b> · menos gente, poca lluvia y sin temporada de tormentas": "ベストシーズン：<b>{m0}</b> · 人が少なく、雨も少なく、嵐の季節ではありません",
"Mejor ve al sur": "南部がおすすめ",
"Menú": "メニュー",
"Mes": "月",
"Mes normal": "普通の月",
"Mes tranquilo": "落ち着いた月",
"Modo noche": "ナイトモード",
"Museo · a {n0} km del centro": "博物館 · 中心部から {n0} km",
"Museo · en el centro": "博物館 · 中心部",
"Museo · en {p0}, a {n0} km": "博物館 · {p0}、{n0} km 先",
"Museos de la cultura maya": "マヤ文化の博物館",
"Nadar en la Laguna Milagros": "ミラグロス湖で泳ぐ",
"No damos precios: ninguna fuente oficial abierta publica tarifas de hotel por lugar, y no las inventamos. Lo que sí sabemos es que en el sur los hoteles son chicos: {n0} cuartos por hotel en {p0} contra {n1} en {p1} ({m0} de {n2}).": "料金は掲載していません：場所ごとのホテル料金を公表している公式のオープンデータはなく、私たちが作り出すこともしません。わかっているのは、南部のホテルは小規模だということです：{p0}では1軒あたり {n0} 室、{p1}では {n1} 室（{n2}年{m0}）。",
"No hay estadística oficial de visitantes: por eso se cuida con un límite estricto de gente. <small>Fuente: Selección de regiones del proyecto</small>": "公式の来訪者統計がないため、厳しい人数制限で守られています。<small>出典：プロジェクトの地域選定</small>",
"Palapas en Huay-Pix, a la orilla de la laguna": "ワイピシュのラグーンのほとりのパラパ",
"Parque · a {n0} km del centro": "公園 · 中心部から {n0} km",
"Parque · en {p0}, a {n0} km": "公園 · {p0}、{n0} km 先",
"Paseo en lancha · en el centro": "ボートツアー · 中心部",
"Paseo en lancha · en {p0}, a {n0} km": "ボートツアー · {p0}、{n0} km 先",
"Pirámide de la Tumba {n0} en Oxtankah": "オシュタンカの墓 {n0} のピラミッド",
"Pirámide de la Tumba {n0} en Oxtankah<small>Foto: {x0}, {x1}</small>": "オシュタンカの墓 {n0} のピラミッド<small>写真: {x0}, {x1}</small>",
"Pirámides en la selva": "ジャングルの中のピラミッド",
"Pizzas y hamburguesas · a {n0} km del centro": "ピザ・ハンバーガー · 中心部から {n0} km",
"Pizzas y hamburguesas · en el centro": "ピザ・ハンバーガー · 中心部",
"Planea tu viaje": "旅の計画",
"Planea tu viaje · el sur de Quintana Roo": "旅の計画 · キンタナ・ロー州南部",
"Playa Gaviota Azul, en la punta de {p0}": "{p0}の先端にあるガビオタ・アスール・ビーチ",
"Playa Gaviota Azul, en la punta de {p0}, {p0}": "{p0}の先端にあるガビオタ・アスール・ビーチ, {p0}",
"Playa Gaviota Azul, en la punta de {p0}. Foto: {x0}, {x1}, vía Wikimedia Commons.": "{p0}の先端にあるガビオタ・アスール・ビーチ. 写真: {x0}, {x1}, 出典 Wikimedia Commons.",
"Playa Gaviota Azul, en la punta de {p0}<small>Foto: {x0}, {x1}</small>": "{p0}の先端にあるガビオタ・アスール・ビーチ<small>写真: {x0}, {x1}</small>",
"Playa de la zona hotelera de {p0}": "{p0}のホテルゾーンのビーチ",
"Playa de la zona hotelera de {p0}<small>Foto: {x0}, {x1}</small>": "{p0}のホテルゾーンのビーチ<small>写真: {x0}, {x1}</small>",
"Playa del Carmen desde el aire": "上空から見たプラヤ・デル・カルメン",
"Playa del Carmen desde el aire, {p0}": "上空から見たプラヤ・デル・カルメン, {p0}",
"Playa del Carmen desde el aire. Foto: {x0}, {x1}, vía Wikimedia Commons.": "上空から見たプラヤ・デル・カルメン. 写真: {x0}, {x1}, 出典 Wikimedia Commons.",
"Playa del Carmen desde el aire<small>Foto: {x0}, {x1}</small>": "上空から見たプラヤ・デル・カルメン<small>写真: {x0}, {x1}</small>",
"Por la tarde": "午後",
"Posada · a {n0} km del centro": "宿 · 中心部から {n0} km",
"Posada · en el centro": "宿 · 中心部",
"Posada · en {p0}, a {n0} km": "宿 · {p0}、{n0} km 先",
"Postales del sur": "南部からの絵はがき",
"Postales del sur · fotos tomadas en cada lugar": "南部からの絵はがき · 各地で撮影した写真",
"Preguntas": "質問",
"Preguntas frecuentes": "よくある質問",
"Preguntas rápidas": "クイック質問",
"Pregúntanos": "質問する",
"Pueblo de pescadores junto a la bahía y la zona arqueológica de Oxtankah, casi siempre sin filas.": "湾沿いの漁村。オシュタンカ遺跡もあり、ほとんど行列がありません。",
"Pueblo de pescadores junto a la bahía y la zona arqueológica de Oxtankah, casi siempre sin filas. Tiene {n0} lugares para comer y {n1} para dormir. Cuidado: comparte con {p0} la vigilancia del sargazo en la bahía.": "湾沿いの漁村。オシュタンカ遺跡もあり、ほとんど行列がありません。食事できる場所が {n0} か所、泊まれる場所が {n1} か所あります。注意：湾内のサルガッサム監視を{p0}と共有しています。",
"Pueblos de {p0}": "{p0}の村々",
"Pueblos mayas con turismo comunitario y la cueva de Kantemó.": "地域主体の観光を行うマヤの村々と、カンテモの洞窟。",
"Pueblos mayas con turismo comunitario y la cueva de Kantemó. Tiene {n0} lugares para comer y {n1} para dormir; {n2} personas llegaron en el Tren Maya en {m0} de {n3}. Cuidado: hay pocos cuartos de hotel: la campaña pone un límite de visitantes para no rebasar a los pueblos.": "地域主体の観光を行うマヤの村々と、カンテモの洞窟。食事できる場所が {n0} か所、泊まれる場所が {n1} か所あり、{n3}年{m0}には {n2} 人がマヤ・トレインで到着しました。注意：ホテルの客室が少ないため、キャンペーンでは村に負担をかけないよう来訪者数に上限を設けています。",
"Qué hacer": "過ごし方",
"Radar, {m0} de {n0}:": "レーダー、{n0}年{m0}：",
"Recreación · a {n0} km del centro": "レジャー · 中心部から {n0} km",
"Recreación · en Xul-ha, a {n0} km": "レジャー · シュルハ、{n0} km 先",
"Recreación · en el centro": "レジャー · 中心部",
"Recreación · en {p0}, a {n0} km": "レジャー · {p0}、{n0} km 先",
"Respondo con los datos del proyecto. Si no lo sé, lo digo.": "プロジェクトのデータでお答えします。わからないときは、そう伝えます。",
"Restaurante Bahía Villamar, en una casa de madera": "木造の家にあるレストラン「バイア・ビジャマル」",
"Restaurante Bahía Villamar, en una casa de madera<small>Foto: {x0}, {x1}</small>": "木造の家にあるレストラン「バイア・ビジャマル」<small>写真: {x0}, {x1}</small>",
"Restaurante a la carta · a {n0} km del centro": "アラカルトレストラン · 中心部から {n0} km",
"Restaurante a la carta · en el centro": "アラカルトレストラン · 中心部",
"Rutas de {n0} y {n1} días": "{n0}日・{n1}日のモデルコース",
"Saltar al contenido": "本文へ移動",
"Se espera alrededor de <b>{n0} %</b> de los cuartos de hotel ocupados, muy probablemente entre {n1} y {n2} %.": "ホテル客室の約 <b>{n0} %</b> が埋まる見込みで、おそらく {n1}〜{n2} % の間です。",
"Se esperan alrededor de <b>{n0}</b> cruces desde Belice, muy probablemente entre {n1} y {n2}.": "ベリーズからの越境は約 <b>{n0}</b> 件の見込みで、おそらく {n1}〜{n2} 件の間です。",
"Se esperan alrededor de <b>{n0}</b> visitantes a Kohunlich, Dzibanché e Ichkabal, muy probablemente entre {n1} y {n2}.": "コフンリッチ、ジバンチェ、イチカバルの来訪者は約 <b>{n0}</b> 人の見込みで、おそらく {n1}〜{n2} 人の間です。",
"Se esperan alrededor de <b>{n0}</b> visitantes a la zona de Oxtankah, muy probablemente entre {n1} y {n2}.": "オシュタンカ遺跡の来訪者は約 <b>{n0}</b> 人の見込みで、おそらく {n1}〜{n2} 人の間です。",
"Se vigila el sargazo que apareció en los canales de entrada de la bahía ({m0} de {n0}).": "湾へ続く水路で確認されたサルガッサムを監視しています（{n0}年{m0}）。",
"Secciones": "セクション",
"Seis experiencias con lugares reales y una cifra oficial cada una. Sin precios: ninguna fuente oficial los publica.": "実在の場所と公式の数字をひとつずつ添えた6つの体験。料金は表示しません：公式な情報源が公表していないためです。",
"Sin dato": "データなし",
"Sin dato oficial": "公式データなし",
"Sí: en {n0} {n1} de cada {n2} cuartos de hotel de {p0} se quedaron vacíos ({n3} de {n4} noches ocupadas).": "はい：{n0} 年、{p0}のホテル客室は {n2} 室中 {n1} 室が空いていました（{n4} 泊中 {n3} 泊が利用）。",
"Tacos y tortas · a {n0} km del centro": "タコス・トルタ · 中心部から {n0} km",
"Tacos y tortas · en el centro": "タコス・トルタ · 中心部",
"Te conviene más": "こちらがおすすめ",
"Temporada alta": "ハイシーズン",
"Temporada alta.": "ハイシーズン。",
"Tienen sargazo y se llenan: en su semana más llena, {p0} tuvo {n0} de cada {n1} cuartos ocupados, y en Tulum se reportaron cierres de negocios en {n2}. La campaña lleva gente a donde sí hay espacio.": "サルガッサムがあり、混み合います：最も混んだ週、{p0}は {n1} 室中 {n0} 室が埋まり、{n2} 年にはトゥルムで店舗の閉店が報じられました。キャンペーンは、本当に余裕のある場所へ人を案内します。",
"Todo lo que viste arriba sale de datos oficiales, modelos y pruebas. Esta parte es para quien quiera revisar cómo lo sabemos.": "ここまでの内容はすべて、公式データ、モデル、テストに基づいています。この部分は、どうやって知ったのかを確かめたい方のためのものです。",
"Tranquilo": "落ち着いている",
"Tu viaje": "あなたの旅",
"Turismo comunitario maya": "マヤの地域主体の観光",
"Un balneario o un parque, y a comer: mariscos, cocina yucateca o comida casera.": "水浴び場か公園へ、そして食事：シーフード、ユカタン料理、家庭料理。",
"Un día en <em>{p0}</em>": "<em>{p0}</em>での一日",
"Un equipo de estudiantes de Ciencias de Datos para Negocios de la Universidad Nacional Rosario Castellanos (UNRC), como proyecto escolar {n0}-{n1}.": "ロサリオ・カステジャノス国立大学（UNRC）のビジネスデータサイエンス専攻の学生チームによる、{n0}-{n1} 学期の授業プロジェクトです。",
"Un matapalo en la selva de Felipe Carrillo Puerto": "フェリペ・カリージョ・プエルトのジャングルの絞め殺しの木",
"Un muelle en la Laguna Milagros": "ミラグロス湖の桟橋",
"Un muelle en la Laguna Milagros. Foto: {x0}, {x1}, vía Wikimedia Commons.": "ミラグロス湖の桟橋. 写真: {x0}, {x1}, 出典 Wikimedia Commons.",
"Una laguna del mismo sistema que Bacalar, con pueblos a la orilla.": "バカラルと同じ水系のラグーンで、ほとりに村があります。",
"Una laguna del mismo sistema que Bacalar, con pueblos a la orilla. Tiene {n0} lugares para comer y {n1} para dormir. Cuidado: la laguna es frágil: visitas con límite estricto y sin actividades que la dañen.": "バカラルと同じ水系のラグーンで、ほとりに村があります。食事できる場所が {n0} か所、泊まれる場所が {n1} か所あります。注意：ラグーンは繊細なため、厳しい人数制限があり、傷つける活動は行いません。",
"Una laguna dulce y un cenote": "淡水のラグーンとセノーテ",
"Unas {n0} personas al día entre las tres zonas en {n1}: tienes la pirámide casi para ti. <small>Fuente: INAH</small>": "{n1} 年、3つの遺跡を合わせて1日およそ {n0} 人：ピラミッドをほぼ独り占めできます。<small>出典：INAH</small>",
"Ver cómo está en {m0}": "{m0}の様子を見る",
"Ver cómo va a estar": "どんな様子か見る",
"Ver la {p0} en {m0}": "{m0}の{p0}を見る",
"Ver todo el mapa": "地図全体を見る",
"Ver {p0} en {m0}": "{m0}の{p0}を見る",
"Vive el sur": "南部を体験",
"Zona arqueológica (INAH)": "遺跡（INAH）",
"Zona arqueológica de El Meco": "エル・メコ遺跡",
"Zona arqueológica de El Meco<small>Foto: {x0}, {x1}</small>": "エル・メコ遺跡<small>写真: {x0}, {x1}</small>",
"Zonas arqueológicas, museos y paseos; para empezar, un café o un desayuno.": "遺跡、博物館、散策。まずはコーヒーか朝食から。",
"de lluvia en un {m0} normal": "平年の{m0}の降水量",
"de máxima, en promedio": "平均最高気温",
"de probabilidad de tormenta": "嵐の確率",
"llegaron en el Tren Maya en {m0} de {n0}": "{n0}年{m0}にマヤ・トレインで到着",
"lugar para dormir": "泊まれる場所",
"lugares para comer": "食事できる場所",
"lugares para dormir": "泊まれる場所",
"no hay estadística oficial de turistas": "公式の観光客統計はありません",
"sin tormentas registradas en este mes": "この月の嵐の記録はありません",
"visitantes a sus zonas arqueológicas en {n0}": "{n0} 年の遺跡来訪者",
"{m0} de {n0}: mes normal": "{n0}年{m0}：普通の月",
"{m0} de {n0}: mes tranquilo": "{n0}年{m0}：落ち着いた月",
"{m0} de {n0}: temporada alta": "{n0}年{m0}：ハイシーズン",
"{n0} días": "{n0}日間",
"{n0} marisquerías en Calderitas y {n1} visitantes a Oxtankah en {n2}. <small>Fuente: INEGI (DENUE) e INAH</small>": "{n2} 年、カルデリタスにはシーフード店が {n0} 軒、オシュタンカの来訪者は {n1} 人。<small>出典：INEGI（DENUE）と INAH</small>",
"{n0} mm": "{n0} mm",
"{n0} museos en {p1} y {p0} según el directorio del INEGI. <small>Fuente: INEGI (DENUE)</small>": "INEGI の名簿によると、{p1}と{p0}に博物館が {n0} 館あります。<small>出典：INEGI（DENUE）</small>",
"{n0} °C": "{n0} °C",
"{n0}. {p0}: ir a su descripción": "{n0}. {p0}：説明へ移動",
"{p0} en {m0} de {n0}: temporada alta.": "{p0}・{n0}年{m0}：ハイシーズン。",
"{p0} · {m0} de {n0}": "{p0} · {n0}年{m0}",
"{p0} · {m0} de {n0} <span>Referencia: la campaña no lo promueve</span>": "{p0} · {n0}年{m0} <span>参考：キャンペーンでは宣伝していません</span>",
"· {m0} de {n0} (estimado): tranquilo": "· {n0}年{m0}（推定）：落ち着いている",
"¿Cuándo conviene ir?": "いつ行くのがいい？",
"¿Cuánto cuesta ir?": "費用はいくら？",
"¿Cómo llego al sur?": "南部への行き方は？",
"¿Cómo lo sabemos?": "どうやって知ったの？",
"¿De dónde salen los datos?": "データはどこから？",
"¿Dónde se queda el dinero?": "お金はどこに残る？",
"¿Hay espacio en {p0}?": "{p0}に余裕はある？",
"¿Hay sargazo en el sur?": "南部にサルガッサムはある？",
"¿Ibas al norte?": "北部へ行くつもりでしたか？",
"¿Por qué no {p0} o Tulum?": "なぜ{p0}やトゥルムではないの？",
"¿Quién hizo esto?": "誰が作ったの？",
"¿Qué hay en {p0}?": "{p0}には何がある？",
"¿Qué lugares promueve la campaña?": "キャンペーンが宣伝している場所は？",
"Modo día": "デイモード"
},
"lugares": {
"Ruta de las pirámides": "ピラミッドの道",
"Calderitas y Oxtankah": "カルデリタスとオシュタンカ",
"Laguna Milagros y Xul-Ha": "ミラグロス湖とシュルハ",
"Chetumal": "チェトゥマル",
"Cancún": "カンクン",
"Riviera Maya": "リビエラ・マヤ",
"Maya Ka'an": "マヤ・カアン"
}
};
