/* Traducción al idioma «ko» de la parte del viajero. Generado por backend/torre/campana/idiomas.py desde docs/idiomas/ko.tsv: no editar a mano. */
window.IDIOMAS_TRAD = window.IDIOMAS_TRAD || {};
window.IDIOMAS_TRAD["ko"] = {
"frases": {
"<b>Temporada alta.</b> El sur también está lleno ese mes.": "<b>성수기.</b> 그달에는 남부도 붐빕니다.",
"<b>Temporada alta.</b> {p0} está más tranquilo ese mes.": "<b>성수기.</b> 그달에는 {p0}이(가) 더 한적합니다.",
"<b>Temporada alta</b> quiere decir que ese mes llega {n0} % o más gente que en un mes promedio del año, o que hay {n1} % o más de probabilidad de rebasar el mes más lleno que el lugar ha tenido. Se calcula con los visitantes del INAH a las zonas arqueológicas y, en {p0}, con los cruces desde Belice.": "<b>성수기</b>란 그달 방문객이 연중 평균적인 달보다 {n0} % 이상 많거나, 그곳의 역대 가장 붐볐던 달을 넘어설 확률이 {n1} % 이상인 경우를 뜻합니다. INAH 유적지 방문객 수와, {p0}의 경우 벨리즈에서 넘어오는 입국자 수로 계산합니다.",
"<b>{p0} en {m0} de {n0}: temporada alta.</b> El sur también está lleno ese mes.": "<b>{p0}, {n0}년 {m0}: 성수기.</b> 그달에는 남부도 붐빕니다.",
"<b>{p0} en {m0} de {n0}: temporada alta.</b> {p1} está más tranquilo ese mes.": "<b>{p0}, {n0}년 {m0}: 성수기.</b> 그달에는 {p1}이(가) 더 한적합니다.",
"<b>{p1} en {m0} de {n0}: temporada alta.</b> {p0} está más tranquilo ese mes.": "<b>{p1}, {n0}년 {m0}: 성수기.</b> 그달에는 {p0}이(가) 더 한적합니다.",
"<b>{p1} y {p0}</b> están como referencia, para quien pensaba ir al norte; la campaña no los promueve. Ahí se mide la ocupación de los hoteles: es temporada alta si se espera {n0} % de cuartos ocupados o más, el nivel que el Radar ya cuenta como \"concurrido\". Si el mes está lleno, te recomendamos un lugar del sur. Tómalo con cuidado en la {p0}: su ocupación bajó ({n1} % en {m0} de {n2} contra {n3} % un año antes), el pronóstico supone que sigue así y se equivoca más que solo repetir lo del año anterior; se usa porque es el único cuyo rango sí atrapó el valor real {n4} de cada {n5} veces.": "<b>{p1}와(과) {p0}</b>은(는) 북부로 가려던 분들을 위한 참고용으로 보여 드립니다. 이 캠페인은 이곳들을 홍보하지 않습니다. 여기서는 호텔 객실 점유율을 측정합니다. 객실의 {n0} % 이상이 찰 것으로 예상되면 성수기이며, 이는 레이더가 이미 '붐빔'으로 보는 수준입니다. 그달이 꽉 찼다면 남부의 장소를 추천해 드립니다. {p0}은(는) 신중하게 보세요. 점유율이 떨어졌고({n2}년 {m0} {n1} %, 1년 전 {n3} %), 예측은 이 상태가 이어진다고 가정하며 작년을 그대로 반복하는 것보다 오차가 큽니다. 그래도 쓰는 이유는 범위가 실제 값을 {n5}번 중 {n4}번 제대로 잡아낸 유일한 예측이기 때문입니다.",
"<span></span><b>Radar, {m0} de {n0}:</b> {n1} de los {n2} lugares del sur, tranquilos<span> · {p0}, sin dato oficial</span><span> · Ver el Radar →</span>": "<span></span><b>레이더, {n0}년 {m0}:</b> 남부 {n2}곳 중 {n1}곳이 한적합니다<span> · {p0}, 공식 데이터 없음</span><span> · 레이더 보기 →</span>",
"<span></span>Calderitas: mariscos y la zona de Oxtankah<small>{n0} km →</small>": "<span></span>칼데리타스: 해산물과 옥스탄카 유적<small>{n0} km →</small>",
"<span></span>Felipe Carrillo Puerto (estación del Tren Maya)<small>{n0} km →</small>": "<span></span>펠리페 카리요 푸에르토(마야 열차 역)<small>{n0} km →</small>",
"<span></span>Kantemó: la cueva": "<span></span>칸테모: 동굴",
"<span></span>Kohunlich y Dzibanché, en la selva": "<span></span>코훈리치와 지반체, 정글 속",
"<span></span>Kohunlich, Dzibanché e Ichkabal": "<span></span>코훈리치, 지반체, 이치카발",
"<span></span>Laguna Milagros y el cenote de Xul-Ha<small>{n0} km →</small>": "<span></span>밀라그로스 석호와 슐하 세노테<small>{n0} km →</small>",
"<span></span>Señor: ecoturismo comunitario<small>{n0} km →</small>": "<span></span>세뇨르: 지역 공동체 생태 관광<small>{n0} km →</small>",
"<span></span>Tihosuco: el Museo de la Guerra de Castas<small>{n0} km →</small>": "<span></span>티오수코: 카스트 전쟁 박물관<small>{n0} km →</small>",
"<span></span>Tranquilo <span></span>Normal <span></span>Temporada alta": "<span></span>한적함 <span></span>보통 <span></span>성수기",
"<span></span>{p0}: el malecón y el Museo de la Cultura Maya<small>{n0} km →</small>": "<span></span>{p0}: 해변 산책로와 마야 문화 박물관<small>{n0} km →</small>",
"<span></span>{p0}: la bahía al atardecer<small>{n0} km →</small>": "<span></span>{p0}: 해 질 녘의 만<small>{n0} km →</small>",
"<span>★ </span>Reseñas<span> ↗</span><span> en Google Maps (otra pestaña)</span>": "<span>★ </span>리뷰<span> ↗</span><span>(Google 지도, 새 탭)</span>",
"Agencia de viajes y tours · en el centro": "여행사·투어 · 중심가",
"Agencia de viajes y tours · en {p0}, a {n0} km": "여행사·투어 · {p0}, {n0} km 거리",
"Antojitos y tacos para cenar, un bar para cerrar el día y dónde dormir.": "저녁으로 멕시코 간식과 타코, 하루를 마무리할 바, 그리고 잘 곳.",
"Antojitos · a {n0} km del centro": "멕시코 간식 · 중심가에서 {n0} km",
"Antojitos · en el centro": "멕시코 간식 · 중심가",
"Asados y pollos · a {n0} km del centro": "구이·치킨 · 중심가에서 {n0} km",
"Asados y pollos · en el centro": "구이·치킨 · 중심가",
"Así se ve la {p0}": "{p0}의 모습",
"Así se ve {p0}": "{p0}의 모습",
"Así va a <em>estar</em>.": "이렇게 <em>될</em> 거예요.",
"Atardecer en el malecón": "해변 산책로의 노을",
"Atardecer en una calle de Calderitas": "칼데리타스 거리의 노을",
"Atardecer en una calle de Calderitas<small>Foto: {x0}, {x1}</small>": "칼데리타스 거리의 노을<small>사진: {x0}, {x1}</small>",
"Atardecer sobre la laguna de {p0}": "{p0} 석호 위의 노을",
"Atardecer sobre la laguna de {p0}<small>Foto: {x0}, {x1}</small>": "{p0} 석호 위의 노을<small>사진: {x0}, {x1}</small>",
"Avenida Constituyentes, en Felipe Carrillo Puerto": "펠리페 카리요 푸에르토의 콘스티투옌테스 거리",
"Aves en un muelle de la Laguna Milagros": "밀라그로스 석호 부두 위의 새들",
"Bahía y pirámides": "만과 피라미드",
"Balneario · a {n0} km del centro": "물놀이 장소 · 중심가에서 {n0} km",
"Balneario · en Calderitas, a {n0} km": "물놀이 장소 · 칼데리타스, {n0} km 거리",
"Balneario · en el centro": "물놀이 장소 · 중심가",
"Balneario · en {p0}, a {n0} km": "물놀이 장소 · {p0}, {n0} km 거리",
"Bar o cantina · a {n0} km del centro": "바·칸티나 · 중심가에서 {n0} km",
"Bar o cantina · en el centro": "바·칸티나 · 중심가",
"Bar o cantina · en {p0}, a {n0} km": "바·칸티나 · {p0}, {n0} km 거리",
"Cabañas y villas · a {n0} km del centro": "오두막·빌라 · 중심가에서 {n0} km",
"Cabañas y villas · en el centro": "오두막·빌라 · 중심가",
"Café, desayunos y postres · a {n0} km del centro": "카페·아침 식사·디저트 · 중심가에서 {n0} km",
"Café, desayunos y postres · en el centro": "카페·아침 식사·디저트 · 중심가",
"Café, desayunos y postres · en {p0}, a {n0} km": "카페·아침 식사·디저트 · {p0}, {n0} km 거리",
"Cambiar a {p0} en {m0}": "{m0}의 {p0}(으)로 바꾸기",
"Campamento · en Calderitas, a {n0} km": "캠핑장 · 칼데리타스, {n0} km 거리",
"Campamento · en el centro": "캠핑장 · 중심가",
"Casa de huéspedes · a {n0} km del centro": "게스트하우스 · 중심가에서 {n0} km",
"Casas típicas de madera en el Boulevard Bahía": "바이아 대로의 전통 목조 주택",
"Casas típicas de madera en el Boulevard Bahía<small>Foto: {x0}, {x1}</small>": "바이아 대로의 전통 목조 주택<small>사진: {x0}, {x1}</small>",
"Centro nocturno · a {n0} km del centro": "나이트클럽 · 중심가에서 {n0} km",
"Centro nocturno · en el centro": "나이트클럽 · 중심가",
"Centro nocturno · en {p0}, a {n0} km": "나이트클럽 · {p0}, {n0} km 거리",
"Cerrar aviso": "알림 닫기",
"Cerrar preguntas": "질문 닫기",
"Cinco lugares": "다섯 곳",
"Cinco lugares del sur de Quintana Roo: {p4}, {p1}, {p2}, {p3} y {p0}.": "킨타나로오주 남부의 다섯 곳: {p4}, {p1}, {p2}, {p3}, {p0}.",
"Cocina internacional · en el centro": "세계 요리 · 중심가",
"Cocina yucateca · en el centro": "유카탄 요리 · 중심가",
"Comida casera · a {n0} km del centro": "가정식 · 중심가에서 {n0} km",
"Comida casera · en el centro": "가정식 · 중심가",
"Comida para llevar · a {n0} km del centro": "포장 음식 · 중심가에서 {n0} km",
"Comida para llevar · en el centro": "포장 음식 · 중심가",
"Comida rápida · a {n0} km del centro": "패스트푸드 · 중심가에서 {n0} km",
"Comida rápida · en el centro": "패스트푸드 · 중심가",
"Comparte con {p0} la vigilancia del sargazo en la bahía.": "{p0}와(과) 함께 만의 사르가숨을 감시합니다.",
"Con datos oficiales": "공식 데이터로",
"Cuatro están en el mismo municipio que {p0}.": "네 곳은 {p0}와(과) 같은 시에 있습니다.",
"Cómo llega la gente": "사람들이 오는 방법",
"Cómo llegar<span> ↗</span><span> (Google Maps, otra pestaña)</span>": "길찾기<span> ↗</span><span>(Google 지도, 새 탭)</span>",
"De día": "낮",
"De fuentes oficiales y abiertas: Secretaría de Turismo, gobierno de Quintana Roo, INEGI, INAH, NOAA, Open-Meteo y la Reserva Federal. Las fotos, de Wikimedia Commons con licencia libre.": "공식·공개 출처: 관광부, 킨타나로오 주정부, INEGI, INAH, NOAA, Open-Meteo, 미국 연방준비제도. 사진은 자유 라이선스의 Wikimedia Commons 자료입니다.",
"De noche": "밤",
"Del Museo de la Cultura Maya en {p0} al de la Guerra de Castas en Tihosuco: la historia del sur contada desde aquí.": "{p0}의 마야 문화 박물관부터 티오수코의 카스트 전쟁 박물관까지: 남부의 역사를 이곳에서 들려줍니다.",
"Del mar a la selva, en un <em>solo</em> viaje.": "바다에서 정글까지, <em>한 번</em>의 여행으로.",
"Depende del lugar: arriba, en \"Planea tu viaje\", eliges lugar y mes y te decimos cómo va a estar. Por ejemplo, a la {p0} llega {n0} % menos gente que en un mes promedio en {m0}, y {n1} % más en {m1}.": "장소에 따라 다릅니다. 위의 '여행 계획'에서 장소와 달을 고르면 어떤지 알려 드립니다. 예를 들어 {p0}은(는) {m0}에 평균적인 달보다 {n0} % 사람이 적고, {m1}에는 {n1} % 많습니다.",
"Distancias en línea recta entre los centros de cada lugar (no hay datos abiertos de distancias por carretera). Sin precios: ninguna fuente oficial los publica. Las reseñas se leen en Google Maps.": "거리는 각 장소 중심 사이의 직선거리입니다(도로 거리 공개 데이터는 없습니다). 가격은 표시하지 않습니다: 공식 출처가 공개하지 않기 때문입니다. 리뷰는 Google 지도에서 보세요.",
"Documento": "자료",
"Dzibanché: el Templo del Búho": "지반체: 올빼미 신전",
"Dzibanché: el Templo del Búho, {p0}": "지반체: 올빼미 신전, {p0}",
"Dzibanché: el Templo del Búho. Foto: {x0}, {x1}, vía Wikimedia Commons.": "지반체: 올빼미 신전. 사진: {x0}, {x1}, 출처 Wikimedia Commons.",
"Dzibanché: el Templo del Búho<small>Foto: {x0}, {x1}</small>": "지반체: 올빼미 신전<small>사진: {x0}, {x1}</small>",
"Dzibanché: la Estructura {n0}": "지반체: {n0}번 구조물",
"Dzibanché: la Estructura {n0}<small>Foto: {x0}, {x1}</small>": "지반체: {n0}번 구조물<small>사진: {x0}, {x1}</small>",
"Dónde comer": "먹을 곳",
"Dónde dormir": "묵을 곳",
"El Boulevard Bahía de {p0}: casas de madera, monumentos y el sol bajando sobre el agua.": "{p0}의 바이아 대로: 목조 주택, 기념비, 그리고 물 위로 지는 해.",
"El Mercado {n0} en el centro de {p0}": "{p0} 중심가의 {n0} 시장",
"El Mercado {n0} en el centro de {p0}<small>Foto: {x0}, {x1}</small>": "{p0} 중심가의 {n0} 시장<small>사진: {x0}, {x1}</small>",
"El Monumento a la Bandera frente a la bahía": "만을 마주한 국기 기념비",
"El Monumento a la Bandera frente a la bahía<small>Foto: {x0}, {x1}</small>": "만을 마주한 국기 기념비<small>사진: {x0}, {x1}</small>",
"El Monumento al Pescador al atardecer, en la bahía": "해 질 녘 만의 어부 기념비",
"El Monumento al Pescador al atardecer, en la bahía, {p0}": "해 질 녘 만의 어부 기념비, {p0}",
"El Monumento al Pescador al atardecer, en la bahía. Foto: {x0}, {x1}, vía Wikimedia Commons.": "해 질 녘 만의 어부 기념비. 사진: {x0}, {x1}, 출처 Wikimedia Commons.",
"El Monumento al Pescador al atardecer, en la bahía<small>Foto: {x0}, {x1}</small>": "해 질 녘 만의 어부 기념비<small>사진: {x0}, {x1}</small>",
"El Portal Maya del parque Fundadores": "푼다도레스 공원의 마야 포털",
"El Portal Maya del parque Fundadores<small>Foto: {x0}, {x1}</small>": "푼다도레스 공원의 마야 포털<small>사진: {x0}, {x1}</small>",
"El Radar": "레이더",
"El agua turquesa de la Laguna Milagros": "밀라그로스 석호의 청록빛 물",
"El cenote de Xul-Ha": "슐하 세노테",
"El clima es el normal de {n0} a {n1}. El riesgo de tormenta cuenta las tormentas que pasaron a {n2} km o menos del lugar desde {n3} ({n4} en el caso de {p1}). {p0} y la Laguna Milagros no tienen estadística oficial de visitantes, así que no están en el planeador; los encuentras en \"Los lugares\".": "기후는 {n0}~{n1}년의 평년값입니다. 폭풍 위험은 {n3}년 이후 그곳에서 {n2} km 이내를 지나간 폭풍을 센 것입니다({p1}은(는) {n4}번). {p0}와(과) 밀라그로스 석호는 공식 방문객 통계가 없어서 플래너에 없습니다. '장소'에서 보실 수 있습니다.",
"El dato": "주목할 숫자",
"El dinero": "돈",
"El kiosco del centro de {p0}": "{p0} 중심가의 키오스크",
"El kiosco del centro de {p0}<small>Foto: {x0}, {x1}</small>": "{p0} 중심가의 키오스크<small>사진: {x0}, {x1}</small>",
"El norte": "북부",
"El parque y los restaurantes de Calderitas al atardecer": "해 질 녘 칼데리타스의 공원과 식당",
"El parque y los restaurantes de Calderitas al atardecer<small>Foto: {x0}, {x1}</small>": "해 질 녘 칼데리타스의 공원과 식당<small>사진: {x0}, {x1}</small>",
"El problema": "문제",
"El sur": "남부",
"El sur tiene <em>espacio</em>.": "남부에는 <em>여유</em>가 있습니다.",
"El sur tiene <em>espacio</em>.<br>Y te está esperando.": "남부에는 <em>여유</em>가 있습니다.<br>당신을 기다리고 있어요.",
"Elige a dónde y cuándo. Te decimos cómo va a estar.": "어디로, 언제 갈지 고르세요. 어떨지 알려 드릴게요.",
"En Calderitas, a {n0} km de {p0}, se come viendo el agua; al lado está Oxtankah, la ciudad maya de la bahía.": "{p0}에서 {n0} km 떨어진 칼데리타스에서는 물을 바라보며 식사합니다. 바로 옆에는 만의 마야 도시 옥스탄카가 있습니다.",
"En Felipe Carrillo Puerto, Señor y Tihosuco las comunidades mayas reciben a quien llega: selva, historia y su forma de vivir.": "펠리페 카리요 푸에르토, 세뇨르, 티오수코에서는 마야 공동체가 방문객을 맞이합니다: 정글, 역사, 그리고 그들의 삶의 방식.",
"En la costa de {p1} y Calderitas no hay reporte de sargazo. Sí apareció en los canales de entrada de la bahía ({m0} de {n0}), así que se vigila. La ruta de las pirámides, {p0} y la laguna están lejos del mar abierto.": "{p1}와(과) 칼데리타스 해안에는 사르가숨 보고가 없습니다. 만으로 들어오는 수로에서는 나타났기 때문에({n0}년 {m0}) 감시하고 있습니다. 피라미드 길, {p0}, 석호는 먼바다에서 멀리 떨어져 있습니다.",
"En los municipios de los cinco lugares no hay ningún hospedaje grande: {n0} son chicos (hasta {n1} personas) y {n2} medianos. La derrama económica por destino no se muestra porque la fuente no dice en qué unidad está.": "다섯 곳이 있는 시에는 대형 숙소가 없습니다: {n0}곳은 소규모({n1}명까지), {n2}곳은 중규모입니다. 목적지별 관광 지출은 출처가 단위를 밝히지 않아 표시하지 않습니다.",
"En {m0} el sur también tiene temporada alta. Si puedes mover tu viaje, busca los meses en verde.": "{m0}에는 남부도 성수기입니다. 일정을 옮길 수 있다면 초록색 달을 찾아보세요.",
"En {m0}, <b>{p0}</b> no está en temporada alta: hay espacio, sin el gentío del norte.": "{m0}의 <b>{p0}</b>은(는) 성수기가 아닙니다: 여유가 있고 북부 같은 인파도 없습니다.",
"En {m0}, <b>{p1}</b> está más tranquilo. O ve a la {p0} en <b>{m1}</b>: menos gente, poca lluvia y fuera de la temporada de tormentas.": "{m0}에는 <b>{p1}</b>이(가) 더 한적합니다. 아니면 <b>{m1}</b>에 {p0}에 가세요: 사람도 비도 적고 폭풍 철도 아닙니다.",
"En {m0}, <b>{p1}</b> está más tranquilo. O ve a {p0} en <b>{m1}</b>: menos gente, poca lluvia y fuera de la temporada de tormentas.": "{m0}에는 <b>{p1}</b>이(가) 더 한적합니다. 아니면 <b>{m1}</b>에 {p0}에 가세요: 사람도 비도 적고 폭풍 철도 아닙니다.",
"En {n0} llegaron {n1} pasajeros en avión a {p1}, y el Tren Maya para en {p1}, Bacalar y Felipe Carrillo Puerto ({p0}). Solo en {m0} de {n2} {n3} personas bajaron del tren en {p1}.": "{n0}년에 {n1}명의 승객이 비행기로 {p1}에 도착했고, 마야 열차는 {p1}, 바칼라르, 펠리페 카리요 푸에르토({p0})에 정차합니다. {n2}년 {m0} 한 달에만 {n3}명이 {p1}에서 열차를 내렸습니다.",
"Enviar pregunta": "질문 보내기",
"Escribe tu pregunta": "질문을 입력하세요",
"Escribe tu pregunta…": "질문을 입력하세요…",
"Ese mes todavía no está en el pronóstico (llega hasta {m0} de {n0}): en un {m1} típico, de {n1} a {n2} los hoteles estuvieron al <b>{n3} %</b>.": "그달은 아직 예측에 없습니다(예측은 {n0}년 {m0}까지): 예년의 {m1}({n1}~{n2}년)에는 호텔 점유율이 <b>{n3} %</b>였습니다.",
"Ese mes todavía no está en el pronóstico (llega hasta {m0} de {n0}): esto es lo típico de {m1}.": "그달은 아직 예측에 없습니다(예측은 {n0}년 {m0}까지): {m1}의 예년 모습입니다.",
"Esta parte está en español: son los datos técnicos del proyecto.": "이 부분은 스페인어로 되어 있습니다: 프로젝트의 기술 데이터입니다.",
"Estructura {n0} de Oxtankah, con pintura original": "원래 채색이 남은 옥스탄카 {n0}번 구조물",
"Estructura {n0} de Oxtankah, con pintura original<small>Foto: {x0}, {x1}</small>": "원래 채색이 남은 옥스탄카 {n0}번 구조물<small>사진: {x0}, {x1}</small>",
"Fotos de los cinco lugares; se pueden recorrer con las flechas": "다섯 곳의 사진. 화살표 키로 넘겨 볼 수 있습니다",
"Fuente: ECOSUR y notas del {n0} de {m0} de {n1}": "출처: ECOSUR와 {n1}년 {m0} {n0}일 보도",
"Fuente: Gobierno de Quintana Roo (SITUR-Q)": "출처: 킨타나로오 주정부(SITUR-Q)",
"Fuente: INAH (BdINAH) y forma del año del proyecto (Fase {n0})": "출처: INAH(BdINAH)와 프로젝트의 연간 패턴 분석({n0}단계)",
"Fuente: INAH (BdINAH), SITUR-Q (frontera con Belice), SECTUR-DataTur (ocupación hotelera de {p1} y {p0}), NOAA HURDAT2, Open-Meteo (clima {n0}–{n1}) y pronóstico del proyecto (Fase {n2}); negocios: INEGI, DENUE.": "출처: INAH(BdINAH), SITUR-Q(벨리즈 국경), SECTUR-DataTur({p1}와(과) {p0}의 호텔 점유율), NOAA HURDAT2, Open-Meteo({n0}–{n1}년 기후), 프로젝트 예측({n2}단계). 업체: INEGI, DENUE.",
"Fuente: INEGI (DENUE) y SITUR-Q": "출처: INEGI(DENUE)와 SITUR-Q",
"Fuente: INEGI y gobierno de Quintana Roo": "출처: INEGI와 킨타나로오 주정부",
"Fuente: INEGI, Directorio Estadístico Nacional de Unidades Económicas (DENUE). El tipo de lugar y el momento del día los sugiere un clasificador de texto que lee el nombre y el giro oficial de cada negocio (acertó {n0} de {n1} en una revisión al azar). Cuando un lugar no tiene algo cerca, se muestra lo más cercano de los otros lugares del sur. \"Ver en Google Maps\" abre Google Maps en otra pestaña; esta página no descarga nada de Google.": "출처: INEGI 전국 경제 단위 통계 명부(DENUE). 장소 유형과 시간대는 각 업체의 이름과 공식 업종을 읽는 텍스트 분류기가 제안합니다(무작위 점검에서 {n1}건 중 {n0}건 정답). 가까이에 없는 유형은 남부의 다른 장소 중 가장 가까운 곳을 보여 줍니다. 'Google 지도에서 보기'는 새 탭에서 Google 지도를 엽니다. 이 페이지는 Google에서 아무것도 내려받지 않습니다.",
"Fuente: Inventario de fuentes del proyecto": "출처: 프로젝트 출처 목록",
"Fuente: Secretaría de Turismo y notas verificadas de {n0}": "출처: 관광부와 {n0}년 검증된 보도",
"Fuente: Selección de regiones del proyecto": "출처: 프로젝트의 지역 선정",
"Fuente: Torre del Caribe": "출처: Torre del Caribe",
"Girar el mapa solo": "지도 자동 회전",
"Habrá mucha gente: los hoteles suelen pasar del {n0} % de cuartos ocupados, lo que el Radar ya cuenta como \"concurrido\".": "붐빌 거예요: 호텔 점유율이 보통 {n0} %를 넘으며, 레이더는 이를 이미 '붐빔'으로 봅니다.",
"Habrá mucha gente: se espera que los hoteles pasen del {n0} % de cuartos ocupados, lo que el Radar ya cuenta como \"concurrido\".": "붐빌 거예요: 호텔 점유율이 {n0} %를 넘을 것으로 예상되며, 레이더는 이를 이미 '붐빔'으로 봅니다.",
"Hasta {m0} de {n0} hay un pronóstico con su rango: el valor real cayó dentro de ese rango entre {n1} y {n2} de cada {n3} veces cuando se probó con meses que el modelo nunca vio. Después de esa fecha se muestra lo típico de cada mes.": "{n0}년 {m0}까지는 범위가 있는 예측이 있습니다: 모델이 한 번도 보지 못한 달로 검증했을 때 실제 값이 {n3}번 중 {n1}~{n2}번 그 범위 안에 들었습니다. 그 이후에는 달마다 예년 모습을 보여 줍니다.",
"Hay espacio: los hoteles suelen quedar debajo del {n0} % de cuartos ocupados, lo que el Radar cuenta como \"concurrido\".": "여유가 있어요: 호텔 점유율이 보통 {n0} % 아래로, 레이더가 '붐빔'으로 보는 수준보다 낮습니다.",
"Hay espacio: se espera que los hoteles queden debajo del {n0} % de cuartos ocupados, lo que el Radar cuenta como \"concurrido\".": "여유가 있어요: 호텔 점유율이 {n0} % 아래일 것으로 예상되며, 레이더가 '붐빔'으로 보는 수준보다 낮습니다.",
"Hay lugar: {n0} de cada {n1} cuartos de hotel de {p0} se quedaron vacíos en {n2}. <small>Fuente: Gobierno de Quintana Roo (SITUR-Q)</small>": "자리가 있어요: {n2}년 {p0}의 호텔 객실 {n1}개 중 {n0}개가 비어 있었습니다. <small>출처: 킨타나로오 주정부(SITUR-Q)</small>",
"Hay pocos cuartos de hotel: la campaña pone un límite de visitantes para no rebasar a los pueblos.": "호텔 객실이 적습니다: 캠페인은 마을에 부담을 주지 않도록 방문객 수에 상한을 둡니다.",
"Hola. Pregúntame sobre los cinco lugares, cómo llegar o de dónde salen los datos.": "안녕하세요. 다섯 곳, 가는 방법, 데이터의 출처에 대해 물어보세요.",
"Hospedaje de la gente de aquí: en los municipios de los cinco lugares hay {n0} hospedajes chicos, {n1} medianos y {n2} grandes. <small>Fuente: INEGI (DENUE)</small>": "이곳 사람들이 운영하는 숙소: 다섯 곳이 있는 시에는 소규모 {n0}곳, 중규모 {n1}곳, 대규모 {n2}곳의 숙소가 있습니다. <small>출처: INEGI(DENUE)</small>",
"Hostal · en el centro": "호스텔 · 중심가",
"Hostal · en {p0}, a {n0} km": "호스텔 · {p0}, {n0} km 거리",
"Hotel · en Xul-ha, a {n0} km": "호텔 · 슐하, {n0} km 거리",
"Hotel · en el centro": "호텔 · 중심가",
"Hotel · en {p0}, a {n0} km": "호텔 · {p0}, {n0} km 거리",
"Idioma": "언어",
"Idioma / Language": "언어 / Language",
"Iglesia en Felipe Carrillo Puerto": "펠리페 카리요 푸에르토의 성당",
"Iglesia en Felipe Carrillo Puerto. Foto: {x0}, {x1}, vía Wikimedia Commons.": "펠리페 카리요 푸에르토의 성당. 사진: {x0}, {x1}, 출처 Wikimedia Commons.",
"Jardín botánico o zoológico · a {n0} km del centro": "식물원·동물원 · 중심가에서 {n0} km",
"Jardín botánico o zoológico · en el centro": "식물원·동물원 · 중심가",
"Jardín botánico o zoológico · en {p0}, a {n0} km": "식물원·동물원 · {p0}, {n0} km 거리",
"Kohunlich, Dzibanché e Ichkabal: ciudades mayas entre la selva, con sus mascarones y templos.": "코훈리치, 지반체, 이치카발: 가면과 신전이 남아 있는 정글 속 마야 도시.",
"Kohunlich, Dzibanché e Ichkabal: tres ciudades mayas en la selva, lejos del mar.": "코훈리치, 지반체, 이치카발: 바다에서 멀리 떨어진 정글 속 세 마야 도시.",
"Kohunlich, Dzibanché e Ichkabal: tres ciudades mayas en la selva, lejos del mar. Tiene {n0} lugares para comer y {n1} para dormir. Cuidado: los poblados cercanos casi no tienen hoteles: la visita se hace desde {p0}.": "코훈리치, 지반체, 이치카발: 바다에서 멀리 떨어진 정글 속 세 마야 도시. 먹을 곳 {n0}곳, 묵을 곳 {n1}곳이 있습니다. 주의: 근처 마을에는 호텔이 거의 없어 {p0}에서 출발해 방문합니다.",
"Kohunlich: detalle de un mascarón": "코훈리치: 가면의 세부",
"Kohunlich: detalle de un mascarón<small>Foto: {x0}, {x1}</small>": "코훈리치: 가면의 세부<small>사진: {x0}, {x1}</small>",
"Kohunlich: el juego de pelota": "코훈리치: 구기장",
"Kohunlich: el juego de pelota<small>Foto: {x0}, {x1}</small>": "코훈리치: 구기장<small>사진: {x0}, {x1}</small>",
"Kohunlich: los mascarones de estuco": "코훈리치: 회반죽 가면",
"Kohunlich: los mascarones de estuco<small>Foto: {x0}, {x1}</small>": "코훈리치: 회반죽 가면<small>사진: {x0}, {x1}</small>",
"Kohunlich: una de sus plataformas en la selva": "코훈리치: 정글 속 기단 중 하나",
"Kohunlich: una de sus plataformas en la selva<small>Foto: {x0}, {x1}</small>": "코훈리치: 정글 속 기단 중 하나<small>사진: {x0}, {x1}</small>",
"La Campana del Bicentenario": "독립 200주년 종",
"La Campana del Bicentenario<small>Foto: {x0}, {x1}</small>": "독립 200주년 종<small>사진: {x0}, {x1}</small>",
"La Laguna Milagros y el cenote de Xul-Ha, a {n0} km de {p0}. Es frágil: se nada sin bloqueador y sin dejar nada.": "{p0}에서 {n0} km 떨어진 밀라그로스 석호와 슐하 세노테. 연약한 곳입니다: 자외선 차단제 없이 수영하고 아무것도 남기지 마세요.",
"La Quinta Avenida de Playa del Carmen": "플라야 델 카르멘의 5번가",
"La Quinta Avenida de Playa del Carmen<small>Foto: {x0}, {x1}</small>": "플라야 델 카르멘의 5번가<small>사진: {x0}, {x1}</small>",
"La bahía de {p0} desde el Boulevard": "대로에서 본 {p0}의 만",
"La bahía de {p0} desde el Boulevard. Foto: {x0}, {x1}, vía Wikimedia Commons.": "대로에서 본 {p0}의 만. 사진: {x0}, {x1}, 출처 Wikimedia Commons.",
"La bahía frente a Calderitas": "칼데리타스 앞바다의 만",
"La bahía frente a Calderitas. Foto: {x0}, {x1}, vía Wikimedia Commons.": "칼데리타스 앞바다의 만. 사진: {x0}, {x1}, 출처 Wikimedia Commons.",
"La bahía vista desde Calderitas": "칼데리타스에서 본 만",
"La bahía vista desde Calderitas, {p0}": "칼데리타스에서 본 만, {p0}",
"La bahía vista desde Calderitas. Foto: {x0}, {x1}, vía Wikimedia Commons.": "칼데리타스에서 본 만. 사진: {x0}, {x1}, 출처 Wikimedia Commons.",
"La bahía vista desde Calderitas<small>Foto: {x0}, {x1}</small>": "칼데리타스에서 본 만<small>사진: {x0}, {x1}</small>",
"La capilla antigua dentro de la zona de Oxtankah": "옥스탄카 유적 안의 오래된 예배당",
"La capilla antigua dentro de la zona de Oxtankah<small>Foto: {x0}, {x1}</small>": "옥스탄카 유적 안의 오래된 예배당<small>사진: {x0}, {x1}</small>",
"La capilla de Nuestra Señora del Carmen": "카르멘 성모 예배당",
"La capilla de Nuestra Señora del Carmen<small>Foto: {x0}, {x1}</small>": "카르멘 성모 예배당<small>사진: {x0}, {x1}</small>",
"La capital del estado, frente a la bahía, con el Museo de la Cultura Maya.": "만을 마주한 주도, 마야 문화 박물관이 있습니다.",
"La capital del estado, frente a la bahía, con el Museo de la Cultura Maya. Tiene {n0} lugares para comer y {n1} para dormir; {n2} personas llegaron en el Tren Maya en {m0} de {n3}. Cuidado: se vigila el sargazo que apareció en los canales de entrada de la bahía ({m1} de {n4}).": "만을 마주한 주도, 마야 문화 박물관이 있습니다. 먹을 곳 {n0}곳, 묵을 곳 {n1}곳이 있고, {n3}년 {m0}에는 {n2}명이 마야 열차로 도착했습니다. 주의: 만으로 들어오는 수로에 나타난 사르가숨을 감시하고 있습니다({n4}년 {m1}).",
"La gran pirámide de Dzibanché en la selva": "정글 속 지반체의 대피라미드",
"La gran pirámide de Dzibanché en la selva. Foto: {x0}, {x1}, vía Wikimedia Commons.": "정글 속 지반체의 대피라미드. 사진: {x0}, {x1}, 출처 Wikimedia Commons.",
"La laguna Nichupté": "니춥테 석호",
"La laguna Nichupté<small>Foto: {x0}, {x1}</small>": "니춥테 석호<small>사진: {x0}, {x1}</small>",
"La laguna es frágil: visitas con límite estricto y sin actividades que la dañen.": "석호는 연약합니다: 엄격한 인원 제한이 있고, 해를 끼치는 활동은 하지 않습니다.",
"La orilla de la laguna en Huay-Pix": "와이피시의 석호 기슭",
"La playa del pueblo, en Playa del Carmen": "플라야 델 카르멘의 마을 해변",
"La playa del pueblo, en Playa del Carmen<small>Foto: {x0}, {x1}</small>": "플라야 델 카르멘의 마을 해변<small>사진: {x0}, {x1}</small>",
"Laguna y selva": "석호와 정글",
"Las fases": "단계",
"Las fotos son de Wikimedia Commons, con licencia libre, y cada una se tomó dentro del municipio del lugar (su coordenada se comprobó con el mapa oficial).": "사진은 자유 라이선스의 Wikimedia Commons 자료이며, 모두 그 장소가 속한 시 안에서 찍었습니다(좌표를 공식 지도와 대조했습니다).",
"Llega más o menos la gente de un mes promedio.": "사람 수가 평균적인 달과 비슷합니다.",
"Llega {n0} % menos gente que en un mes promedio: hay espacio.": "평균적인 달보다 사람이 {n0} % 적어 여유가 있습니다.",
"Llega {n0} % más gente que en un mes promedio, y hay {n1} % de probabilidad de rebasar el mes más lleno de su historia.": "평균적인 달보다 사람이 {n0} % 많고, 역대 가장 붐볐던 달을 넘어설 확률이 {n1} %입니다.",
"Llega {n0} % más gente que en un mes promedio.": "평균적인 달보다 사람이 {n0} % 많습니다.",
"Lo que hay <em>detrás</em> del viaje.": "여행 <em>뒤</em>에 있는 것.",
"Lo que no te <em>cuentan</em> del Caribe.": "카리브해에 대해 아무도 <em>말해 주지</em> 않는 것.",
"Lo que todos <em>preguntan</em>.": "모두가 <em>묻는</em> 것.",
"Los Voladores en el parque Fundadores": "푼다도레스 공원의 볼라도레스",
"Los Voladores en el parque Fundadores<small>Foto: {x0}, {x1}</small>": "푼다도레스 공원의 볼라도레스<small>사진: {x0}, {x1}</small>",
"Los datos": "데이터",
"Los lugares": "장소",
"Los lugares del sur con estadística están en temporada alta este mes. Mejor ve a la {p0} en <b>{m0}</b>: menos gente, poca lluvia y fuera de la temporada de tormentas.": "통계가 있는 남부의 장소는 이번 달 모두 성수기입니다. <b>{m0}</b>에 {p0}에 가는 편이 좋습니다: 사람도 비도 적고 폭풍 철도 아닙니다.",
"Los lugares del sur con estadística están en temporada alta este mes. Mejor ve a {p0} en <b>{m0}</b>: menos gente, poca lluvia y fuera de la temporada de tormentas.": "통계가 있는 남부의 장소는 이번 달 모두 성수기입니다. <b>{m0}</b>에 {p0}에 가는 편이 좋습니다: 사람도 비도 적고 폭풍 철도 아닙니다.",
"Los poblados cercanos casi no tienen hoteles: la visita se hace desde {p0}.": "근처 마을에는 호텔이 거의 없어 {p0}에서 출발해 방문합니다.",
"Lugar": "장소",
"Lugares reales del directorio de negocios del INEGI, del más cercano al más lejano. No son reseñas ni anuncios pagados y el directorio no publica horarios: confirma antes de ir.": "INEGI 사업체 명부에 있는 실제 장소를 가까운 순서로 보여 줍니다. 리뷰나 유료 광고가 아니며, 명부에는 영업시간이 없으니 가기 전에 확인하세요.",
"Maqueta del sur de Quintana Roo. Arrastra para girarla.": "킨타나로오주 남부 모형. 드래그해서 돌려 보세요.",
"Mariposa búho cerca de Chunhuhub": "춘우훕 근처의 올빼미나비",
"Mariposa en la selva cerca de Chunhuhub": "춘우훕 근처 정글의 나비",
"Mariscos frente a la bahía": "만을 바라보는 해산물",
"Mariscos y pescado · a {n0} km del centro": "해산물·생선 · 중심가에서 {n0} km",
"Mariscos y pescado · en el centro": "해산물·생선 · 중심가",
"Mejor mes: <b>{m0}</b> · el mes más seco y sin tormentas (no hay estadística de visitantes)": "가장 좋은 달: <b>{m0}</b> · 가장 건조하고 폭풍이 없는 달(방문객 통계 없음)",
"Mejor mes: <b>{m0}</b> · menos gente, poca lluvia y sin temporada de tormentas": "가장 좋은 달: <b>{m0}</b> · 사람도 비도 적고 폭풍 철이 아닙니다",
"Mejor ve al sur": "남부로 가세요",
"Menú": "메뉴",
"Mes": "달",
"Mes normal": "보통인 달",
"Mes tranquilo": "한적한 달",
"Modo noche": "야간 모드",
"Museo · a {n0} km del centro": "박물관 · 중심가에서 {n0} km",
"Museo · en el centro": "박물관 · 중심가",
"Museo · en {p0}, a {n0} km": "박물관 · {p0}, {n0} km 거리",
"Museos de la cultura maya": "마야 문화 박물관들",
"Nadar en la Laguna Milagros": "밀라그로스 석호에서 수영하기",
"No damos precios: ninguna fuente oficial abierta publica tarifas de hotel por lugar, y no las inventamos. Lo que sí sabemos es que en el sur los hoteles son chicos: {n0} cuartos por hotel en {p0} contra {n1} en {p1} ({m0} de {n2}).": "가격은 안내하지 않습니다: 장소별 호텔 요금을 공개하는 공식 공개 출처가 없고, 저희도 지어내지 않습니다. 저희가 아는 것은 남부의 호텔이 작다는 점입니다: {p0}은(는) 호텔당 객실 {n0}개, {p1}은(는) {n1}개({n2}년 {m0}).",
"No hay estadística oficial de visitantes: por eso se cuida con un límite estricto de gente. <small>Fuente: Selección de regiones del proyecto</small>": "공식 방문객 통계가 없어 엄격한 인원 제한으로 보호합니다. <small>출처: 프로젝트의 지역 선정</small>",
"Palapas en Huay-Pix, a la orilla de la laguna": "석호 기슭 와이피시의 팔라파",
"Parque · a {n0} km del centro": "공원 · 중심가에서 {n0} km",
"Parque · en {p0}, a {n0} km": "공원 · {p0}, {n0} km 거리",
"Paseo en lancha · en el centro": "보트 투어 · 중심가",
"Paseo en lancha · en {p0}, a {n0} km": "보트 투어 · {p0}, {n0} km 거리",
"Pirámide de la Tumba {n0} en Oxtankah": "옥스탄카의 {n0}번 무덤 피라미드",
"Pirámide de la Tumba {n0} en Oxtankah<small>Foto: {x0}, {x1}</small>": "옥스탄카의 {n0}번 무덤 피라미드<small>사진: {x0}, {x1}</small>",
"Pirámides en la selva": "정글 속 피라미드",
"Pizzas y hamburguesas · a {n0} km del centro": "피자·햄버거 · 중심가에서 {n0} km",
"Pizzas y hamburguesas · en el centro": "피자·햄버거 · 중심가",
"Planea tu viaje": "여행 계획",
"Planea tu viaje · el sur de Quintana Roo": "여행 계획 · 킨타나로오주 남부",
"Playa Gaviota Azul, en la punta de {p0}": "{p0} 끝자락의 가비오타 아술 해변",
"Playa Gaviota Azul, en la punta de {p0}, {p0}": "{p0} 끝자락의 가비오타 아술 해변, {p0}",
"Playa Gaviota Azul, en la punta de {p0}. Foto: {x0}, {x1}, vía Wikimedia Commons.": "{p0} 끝자락의 가비오타 아술 해변. 사진: {x0}, {x1}, 출처 Wikimedia Commons.",
"Playa Gaviota Azul, en la punta de {p0}<small>Foto: {x0}, {x1}</small>": "{p0} 끝자락의 가비오타 아술 해변<small>사진: {x0}, {x1}</small>",
"Playa de la zona hotelera de {p0}": "{p0} 호텔 지구의 해변",
"Playa de la zona hotelera de {p0}<small>Foto: {x0}, {x1}</small>": "{p0} 호텔 지구의 해변<small>사진: {x0}, {x1}</small>",
"Playa del Carmen desde el aire": "하늘에서 본 플라야 델 카르멘",
"Playa del Carmen desde el aire, {p0}": "하늘에서 본 플라야 델 카르멘, {p0}",
"Playa del Carmen desde el aire. Foto: {x0}, {x1}, vía Wikimedia Commons.": "하늘에서 본 플라야 델 카르멘. 사진: {x0}, {x1}, 출처 Wikimedia Commons.",
"Playa del Carmen desde el aire<small>Foto: {x0}, {x1}</small>": "하늘에서 본 플라야 델 카르멘<small>사진: {x0}, {x1}</small>",
"Por la tarde": "오후",
"Posada · a {n0} km del centro": "여관 · 중심가에서 {n0} km",
"Posada · en el centro": "여관 · 중심가",
"Posada · en {p0}, a {n0} km": "여관 · {p0}, {n0} km 거리",
"Postales del sur": "남부에서 온 엽서",
"Postales del sur · fotos tomadas en cada lugar": "남부에서 온 엽서 · 각 장소에서 찍은 사진",
"Preguntas": "질문",
"Preguntas frecuentes": "자주 묻는 질문",
"Preguntas rápidas": "빠른 질문",
"Pregúntanos": "물어보세요",
"Pueblo de pescadores junto a la bahía y la zona arqueológica de Oxtankah, casi siempre sin filas.": "만 옆의 어촌 마을과 옥스탄카 유적, 거의 항상 줄이 없습니다.",
"Pueblo de pescadores junto a la bahía y la zona arqueológica de Oxtankah, casi siempre sin filas. Tiene {n0} lugares para comer y {n1} para dormir. Cuidado: comparte con {p0} la vigilancia del sargazo en la bahía.": "만 옆의 어촌 마을과 옥스탄카 유적, 거의 항상 줄이 없습니다. 먹을 곳 {n0}곳, 묵을 곳 {n1}곳이 있습니다. 주의: {p0}와(과) 함께 만의 사르가숨을 감시합니다.",
"Pueblos de {p0}": "{p0}의 마을들",
"Pueblos mayas con turismo comunitario y la cueva de Kantemó.": "공동체 관광을 하는 마야 마을들과 칸테모 동굴.",
"Pueblos mayas con turismo comunitario y la cueva de Kantemó. Tiene {n0} lugares para comer y {n1} para dormir; {n2} personas llegaron en el Tren Maya en {m0} de {n3}. Cuidado: hay pocos cuartos de hotel: la campaña pone un límite de visitantes para no rebasar a los pueblos.": "공동체 관광을 하는 마야 마을들과 칸테모 동굴. 먹을 곳 {n0}곳, 묵을 곳 {n1}곳이 있고, {n3}년 {m0}에는 {n2}명이 마야 열차로 도착했습니다. 주의: 호텔 객실이 적어 캠페인은 마을에 부담을 주지 않도록 방문객 수에 상한을 둡니다.",
"Qué hacer": "할 일",
"Radar, {m0} de {n0}:": "레이더, {n0}년 {m0}:",
"Recreación · a {n0} km del centro": "레저 · 중심가에서 {n0} km",
"Recreación · en Xul-ha, a {n0} km": "레저 · 슐하, {n0} km 거리",
"Recreación · en el centro": "레저 · 중심가",
"Recreación · en {p0}, a {n0} km": "레저 · {p0}, {n0} km 거리",
"Respondo con los datos del proyecto. Si no lo sé, lo digo.": "프로젝트 데이터로 답합니다. 모르면 모른다고 말합니다.",
"Restaurante Bahía Villamar, en una casa de madera": "목조 주택에 있는 바이아 비야마르 식당",
"Restaurante Bahía Villamar, en una casa de madera<small>Foto: {x0}, {x1}</small>": "목조 주택에 있는 바이아 비야마르 식당<small>사진: {x0}, {x1}</small>",
"Restaurante a la carta · a {n0} km del centro": "일품요리 레스토랑 · 중심가에서 {n0} km",
"Restaurante a la carta · en el centro": "일품요리 레스토랑 · 중심가",
"Rutas de {n0} y {n1} días": "{n0}일·{n1}일 코스",
"Saltar al contenido": "본문으로 건너뛰기",
"Se espera alrededor de <b>{n0} %</b> de los cuartos de hotel ocupados, muy probablemente entre {n1} y {n2} %.": "호텔 객실의 약 <b>{n0} %</b>가 찰 것으로 예상되며, {n1}~{n2} % 사이일 가능성이 큽니다.",
"Se esperan alrededor de <b>{n0}</b> cruces desde Belice, muy probablemente entre {n1} y {n2}.": "벨리즈에서 약 <b>{n0}</b>건의 입국이 예상되며, {n1}~{n2}건 사이일 가능성이 큽니다.",
"Se esperan alrededor de <b>{n0}</b> visitantes a Kohunlich, Dzibanché e Ichkabal, muy probablemente entre {n1} y {n2}.": "코훈리치, 지반체, 이치카발에 약 <b>{n0}</b>명의 방문객이 예상되며, {n1}~{n2}명 사이일 가능성이 큽니다.",
"Se esperan alrededor de <b>{n0}</b> visitantes a la zona de Oxtankah, muy probablemente entre {n1} y {n2}.": "옥스탄카 유적에 약 <b>{n0}</b>명의 방문객이 예상되며, {n1}~{n2}명 사이일 가능성이 큽니다.",
"Se vigila el sargazo que apareció en los canales de entrada de la bahía ({m0} de {n0}).": "만으로 들어오는 수로에 나타난 사르가숨을 감시하고 있습니다({n0}년 {m0}).",
"Secciones": "섹션",
"Seis experiencias con lugares reales y una cifra oficial cada una. Sin precios: ninguna fuente oficial los publica.": "실제 장소와 공식 수치 하나씩을 담은 여섯 가지 체험. 가격은 표시하지 않습니다: 공식 출처가 공개하지 않기 때문입니다.",
"Sin dato": "데이터 없음",
"Sin dato oficial": "공식 데이터 없음",
"Sí: en {n0} {n1} de cada {n2} cuartos de hotel de {p0} se quedaron vacíos ({n3} de {n4} noches ocupadas).": "네: {n0}년 {p0}의 호텔 객실 {n2}개 중 {n1}개가 비어 있었습니다({n4}박 중 {n3}박 이용).",
"Tacos y tortas · a {n0} km del centro": "타코·토르타 · 중심가에서 {n0} km",
"Tacos y tortas · en el centro": "타코·토르타 · 중심가",
"Te conviene más": "이쪽이 더 좋아요",
"Temporada alta": "성수기",
"Temporada alta.": "성수기.",
"Tienen sargazo y se llenan: en su semana más llena, {p0} tuvo {n0} de cada {n1} cuartos ocupados, y en Tulum se reportaron cierres de negocios en {n2}. La campaña lleva gente a donde sí hay espacio.": "사르가숨이 있고 붐빕니다: 가장 붐빈 주에 {p0}은(는) 객실 {n1}개 중 {n0}개가 찼고, {n2}년 툴룸에서는 가게 폐업이 보도되었습니다. 캠페인은 정말 여유 있는 곳으로 사람들을 안내합니다.",
"Todo lo que viste arriba sale de datos oficiales, modelos y pruebas. Esta parte es para quien quiera revisar cómo lo sabemos.": "위에서 본 모든 것은 공식 데이터, 모델, 테스트에서 나왔습니다. 이 부분은 저희가 어떻게 아는지 확인하고 싶은 분들을 위한 것입니다.",
"Tranquilo": "한적함",
"Tu viaje": "나의 여행",
"Turismo comunitario maya": "마야 공동체 관광",
"Un balneario o un parque, y a comer: mariscos, cocina yucateca o comida casera.": "물놀이 장소나 공원에 들른 뒤 식사: 해산물, 유카탄 요리, 가정식.",
"Un día en <em>{p0}</em>": "<em>{p0}</em>에서의 하루",
"Un equipo de estudiantes de Ciencias de Datos para Negocios de la Universidad Nacional Rosario Castellanos (UNRC), como proyecto escolar {n0}-{n1}.": "로사리오 카스테야노스 국립대학교(UNRC) 비즈니스 데이터 사이언스 전공 학생 팀의 {n0}-{n1} 학기 수업 프로젝트입니다.",
"Un matapalo en la selva de Felipe Carrillo Puerto": "펠리페 카리요 푸에르토 정글의 교살무화과나무",
"Un muelle en la Laguna Milagros": "밀라그로스 석호의 부두",
"Un muelle en la Laguna Milagros. Foto: {x0}, {x1}, vía Wikimedia Commons.": "밀라그로스 석호의 부두. 사진: {x0}, {x1}, 출처 Wikimedia Commons.",
"Una laguna del mismo sistema que Bacalar, con pueblos a la orilla.": "바칼라르와 같은 수계의 석호로, 기슭에 마을이 있습니다.",
"Una laguna del mismo sistema que Bacalar, con pueblos a la orilla. Tiene {n0} lugares para comer y {n1} para dormir. Cuidado: la laguna es frágil: visitas con límite estricto y sin actividades que la dañen.": "바칼라르와 같은 수계의 석호로, 기슭에 마을이 있습니다. 먹을 곳 {n0}곳, 묵을 곳 {n1}곳이 있습니다. 주의: 석호가 연약해 엄격한 인원 제한이 있고, 해를 끼치는 활동은 하지 않습니다.",
"Una laguna dulce y un cenote": "민물 석호와 세노테",
"Unas {n0} personas al día entre las tres zonas en {n1}: tienes la pirámide casi para ti. <small>Fuente: INAH</small>": "{n1}년 세 유적을 합쳐 하루 약 {n0}명: 피라미드를 거의 혼자 차지할 수 있어요. <small>출처: INAH</small>",
"Ver cómo está en {m0}": "{m0}의 모습 보기",
"Ver cómo va a estar": "어떨지 보기",
"Ver la {p0} en {m0}": "{m0}의 {p0} 보기",
"Ver todo el mapa": "지도 전체 보기",
"Ver {p0} en {m0}": "{m0}의 {p0} 보기",
"Vive el sur": "남부를 즐기세요",
"Zona arqueológica (INAH)": "유적지(INAH)",
"Zona arqueológica de El Meco": "엘 메코 유적",
"Zona arqueológica de El Meco<small>Foto: {x0}, {x1}</small>": "엘 메코 유적<small>사진: {x0}, {x1}</small>",
"Zonas arqueológicas, museos y paseos; para empezar, un café o un desayuno.": "유적지, 박물관, 나들이. 시작은 커피나 아침 식사로.",
"de lluvia en un {m0} normal": "평년 {m0}의 강수량",
"de máxima, en promedio": "평균 최고 기온",
"de probabilidad de tormenta": "폭풍 확률",
"llegaron en el Tren Maya en {m0} de {n0}": "{n0}년 {m0}에 마야 열차로 도착",
"lugar para dormir": "묵을 곳",
"lugares para comer": "먹을 곳",
"lugares para dormir": "묵을 곳",
"no hay estadística oficial de turistas": "공식 관광객 통계 없음",
"sin tormentas registradas en este mes": "이달에 기록된 폭풍 없음",
"visitantes a sus zonas arqueológicas en {n0}": "{n0}년 유적지 방문객",
"{m0} de {n0}: mes normal": "{n0}년 {m0}: 보통인 달",
"{m0} de {n0}: mes tranquilo": "{n0}년 {m0}: 한적한 달",
"{m0} de {n0}: temporada alta": "{n0}년 {m0}: 성수기",
"{n0} días": "{n0}일",
"{n0} marisquerías en Calderitas y {n1} visitantes a Oxtankah en {n2}. <small>Fuente: INEGI (DENUE) e INAH</small>": "{n2}년 칼데리타스에는 해산물 식당 {n0}곳, 옥스탄카에는 방문객 {n1}명. <small>출처: INEGI(DENUE)와 INAH</small>",
"{n0} mm": "{n0} mm",
"{n0} museos en {p1} y {p0} según el directorio del INEGI. <small>Fuente: INEGI (DENUE)</small>": "INEGI 명부에 따르면 {p1}와(과) {p0}에 박물관이 {n0}곳 있습니다. <small>출처: INEGI(DENUE)</small>",
"{n0} °C": "{n0} °C",
"{n0}. {p0}: ir a su descripción": "{n0}. {p0}: 설명으로 이동",
"{p0} en {m0} de {n0}: temporada alta.": "{p0}, {n0}년 {m0}: 성수기.",
"{p0} · {m0} de {n0}": "{p0} · {n0}년 {m0}",
"{p0} · {m0} de {n0} <span>Referencia: la campaña no lo promueve</span>": "{p0} · {n0}년 {m0} <span>참고: 캠페인에서 홍보하지 않음</span>",
"· {m0} de {n0} (estimado): tranquilo": "· {n0}년 {m0}(추정): 한적함",
"¿Cuándo conviene ir?": "언제 가는 게 좋을까요?",
"¿Cuánto cuesta ir?": "비용은 얼마나 드나요?",
"¿Cómo llego al sur?": "남부에는 어떻게 가나요?",
"¿Cómo lo sabemos?": "어떻게 알 수 있나요?",
"¿De dónde salen los datos?": "데이터는 어디서 왔나요?",
"¿Dónde se queda el dinero?": "돈은 어디에 남나요?",
"¿Hay espacio en {p0}?": "{p0}에 여유가 있나요?",
"¿Hay sargazo en el sur?": "남부에 사르가숨이 있나요?",
"¿Ibas al norte?": "북부로 가려고 했나요?",
"¿Por qué no {p0} o Tulum?": "왜 {p0}이나 툴룸이 아닌가요?",
"¿Quién hizo esto?": "누가 만들었나요?",
"¿Qué hay en {p0}?": "{p0}에는 무엇이 있나요?",
"¿Qué lugares promueve la campaña?": "캠페인은 어떤 곳을 홍보하나요?",
"Modo día": "주간 모드",
"<span></span>El Mercado {n0} y los antojitos del centro<small>{n1} km →</small>": "<span></span>{n0} 시장과 중심가 간식<small>{n1} km →</small>",
"<span></span>El parque Fundadores y el Portal Maya<small>a pie →</small>": "<span></span>푼다도레스 공원과 마야 포털<small>걸어서 →</small>",
"<span></span>La Quinta Avenida<small>{n0} km →</small>": "<span></span>5번가<small>{n0} km →</small>",
"<span></span>La playa del pueblo": "<span></span>마을 해변",
"<span></span>La zona arqueológica de El Meco": "<span></span>엘 메코 유적",
"<span></span>La zona hotelera y Playa Gaviota Azul<small>{n0} km →</small>": "<span></span>호텔 지구와 가비오타 아술 해변<small>{n0} km →</small>",
"<span></span>{p0} o Playa del Carmen: subir al Tren Maya<small>{n0} km →</small>": "<span></span>{p0} 또는 플라야 델 카르멘: 마야 열차 타기<small>{n0} km →</small>",
"<span></span>{p0}: el malecón al atardecer<small>{n0} km →</small>": "<span></span>{p0}: 해 질 녘 해변 산책로<small>{n0} km →</small>",
"<span>★★★★★</span> {n0} % de los cuartos de hotel son de {n1} estrellas (categoría oficial, {n2})": "<span>★★★★★</span> 호텔 객실의 {n0} %가 {n1}성급(공식 등급, {n2}년)",
"Antojitos y Mercado {n0}": "간식과 {n0} 시장",
"Así se come en {p0}": "{p0}에서 먹는 것",
"Categoría de hotel: SECTUR-DataTur, Compendio Estadístico del Turismo en México {n0} (tabla {n1}_2). Fuente: INEGI, Directorio Estadístico Nacional de Unidades Económicas (DENUE). El tipo de lugar y el momento del día los sugiere un clasificador de texto que lee el nombre y el giro oficial de cada negocio (acertó {n2} de {n3} en una revisión al azar). Cuando un lugar no tiene algo cerca, se muestra lo más cercano de los otros lugares del sur. \"Ver en Google Maps\" abre Google Maps en otra pestaña; esta página no descarga nada de Google.": "호텔 등급: SECTUR-DataTur, 『멕시코 관광 통계 개요 {n0}』(표 {n1}_2). 출처: INEGI 전국 경제 단위 통계 명부(DENUE). 장소 유형과 시간대는 각 업체의 이름과 공식 업종을 읽는 텍스트 분류기가 제안합니다(무작위 점검에서 {n3}건 중 {n2}건 정답). 가까이에 없는 유형은 남부의 다른 장소 중 가장 가까운 곳을 보여 줍니다. 'Google 지도에서 보기'는 새 탭에서 Google 지도를 엽니다. 이 페이지는 Google에서 아무것도 내려받지 않습니다.",
"Cenar en la calle, de noche": "밤에 길거리에서 먹는 저녁",
"Cenar en la calle, de noche<small>Foto: {x0}, {x1}</small>": "밤에 길거리에서 먹는 저녁<small>사진: {x0}, {x1}</small>",
"Cocina mexicana en la Quinta Avenida": "5번가의 멕시코 요리",
"Cocina mexicana en la Quinta Avenida<small>Foto: {x0}, {x1}</small>": "5번가의 멕시코 요리<small>사진: {x0}, {x1}</small>",
"Comida de mariscos frente al mar": "바닷가의 해산물 점심",
"Comida de mariscos frente al mar<small>Foto: {x0}, {x1}</small>": "바닷가의 해산물 점심<small>사진: {x0}, {x1}</small>",
"Del Caribe a la selva, en un <em>solo</em> mapa.": "카리브해에서 정글까지, <em>하나</em>의 지도로.",
"Del Caribe al sur en Tren Maya": "마야 열차로 카리브해에서 남부로",
"Distancias en línea recta (no hay datos abiertos de distancias por carretera). Sin precios: ninguna fuente oficial los publica. Las reseñas se leen en Google Maps.": "거리는 직선거리입니다(도로 거리 공개 데이터는 없습니다). 가격은 표시하지 않습니다: 공식 출처가 공개하지 않기 때문입니다. 리뷰는 Google 지도에서 보세요.",
"El Meco, El Rey y el Museo Maya de {p0}: ciudades mayas entre los hoteles y la laguna.": "엘 메코, 엘 레이, {p0} 마야 박물관: 호텔과 석호 사이의 마야 도시.",
"El Museo de la Cultura Maya, el planetario y la historia de la ciudad, a pasos de la bahía.": "마야 문화 박물관, 천문관, 도시의 역사가 만에서 몇 걸음 거리에 있습니다.",
"El Portal Maya y los Voladores": "마야 포털과 볼라도레스",
"El clima es el normal de {n0} a {n1}. El riesgo de tormenta cuenta las tormentas que pasaron a {n2} km o menos del lugar desde {n3} ({n4} en el caso de {p0}).": "기후는 {n0}~{n1}년의 평년값입니다. 폭풍 위험은 {n3}년 이후 그곳에서 {n2} km 이내를 지나간 폭풍을 센 것입니다({p0}은(는) {n4}번).",
"El parque Fundadores frente al mar, con el Portal Maya y la danza de los Voladores.": "바다를 마주한 푼다도레스 공원, 마야 포털과 볼라도레스 춤.",
"El sur: {p3}, {p0}, {p1}. {p4} y la {p2} aparecen como referencia, para quien pensaba ir al norte: si su mes está lleno, te recomendamos un lugar del sur.": "남부: {p3}, {p0}, {p1}. {p4}와(과) {p2}은(는) 북부로 가려던 분들을 위한 참고용입니다. 그달이 꽉 찼다면 남부의 장소를 추천해 드립니다.",
"En el sur · {p0}": "남부 · {p0}",
"En la costa de {p0} y Calderitas no hay reporte de sargazo. Sí apareció en los canales de entrada de la bahía ({m0} de {n0}), así que se vigila. La ruta de las pirámides está lejos del mar abierto.": "{p0}와(과) 칼데리타스 해안에는 사르가숨 보고가 없습니다. 만으로 들어오는 수로에서는 나타났기 때문에({n0}년 {m0}) 감시하고 있습니다. 피라미드 길은 먼바다에서 멀리 떨어져 있습니다.",
"En los municipios del sur que promueve la campaña no hay ningún hospedaje grande: {n0} son chicos (hasta {n1} personas) y {n2} medianos. La derrama económica por destino no se muestra porque la fuente no dice en qué unidad está.": "캠페인이 홍보하는 남부 시들에는 대형 숙소가 없습니다: {n0}곳은 소규모({n1}명까지), {n2}곳은 중규모입니다. 목적지별 관광 지출은 출처가 단위를 밝히지 않아 표시하지 않습니다.",
"En {n0} llegaron {n1} pasajeros en avión a {p0}, y el Tren Maya para en {p0}, Bacalar, {p1} y Playa del Carmen. Solo en {m0} de {n2} {n3} personas bajaron del tren en {p0}.": "{n0}년에 {n1}명의 승객이 비행기로 {p0}에 도착했고, 마야 열차는 {p0}, 바칼라르, {p1}, 플라야 델 카르멘에 정차합니다. {n2}년 {m0} 한 달에만 {n3}명이 {p0}에서 열차를 내렸습니다.",
"Fajitas de pollo en Playa del Carmen": "플라야 델 카르멘의 치킨 파히타",
"Fajitas de pollo en Playa del Carmen<small>Foto: {x0}, {x1}</small>": "플라야 델 카르멘의 치킨 파히타<small>사진: {x0}, {x1}</small>",
"Fotos del lugar elegido; se pueden recorrer con las flechas": "고른 장소의 사진. 화살표 키로 넘겨 볼 수 있습니다",
"Guacamole y mojitos": "과카몰레와 모히토",
"Guacamole y mojitos<small>Foto: {x0}, {x1}</small>": "과카몰레와 모히토<small>사진: {x0}, {x1}</small>",
"La Quinta Avenida": "5번가",
"La calle peatonal de Playa del Carmen: restaurantes, tiendas y el mar a una cuadra.": "플라야 델 카르멘의 보행자 거리: 식당과 가게, 바다까지 한 블록.",
"La ciudad más visitada del Caribe mexicano: la zona hotelera, la laguna Nichupté y zonas mayas dentro de la ciudad.": "멕시코 카리브해에서 가장 많이 찾는 도시: 호텔 지구, 니춥테 석호, 도시 안의 마야 유적.",
"La ciudad más visitada del Caribe mexicano: la zona hotelera, la laguna Nichupté y zonas mayas dentro de la ciudad. Tiene {n0} lugares para comer y {n1} para dormir. Referencia: la campaña no lo promueve. Tiene sargazo en {n2} y está en temporada alta de {m0} a {m1}.": "멕시코 카리브해에서 가장 많이 찾는 도시: 호텔 지구, 니춥테 석호, 도시 안의 마야 유적. 먹을 곳 {n0}곳, 묵을 곳 {n1}곳이 있습니다. 참고: 캠페인에서 홍보하지 않음. {n2}년에 사르가숨이 있고 {m0}부터 {m1}까지 성수기입니다.",
"La zona hotelera": "호텔 지구",
"Las fotos son de Wikimedia Commons, con licencia libre, y cada una se tomó dentro del municipio del lugar (su coordenada se comprobó con el mapa oficial). Las fotos de comida solo existen con licencia libre para {p0} y Playa del Carmen; las del sur las aportará el equipo.": "사진은 자유 라이선스의 Wikimedia Commons 자료이며, 모두 그 장소가 속한 시 안에서 찍었습니다(좌표를 공식 지도와 대조했습니다). 자유 라이선스 음식 사진은 {p0}와(과) 플라야 델 카르멘에만 있습니다. 남부의 사진은 팀이 제공합니다.",
"Maqueta de Quintana Roo. Arrastra para girarla.": "킨타나로오주 모형. 드래그해서 돌려 보세요.",
"Mes menos lleno: <b>{m0}</b> · el menos lleno de los meses secos y sin tormentas; aun así, hoteles al {n0} %": "가장 덜 붐비는 달: <b>{m0}</b> · 건조하고 폭풍 없는 달 중 가장 덜 찬 달. 그래도 호텔은 {n0} %",
"Panuchos, el antojito yucateco": "파누초스, 유카탄 간식",
"Panuchos, el antojito yucateco<small>Foto: {x0}, {x1}</small>": "파누초스, 유카탄 간식<small>사진: {x0}, {x1}</small>",
"Panuchos, salbutes y tacos en el centro, lejos de la zona hotelera.": "호텔 지구에서 떨어진 중심가의 파누초스, 살부테스, 타코.",
"Playa Gaviota Azul y la punta de {p0}: arena blanca entre el mar y la laguna Nichupté.": "가비오타 아술 해변과 {p0}의 끝자락: 바다와 니춥테 석호 사이의 하얀 모래.",
"Playa del Carmen en un día": "플라야 델 카르멘 하루 코스",
"Playa del Carmen, el centro de la {p0}: la Quinta Avenida, el parque Fundadores y la playa del pueblo.": "{p0}의 중심 플라야 델 카르멘: 5번가, 푼다도레스 공원, 마을 해변.",
"Playa del Carmen, el centro de la {p0}: la Quinta Avenida, el parque Fundadores y la playa del pueblo. Tiene {n0} lugares para comer y {n1} para dormir. Referencia: la campaña no la promueve. Tiene sargazo en {n2}; su ocupación bajó y se llena en {m0} y {m1}.": "{p0}의 중심 플라야 델 카르멘: 5번가, 푼다도레스 공원, 마을 해변. 먹을 곳 {n0}곳, 묵을 곳 {n1}곳이 있습니다. 참고: 캠페인에서 홍보하지 않음. {n2}년에 사르가숨이 있고, 점유율은 떨어졌지만 {m0}과 {m1}에는 꽉 찹니다.",
"Postales de {p0} · fotos tomadas en cada lugar": "{p0}에서 온 엽서 · 각 장소에서 찍은 사진",
"Primero, lo del lugar que elegiste arriba; después, lo del sur. Lugares reales y una cifra oficial en cada uno. Sin precios: ninguna fuente oficial los publica.": "먼저 위에서 고른 곳, 그다음 남부. 실제 장소마다 공식 수치를 하나씩 담았습니다. 가격은 표시하지 않습니다: 공식 출처가 공개하지 않기 때문입니다.",
"Referencia: la campaña no la promueve. Tiene sargazo en {n0}; su ocupación bajó y se llena en {m0} y {m1}.": "참고: 캠페인에서 홍보하지 않음. {n0}년에 사르가숨이 있고, 점유율은 떨어졌지만 {m0}과 {m1}에는 꽉 찹니다.",
"Referencia: la campaña no lo promueve": "참고: 캠페인에서 홍보하지 않음",
"Referencia: la campaña no lo promueve. Tiene sargazo en {n0} y está en temporada alta de {m0} a {m1}.": "참고: 캠페인에서 홍보하지 않음. {n0}년에 사르가숨이 있고 {m0}부터 {m1}까지 성수기입니다.",
"Todavía no tengo esa respuesta. Prueba con una de las preguntas de abajo: solo respondo lo que los datos del proyecto pueden sostener.": "아직 그 답은 없습니다. 아래 질문을 눌러 보세요: 프로젝트 데이터로 뒷받침되는 것만 답합니다.",
"Tres en el sur, con espacio. {p1} y la {p0}, como referencia para quien iba al norte.": "남부 세 곳은 여유가 있습니다. {p1}와(과) {p0}은(는) 북부로 가려던 분들을 위한 참고용입니다.",
"Un puesto de quesadillas": "케사디야 노점",
"Un puesto de quesadillas<small>Foto: {x0}, {x1}</small>": "케사디야 노점<small>사진: {x0}, {x1}</small>",
"Una taquería del centro": "중심가의 타코 가게",
"Una taquería del centro<small>Foto: {x0}, {x1}</small>": "중심가의 타코 가게<small>사진: {x0}, {x1}</small>",
"Zonas mayas dentro de {p0}": "{p0} 안의 마야 유적",
"cuartos de hotel ({m0} de {n0})": "호텔 객실({n0}년 {m0})",
"de los cuartos son de {n0} estrellas ({n1})": "의 객실이 {n0}성급({n1}년)",
"sin temporada alta en los cinco lugares": "다섯 곳 모두 성수기가 아닙니다",
"{m0} de {n0}:": "{n0}년 {m0}:",
"{n0} % de los cuartos de hotel de Playa del Carmen son de {n1} estrellas, según la categoría oficial ({n2}). <small>Fuente: SECTUR-DataTur (Compendio {n3})</small>": "공식 등급에 따르면 플라야 델 카르멘 호텔 객실의 {n0} %가 {n1}성급입니다({n2}년). <small>출처: SECTUR-DataTur({n3}년 개요)</small>",
"{n0} % de sus cuartos de hotel son de {n1} estrellas, según la categoría oficial ({n2}). <small>Fuente: SECTUR-DataTur (Compendio {n3})</small>": "공식 등급에 따르면 호텔 객실의 {n0} %가 {n1}성급입니다({n2}년). <small>출처: SECTUR-DataTur({n3}년 개요)</small>",
"{n0} día": "{n0}일",
"{n0} lugares de antojitos, tacos y cocina yucateca en la ciudad según el directorio del INEGI. <small>Fuente: INEGI (DENUE)</small>": "INEGI 명부에 따르면 시내에 간식·타코·유카탄 요리 가게가 {n0}곳 있습니다. <small>출처: INEGI(DENUE)</small>",
"{n0} lugares para comer en Playa del Carmen según el directorio del INEGI. <small>Fuente: INEGI (DENUE)</small>": "INEGI 명부에 따르면 플라야 델 카르멘에는 먹을 곳이 {n0}곳 있습니다. <small>출처: INEGI(DENUE)</small>",
"{n0} museos en {p0} según el directorio del INEGI. <small>Fuente: INEGI (DENUE)</small>": "INEGI 명부에 따르면 {p0}에 박물관이 {n0}곳 있습니다. <small>출처: INEGI(DENUE)</small>",
"{n0} visitantes en {n1} entre las tres: unas {n2} al día. <small>Fuente: INAH</small>": "{n1}년 세 곳에 방문객 {n0}명: 하루 약 {n2}명. <small>출처: INAH</small>",
"{p0} <span>Referencia: la campaña no lo promueve</span>": "{p0} <span>참고: 캠페인에서 홍보하지 않음</span>",
"{p0} en {n0} días": "{p0} {n0}일 코스",
"{p0}, temporada alta": "{p0}, 성수기",
"· Planea tu viaje →": "· 여행 계획 →",
"· {p0}, tranquilo": "· {p0}, 한적함"
},
"lugares": {
"Ruta de las pirámides": "피라미드 길",
"Calderitas y Oxtankah": "칼데리타스와 옥스탄카",
"Laguna Milagros y Xul-Ha": "밀라그로스 석호와 슐하",
"Chetumal": "체투말",
"Cancún": "칸쿤",
"Riviera Maya": "리비에라 마야",
"Maya Ka'an": "마야 카안"
}
};
