/* Traducción al idioma «zh» de la parte del viajero. Generado por backend/torre/campana/idiomas.py desde docs/idiomas/zh.tsv: no editar a mano. */
window.IDIOMAS_TRAD = window.IDIOMAS_TRAD || {};
window.IDIOMAS_TRAD["zh"] = {
"frases": {
"<b>Temporada alta.</b> El sur también está lleno ese mes.": "<b>旺季。</b>那个月南部也很拥挤。",
"<b>Temporada alta.</b> {p0} está más tranquilo ese mes.": "<b>旺季。</b>那个月{p0}更安静。",
"<b>Temporada alta</b> quiere decir que ese mes llega {n0} % o más gente que en un mes promedio del año, o que hay {n1} % o más de probabilidad de rebasar el mes más lleno que el lugar ha tenido. Se calcula con los visitantes del INAH a las zonas arqueológicas y, en {p0}, con los cruces desde Belice.": "<b>旺季</b>是指那个月的游客比全年平均月份多出 {n0} % 或以上，或者有 {n1} % 或以上的可能超过该地历史上最拥挤的月份。计算依据是 INAH 考古遗址的游客人数，以及{p0}来自伯利兹的入境人次。",
"<b>{p0} en {m0} de {n0}: temporada alta.</b> El sur también está lleno ese mes.": "<b>{p0}，{n0}年{m0}：旺季。</b>那个月南部也很拥挤。",
"<b>{p0} en {m0} de {n0}: temporada alta.</b> {p1} está más tranquilo ese mes.": "<b>{p0}，{n0}年{m0}：旺季。</b>那个月{p1}更安静。",
"<b>{p1} en {m0} de {n0}: temporada alta.</b> {p0} está más tranquilo ese mes.": "<b>{p1}，{n0}年{m0}：旺季。</b>那个月{p0}更安静。",
"<b>{p1} y {p0}</b> están como referencia, para quien pensaba ir al norte; la campaña no los promueve. Ahí se mide la ocupación de los hoteles: es temporada alta si se espera {n0} % de cuartos ocupados o más, el nivel que el Radar ya cuenta como \"concurrido\". Si el mes está lleno, te recomendamos un lugar del sur. Tómalo con cuidado en la {p0}: su ocupación bajó ({n1} % en {m0} de {n2} contra {n3} % un año antes), el pronóstico supone que sigue así y se equivoca más que solo repetir lo del año anterior; se usa porque es el único cuyo rango sí atrapó el valor real {n4} de cada {n5} veces.": "<b>{p1}和{p0}</b>仅作参考，供原本打算去北部的人查看；本活动不推广它们。那里衡量的是酒店入住率：如果预计入住率达到 {n0} % 或以上，即为旺季，这是雷达已视为\"拥挤\"的水平。如果那个月客满，我们会推荐南部的一个地方。请谨慎看待{p0}：其入住率下降了（{n2}年{m0}为 {n1} %，一年前为 {n3} %），预测假设这一趋势持续，误差也比简单重复去年更大；之所以采用，是因为只有它的区间在 {n5} 次中有 {n4} 次真正覆盖了实际值。",
"<span></span><b>Radar, {m0} de {n0}:</b> {n1} de los {n2} lugares del sur, tranquilos<span> · {p0}, sin dato oficial</span><span> · Ver el Radar →</span>": "<span></span><b>雷达，{n0}年{m0}：</b>南部 {n2} 个地方中有 {n1} 个很安静<span> · {p0}，无官方数据</span><span> · 查看雷达 →</span>",
"<span></span>Calderitas: mariscos y la zona de Oxtankah<small>{n0} km →</small>": "<span></span>卡尔德里塔斯：海鲜与奥斯坦卡遗址<small>{n0} 公里 →</small>",
"<span></span>Felipe Carrillo Puerto (estación del Tren Maya)<small>{n0} km →</small>": "<span></span>费利佩·卡里略·普埃尔托（玛雅列车车站）<small>{n0} 公里 →</small>",
"<span></span>Kantemó: la cueva": "<span></span>坎特莫：洞穴",
"<span></span>Kohunlich y Dzibanché, en la selva": "<span></span>科洪利奇与兹班切，在丛林中",
"<span></span>Kohunlich, Dzibanché e Ichkabal": "<span></span>科洪利奇、兹班切与伊奇卡巴尔",
"<span></span>Laguna Milagros y el cenote de Xul-Ha<small>{n0} km →</small>": "<span></span>米拉格罗斯湖与舒尔哈天然井<small>{n0} 公里 →</small>",
"<span></span>Señor: ecoturismo comunitario<small>{n0} km →</small>": "<span></span>塞尼奥尔：社区生态旅游<small>{n0} 公里 →</small>",
"<span></span>Tihosuco: el Museo de la Guerra de Castas<small>{n0} km →</small>": "<span></span>蒂奥苏科：种姓战争博物馆<small>{n0} 公里 →</small>",
"<span></span>Tranquilo <span></span>Normal <span></span>Temporada alta": "<span></span>安静 <span></span>一般 <span></span>旺季",
"<span></span>{p0}: el malecón y el Museo de la Cultura Maya<small>{n0} km →</small>": "<span></span>{p0}：海滨大道与玛雅文化博物馆<small>{n0} 公里 →</small>",
"<span></span>{p0}: la bahía al atardecer<small>{n0} km →</small>": "<span></span>{p0}：夕阳下的海湾<small>{n0} 公里 →</small>",
"<span>★ </span>Reseñas<span> ↗</span><span> en Google Maps (otra pestaña)</span>": "<span>★ </span>评价<span> ↗</span><span>（在 Google 地图中打开新标签页）</span>",
"Agencia de viajes y tours · en el centro": "旅行社与游览 · 在市中心",
"Agencia de viajes y tours · en {p0}, a {n0} km": "旅行社与游览 · 在{p0}，距离 {n0} 公里",
"Antojitos y tacos para cenar, un bar para cerrar el día y dónde dormir.": "晚餐吃小吃和塔可，去酒吧结束一天，再找个地方住下。",
"Antojitos · a {n0} km del centro": "墨西哥小吃 · 距市中心 {n0} 公里",
"Antojitos · en el centro": "墨西哥小吃 · 在市中心",
"Asados y pollos · a {n0} km del centro": "烤肉与鸡 · 距市中心 {n0} 公里",
"Asados y pollos · en el centro": "烤肉与鸡 · 在市中心",
"Así se ve la {p0}": "{p0}的样子",
"Así se ve {p0}": "{p0}的样子",
"Así va a <em>estar</em>.": "就会是<em>这样</em>。",
"Atardecer en el malecón": "海滨大道的日落",
"Atardecer en una calle de Calderitas": "卡尔德里塔斯街头的日落",
"Atardecer en una calle de Calderitas<small>Foto: {x0}, {x1}</small>": "卡尔德里塔斯街头的日落<small>照片: {x0}, {x1}</small>",
"Atardecer sobre la laguna de {p0}": "{p0}潟湖上的日落",
"Atardecer sobre la laguna de {p0}<small>Foto: {x0}, {x1}</small>": "{p0}潟湖上的日落<small>照片: {x0}, {x1}</small>",
"Avenida Constituyentes, en Felipe Carrillo Puerto": "费利佩·卡里略·普埃尔托的宪法大道",
"Aves en un muelle de la Laguna Milagros": "米拉格罗斯湖码头上的鸟",
"Bahía y pirámides": "海湾与金字塔",
"Balneario · a {n0} km del centro": "游泳场所 · 距市中心 {n0} 公里",
"Balneario · en Calderitas, a {n0} km": "游泳场所 · 在卡尔德里塔斯，距离 {n0} 公里",
"Balneario · en el centro": "游泳场所 · 在市中心",
"Balneario · en {p0}, a {n0} km": "游泳场所 · 在{p0}，距离 {n0} 公里",
"Bar o cantina · a {n0} km del centro": "酒吧 · 距市中心 {n0} 公里",
"Bar o cantina · en el centro": "酒吧 · 在市中心",
"Bar o cantina · en {p0}, a {n0} km": "酒吧 · 在{p0}，距离 {n0} 公里",
"Cabañas y villas · a {n0} km del centro": "小屋与别墅 · 距市中心 {n0} 公里",
"Cabañas y villas · en el centro": "小屋与别墅 · 在市中心",
"Café, desayunos y postres · a {n0} km del centro": "咖啡、早餐与甜点 · 距市中心 {n0} 公里",
"Café, desayunos y postres · en el centro": "咖啡、早餐与甜点 · 在市中心",
"Café, desayunos y postres · en {p0}, a {n0} km": "咖啡、早餐与甜点 · 在{p0}，距离 {n0} 公里",
"Cambiar a {p0} en {m0}": "{m0}改去{p0}",
"Campamento · en Calderitas, a {n0} km": "露营地 · 在卡尔德里塔斯，距离 {n0} 公里",
"Campamento · en el centro": "露营地 · 在市中心",
"Casa de huéspedes · a {n0} km del centro": "家庭旅馆 · 距市中心 {n0} 公里",
"Casas típicas de madera en el Boulevard Bahía": "海湾大道上的传统木屋",
"Casas típicas de madera en el Boulevard Bahía<small>Foto: {x0}, {x1}</small>": "海湾大道上的传统木屋<small>照片: {x0}, {x1}</small>",
"Centro nocturno · a {n0} km del centro": "夜店 · 距市中心 {n0} 公里",
"Centro nocturno · en el centro": "夜店 · 在市中心",
"Centro nocturno · en {p0}, a {n0} km": "夜店 · 在{p0}，距离 {n0} 公里",
"Cerrar aviso": "关闭提示",
"Cerrar preguntas": "关闭问答",
"Cinco lugares": "五个地方",
"Cinco lugares del sur de Quintana Roo: {p4}, {p1}, {p2}, {p3} y {p0}.": "金塔纳罗奥州南部的五个地方：{p4}、{p1}、{p2}、{p3}和{p0}。",
"Cocina internacional · en el centro": "国际美食 · 在市中心",
"Cocina yucateca · en el centro": "尤卡坦菜 · 在市中心",
"Comida casera · a {n0} km del centro": "家常菜 · 距市中心 {n0} 公里",
"Comida casera · en el centro": "家常菜 · 在市中心",
"Comida para llevar · a {n0} km del centro": "外卖 · 距市中心 {n0} 公里",
"Comida para llevar · en el centro": "外卖 · 在市中心",
"Comida rápida · a {n0} km del centro": "快餐 · 距市中心 {n0} 公里",
"Comida rápida · en el centro": "快餐 · 在市中心",
"Comparte con {p0} la vigilancia del sargazo en la bahía.": "与{p0}共同监测海湾里的马尾藻。",
"Con datos oficiales": "基于官方数据",
"Cuatro están en el mismo municipio que {p0}.": "其中四个与{p0}位于同一个市。",
"Cómo llega la gente": "人们如何到达",
"Cómo llegar<span> ↗</span><span> (Google Maps, otra pestaña)</span>": "路线<span> ↗</span><span>（Google 地图，新标签页）</span>",
"De día": "白天",
"De fuentes oficiales y abiertas: Secretaría de Turismo, gobierno de Quintana Roo, INEGI, INAH, NOAA, Open-Meteo y la Reserva Federal. Las fotos, de Wikimedia Commons con licencia libre.": "来自官方和公开来源：旅游部、金塔纳罗奥州政府、INEGI、INAH、NOAA、Open-Meteo 以及美国联邦储备委员会。照片来自 Wikimedia Commons，均为自由授权。",
"De noche": "夜晚",
"Del Museo de la Cultura Maya en {p0} al de la Guerra de Castas en Tihosuco: la historia del sur contada desde aquí.": "从{p0}的玛雅文化博物馆到蒂奥苏科的种姓战争博物馆：由这里讲述南部的历史。",
"Del mar a la selva, en un <em>solo</em> viaje.": "从大海到丛林，<em>一次</em>旅行就够。",
"Depende del lugar: arriba, en \"Planea tu viaje\", eliges lugar y mes y te decimos cómo va a estar. Por ejemplo, a la {p0} llega {n0} % menos gente que en un mes promedio en {m0}, y {n1} % más en {m1}.": "这取决于地方：在上方的\"规划你的旅行\"中选择地点和月份，我们会告诉你那时的情况。例如，{m0}去{p0}的人比平均月份少 {n0} %，{m1}则多 {n1} %。",
"Distancias en línea recta entre los centros de cada lugar (no hay datos abiertos de distancias por carretera). Sin precios: ninguna fuente oficial los publica. Las reseñas se leen en Google Maps.": "距离为各地中心之间的直线距离（没有公开的公路距离数据）。不显示价格：没有官方来源公布。评价请在 Google 地图上查看。",
"Documento": "文件",
"Dzibanché: el Templo del Búho": "兹班切：猫头鹰神庙",
"Dzibanché: el Templo del Búho, {p0}": "兹班切：猫头鹰神庙, {p0}",
"Dzibanché: el Templo del Búho. Foto: {x0}, {x1}, vía Wikimedia Commons.": "兹班切：猫头鹰神庙. 照片: {x0}, {x1}, 来源 Wikimedia Commons.",
"Dzibanché: el Templo del Búho<small>Foto: {x0}, {x1}</small>": "兹班切：猫头鹰神庙<small>照片: {x0}, {x1}</small>",
"Dzibanché: la Estructura {n0}": "兹班切：{n0} 号建筑",
"Dzibanché: la Estructura {n0}<small>Foto: {x0}, {x1}</small>": "兹班切：{n0} 号建筑<small>照片: {x0}, {x1}</small>",
"Dónde comer": "在哪里吃",
"Dónde dormir": "在哪里住",
"El Boulevard Bahía de {p0}: casas de madera, monumentos y el sol bajando sobre el agua.": "{p0}的海湾大道：木屋、纪念碑，以及落在水面上的夕阳。",
"El Mercado {n0} en el centro de {p0}": "{p0}市中心的 {n0} 号市场",
"El Mercado {n0} en el centro de {p0}<small>Foto: {x0}, {x1}</small>": "{p0}市中心的 {n0} 号市场<small>照片: {x0}, {x1}</small>",
"El Monumento a la Bandera frente a la bahía": "面朝海湾的国旗纪念碑",
"El Monumento a la Bandera frente a la bahía<small>Foto: {x0}, {x1}</small>": "面朝海湾的国旗纪念碑<small>照片: {x0}, {x1}</small>",
"El Monumento al Pescador al atardecer, en la bahía": "夕阳下海湾边的渔夫纪念碑",
"El Monumento al Pescador al atardecer, en la bahía, {p0}": "夕阳下海湾边的渔夫纪念碑, {p0}",
"El Monumento al Pescador al atardecer, en la bahía. Foto: {x0}, {x1}, vía Wikimedia Commons.": "夕阳下海湾边的渔夫纪念碑. 照片: {x0}, {x1}, 来源 Wikimedia Commons.",
"El Monumento al Pescador al atardecer, en la bahía<small>Foto: {x0}, {x1}</small>": "夕阳下海湾边的渔夫纪念碑<small>照片: {x0}, {x1}</small>",
"El Portal Maya del parque Fundadores": "创始人公园的玛雅之门",
"El Portal Maya del parque Fundadores<small>Foto: {x0}, {x1}</small>": "创始人公园的玛雅之门<small>照片: {x0}, {x1}</small>",
"El Radar": "雷达",
"El agua turquesa de la Laguna Milagros": "米拉格罗斯湖的碧绿湖水",
"El cenote de Xul-Ha": "舒尔哈天然井",
"El clima es el normal de {n0} a {n1}. El riesgo de tormenta cuenta las tormentas que pasaron a {n2} km o menos del lugar desde {n3} ({n4} en el caso de {p1}). {p0} y la Laguna Milagros no tienen estadística oficial de visitantes, así que no están en el planeador; los encuentras en \"Los lugares\".": "气候为 {n0} 至 {n1} 年的常年平均值。风暴风险统计的是自 {n3} 年以来经过该地 {n2} 公里以内的风暴（{p1}为 {n4} 次）。{p0}和米拉格罗斯湖没有官方游客统计，因此不在规划器中；你可以在\"这些地方\"中找到它们。",
"El dato": "关键数据",
"El dinero": "钱",
"El kiosco del centro de {p0}": "{p0}市中心的凉亭",
"El kiosco del centro de {p0}<small>Foto: {x0}, {x1}</small>": "{p0}市中心的凉亭<small>照片: {x0}, {x1}</small>",
"El norte": "北部",
"El parque y los restaurantes de Calderitas al atardecer": "夕阳下卡尔德里塔斯的公园与餐厅",
"El parque y los restaurantes de Calderitas al atardecer<small>Foto: {x0}, {x1}</small>": "夕阳下卡尔德里塔斯的公园与餐厅<small>照片: {x0}, {x1}</small>",
"El problema": "问题",
"El sur": "南部",
"El sur tiene <em>espacio</em>.": "南部有<em>空间</em>。",
"El sur tiene <em>espacio</em>.<br>Y te está esperando.": "南部有<em>空间</em>。<br>它在等你。",
"Elige a dónde y cuándo. Te decimos cómo va a estar.": "选择去哪里、什么时候去。我们告诉你会是什么样子。",
"En Calderitas, a {n0} km de {p0}, se come viendo el agua; al lado está Oxtankah, la ciudad maya de la bahía.": "在卡尔德里塔斯，距{p0} {n0} 公里，你可以一边看海一边用餐；旁边就是海湾的玛雅古城奥斯坦卡。",
"En Felipe Carrillo Puerto, Señor y Tihosuco las comunidades mayas reciben a quien llega: selva, historia y su forma de vivir.": "在费利佩·卡里略·普埃尔托、塞尼奥尔和蒂奥苏科，玛雅社区欢迎来访者：丛林、历史和他们的生活方式。",
"En la costa de {p1} y Calderitas no hay reporte de sargazo. Sí apareció en los canales de entrada de la bahía ({m0} de {n0}), así que se vigila. La ruta de las pirámides, {p0} y la laguna están lejos del mar abierto.": "{p1}和卡尔德里塔斯海岸没有马尾藻报告。它曾出现在通往海湾的水道中（{n0}年{m0}），因此正在监测。金字塔之路、{p0}和潟湖都远离外海。",
"En los municipios de los cinco lugares no hay ningún hospedaje grande: {n0} son chicos (hasta {n1} personas) y {n2} medianos. La derrama económica por destino no se muestra porque la fuente no dice en qué unidad está.": "五个地方所在的各市没有大型住宿：{n0} 家是小型（最多 {n1} 人），{n2} 家是中型。按目的地划分的旅游消费不予显示，因为数据来源没有说明单位。",
"En {m0} el sur también tiene temporada alta. Si puedes mover tu viaje, busca los meses en verde.": "{m0}南部也处于旺季。如果你能调整行程，请找绿色的月份。",
"En {m0}, <b>{p0}</b> no está en temporada alta: hay espacio, sin el gentío del norte.": "{m0}，<b>{p0}</b>不是旺季：有空间，也没有北部的人潮。",
"En {m0}, <b>{p1}</b> está más tranquilo. O ve a la {p0} en <b>{m1}</b>: menos gente, poca lluvia y fuera de la temporada de tormentas.": "{m0}，<b>{p1}</b>更安静。或者在<b>{m1}</b>去{p0}：人更少、雨更少，而且不在风暴季。",
"En {m0}, <b>{p1}</b> está más tranquilo. O ve a {p0} en <b>{m1}</b>: menos gente, poca lluvia y fuera de la temporada de tormentas.": "{m0}，<b>{p1}</b>更安静。或者在<b>{m1}</b>去{p0}：人更少、雨更少，而且不在风暴季。",
"En {n0} llegaron {n1} pasajeros en avión a {p1}, y el Tren Maya para en {p1}, Bacalar y Felipe Carrillo Puerto ({p0}). Solo en {m0} de {n2} {n3} personas bajaron del tren en {p1}.": "{n0} 年有 {n1} 名乘客乘飞机抵达{p1}，玛雅列车停靠{p1}、巴卡拉尔和费利佩·卡里略·普埃尔托（{p0}）。仅 {n2}年{m0}，就有 {n3} 人在{p1}下车。",
"Enviar pregunta": "发送问题",
"Escribe tu pregunta": "输入你的问题",
"Escribe tu pregunta…": "输入你的问题…",
"Ese mes todavía no está en el pronóstico (llega hasta {m0} de {n0}): en un {m1} típico, de {n1} a {n2} los hoteles estuvieron al <b>{n3} %</b>.": "那个月还不在预测范围内（预测到 {n0}年{m0}）：在典型的{m1}，{n1} 至 {n2} 年酒店入住率为 <b>{n3} %</b>。",
"Ese mes todavía no está en el pronóstico (llega hasta {m0} de {n0}): esto es lo típico de {m1}.": "那个月还不在预测范围内（预测到 {n0}年{m0}）：这是{m1}的典型情况。",
"Esta parte está en español: son los datos técnicos del proyecto.": "这一部分为西班牙语：是本项目的技术数据。",
"Estructura {n0} de Oxtankah, con pintura original": "奥斯坦卡 {n0} 号建筑，保留原始彩绘",
"Estructura {n0} de Oxtankah, con pintura original<small>Foto: {x0}, {x1}</small>": "奥斯坦卡 {n0} 号建筑，保留原始彩绘<small>照片: {x0}, {x1}</small>",
"Fotos de los cinco lugares; se pueden recorrer con las flechas": "五个地方的照片；可以用方向键浏览",
"Fuente: ECOSUR y notas del {n0} de {m0} de {n1}": "来源：ECOSUR 及 {n1}年{m0}{n0}日的新闻",
"Fuente: Gobierno de Quintana Roo (SITUR-Q)": "来源：金塔纳罗奥州政府（SITUR-Q）",
"Fuente: INAH (BdINAH) y forma del año del proyecto (Fase {n0})": "来源：INAH（BdINAH）及本项目的年度形态分析（第 {n0} 阶段）",
"Fuente: INAH (BdINAH), SITUR-Q (frontera con Belice), SECTUR-DataTur (ocupación hotelera de {p1} y {p0}), NOAA HURDAT2, Open-Meteo (clima {n0}–{n1}) y pronóstico del proyecto (Fase {n2}); negocios: INEGI, DENUE.": "来源：INAH（BdINAH）、SITUR-Q（伯利兹边境）、SECTUR-DataTur（{p1}和{p0}的酒店入住率）、NOAA HURDAT2、Open-Meteo（{n0}–{n1} 年气候）及本项目的预测（第 {n2} 阶段）；商户：INEGI、DENUE。",
"Fuente: INEGI (DENUE) y SITUR-Q": "来源：INEGI（DENUE）和 SITUR-Q",
"Fuente: INEGI y gobierno de Quintana Roo": "来源：INEGI 和金塔纳罗奥州政府",
"Fuente: INEGI, Directorio Estadístico Nacional de Unidades Económicas (DENUE). El tipo de lugar y el momento del día los sugiere un clasificador de texto que lee el nombre y el giro oficial de cada negocio (acertó {n0} de {n1} en una revisión al azar). Cuando un lugar no tiene algo cerca, se muestra lo más cercano de los otros lugares del sur. \"Ver en Google Maps\" abre Google Maps en otra pestaña; esta página no descarga nada de Google.": "来源：INEGI，全国经济单位统计名录（DENUE）。地点类型和一天中的时段由一个文本分类器建议，它读取每家商户的名称和官方行业（在随机抽查中 {n1} 个对了 {n0} 个）。当某地附近没有某类地点时，显示南部其他地方中最近的一个。\"在 Google 地图中查看\"会在新标签页中打开 Google 地图；本页面不会从 Google 下载任何内容。",
"Fuente: Inventario de fuentes del proyecto": "来源：本项目的数据来源清单",
"Fuente: Secretaría de Turismo y notas verificadas de {n0}": "来源：旅游部及 {n0} 年经核实的新闻",
"Fuente: Selección de regiones del proyecto": "来源：本项目的区域选择",
"Fuente: Torre del Caribe": "来源：Torre del Caribe",
"Girar el mapa solo": "让地图自动旋转",
"Habrá mucha gente: los hoteles suelen pasar del {n0} % de cuartos ocupados, lo que el Radar ya cuenta como \"concurrido\".": "会很拥挤：酒店入住率通常超过 {n0} %，雷达已将其视为\"拥挤\"。",
"Habrá mucha gente: se espera que los hoteles pasen del {n0} % de cuartos ocupados, lo que el Radar ya cuenta como \"concurrido\".": "会很拥挤：预计酒店入住率将超过 {n0} %，雷达已将其视为\"拥挤\"。",
"Hasta {m0} de {n0} hay un pronóstico con su rango: el valor real cayó dentro de ese rango entre {n1} y {n2} de cada {n3} veces cuando se probó con meses que el modelo nunca vio. Después de esa fecha se muestra lo típico de cada mes.": "到 {n0}年{m0} 为止有带区间的预测：在模型从未见过的月份上测试时，实际值有 {n1} 到 {n2} 次（共 {n3} 次）落在该区间内。在此之后显示每个月的典型情况。",
"Hay espacio: los hoteles suelen quedar debajo del {n0} % de cuartos ocupados, lo que el Radar cuenta como \"concurrido\".": "有空间：酒店入住率通常低于 {n0} %，即雷达视为\"拥挤\"的水平。",
"Hay espacio: se espera que los hoteles queden debajo del {n0} % de cuartos ocupados, lo que el Radar cuenta como \"concurrido\".": "有空间：预计酒店入住率将低于 {n0} %，即雷达视为\"拥挤\"的水平。",
"Hay lugar: {n0} de cada {n1} cuartos de hotel de {p0} se quedaron vacíos en {n2}. <small>Fuente: Gobierno de Quintana Roo (SITUR-Q)</small>": "有空房：{n2} 年{p0}每 {n1} 间酒店客房中有 {n0} 间空置。<small>来源：金塔纳罗奥州政府（SITUR-Q）</small>",
"Hay pocos cuartos de hotel: la campaña pone un límite de visitantes para no rebasar a los pueblos.": "酒店客房很少：本活动设定了游客上限，以免村庄不堪重负。",
"Hola. Pregúntame sobre los cinco lugares, cómo llegar o de dónde salen los datos.": "你好。可以问我关于这五个地方、如何到达或数据来源的问题。",
"Hospedaje de la gente de aquí: en los municipios de los cinco lugares hay {n0} hospedajes chicos, {n1} medianos y {n2} grandes. <small>Fuente: INEGI (DENUE)</small>": "当地人经营的住宿：五个地方所在的各市有 {n0} 家小型、{n1} 家中型和 {n2} 家大型住宿。<small>来源：INEGI（DENUE）</small>",
"Hostal · en el centro": "青年旅舍 · 在市中心",
"Hostal · en {p0}, a {n0} km": "青年旅舍 · 在{p0}，距离 {n0} 公里",
"Hotel · en Xul-ha, a {n0} km": "酒店 · 在舒尔哈，距离 {n0} 公里",
"Hotel · en el centro": "酒店 · 在市中心",
"Hotel · en {p0}, a {n0} km": "酒店 · 在{p0}，距离 {n0} 公里",
"Idioma": "语言",
"Idioma / Language": "语言 / Language",
"Iglesia en Felipe Carrillo Puerto": "费利佩·卡里略·普埃尔托的教堂",
"Iglesia en Felipe Carrillo Puerto. Foto: {x0}, {x1}, vía Wikimedia Commons.": "费利佩·卡里略·普埃尔托的教堂. 照片: {x0}, {x1}, 来源 Wikimedia Commons.",
"Jardín botánico o zoológico · a {n0} km del centro": "植物园或动物园 · 距市中心 {n0} 公里",
"Jardín botánico o zoológico · en el centro": "植物园或动物园 · 在市中心",
"Jardín botánico o zoológico · en {p0}, a {n0} km": "植物园或动物园 · 在{p0}，距离 {n0} 公里",
"Kohunlich, Dzibanché e Ichkabal: ciudades mayas entre la selva, con sus mascarones y templos.": "科洪利奇、兹班切与伊奇卡巴尔：丛林中的玛雅古城，有面具和神庙。",
"Kohunlich, Dzibanché e Ichkabal: tres ciudades mayas en la selva, lejos del mar.": "科洪利奇、兹班切与伊奇卡巴尔：丛林中远离大海的三座玛雅古城。",
"Kohunlich, Dzibanché e Ichkabal: tres ciudades mayas en la selva, lejos del mar. Tiene {n0} lugares para comer y {n1} para dormir. Cuidado: los poblados cercanos casi no tienen hoteles: la visita se hace desde {p0}.": "科洪利奇、兹班切与伊奇卡巴尔：丛林中远离大海的三座玛雅古城。这里有 {n0} 个吃饭的地方和 {n1} 个住宿的地方。注意：附近村庄几乎没有酒店，需从{p0}出发参观。",
"Kohunlich: detalle de un mascarón": "科洪利奇：面具细节",
"Kohunlich: detalle de un mascarón<small>Foto: {x0}, {x1}</small>": "科洪利奇：面具细节<small>照片: {x0}, {x1}</small>",
"Kohunlich: el juego de pelota": "科洪利奇：球场",
"Kohunlich: el juego de pelota<small>Foto: {x0}, {x1}</small>": "科洪利奇：球场<small>照片: {x0}, {x1}</small>",
"Kohunlich: los mascarones de estuco": "科洪利奇：灰泥面具",
"Kohunlich: los mascarones de estuco<small>Foto: {x0}, {x1}</small>": "科洪利奇：灰泥面具<small>照片: {x0}, {x1}</small>",
"Kohunlich: una de sus plataformas en la selva": "科洪利奇：丛林中的一座平台",
"Kohunlich: una de sus plataformas en la selva<small>Foto: {x0}, {x1}</small>": "科洪利奇：丛林中的一座平台<small>照片: {x0}, {x1}</small>",
"La Campana del Bicentenario": "独立两百周年纪念钟",
"La Campana del Bicentenario<small>Foto: {x0}, {x1}</small>": "独立两百周年纪念钟<small>照片: {x0}, {x1}</small>",
"La Laguna Milagros y el cenote de Xul-Ha, a {n0} km de {p0}. Es frágil: se nada sin bloqueador y sin dejar nada.": "米拉格罗斯湖与舒尔哈天然井，距{p0} {n0} 公里。这里很脆弱：游泳时不涂防晒霜，不留下任何东西。",
"La Quinta Avenida de Playa del Carmen": "卡门海滩的第五大道",
"La Quinta Avenida de Playa del Carmen<small>Foto: {x0}, {x1}</small>": "卡门海滩的第五大道<small>照片: {x0}, {x1}</small>",
"La bahía de {p0} desde el Boulevard": "从海湾大道看{p0}的海湾",
"La bahía de {p0} desde el Boulevard. Foto: {x0}, {x1}, vía Wikimedia Commons.": "从海湾大道看{p0}的海湾. 照片: {x0}, {x1}, 来源 Wikimedia Commons.",
"La bahía frente a Calderitas": "卡尔德里塔斯前的海湾",
"La bahía frente a Calderitas. Foto: {x0}, {x1}, vía Wikimedia Commons.": "卡尔德里塔斯前的海湾. 照片: {x0}, {x1}, 来源 Wikimedia Commons.",
"La bahía vista desde Calderitas": "从卡尔德里塔斯看海湾",
"La bahía vista desde Calderitas, {p0}": "从卡尔德里塔斯看海湾, {p0}",
"La bahía vista desde Calderitas. Foto: {x0}, {x1}, vía Wikimedia Commons.": "从卡尔德里塔斯看海湾. 照片: {x0}, {x1}, 来源 Wikimedia Commons.",
"La bahía vista desde Calderitas<small>Foto: {x0}, {x1}</small>": "从卡尔德里塔斯看海湾<small>照片: {x0}, {x1}</small>",
"La capilla antigua dentro de la zona de Oxtankah": "奥斯坦卡遗址内的古老小教堂",
"La capilla antigua dentro de la zona de Oxtankah<small>Foto: {x0}, {x1}</small>": "奥斯坦卡遗址内的古老小教堂<small>照片: {x0}, {x1}</small>",
"La capilla de Nuestra Señora del Carmen": "卡门圣母小教堂",
"La capilla de Nuestra Señora del Carmen<small>Foto: {x0}, {x1}</small>": "卡门圣母小教堂<small>照片: {x0}, {x1}</small>",
"La capital del estado, frente a la bahía, con el Museo de la Cultura Maya.": "州首府，面朝海湾，有玛雅文化博物馆。",
"La capital del estado, frente a la bahía, con el Museo de la Cultura Maya. Tiene {n0} lugares para comer y {n1} para dormir; {n2} personas llegaron en el Tren Maya en {m0} de {n3}. Cuidado: se vigila el sargazo que apareció en los canales de entrada de la bahía ({m1} de {n4}).": "州首府，面朝海湾，有玛雅文化博物馆。这里有 {n0} 个吃饭的地方和 {n1} 个住宿的地方；{n3}年{m0} 有 {n2} 人乘玛雅列车抵达。注意：通往海湾的水道中出现的马尾藻正在监测中（{n4}年{m1}）。",
"La gran pirámide de Dzibanché en la selva": "丛林中兹班切的大金字塔",
"La gran pirámide de Dzibanché en la selva. Foto: {x0}, {x1}, vía Wikimedia Commons.": "丛林中兹班切的大金字塔. 照片: {x0}, {x1}, 来源 Wikimedia Commons.",
"La laguna Nichupté": "尼丘普特潟湖",
"La laguna Nichupté<small>Foto: {x0}, {x1}</small>": "尼丘普特潟湖<small>照片: {x0}, {x1}</small>",
"La laguna es frágil: visitas con límite estricto y sin actividades que la dañen.": "潟湖很脆弱：严格限制游客人数，不进行任何会伤害它的活动。",
"La orilla de la laguna en Huay-Pix": "瓦伊皮克斯的潟湖岸边",
"La playa del pueblo, en Playa del Carmen": "卡门海滩的镇上海滩",
"La playa del pueblo, en Playa del Carmen<small>Foto: {x0}, {x1}</small>": "卡门海滩的镇上海滩<small>照片: {x0}, {x1}</small>",
"Laguna y selva": "潟湖与丛林",
"Las fases": "各个阶段",
"Las fotos son de Wikimedia Commons, con licencia libre, y cada una se tomó dentro del municipio del lugar (su coordenada se comprobó con el mapa oficial).": "照片来自 Wikimedia Commons，均为自由授权，每张都拍摄于该地所在的市内（其坐标已与官方地图核对）。",
"Llega más o menos la gente de un mes promedio.": "人数与平均月份大致相同。",
"Llega {n0} % menos gente que en un mes promedio: hay espacio.": "人数比平均月份少 {n0} %：有空间。",
"Llega {n0} % más gente que en un mes promedio, y hay {n1} % de probabilidad de rebasar el mes más lleno de su historia.": "人数比平均月份多 {n0} %，并有 {n1} % 的可能超过历史上最拥挤的月份。",
"Llega {n0} % más gente que en un mes promedio.": "人数比平均月份多 {n0} %。",
"Lo que hay <em>detrás</em> del viaje.": "旅行<em>背后</em>的东西。",
"Lo que no te <em>cuentan</em> del Caribe.": "关于加勒比海，没人<em>告诉</em>你的事。",
"Lo que todos <em>preguntan</em>.": "大家都在<em>问</em>的问题。",
"Los Voladores en el parque Fundadores": "创始人公园的飞人表演",
"Los Voladores en el parque Fundadores<small>Foto: {x0}, {x1}</small>": "创始人公园的飞人表演<small>照片: {x0}, {x1}</small>",
"Los datos": "数据",
"Los lugares": "这些地方",
"Los lugares del sur con estadística están en temporada alta este mes. Mejor ve a la {p0} en <b>{m0}</b>: menos gente, poca lluvia y fuera de la temporada de tormentas.": "南部有统计数据的地方本月都处于旺季。最好在<b>{m0}</b>去{p0}：人更少、雨更少，而且不在风暴季。",
"Los lugares del sur con estadística están en temporada alta este mes. Mejor ve a {p0} en <b>{m0}</b>: menos gente, poca lluvia y fuera de la temporada de tormentas.": "南部有统计数据的地方本月都处于旺季。最好在<b>{m0}</b>去{p0}：人更少、雨更少，而且不在风暴季。",
"Los poblados cercanos casi no tienen hoteles: la visita se hace desde {p0}.": "附近村庄几乎没有酒店：需从{p0}出发参观。",
"Lugar": "地点",
"Lugares reales del directorio de negocios del INEGI, del más cercano al más lejano. No son reseñas ni anuncios pagados y el directorio no publica horarios: confirma antes de ir.": "来自 INEGI 商户名录的真实地点，由近到远排列。不是评价，也不是付费广告，名录也不公布营业时间：出发前请确认。",
"Maqueta del sur de Quintana Roo. Arrastra para girarla.": "金塔纳罗奥州南部模型。拖动即可旋转。",
"Mariposa búho cerca de Chunhuhub": "猫头鹰蝶，在丘恩胡胡布附近",
"Mariposa en la selva cerca de Chunhuhub": "丘恩胡胡布附近丛林中的蝴蝶",
"Mariscos frente a la bahía": "海湾边的海鲜",
"Mariscos y pescado · a {n0} km del centro": "海鲜与鱼 · 距市中心 {n0} 公里",
"Mariscos y pescado · en el centro": "海鲜与鱼 · 在市中心",
"Mejor mes: <b>{m0}</b> · el mes más seco y sin tormentas (no hay estadística de visitantes)": "最佳月份：<b>{m0}</b> · 最干燥且无风暴的月份（没有游客统计）",
"Mejor mes: <b>{m0}</b> · menos gente, poca lluvia y sin temporada de tormentas": "最佳月份：<b>{m0}</b> · 人更少、雨更少，且不在风暴季",
"Mejor ve al sur": "不如去南部",
"Menú": "菜单",
"Mes": "月份",
"Mes normal": "一般月份",
"Mes tranquilo": "安静月份",
"Modo noche": "夜间模式",
"Museo · a {n0} km del centro": "博物馆 · 距市中心 {n0} 公里",
"Museo · en el centro": "博物馆 · 在市中心",
"Museo · en {p0}, a {n0} km": "博物馆 · 在{p0}，距离 {n0} 公里",
"Museos de la cultura maya": "玛雅文化博物馆",
"Nadar en la Laguna Milagros": "在米拉格罗斯湖游泳",
"No damos precios: ninguna fuente oficial abierta publica tarifas de hotel por lugar, y no las inventamos. Lo que sí sabemos es que en el sur los hoteles son chicos: {n0} cuartos por hotel en {p0} contra {n1} en {p1} ({m0} de {n2}).": "我们不提供价格：没有任何公开的官方来源按地点公布酒店价格，我们也不编造。我们知道的是，南部的酒店规模小：{p0}平均每家酒店 {n0} 间客房，而{p1}为 {n1} 间（{n2}年{m0}）。",
"No hay estadística oficial de visitantes: por eso se cuida con un límite estricto de gente. <small>Fuente: Selección de regiones del proyecto</small>": "没有官方游客统计：因此通过严格的人数上限来保护。<small>来源：本项目的区域选择</small>",
"Palapas en Huay-Pix, a la orilla de la laguna": "瓦伊皮克斯潟湖岸边的棕榈屋",
"Parque · a {n0} km del centro": "公园 · 距市中心 {n0} 公里",
"Parque · en {p0}, a {n0} km": "公园 · 在{p0}，距离 {n0} 公里",
"Paseo en lancha · en el centro": "乘船游 · 在市中心",
"Paseo en lancha · en {p0}, a {n0} km": "乘船游 · 在{p0}，距离 {n0} 公里",
"Pirámide de la Tumba {n0} en Oxtankah": "奥斯坦卡 {n0} 号墓金字塔",
"Pirámide de la Tumba {n0} en Oxtankah<small>Foto: {x0}, {x1}</small>": "奥斯坦卡 {n0} 号墓金字塔<small>照片: {x0}, {x1}</small>",
"Pirámides en la selva": "丛林中的金字塔",
"Pizzas y hamburguesas · a {n0} km del centro": "披萨与汉堡 · 距市中心 {n0} 公里",
"Pizzas y hamburguesas · en el centro": "披萨与汉堡 · 在市中心",
"Planea tu viaje": "规划你的旅行",
"Planea tu viaje · el sur de Quintana Roo": "规划你的旅行 · 金塔纳罗奥州南部",
"Playa Gaviota Azul, en la punta de {p0}": "{p0}尖角的海鸥蓝海滩",
"Playa Gaviota Azul, en la punta de {p0}, {p0}": "{p0}尖角的海鸥蓝海滩, {p0}",
"Playa Gaviota Azul, en la punta de {p0}. Foto: {x0}, {x1}, vía Wikimedia Commons.": "{p0}尖角的海鸥蓝海滩. 照片: {x0}, {x1}, 来源 Wikimedia Commons.",
"Playa Gaviota Azul, en la punta de {p0}<small>Foto: {x0}, {x1}</small>": "{p0}尖角的海鸥蓝海滩<small>照片: {x0}, {x1}</small>",
"Playa de la zona hotelera de {p0}": "{p0}酒店区的海滩",
"Playa de la zona hotelera de {p0}<small>Foto: {x0}, {x1}</small>": "{p0}酒店区的海滩<small>照片: {x0}, {x1}</small>",
"Playa del Carmen desde el aire": "空中俯瞰卡门海滩",
"Playa del Carmen desde el aire, {p0}": "空中俯瞰卡门海滩, {p0}",
"Playa del Carmen desde el aire. Foto: {x0}, {x1}, vía Wikimedia Commons.": "空中俯瞰卡门海滩. 照片: {x0}, {x1}, 来源 Wikimedia Commons.",
"Playa del Carmen desde el aire<small>Foto: {x0}, {x1}</small>": "空中俯瞰卡门海滩<small>照片: {x0}, {x1}</small>",
"Por la tarde": "下午",
"Posada · a {n0} km del centro": "客栈 · 距市中心 {n0} 公里",
"Posada · en el centro": "客栈 · 在市中心",
"Posada · en {p0}, a {n0} km": "客栈 · 在{p0}，距离 {n0} 公里",
"Postales del sur": "来自南部的明信片",
"Postales del sur · fotos tomadas en cada lugar": "来自南部的明信片 · 均在当地拍摄",
"Preguntas": "问答",
"Preguntas frecuentes": "常见问题",
"Preguntas rápidas": "快速问答",
"Pregúntanos": "问我们",
"Pueblo de pescadores junto a la bahía y la zona arqueológica de Oxtankah, casi siempre sin filas.": "海湾边的渔村，旁边是奥斯坦卡考古遗址，几乎从不需要排队。",
"Pueblo de pescadores junto a la bahía y la zona arqueológica de Oxtankah, casi siempre sin filas. Tiene {n0} lugares para comer y {n1} para dormir. Cuidado: comparte con {p0} la vigilancia del sargazo en la bahía.": "海湾边的渔村，旁边是奥斯坦卡考古遗址，几乎从不需要排队。这里有 {n0} 个吃饭的地方和 {n1} 个住宿的地方。注意：与{p0}共同监测海湾里的马尾藻。",
"Pueblos de {p0}": "{p0}的村庄",
"Pueblos mayas con turismo comunitario y la cueva de Kantemó.": "开展社区旅游的玛雅村庄，以及坎特莫洞穴。",
"Pueblos mayas con turismo comunitario y la cueva de Kantemó. Tiene {n0} lugares para comer y {n1} para dormir; {n2} personas llegaron en el Tren Maya en {m0} de {n3}. Cuidado: hay pocos cuartos de hotel: la campaña pone un límite de visitantes para no rebasar a los pueblos.": "开展社区旅游的玛雅村庄，以及坎特莫洞穴。这里有 {n0} 个吃饭的地方和 {n1} 个住宿的地方；{n3}年{m0} 有 {n2} 人乘玛雅列车抵达。注意：酒店客房很少，因此本活动设定了游客上限，以免村庄不堪重负。",
"Qué hacer": "做什么",
"Radar, {m0} de {n0}:": "雷达，{n0}年{m0}：",
"Recreación · a {n0} km del centro": "休闲娱乐 · 距市中心 {n0} 公里",
"Recreación · en Xul-ha, a {n0} km": "休闲娱乐 · 在舒尔哈，距离 {n0} 公里",
"Recreación · en el centro": "休闲娱乐 · 在市中心",
"Recreación · en {p0}, a {n0} km": "休闲娱乐 · 在{p0}，距离 {n0} 公里",
"Respondo con los datos del proyecto. Si no lo sé, lo digo.": "我用本项目的数据回答。如果不知道，我会直说。",
"Restaurante Bahía Villamar, en una casa de madera": "木屋里的 Bahía Villamar 餐厅",
"Restaurante Bahía Villamar, en una casa de madera<small>Foto: {x0}, {x1}</small>": "木屋里的 Bahía Villamar 餐厅<small>照片: {x0}, {x1}</small>",
"Restaurante a la carta · a {n0} km del centro": "点菜餐厅 · 距市中心 {n0} 公里",
"Restaurante a la carta · en el centro": "点菜餐厅 · 在市中心",
"Rutas de {n0} y {n1} días": "{n0} 天和 {n1} 天的路线",
"Saltar al contenido": "跳到内容",
"Se espera alrededor de <b>{n0} %</b> de los cuartos de hotel ocupados, muy probablemente entre {n1} y {n2} %.": "预计约有 <b>{n0} %</b> 的酒店客房被入住，很可能在 {n1} % 到 {n2} % 之间。",
"Se esperan alrededor de <b>{n0}</b> cruces desde Belice, muy probablemente entre {n1} y {n2}.": "预计约有 <b>{n0}</b> 人次从伯利兹入境，很可能在 {n1} 到 {n2} 之间。",
"Se esperan alrededor de <b>{n0}</b> visitantes a Kohunlich, Dzibanché e Ichkabal, muy probablemente entre {n1} y {n2}.": "预计科洪利奇、兹班切和伊奇卡巴尔约有 <b>{n0}</b> 名游客，很可能在 {n1} 到 {n2} 之间。",
"Se esperan alrededor de <b>{n0}</b> visitantes a la zona de Oxtankah, muy probablemente entre {n1} y {n2}.": "预计奥斯坦卡遗址约有 <b>{n0}</b> 名游客，很可能在 {n1} 到 {n2} 之间。",
"Se vigila el sargazo que apareció en los canales de entrada de la bahía ({m0} de {n0}).": "通往海湾的水道中出现的马尾藻正在监测中（{n0}年{m0}）。",
"Secciones": "栏目",
"Seis experiencias con lugares reales y una cifra oficial cada una. Sin precios: ninguna fuente oficial los publica.": "六种体验，每种都有真实的地点和一个官方数据。不显示价格：没有官方来源公布。",
"Sin dato": "无数据",
"Sin dato oficial": "无官方数据",
"Sí: en {n0} {n1} de cada {n2} cuartos de hotel de {p0} se quedaron vacíos ({n3} de {n4} noches ocupadas).": "是的：{n0} 年{p0}每 {n2} 间酒店客房中有 {n1} 间空置（{n4} 个房晚中有 {n3} 个被入住）。",
"Tacos y tortas · a {n0} km del centro": "塔可与墨西哥三明治 · 距市中心 {n0} 公里",
"Tacos y tortas · en el centro": "塔可与墨西哥三明治 · 在市中心",
"Te conviene más": "更好的选择",
"Temporada alta": "旺季",
"Temporada alta.": "旺季。",
"Tienen sargazo y se llenan: en su semana más llena, {p0} tuvo {n0} de cada {n1} cuartos ocupados, y en Tulum se reportaron cierres de negocios en {n2}. La campaña lleva gente a donde sí hay espacio.": "那里有马尾藻而且人满为患：在最拥挤的一周，{p0}每 {n1} 间客房有 {n0} 间被入住，{n2} 年图卢姆还出现了商户关门的报道。本活动把人们带到真正有空间的地方。",
"Todo lo que viste arriba sale de datos oficiales, modelos y pruebas. Esta parte es para quien quiera revisar cómo lo sabemos.": "你在上面看到的一切都来自官方数据、模型和测试。这一部分供想要核实我们如何得知的人查看。",
"Tranquilo": "安静",
"Tu viaje": "你的旅行",
"Turismo comunitario maya": "玛雅社区旅游",
"Un balneario o un parque, y a comer: mariscos, cocina yucateca o comida casera.": "去游泳场所或公园，然后吃饭：海鲜、尤卡坦菜或家常菜。",
"Un día en <em>{p0}</em>": "在<em>{p0}</em>的一天",
"Un equipo de estudiantes de Ciencias de Datos para Negocios de la Universidad Nacional Rosario Castellanos (UNRC), como proyecto escolar {n0}-{n1}.": "罗萨里奥·卡斯特利亚诺斯国立大学（UNRC）商业数据科学专业的学生团队，{n0}-{n1} 学期的课程项目。",
"Un matapalo en la selva de Felipe Carrillo Puerto": "费利佩·卡里略·普埃尔托丛林中的绞杀榕",
"Un muelle en la Laguna Milagros": "米拉格罗斯湖上的码头",
"Un muelle en la Laguna Milagros. Foto: {x0}, {x1}, vía Wikimedia Commons.": "米拉格罗斯湖上的码头. 照片: {x0}, {x1}, 来源 Wikimedia Commons.",
"Una laguna del mismo sistema que Bacalar, con pueblos a la orilla.": "与巴卡拉尔同一水系的潟湖，岸边有村庄。",
"Una laguna del mismo sistema que Bacalar, con pueblos a la orilla. Tiene {n0} lugares para comer y {n1} para dormir. Cuidado: la laguna es frágil: visitas con límite estricto y sin actividades que la dañen.": "与巴卡拉尔同一水系的潟湖，岸边有村庄。这里有 {n0} 个吃饭的地方和 {n1} 个住宿的地方。注意：潟湖很脆弱，因此严格限制游客人数，不进行任何会伤害它的活动。",
"Una laguna dulce y un cenote": "淡水潟湖与天然井",
"Unas {n0} personas al día entre las tres zonas en {n1}: tienes la pirámide casi para ti. <small>Fuente: INAH</small>": "{n1} 年三处遗址每天合计约 {n0} 人：金字塔几乎只属于你。<small>来源：INAH</small>",
"Ver cómo está en {m0}": "查看{m0}的情况",
"Ver cómo va a estar": "看看会是什么样子",
"Ver la {p0} en {m0}": "查看{m0}的{p0}",
"Ver todo el mapa": "查看整张地图",
"Ver {p0} en {m0}": "查看{m0}的{p0}",
"Vive el sur": "体验南部",
"Zona arqueológica (INAH)": "考古遗址（INAH）",
"Zona arqueológica de El Meco": "埃尔梅科考古遗址",
"Zona arqueológica de El Meco<small>Foto: {x0}, {x1}</small>": "埃尔梅科考古遗址<small>照片: {x0}, {x1}</small>",
"Zonas arqueológicas, museos y paseos; para empezar, un café o un desayuno.": "考古遗址、博物馆和游览；先来一杯咖啡或一份早餐。",
"de lluvia en un {m0} normal": "常年{m0}的降雨量",
"de máxima, en promedio": "平均最高气温",
"de probabilidad de tormenta": "风暴概率",
"llegaron en el Tren Maya en {m0} de {n0}": "{n0}年{m0}乘玛雅列车抵达",
"lugar para dormir": "个住宿的地方",
"lugares para comer": "个吃饭的地方",
"lugares para dormir": "个住宿的地方",
"no hay estadística oficial de turistas": "没有官方游客统计",
"sin tormentas registradas en este mes": "本月没有风暴记录",
"visitantes a sus zonas arqueológicas en {n0}": "{n0} 年其考古遗址的游客",
"{m0} de {n0}: mes normal": "{n0}年{m0}：一般月份",
"{m0} de {n0}: mes tranquilo": "{n0}年{m0}：安静月份",
"{m0} de {n0}: temporada alta": "{n0}年{m0}：旺季",
"{n0} días": "{n0} 天",
"{n0} marisquerías en Calderitas y {n1} visitantes a Oxtankah en {n2}. <small>Fuente: INEGI (DENUE) e INAH</small>": "{n2} 年卡尔德里塔斯有 {n0} 家海鲜餐厅，奥斯坦卡有 {n1} 名游客。<small>来源：INEGI（DENUE）和 INAH</small>",
"{n0} mm": "{n0} 毫米",
"{n0} museos en {p1} y {p0} según el directorio del INEGI. <small>Fuente: INEGI (DENUE)</small>": "根据 INEGI 名录，{p1}和{p0}共有 {n0} 家博物馆。<small>来源：INEGI（DENUE）</small>",
"{n0} °C": "{n0} °C",
"{n0}. {p0}: ir a su descripción": "{n0}. {p0}：查看介绍",
"{p0} en {m0} de {n0}: temporada alta.": "{p0}，{n0}年{m0}：旺季。",
"{p0} · {m0} de {n0}": "{p0} · {n0}年{m0}",
"{p0} · {m0} de {n0} <span>Referencia: la campaña no lo promueve</span>": "{p0} · {n0}年{m0} <span>参考：本活动不推广此地</span>",
"· {m0} de {n0} (estimado): tranquilo": "· {n0}年{m0}（估计）：安静",
"¿Cuándo conviene ir?": "什么时候去最好？",
"¿Cuánto cuesta ir?": "去一趟要花多少钱？",
"¿Cómo llego al sur?": "怎么去南部？",
"¿Cómo lo sabemos?": "我们是怎么知道的？",
"¿De dónde salen los datos?": "数据从哪里来？",
"¿Dónde se queda el dinero?": "钱留在了哪里？",
"¿Hay espacio en {p0}?": "{p0}还有空间吗？",
"¿Hay sargazo en el sur?": "南部有马尾藻吗？",
"¿Ibas al norte?": "原本要去北部？",
"¿Por qué no {p0} o Tulum?": "为什么不去{p0}或图卢姆？",
"¿Quién hizo esto?": "这是谁做的？",
"¿Qué hay en {p0}?": "{p0}有什么？",
"¿Qué lugares promueve la campaña?": "本活动推广哪些地方？",
"Modo día": "日间模式",
"<span></span>El Mercado {n0} y los antojitos del centro<small>{n1} km →</small>": "<span></span>{n0} 号市场与市中心小吃<small>{n1} 公里 →</small>",
"<span></span>El parque Fundadores y el Portal Maya<small>a pie →</small>": "<span></span>创始人公园与玛雅之门<small>步行 →</small>",
"<span></span>La Quinta Avenida<small>{n0} km →</small>": "<span></span>第五大道<small>{n0} 公里 →</small>",
"<span></span>La playa del pueblo": "<span></span>镇上的海滩",
"<span></span>La zona arqueológica de El Meco": "<span></span>埃尔梅科考古遗址",
"<span></span>La zona hotelera y Playa Gaviota Azul<small>{n0} km →</small>": "<span></span>酒店区与海鸥蓝海滩<small>{n0} 公里 →</small>",
"<span></span>{p0} o Playa del Carmen: subir al Tren Maya<small>{n0} km →</small>": "<span></span>{p0}或卡门海滩：乘玛雅列车<small>{n0} 公里 →</small>",
"<span></span>{p0}: el malecón al atardecer<small>{n0} km →</small>": "<span></span>{p0}：夕阳下的海滨大道<small>{n0} 公里 →</small>",
"<span>★★★★★</span> {n0} % de los cuartos de hotel son de {n1} estrellas (categoría oficial, {n2})": "<span>★★★★★</span> {n0} % 的酒店客房为 {n1} 星级（官方等级，{n2} 年）",
"Antojitos y Mercado {n0}": "小吃与 {n0} 号市场",
"Así se come en {p0}": "{p0}吃什么",
"Categoría de hotel: SECTUR-DataTur, Compendio Estadístico del Turismo en México {n0} (tabla {n1}_2). Fuente: INEGI, Directorio Estadístico Nacional de Unidades Económicas (DENUE). El tipo de lugar y el momento del día los sugiere un clasificador de texto que lee el nombre y el giro oficial de cada negocio (acertó {n2} de {n3} en una revisión al azar). Cuando un lugar no tiene algo cerca, se muestra lo más cercano de los otros lugares del sur. \"Ver en Google Maps\" abre Google Maps en otra pestaña; esta página no descarga nada de Google.": "酒店等级：SECTUR-DataTur，《{n0} 年墨西哥旅游统计汇编》（表 {n1}_2）。来源：INEGI，全国经济单位统计名录（DENUE）。地点类型和一天中的时段由一个文本分类器建议，它读取每家商户的名称和官方行业（在随机抽查中 {n3} 个对了 {n2} 个）。当某地附近没有某类地点时，显示南部其他地方中最近的一个。\"在 Google 地图中查看\"会在新标签页中打开 Google 地图；本页面不会从 Google 下载任何内容。",
"Cenar en la calle, de noche": "夜晚在街边吃晚餐",
"Cenar en la calle, de noche<small>Foto: {x0}, {x1}</small>": "夜晚在街边吃晚餐<small>照片: {x0}, {x1}</small>",
"Cocina mexicana en la Quinta Avenida": "第五大道上的墨西哥菜",
"Cocina mexicana en la Quinta Avenida<small>Foto: {x0}, {x1}</small>": "第五大道上的墨西哥菜<small>照片: {x0}, {x1}</small>",
"Comida de mariscos frente al mar": "海边的海鲜午餐",
"Comida de mariscos frente al mar<small>Foto: {x0}, {x1}</small>": "海边的海鲜午餐<small>照片: {x0}, {x1}</small>",
"Del Caribe a la selva, en un <em>solo</em> mapa.": "从加勒比海到丛林，<em>一张</em>地图看全。",
"Del Caribe al sur en Tren Maya": "乘玛雅列车从加勒比海到南部",
"Distancias en línea recta (no hay datos abiertos de distancias por carretera). Sin precios: ninguna fuente oficial los publica. Las reseñas se leen en Google Maps.": "距离为直线距离（没有公开的公路距离数据）。不显示价格：没有官方来源公布。评价请在 Google 地图上查看。",
"El Meco, El Rey y el Museo Maya de {p0}: ciudades mayas entre los hoteles y la laguna.": "埃尔梅科、埃尔雷伊和{p0}玛雅博物馆：酒店与潟湖之间的玛雅古城。",
"El Museo de la Cultura Maya, el planetario y la historia de la ciudad, a pasos de la bahía.": "玛雅文化博物馆、天文馆和城市历史，离海湾只有几步。",
"El Portal Maya y los Voladores": "玛雅之门与飞人表演",
"El clima es el normal de {n0} a {n1}. El riesgo de tormenta cuenta las tormentas que pasaron a {n2} km o menos del lugar desde {n3} ({n4} en el caso de {p0}).": "气候为 {n0} 至 {n1} 年的常年平均值。风暴风险统计的是自 {n3} 年以来经过该地 {n2} 公里以内的风暴（{p0}为 {n4} 次）。",
"El parque Fundadores frente al mar, con el Portal Maya y la danza de los Voladores.": "面朝大海的创始人公园，有玛雅之门和飞人舞。",
"El sur: {p3}, {p0}, {p1}. {p4} y la {p2} aparecen como referencia, para quien pensaba ir al norte: si su mes está lleno, te recomendamos un lugar del sur.": "南部：{p3}、{p0}、{p1}。{p4}和{p2}仅作参考，供原本打算去北部的人查看：如果那个月客满，我们会推荐南部的一个地方。",
"En el sur · {p0}": "南部 · {p0}",
"En la costa de {p0} y Calderitas no hay reporte de sargazo. Sí apareció en los canales de entrada de la bahía ({m0} de {n0}), así que se vigila. La ruta de las pirámides está lejos del mar abierto.": "{p0}和卡尔德里塔斯海岸没有马尾藻报告。它曾出现在通往海湾的水道中（{n0}年{m0}），因此正在监测。金字塔之路远离外海。",
"En los municipios del sur que promueve la campaña no hay ningún hospedaje grande: {n0} son chicos (hasta {n1} personas) y {n2} medianos. La derrama económica por destino no se muestra porque la fuente no dice en qué unidad está.": "本活动推广的南部各市没有大型住宿：{n0} 家是小型（最多 {n1} 人），{n2} 家是中型。按目的地划分的旅游消费不予显示，因为数据来源没有说明单位。",
"En {n0} llegaron {n1} pasajeros en avión a {p0}, y el Tren Maya para en {p0}, Bacalar, {p1} y Playa del Carmen. Solo en {m0} de {n2} {n3} personas bajaron del tren en {p0}.": "{n0} 年有 {n1} 名乘客乘飞机抵达{p0}，玛雅列车停靠{p0}、巴卡拉尔、{p1}和卡门海滩。仅 {n2}年{m0}，就有 {n3} 人在{p0}下车。",
"Fajitas de pollo en Playa del Carmen": "卡门海滩的鸡肉法士达",
"Fajitas de pollo en Playa del Carmen<small>Foto: {x0}, {x1}</small>": "卡门海滩的鸡肉法士达<small>照片: {x0}, {x1}</small>",
"Fotos del lugar elegido; se pueden recorrer con las flechas": "所选地点的照片；可以用方向键浏览",
"Guacamole y mojitos": "鳄梨酱与莫吉托",
"Guacamole y mojitos<small>Foto: {x0}, {x1}</small>": "鳄梨酱与莫吉托<small>照片: {x0}, {x1}</small>",
"La Quinta Avenida": "第五大道",
"La calle peatonal de Playa del Carmen: restaurantes, tiendas y el mar a una cuadra.": "卡门海滩的步行街：餐厅、商店，离海只有一个街区。",
"La ciudad más visitada del Caribe mexicano: la zona hotelera, la laguna Nichupté y zonas mayas dentro de la ciudad.": "墨西哥加勒比海游客最多的城市：酒店区、尼丘普特潟湖和城中的玛雅遗址。",
"La ciudad más visitada del Caribe mexicano: la zona hotelera, la laguna Nichupté y zonas mayas dentro de la ciudad. Tiene {n0} lugares para comer y {n1} para dormir. Referencia: la campaña no lo promueve. Tiene sargazo en {n2} y está en temporada alta de {m0} a {m1}.": "墨西哥加勒比海游客最多的城市：酒店区、尼丘普特潟湖和城中的玛雅遗址。这里有 {n0} 个吃饭的地方和 {n1} 个住宿的地方。参考：本活动不推广此地。{n2} 年有马尾藻，{m0}到{m1}为旺季。",
"La zona hotelera": "酒店区",
"Las fotos son de Wikimedia Commons, con licencia libre, y cada una se tomó dentro del municipio del lugar (su coordenada se comprobó con el mapa oficial). Las fotos de comida solo existen con licencia libre para {p0} y Playa del Carmen; las del sur las aportará el equipo.": "照片来自 Wikimedia Commons，均为自由授权，每张都拍摄于该地所在的市内（其坐标已与官方地图核对）。自由授权的美食照片只有{p0}和卡门海滩有；南部的将由团队提供。",
"Maqueta de Quintana Roo. Arrastra para girarla.": "金塔纳罗奥州模型。拖动即可旋转。",
"Mes menos lleno: <b>{m0}</b> · el menos lleno de los meses secos y sin tormentas; aun así, hoteles al {n0} %": "最不拥挤的月份：<b>{m0}</b> · 干燥且无风暴的月份中最不满的；即便如此，酒店入住率仍有 {n0} %",
"Panuchos, el antojito yucateco": "帕努乔斯，尤卡坦小吃",
"Panuchos, el antojito yucateco<small>Foto: {x0}, {x1}</small>": "帕努乔斯，尤卡坦小吃<small>照片: {x0}, {x1}</small>",
"Panuchos, salbutes y tacos en el centro, lejos de la zona hotelera.": "市中心的帕努乔斯、萨尔布特斯和塔可，远离酒店区。",
"Playa Gaviota Azul y la punta de {p0}: arena blanca entre el mar y la laguna Nichupté.": "{p0}尖角的海鸥蓝海滩：大海与尼丘普特潟湖之间的白沙。",
"Playa del Carmen en un día": "一天游卡门海滩",
"Playa del Carmen, el centro de la {p0}: la Quinta Avenida, el parque Fundadores y la playa del pueblo.": "卡门海滩，{p0}的中心：第五大道、创始人公园和镇上的海滩。",
"Playa del Carmen, el centro de la {p0}: la Quinta Avenida, el parque Fundadores y la playa del pueblo. Tiene {n0} lugares para comer y {n1} para dormir. Referencia: la campaña no la promueve. Tiene sargazo en {n2}; su ocupación bajó y se llena en {m0} y {m1}.": "卡门海滩，{p0}的中心：第五大道、创始人公园和镇上的海滩。这里有 {n0} 个吃饭的地方和 {n1} 个住宿的地方。参考：本活动不推广此地。{n2} 年有马尾藻；入住率下降，{m0}和{m1}会客满。",
"Postales de {p0} · fotos tomadas en cada lugar": "来自{p0}的明信片 · 均在当地拍摄",
"Primero, lo del lugar que elegiste arriba; después, lo del sur. Lugares reales y una cifra oficial en cada uno. Sin precios: ninguna fuente oficial los publica.": "先看你在上方选择的地方，再看南部。真实的地点，每处都有一个官方数据。不显示价格：没有官方来源公布。",
"Referencia: la campaña no la promueve. Tiene sargazo en {n0}; su ocupación bajó y se llena en {m0} y {m1}.": "参考：本活动不推广此地。{n0} 年有马尾藻；入住率下降，{m0}和{m1}会客满。",
"Referencia: la campaña no lo promueve": "参考：本活动不推广此地",
"Referencia: la campaña no lo promueve. Tiene sargazo en {n0} y está en temporada alta de {m0} a {m1}.": "参考：本活动不推广此地。{n0} 年有马尾藻，{m0}到{m1}为旺季。",
"Todavía no tengo esa respuesta. Prueba con una de las preguntas de abajo: solo respondo lo que los datos del proyecto pueden sostener.": "我还没有这个答案。试试下面的问题：我只回答本项目数据能够支持的内容。",
"Tres en el sur, con espacio. {p1} y la {p0}, como referencia para quien iba al norte.": "南部三处，有空间。{p1}和{p0}仅作参考，供原本要去北部的人查看。",
"Un puesto de quesadillas": "墨西哥馅饼摊",
"Un puesto de quesadillas<small>Foto: {x0}, {x1}</small>": "墨西哥馅饼摊<small>照片: {x0}, {x1}</small>",
"Una taquería del centro": "市中心的塔可店",
"Una taquería del centro<small>Foto: {x0}, {x1}</small>": "市中心的塔可店<small>照片: {x0}, {x1}</small>",
"Zonas mayas dentro de {p0}": "{p0}城中的玛雅遗址",
"cuartos de hotel ({m0} de {n0})": "间酒店客房（{n0}年{m0}）",
"de los cuartos son de {n0} estrellas ({n1})": "的客房为 {n0} 星级（{n1} 年）",
"sin temporada alta en los cinco lugares": "五个地方都不是旺季",
"{m0} de {n0}:": "{n0}年{m0}：",
"{n0} % de los cuartos de hotel de Playa del Carmen son de {n1} estrellas, según la categoría oficial ({n2}). <small>Fuente: SECTUR-DataTur (Compendio {n3})</small>": "卡门海滩 {n0} % 的酒店客房为 {n1} 星级，依据官方等级（{n2} 年）。<small>来源：SECTUR-DataTur（{n3} 年汇编）</small>",
"{n0} % de sus cuartos de hotel son de {n1} estrellas, según la categoría oficial ({n2}). <small>Fuente: SECTUR-DataTur (Compendio {n3})</small>": "其 {n0} % 的酒店客房为 {n1} 星级，依据官方等级（{n2} 年）。<small>来源：SECTUR-DataTur（{n3} 年汇编）</small>",
"{n0} día": "{n0} 天",
"{n0} lugares de antojitos, tacos y cocina yucateca en la ciudad según el directorio del INEGI. <small>Fuente: INEGI (DENUE)</small>": "根据 INEGI 名录，城中有 {n0} 家小吃、塔可和尤卡坦菜馆。<small>来源：INEGI（DENUE）</small>",
"{n0} lugares para comer en Playa del Carmen según el directorio del INEGI. <small>Fuente: INEGI (DENUE)</small>": "根据 INEGI 名录，卡门海滩有 {n0} 个吃饭的地方。<small>来源：INEGI（DENUE）</small>",
"{n0} museos en {p0} según el directorio del INEGI. <small>Fuente: INEGI (DENUE)</small>": "根据 INEGI 名录，{p0}有 {n0} 家博物馆。<small>来源：INEGI（DENUE）</small>",
"{n0} visitantes en {n1} entre las tres: unas {n2} al día. <small>Fuente: INAH</small>": "{n1} 年三处共 {n0} 名游客：每天约 {n2} 人。<small>来源：INAH</small>",
"{p0} <span>Referencia: la campaña no lo promueve</span>": "{p0} <span>参考：本活动不推广此地</span>",
"{p0} en {n0} días": "{p0} {n0} 日游",
"{p0}, temporada alta": "{p0}，旺季",
"· Planea tu viaje →": "· 规划你的旅行 →",
"· {p0}, tranquilo": "· {p0}，安静"
},
"lugares": {
"Ruta de las pirámides": "金字塔之路",
"Calderitas y Oxtankah": "卡尔德里塔斯与奥斯坦卡",
"Laguna Milagros y Xul-Ha": "米拉格罗斯湖与舒尔哈",
"Chetumal": "切图马尔",
"Cancún": "坎昆",
"Riviera Maya": "玛雅里维埃拉",
"Maya Ka'an": "玛雅卡安"
}
};
